### ISSUE TITLE
Url of entity is "occupied" even after entity removal

### ISSUE THREAD

**Issue by Miroslav-Stopka** [shopsys/shopsys#1011]
Hi, 

I have found out some strange behaviour...

### What is happening
1. I'm removing brand PUMA, this brand has url puma/
2. After some time, I'm trying to create brand PUMA once again. Seems that I can't use this url puma/ anymore.

### Reason 
When I removed brand PUMA before, url puma/ was not deleted from table friendly_url. Sadly, I'm not able to remove this url from this table through the administration. 

### Expected result
- url should be removed from friendly_url along with removed entity?
- a new page in administration with a list of old/unused-but-occupied urls with delete button?

**Comment by ivoxfilip** [comment]
Has not been fixed, please reopen.
