### ISSUE TITLE
Possibility of overriding CronModuleExecutor

### ISSUE THREAD

**Issue by malyMiso** [shopsys/shopsys#1019]
### What is happening

I would like to override `CronModuleExecutor` (esspecially `CronModuleExecutor::runModule`), but there is no easy way how to achieve that.
It is because of these lines:
https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Component/Cron/CronFacade.php#L59
https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Component/Cron/CronFacade.php#L72
https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Component/Cron/CronFacade.php#L116

### Expected result

There should exist a factory for creating CronModuleExecutor instance, or CronModuleExecutor should be registered as a service

**Comment by PetrHeinz** [comment]
I think the best approach here would be a `CronModuleExecutorFactory` injected through a setter injector (because of BC). This would make the implementation interchangable via DIC configuration without causing  a BC break.

**Comment by pk16011990** [comment]
@PetrHeinz I have question about your idea. If next minor version has setter injector, will next major version use constructor injection instead of setter injection? I don't know how it works on this project, I'm just asking, no offense.

**Comment by PetrHeinz** [comment]
@pk16011990 The `v8.0.0` will be the first major version with backward-compatibility in mind, so we actually haven't decided on this yet.

Generally, we strongly prefer constructor injection over setter injection (see [DI principle in our docs](https://github.com/shopsys/shopsys/blob/v7.2.0/docs/contributing/code-quality-principles.md#dependency-injection)), but I'm not sure if that's sufficient reason to make that BC breaking change in the next major as it may complicate upgrading.

Maybe we'll postpone this until there's more such changes or until we provide some automated way to make such changes in your project during the upgrade (such as using the [`phprector/rector`](https://github.com/rectorphp/rector))...

Can you share your point of view on this? What would you prefer?
