### ISSUE TITLE
Creating variant in administration doesn't open a new window

### ISSUE THREAD

**Issue by PetrHeinz** [shopsys/shopsys#1024]
### What is happening

When administration creates a new product, a new window (or tab) is opened. This is fine - the product detail page is meant to be opened in a new window as it doesn't contain main navigation panel and offers "closing without saving".

When administrator creates a new variant, no new window is opened. This leads to inconsistency and may confuse users.

### Expected result

The product detail should always open in a new window, even if it is created as a variant.

I can think of four possible solutions:

1) When administrator creates a variant using the page "Products >  Products overview >  Create variant", it is redirected to the product list. A flash message is displayed with a link to the product detail, which opens in a new window.
It's a simple solution, but introduces an extra step for the administrator to edit the newly created variant. Probably best for backward compatibility.

2) The page "Products >  Products overview >  Create variant" should open in a new window and have it's layout changed so it doesn't contain the main navigation and offers "closing without saving".
Requires changing the layout of the "Create variant" page. I think there is currently no similar page in the administration, so we would be creating entirely new layout.

3) When administrator creates a variant using the page "Products >  Products overview >  Create variant", the product detail is opened in a new window. The form in the original window (`VariantFormType`) should either be reset, or the original window should be redirected on the product list (otherwise it would be filled with data that cannot be resubmitted).

4) Instead of the admin page "Products >  Products overview >  Create variant" a popup should open. When administrator creates a variant using the popup, the product detail is opened in a new window and the popup is closed.

**Comment by LukasHeinz** [comment]
Hi, I like idea number one as it is simple, quick and resolves the problem.
