### ISSUE TITLE
Inconsistent aliasing of Symfony services (missing standard in services.yml)

### ISSUE THREAD

**Issue by PetrHeinz** [shopsys/shopsys#1037]
### What is happening

In `services.yml` configuration we use two different notations for defining service aliases:

```yaml
    Shopsys\FrameworkBundle\Model\Advert\AdvertFactoryInterface:
        alias: Shopsys\FrameworkBundle\Model\Advert\AdvertFactory
```

and

```yaml
    Shopsys\FrameworkBundle\Model\Advert\AdvertFactoryInterface: '@Shopsys\FrameworkBundle\Model\Advert\AdvertFactory'
```

which is inconsistent and may be confusing. The two notations work exactly the same way (see [Symfony docs on Aliasing](https://symfony.com/doc/3.4/service_container/alias_private.html#aliasing)).

### Expected result

We use only one of these notations and there is a fixer in `shopsys/coding-standards` for easier future maintenance.

I would suggest using only the longer expanded notation as it is easier to read and understand what's going on, even if it's a bit longer.

**Comment by pk16011990** [comment]
.

**Comment by sspooky13** [comment]
Hmm, I like this so I will try to create standard for this in [yaml standards](https://github.com/sspooky13/yaml-standards) library.
I see you try to resolve this with ECS. If you don't want to wait for my solution you can continue with your solution but if you want to wait so you will be able to use my solution 😊.

Thanks for the idea.

**Comment by pesektomas** [comment]
Am I the only one who doesn't like the alias?

**Comment by vitek-rostislav** [comment]
Hi, I would prefer the "original" way with using `@` sign, however, when there is  an automated fixer for using the alias, then it is ok with me :slightly_smiling_face:

**Comment by pesektomas** [comment]
We can use fixer for short variant too :)

**Comment by henzigo** [comment]
I like longer expanded notation. It's more readable and when we have long namespaces then you do not need to scroll horizontally. 

Another advantage can be that you are not able to click through namespace in `services.yml` when you are using short alias with `@`. See:

<img width="1193" alt="Snímek obrazovky 2020-03-20 v 13 34 00" src="https://user-images.githubusercontent.com/1482966/77163938-7e5bfc00-6aaf-11ea-8238-94386344c614.png">
