### ISSUE TITLE
I want to be able to run all tests/standards without the use of no-test database

### ISSUE THREAD

**Issue by boris-brtan** [shopsys/shopsys#1039]
### What is happening

I have a problem to run test phing targets with empty db-create database, i needed to modified parameters.yml database_name to shopsys-test to be able to generate error pages and other things like grunt and so on
### Expected result

I want to launch tests without the need to launch db-demo phing target but just test-db-demo phing target. So build test checks will be faster processed.

**Comment by kaposvary** [comment]
Test comment

**Comment by kaposvary** [comment]
Test comment #2.

**Comment by kaposvary** [comment]
Test comment #3.

**Comment by kaposvary** [comment]
Test commnet #4.

**Comment by simara-svatopluk** [comment]
@kaposvary could you please delete your test comments? They are not related to this issue

**Comment by henzigo** [comment]
This is already implemented for so long time :) Closing
