### ISSUE TITLE
Use phpstan-symfony

### ISSUE THREAD

**Issue by DavidOstrozlik** [shopsys/shopsys#1059]
Use https://github.com/phpstan/phpstan-symfony to check symfony-related problems.

There is hopefully no trouble right now, but it is a step towards safer code.

**Comment by PetrHeinz** [comment]
I've tried doing that, but there are problems with dependencies. Our forks of Symplify repositories and some other dependencies use `nette/utils` in `2.5` and `phpstan-symfony` requires it in `3.0`.

The best approach would probably be fixing the CS in https://github.com/Symplify/Symplify/pull/1589 so it can be (hopefully) merged, abandoning our forks, and upgrading all packages that require the older `nette/utils`...

@vitek-rostislav can you fix the PR? Running `ecs` with `--fix` and commiting the result should suffice.

**Comment by vitek-rostislav** [comment]
Hi @PetrHeinz, I am sorry for the late response. I have fixed the PR (I actually realized that a part of it is completely unnecessary so I created a new PR in our repository as well :slightly_smiling_face:) https://github.com/shopsys/shopsys/pull/1370

**Comment by ondrejmirtes** [comment]
PHPStan 0.12 doesn't declare any dependencies so I recommend upgrading to get rid of the conflict and start using phpstan-symfony,

**Comment by sslt** [comment]
Open it stalebot!
