### ISSUE TITLE
introduce int/null annotation for Identity field of entity

### ISSUE THREAD

**Issue by boris-brtan** [shopsys/shopsys#1061]
### What is happening

During implementation of PHPStan increased level #1040 we have encountered condition in `packages/framework/src/Model/Order/Item/OrderItemPriceCalculation.php`
```
if ($orderItem->getId() === null) {	
                $message = 'OrderItem must have ID filled';	
                throw new \Shopsys\FrameworkBundle\Model\Order\Item\Exception\OrderItemHasNoIdException($message);	
            }
```
there can be situation, when Entity is not yet persisted and its `Id` field is null.
### Expected result

We should introduce all Identity fields of entities with null|int annotation and also their getters
```diff

    /**
-    * @var int
+    * @var null|int
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $id;


    /**
-    * @return int
+    * @return null|int
     */
-    public function getId()
+    public function getId(): ?int
    {
        return $this->id;
    }

```

**Comment by DavidOstrozlik** [comment]
I think we agreed that it would be better to throw exception in the getter if $id is null.

**Comment by pk16011990** [comment]
I think that method `getId()` on non-persistent entity is not common use-case. My excepted result can be:

`OrderItemPriceCalculation.php`:
``` diff
-  if ($orderItem->getId() === null) {	
-                 $message = 'OrderItem must have ID filled';	
-                 throw new \Shopsys\FrameworkBundle\Model\Order\Item\Exception\OrderItemHasNoIdException($message);	
-  }
```
All entities:
```diff
    /**
     * @return int
     */
-    public function getId()
+    public function getId(): int
    {
        return $this->id;
    }

```
And when somebody call `getId()` before persist, developer is notified.

Nullable return type is bigger problem for using in my opinion.

Checking in `OrderItemPriceCalculation.php` was created because PHP 5.6 didn' have scalar return typehint.

**Comment by simara-svatopluk** [comment]
The SSFW consider entities without ID to be in invalid state. There is no way to create a valid entity without persistence. This approach is... well... how to be polite... sub-optimal (not best practice for years even in the Doctrine world), but it is the current state of SSFW.

So I agree with Petr, we should use `getId(): int`
