### ISSUE TITLE
Upgrades with legislative changes

### ISSUE THREAD

**Issue by Miroslav-Stopka** [shopsys/shopsys#1062]
Hi,

I have another question. Is there some plan that includes a release containing legislative changes?

### What is happening
Legislative changes about VAT for the Czech Republic - https://www.du.cz/33/zmeny-v-zakone-o-dph-uniqueidmRRWSbk196FNf8-jVUh4Ep_nyc9No7tEVKUIOb40IRg/

### Expected result
Answer, whether we can expect a release (next 1-2 months) that will reflect this change - so we won't have to invent the wheel - or we should solve this problem on our own.

Thank you for the advice :)

**Comment by vitek-rostislav** [comment]
Hi @Miroslav-Stopka, as far as I know, we will solve this ASAP - in the next minor release (`7.3.0`)

**Comment by Miroslav-Stopka** [comment]
😍

You are stars, thank you very much for the quick response :)

**Comment by henzigo** [comment]
Am I right that this issue is already solved? @vitek-rostislav

**Comment by vitek-rostislav** [comment]
Hi @henzigo, yes, you are right, it has been solved in https://github.com/shopsys/shopsys/pull/1129 :wink:
