### ISSUE TITLE
order of routers priorities

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#1071]
### What is happening
`FriendlyUrlRouter` has a higher priority than basic `Router` - this might cause potential performance problems as the friendly urls are looked up in a database.

### Expected result
`FriendlyUrlRouter` has the lowest priority in `DomainRouter`

**Comment by simara-svatopluk** [comment]
Doesn't this have a reason? Eg. to provide possibility to override basic or localized router by friendly url?

**Comment by pk16011990** [comment]
I totaly agree  with change priorities. Basic router should be more priority then FriendlyUrlRouter... I admit that the original routers priority values were written by me and I thought that a smaller number meant a higher priority.

**Comment by henzigo** [comment]
#1653 closed this issue
