### ISSUE TITLE
Not working URL in cookbook basic-data-import.md

### ISSUE THREAD

**Issue by TomasLudvik** [shopsys/shopsys#1085]
### What is happening
There is URL (https://private-anon-38d0154157-ssfwbasicdataimportdemo.apiary-mock.com/products) in const PRODUCT_DATA_URL that is no longer working.

It seems that there URLs might be regenerated from time to time on apiary.

I went to https://ssfwbasicdataimportdemo.docs.apiary.io/# clicked on "List all products" I was able to get new functioning URL: 
http://private-anon-1567dbe635-ssfwbasicdataimportdemo.apiary-mock.com/products.
### Expected result
There is URL, that is always working in cookbook.

**Comment by simara-svatopluk** [comment]
I don't think you can ever achieve "There is URL, that is always working in cookbook.". But I think you can achieve "There are no temporary URLs in cookbooks" instead ;-)
