### ISSUE TITLE
Registering of BreadcrumbGenerators should be easier

### ISSUE THREAD

**Issue by TomasLudvik** [shopsys/shopsys#1090]
### What is happening
If you want to register new BreadcrumbGenerators, you need to override BreadcrumbResolverFactory.

### Expected result
There should be some tag that would say, that this service is BreadcrumbGenerator and then it should be automatically registered. Same as it is in case of shopsys.friendly_url_provider.

Better way would be to tag services automatically by their classes interfaces:
- all classes implementing FriendlyUrlDataProviderInterface should be automatically tagged by shopsys.friendly_url_provider
- all classes implementing BreadcrumbGeneratorInterface should be automatically tagged by shopsys.breadcrumb_generator.

**Comment by boris-brtan** [comment]
#1176 closes #919 #1090 #1111
```
https://help.github.com/en/articles/closing-issues-using-keywords
If the commit is in a non-default branch, the issue will remain open and the issue will be referenced with a tooltip.
```
