### ISSUE TITLE
Confusing and error-prone access to sizes in ImageEntityConfig

### ISSUE THREAD

**Issue by PetrHeinz** [shopsys/shopsys#1095]
### What is happening
The usage of methods `getSizeConfig()`, `getSizeConfigs()`, `getSizeConfigByType()` and `getSizeConfigsByType()` in [`ImageEntityConfig`](https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Component/Image/Config/ImageEntityConfig.php) is confusing and error prone.

The methods without `ByType` suffix get only image sizes for the default (`null`) type with is not obvious in code. To make things worse, `getSizeConfigsByType` does not work when `null` is provided even though `getSizeConfigByType(null)` works as intended.

This leads to issues such as the one fixed in #1094.

### Expected result

There is only one of methods `ImageEntityConfig::getSizeConfig()` and `ImageEntityConfig::getSizeConfigByType()` which accepts `string|null $type` parameter.

There is only one of methods `ImageEntityConfig::getSizeConfigs()` and `ImageEntityConfig::getSizeConfigsByType()` which accepts `string|null $type` parameter.

(or one of them is deprecated and the deprecated method is not called from within Shopsys Framework)

**Comment by vitek-rostislav** [comment]
Image sizes were completely removed from the backend in https://github.com/shopsys/shopsys/pull/2924 so none of the methods is there anymore :slightly_smiling_face:
