### ISSUE TITLE
Saving payment and shipping after first registration

### ISSUE THREAD

**Issue by PatrikBajer** [shopsys/shopsys#1101]
### What is happening
When some customer finish order, system save his payment and shipping method for next order.
But administrator meanwhile delete that payment or shipping. 

When that customer are going to make new order he get automaticaly error 500 in step 2. (because system want use saved payment/shipping metod, What is no longer available on shop) - https://drive.google.com/file/d/1HQYHOASjNlXEKOIp0WVYa8JSqPsEIEbp/view

### Expected result
- [ ] don't save paymet or shipping method to customer
- [x] If payment or shipping method is not available, then let me go to step 2 with unselected payment or shipping.
- [ ] Try use same validation like is already implemented. (If payment or shipping method is hidden - order step 2 don't drop to error 500).

**Comment by boris-brtan** [comment]
@PatrikBajer will be released in `7.3.0`
