### ISSUE TITLE
Creating product variants when main product variant is set to use stock

### ISSUE THREAD

**Issue by adamtyron** [shopsys/shopsys#1112]
### What is happening
I am creating product A set up as “Use stocks” > yes and “Action after sellout:” > hide product or exclude from sale. 

I am choosing in the products overview “Create variant” and set up product A as “main variant” and any other product is chosen as sub variant. 

When trying to save it like that the application shows error E500 Doctrine\ORM\ORMInvalidArgumentException "Binding entities to query parameters only allowed for entities that have an identifier."

### Note
The issue is there when availability_id is set to null in the product

**Comment by boris-brtan** [comment]
### What is happenging merge
`Available in stock:` is set with `0` value
