### ISSUE TITLE
DRY in DI configurations in framework and project-base

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#1118]
### What is happening
Autodiscovery settings for DI services should be the same in both `framework` and `project-base` packages. This was achieved in https://github.com/shopsys/shopsys/pull/1049, however, now we have a DRY violation in our project (see my 2nd point of [the review](https://github.com/shopsys/shopsys/pull/1049#pullrequestreview-246125730) where I explain why I think it is a problem and also there is an idea how to solve this) 

### Expected result
DI configuration in `framework` and `project-base` packages is unified without violating DRY.

**Comment by boris-brtan** [comment]
should be ShopBundle somehow similiar to Framework ? I think this is entirely different domain|namespace.

**Comment by vitek-rostislav** [comment]
For project developers, I would say they are connected - the developers "copy" the file structure of `framework` in their projects when extending the core classes (e.g. we encourage them to do so in our cookbooks) - so I believe the services configuration should be the same to avoid confusions :slightly_smiling_face:

**Comment by simara-svatopluk** [comment]
I can only agree with Boris. FW configuration can differ from project-base configuration.

If implementator use FW as the source of truth, then yes, I understand that they'll require to have everything "exactly the same" as in the FW.
But once there is a need to have the project configuration "slightly different" from the FW, this rule can start to do problems.

**Comment by PetrHeinz** [comment]
This cannot, to the extend of my knowledge, be implemented using YAML configs.

We can create some compiler passes or see whether this can be achieved by PHP configuration, which can go beyond the definition included in a file (for example, see the difference between `_instanceof` in YAML and `registerForAutoconfiguration()` in PHP in [How to Work with Service Tags](https://symfony.com/doc/current/service_container/tags.html#autoconfiguring-tags)).

If we'll go down this road, service configuration might get more complicated and hard-to-debug than it is now. But it might be worth it...

**Comment by pk16011990** [comment]
I want unified solution...not stale....

**Comment by pk16011990** [comment]
I want unified solution...not stale....

**Comment by grossmannmartin** [comment]
Should be only project-base and framework unified? What if I extend a class from a different package (read-model, frontend-api)? 
I don't want everything unified as I don't want to specify suffixes in package, where I don't have a classes like this.

I thought about sniff in monorepo (only) to check if every suffix used in packages is also in project-base. What do you think?
