### ISSUE TITLE
Products cannot be exported to Elasticsearch when variants doesn't have price for pricing group

### ISSUE THREAD

**Issue by grossmannmartin** [shopsys/shopsys#1142]
If every variant of a product is not sellable for certain pricing group (ie. every variant has null price for the same pricing group), export to Elasticsearch will fail on the Exception and cannot be completed.

#### Steps to reproduce:
1. Have clean build with demo data
2. Edit product variants with IDs 74, 75 and 82
    - delete price for pricing group "Partner" for domain 1
3. Run phing target `product-search-export-products`
4. Nod your head when you see following exception
```
In ProductPriceCalculation.php line 82:

  [Shopsys\FrameworkBundle\Model\Product\Pricing\Exception\MainVariantPriceCalculationException]
  Main variant ID = 149 has no sellable variants.
```

This seems to be a similar problem as https://github.com/shopsys/shopsys/pull/1083 (but for pricing group instead of domain).

### Expected result
All products should be exported successfully. Warning may be shown if necessary.

**Comment by PetrHeinz** [comment]
In my opinion, there should be no warning. Such products should not be visible for particular pricing group, see [functional docs of Product Visibility](https://github.com/shopsys/shopsys/blob/master/docs/functional/product-visibility-and-exclude-from-sale.md#parameters-that-impact-product-visibility).
