### ISSUE TITLE
Ability to debug on production

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#1144]
### What is happening
This is a feature request from project implementation teams - they need the ability to debug on production (eg. display the Symfony debug bar) easily which is not supported in Shopsys Framework at the moment.

### Expected result
It is possible to easily debug on production somehow.

**Comment by henzigo** [comment]
I disagree that. You should never debug on production and framework should not simplify that. Even that it's not hard either to change environment or watch logs to detect exact problem.

**Comment by vitek-rostislav** [comment]
Well, there is another group of developers that states this is their daily bread and strongly demand such a *feature*...maybe we just need to change their minds :thinking:

**Comment by boris-brtan** [comment]
i agrre with that disagreement. I am not sure what this issue is about. Is it about non functional d and dump function ?
you can still use var_dump var_export print_r, is that right?

**Comment by henzigo** [comment]
Yes, its possible to display symfony bar without dev dependencies. It's just about change file name from PRODUCTION to DEVELOPMENT. 

I suggest closing this issue.

**Comment by vitek-rostislav** [comment]
ok, fair enough, thanks for your opinions, I am closing it :+1:
