### ISSUE TITLE
Oath keys and config are not generated correctly

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#1156]
### What is happening
I build the application using Kubernetes (`build_kubernetes.sh`). Then, after the build, the namespace is deleted on our Jenkins CI - this ok and required behavior. However, when I then restart the application once again (`restart_kubernetes.sh`), I have no Ouath keys in the container - therefore I am not able to log in on FE as a consequence.

```
Uncaught PHP Exception LogicException: "Key path "file:///var/www/html/project-base/app/../app/config/packages/oauth2/public.key" does not exist or is not readable" at /var/www/html/vendor/league/oauth2-server/src/CryptKey.php line 45 {"exception":"[object] (LogicException(code: 0): Key path \"file:///var/www/html/project-base/app/../app/config/packages/oauth2/public.key\" does not exist or is not readable at /var/www/html/vendor/league/oauth2-server/src/CryptKey.php:45)"}
```

The `backend-api-oauth-keys-generate` phing target is called only during the build but not during the restart - this will be a problem for scaling as well.

Now, to solve it, I need to call the phing target manually on the running instance.

This bug is not present in `master` yet, but it is present in `8.0` branch (since backend API has been introduced in https://github.com/shopsys/shopsys/pull/1055)

### Expected result
Oauth keys and configuration are always available for the application.

**Comment by boris-brtan** [comment]
@vitek-rostislav we agreed that this could be done the same way as parameters.yml via configmap
