### ISSUE TITLE
In composer is wrong PHP version

### ISSUE THREAD

**Issue by adamtyron** [shopsys/shopsys#1178]
### What is happening

In composer is defined fake platform PHP with version 7.1 and docker php-fpm container is builded with PHP version 7.3

https://github.com/shopsys/project-base/blob/master/docker/php-fpm/Dockerfile#L1
https://github.com/shopsys/project-base/blob/master/composer.json#L126

**Comment by vitek-rostislav** [comment]
Hi, thanks for reporting :+1: In `8.0`, the support of PHP 7.1 has been dropped completely and the `platform` setting has been changed to `7.2` (see https://github.com/shopsys/shopsys/pull/1066) TBH, I am not sure why it has not been changed to `7.3`, @TomasLudvik, do you have any information about this please? :slightly_smiling_face:

**Comment by adamtyron** [comment]
This composer config of the element “platform” defines the PHP version for installed packages from composer. 

This element skips checking of the PHP version from server and automatically defines the PHP version as 7.1

https://getcomposer.org/doc/06-config.md#platform

**Comment by boris-brtan** [comment]
yes this is wanted state, because we garantee backward compatibility with php 7.1 and in ssfw 8.0.0 there will be garanteed backward compatibility with 7.2 you can still remove that from your composer.json if you want to.

**Comment by pk16011990** [comment]
I have a question... Is better garantation of your backward compatibility or right version of dependencies on real projects? 
Composer solves dependencies based on this PHP version. Configuration in project-base is the best practice for new project, isn't it?

Shouldn't the backward compatibility be guaranteed by CI server rather then by this configuration?

**Comment by PetrHeinz** [comment]
I would recommend using the enforced PHP version in `config.platform.php` for developing a project, but I'd definitely change that to the least supported version in that particular dev team (along with a change to `require.php`).

This will ensure that when one dev is using different version of PHP, he or she won't update Composer dependencies to versions that are uninstallable on lower PHP versions. The commits of `composer.lock` and resolving conflicts might get messy in the process.

This configuration is not by any means the only way we try to ensure that Shopsys Framework works on all PHP versions it's supposed to.

**Comment by PetrHeinz** [comment]
Well, if every developer on the team uses the same version of PHP (eg. because everybody uses the same Docker image), the problems I mention in https://github.com/shopsys/shopsys/issues/1178#issuecomment-507685505 cannot occur. Maybe in such a case the `config.platform.php` can be safely removed.

I've tried to propose this approach in the upgrade notes improvement in #1270 and I've proposed to remove the option in our demoshop repository during the upgrade to `v8.0.0` in https://github.com/shopsys/demoshop/pull/56.

**Comment by PetrHeinz** [comment]
I've tried to explain this in detail in #1352:

> ## Why is there a faked PHP 7.2 platform in the Composer config?
> As a general rule, packages and libraries that depend on PHP 7.2 will work as expected even on PHP 7.3 (any higher 7.x version), but not vice versa.
> This is the maintainers of PHP focus on backward-compatibility (even if there were [some incompatible changes](https://www.php.net/manual/en/migration73.incompatible.php) introduced in PHP 7.3, in practice it doesn't cause issues).
> 
> Using [the `config.platform.php` option](https://getcomposer.org/doc/06-config.md#platform) in `composer.json` allows us to force Composer to install such dependencies, that work for all supported versions of PHP by Shopsys Framework.
> These dependencies are locked during each release of SSFW so users that install it can download exact versions of all libraries and tools that were tested and proved working.
> This helps to eliminate unforeseen issues during installation.
> See [Composer docs](https://getcomposer.org/doc/01-basic-usage.md#installing-with-composer-lock) for more details on version locking.
> 
> Without this forced platform version, you could encounter issues when working on your project with developers that use a different version of PHP.
> For example, your `composer.lock` could contain dependencies that not all developers can install.
If that's not your case, you can safely remove the `config.platform.php` option from your `composer.json` and run `composer update` to use higher versions of your dependencies.
