### ISSUE TITLE
DBAL cannot connect to PostgreSQL server

### ISSUE THREAD

**Issue by gabyrusu** [shopsys/shopsys#118]
I'm on Windows 10 and installed the app using docker. 
When running `php phing db-create` from the php-fpm container I get this error: 

> ERROR [app] Doctrine\DBAL\Exception\ConnectionException: An exception occurred in driver: SQLSTATE[08006] [7] could not connect to server: Connection refused
        Is the server running on host "postgres" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

Here are my dev params:

```
...
database_host: postgres
database_port: null
database_name: shopsys
database_user: root
database_password: root
database_server_version: 9.5
...
```

PS: I already updated my code to use the changes from commit 013978d

**Comment by MattCzerner** [comment]
Hello @gabyrusu, did you used `docker-compose-win.yml.dist` instead `docker-compose.yml.dist` one, we created new `docker-compose.yml` for windows because there is different usage of `postgres` data volume.

**Comment by gabyrusu** [comment]
I used the windows tempalte and I managed to install the application, but now I have a warning: 

> Warning: rename(/var/www/html/var/cache/dev/doctrine/orm/Proxies/__CG__ShopsysFrameworkBundleModelProductUnitUnit.php.5af9b0fa244258.52778850,/var/www/html/var/cache/dev/doctrine/orm/Proxies/__CG__ShopsysFrameworkBundleModelProductUnitUnit.php): No such file or directory

I deleted the cache with no results.

**Comment by PetrHeinz** [comment]
Hi @gabyrusu, did you try current master, or just the 013978d? There were a bit more changes to the Docker image, see https://github.com/shopsys/shopsys/compare/c2e767dca...54408aa8b. There are a few notes that should help you with the upgrade in https://github.com/shopsys/shopsys/blob/master/project-base/UPGRADE.md.

Please, let us know if you advance any further.

**Comment by gabyrusu** [comment]
Hi @PetrHeinz, all good now. Some directory rights issues. 
Thanks for your help!
