### ISSUE TITLE
Use full PromoCode entity object in QuantifiedProductDiscountCalculation:calculateDiscount

### ISSUE THREAD

**Issue by pesektomas** [shopsys/shopsys#1196]
Method calculateDiscount has two parameters at the moment. First QuantifiedItemPrice $quantifiedItemPrice and string $discountPercent. I think so it would be more comfortable that second parameter wasn't string $discountPercent, but full PromoCode entity.

Why?

I will can use nominal discount for example. I will can very simple update PromoCode entity and administration of promo codes, but when I can use this functionality on frontend, I have to override QuantifiedProductDiscountCalculation at first time, and next: OrderPreviewCalculation and OrderPreviewFactory to be able set full PromoCode entity object into calculateDiscount method (or only set new property).

I will do PR really glad. But I can know your opinions on this issue?

**Comment by vitek-rostislav** [comment]
Hi, to me, it sounds reasonable to pass the whole object there, even though this change will be a BC break.

I would say that since the beginning of the development of the framework, we have rather passed the particular values than the whole objects to methods when possible - one of the reasons might be the fact that it makes the method testable easier.

But in this case, it perfectly makes sense to pass the whole entity. 

What do the others think?

**Comment by pesektomas** [comment]
Rocket emoji means agreement? :smile:

**Comment by henzigo** [comment]
bump

**Comment by pk16011990** [comment]
In my point of view: Passing object instead of values for discount closes way for another kind of discount. For example manual discount from seller etc...

I vote for preserve scalar values

**Comment by pesektomas** [comment]
Thanks @pk16011990, 

I understand correctly that when you have manual discount from seller, you calculate final price by `QuantifiedProductDiscountCalculation:calculateDiscount` without override this method? 

I think that colleagues solve similar problem with using PriceGroups. Right @TomasLudvik, @malymiso? (I think that it is call individula price list?). 

If I have true  passing full PromoCode object into calculateDiscount will not close way for manual discount, right?

But maybe I need to know your use case.

**Comment by pesektomas** [comment]
Hello @pk16011990,

if I think about it again, I have no idea how passing the complete entity to the calculator could somehow affect the later use of individual prices.

Could you please describe an example of use?

**Comment by pk16011990** [comment]
In current version 14 we use array of promo codes and in version 15 is refactored order creation with middlewares - https://github.com/shopsys/shopsys/pull/3084 I hope it solves this problem.
