### ISSUE TITLE
Info about possibility installing API should be in 'Start you project' guide 

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/shopsys#1212]
# What is happening
If you want to use API for your project, you have to install it. But the beginning developer might not know that and might be in a situation that doesn't have API but does not know what to do. 

### Expected result
Info about the installation of API should be in 'Start you project' guide (https://github.com/shopsys/shopsys/blob/master/docs/introduction/start-building-your-application.md)

**Comment by LukasHeinz** [comment]
@simara-svatopluk you did both US, it might be the best option if you do it.

**Comment by simara-svatopluk** [comment]
backend API is a topic that is pretty narrow - maybe not for everyone, maybe not for beginning of the project. So I have a suggestion...

What about **Check our modules?** a headline with link to modulstore + link to backend API. This section will be prepared for further extension, is general and will provide information almost for all implementators

**Comment by LukasHeinz** [comment]
You are right that backend API is a pretty narrow topic. On the other hand, it is one of the very important topics for SSFW clients and developers will want to check it. And I feel it as with settings of domains - it is much better to start your project with API than to add it in the middle of implementation. 

I will want to add a section about Feature Marketplace when it will be public. But those are modules that might help you ease the implementation of your project. But The AIP might decide if you want to use SSFW at all...

**Comment by simara-svatopluk** [comment]
When I read your arguments, the only valid is
> And I feel it as with settings of domains - it is much better to start your project with API than to add it in the middle of implementation.

Following two arguments aren't related to adding API to "Start building your project"
> On the other hand, it is one of the very important topics for SSFW clients and developers will want to check it.
> But The AIP might decide if you want to use SSFW at all

This article is "Start building your project" and it's aiming to programmers who already started with the implementation. Not to those who are choosing platform. It's true that API is important, but when you read this article, you have already chosen the SSFW.

**Comment by LukasHeinz** [comment]
> This article is "Start building your project" and it's aiming to programmers who already started with the implementation.

I do not feel the same way. If you are developer want to discover SSFW, what you will do after installation? You go to the next article which is `Start building your project`. Right?

**Comment by simara-svatopluk** [comment]
I don't like articles that have multiple purposes. It's impossible to stay as clear as possible while keeping the information as short as possible. So the result is an article that doesn't have flow and have mixed information.

Anyway... You described your use-case clearly, you probably need "Discover SSFW" article that will be for developers that need to decide whether they will use the SSFW. And in this article probably won't be information about setting domains, locales, ...

**Comment by LukasHeinz** [comment]
I believe we need a 3rd party, what about @vitek-rostislav

**Comment by vitek-rostislav** [comment]
Hi guys, after reading your discussion, to me, it makes sense to add the subsection as @simara-svatopluk suggested:
> Check our modules? a headline with link to modulstore + link to backend API

However, as we do not have the public modulestore yet, I would create a new subsection at the end of the article, just about the API, something like this:

## Set up default currency
...
...
## Think about the usage of backend API
Shopsys Framework provides backend API that is not installed by default. However, when you start building your application, it is a good time to think about its usage...etc
