### ISSUE TITLE
There is deprecation in prepared new major version (8.0.0) 

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/shopsys#1213]
### What is happening

During resolving deprecation in preparation of new major #1193 there was one deprecation left.

There is a lot of opinions about whether this is good.

UPDATE: there are more deprecations than just one.

### Expected result

It should be resolved or there should be a strong explanation of why to leave it here.

**Comment by PetrHeinz** [comment]
If you're talking about deprecated method `\Shopsys\MigrationBundle\Component\Doctrine\Migrations\AbstractMigration::addSql`, I would actually remove the deprecation notice and let it just throw the `MethodIsNotAllowedException`.

https://github.com/shopsys/shopsys/blob/2b4ff8fde97e61781ec656392cde68373b101b0e/packages/migrations/src/Component/Doctrine/Migrations/AbstractMigration.php#L8-L18

It's not deprecated as in *"this code will not be supported very long - use the new method"* but rather *"this doesn't work and it never will - use that other method"*. For that, throwing the exception is enough imo.

I would just recommend doing this:
```diff
    /**
     * {@inheritDoc}
-    * @deprecated use "sql" method instead
     */
    protected function addSql($sql, array $params = [], array $types = [])
```

**Comment by boris-brtan** [comment]
hi @PetrHeinz ,
no that was about the deprecation that is mentioned in PR descritpion `One deprecated thing we kept, it is CartController:addProductFormAction since it is still used in productDetail but we have a plan to reimplement it with the new CartController:productActionAction.` we have not come to an agreement whether we want to keep it annotated as deprecation or not, since it is still used for product detail.

**Comment by LukasHeinz** [comment]
There are more deprecations in master as mentioned in #1214 (CartController::addProductFormAction and some methods in StrictWebDriver). I believe that deprecation is something that should be removed but these things will be in a product for some time. I recommend to resolve it all.
