### ISSUE TITLE
Cron / console error shoposys 7.0.0 native instalation

### ISSUE THREAD

**Issue by jan-oliva** [shopsys/shopsys#1223]
**Shopsys version 7.0.0 in production with native instalation**

07:57:03 ERROR     [app] Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function get() on null (uncaught exception) at ..bikerstyle-cz-beta/packages/framework/src/Model/Cart/CartMigrationFacade.php line 77 while running console command `shopsys:cron` ["exception" => Symfony\Component\Debug\Exception\FatalThrowableError { …}]

07:57:03 ERROR     [console] Error thrown while running command "shopsys:cron". Message: "Call to a member function get() on null" ["exception" => Error { …},"command" => "shopsys:cron","message" => "Call to a member function get() on null"]

07:57:03 ERROR     [app] Command `shopsys:cron` exited with status code 1
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function get() on null in bikerstyle-cz-beta/packages/framework/src/Model/Cart/CartMigrationFacade.php:77

**php bin/console**

[Symfony\Component\Debug\Exception\ContextErrorException]                                                                                   
  Warning: Declaration of Redis_ca5fc0f::psubscribe(array $patterns) should be compatible with Redis::psubscribe(array $patterns, $callback)

**Web UI works.**

**In dev version Docker instalation cron works**

**Notes**
When run `php phing clean` and the first time run `php bin/console` (before any web request), console works, but web UI not WORKS with the same errors

When run `php phing clean` and the first time run Web UI (web reauest), WEB UI works, but console  not works same errors

**Comment by boris-brtan** [comment]
hello @jan-oliva ,
can you check version of redis and redis vendors package on Docker and native installation ?
for vendor you can use `composer info`

**Comment by henzigo** [comment]
Hello, which version of Redis extension do you have installed? It seems like you have an older version then application requires.

**Comment by jan-oliva** [comment]
composer info
snc/redis-bundle                             2.1.9    A Redis bundle for Symfony

System
Redis server v=3.2.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=a2cab475abc2115

**Comment by jan-oliva** [comment]
I tried downgrade to snc/redis-bundle 2.1.8 (original in v 7.0.0) and problem persist

**Comment by boris-brtan** [comment]
hmmm, it is better to set the same environment on natively installed production as on Docker.
You will prevent the bugs that will be visible only on production. You can check and use commands for installation and update of all the tools in Dockerfile of the docker working version.

**Comment by jan-oliva** [comment]
When mode set prod (shopsys:environment:change) and web UI run in prod
and use --env=dev `php bin/console --env=dev` console run normally

In other words when web and console use different env all works normally.

**Comment by jan-oliva** [comment]
Problem was solved.
Reason:
PHP cli used redis ext. version 4.3.0, but fpm used used redis ext. version 4.2.0 and cached service is shared for cli and fpm. Redis ext. 4.3.0 has chaned interface Redis::psubscribe()

Before some days I was run apt-get upgrade, without reboot server and php-fpm services used older vesion of redis extension in memory.

My error :(

**Comment by vitek-rostislav** [comment]
Hi, thanks for letting us know :+1:
