### ISSUE TITLE
Order cannot be sent with success flash message

### ISSUE THREAD

**Issue by pk16011990** [shopsys/shopsys#1235]
### What is happening
Imagine use case, when project needs simple success flash message in all order steps. Adding success flash message solves this requirement, but order cannot be sent. It is weird in the first moment.

Order cannot be sent with existing any frontend flash message. It is OK for error messages and info messages but success messages should not stop the order from being sent, I think.

### Expected result
Order cannot be sent only with error or info flash message. Or order can be sent with success flash message.

**Comment by pk16011990** [comment]
.

**Comment by s3tezsky** [comment]
Solved in mentioned PR
