### ISSUE TITLE
Do not allow destructive phing actions in production without warning

### ISSUE THREAD

**Issue by pk16011990** [shopsys/shopsys#1236]
### What is happening
When developer has open more consoles and one of them is in production environemnt, there is chance for running a destructive phing command in production. I do not wish anyone that feeling :smile: 

### Expected result
All destructive phing targets cannot be run without a obstacle. 
We used somethinkg like:
```xml
    <target name='check-dev-enabled'>
        <if>
            <and>
                <isset property="enable-dev-commands" />
                <equals arg1="${enable-dev-commands}" arg2="false" />
            </and>
            <then>
                <fail message = "You can't use this command. If you want to use it you have to edit build.local.properties file."/>
            </then>
        </if>
    </target>
```
and set it like dependency for actions: `build-new`, `build-demo`, `db-create` etc...

**Comment by vitek-rostislav** [comment]
resolved in #1368 (will be released in `9.0`)
