### ISSUE TITLE
[product-feed-zbozi] and [product-feed-heureka] have dependency on project/base

### ISSUE THREAD

**Issue by pk16011990** [shopsys/shopsys#1237]
### What is happening
Packages [product-feed-zbozi] and [product-feed-heureka] have data fixtures with a demo data and dependencies on datafixtures in project-base (hardcoded ids of products and categories).

When project base has changed demo data, it fails on Heureka/Zbozi feed. Solution is disable whole datafixtures from these packages and copy-pase...

### Expected result
[product-feed-zbozi] and [product-feed-heureka] don't dependency on project-base or hardcoded ids can be overridden.

**Comment by henzigo** [comment]
Let's play a game. You will close issue and i will shoot you.
