### ISSUE TITLE
Default values of entity properties should not be set using Doctrine

### ISSUE THREAD

**Issue by PetrHeinz** [shopsys/shopsys#1242]
### What is happening
Currently (as of `v7.3.1`) we use Doctrine default values for 5 properties (see below).

Configuring default values in ORM is not really a best practice. Doctrine should shield the model from the database and having default values configured at the DB level achieves the exact opposite.

Doctrine docs mention that it's not supported to set the default value (see [the official docs](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/faq.html#how-can-i-add-default-values-to-a-column)) - that's why it has to be done via the `options={"default" = <value>}` parameter.

Default values should be defined in the entity constructor (or directly as a default value of the parameter itself) or the data object. Remember that in the best-case scenario, entities should work without the ORM or the DB itself as said by Marco Pivetta (Ocramius) in [Doctrine best practices](http://ocramius.github.io/doctrine-best-practices/#/26).

Imagine you create a new entity and try getting the attribute:
- If it has it's default value only defined at the DB level, you're gonna end up with a `TypeError` (or worse with `NULL`).
- If it has a default value only in constructor you will be fine - you'll get the default as expected.
- And if it has the default set both in constructor and on the DB level you'll be fine - but you'll be in danger of those two default values being changed to different values as it is a DRY violation.

Furthermore, it poses a problem for [entity extension](https://github.com/shopsys/shopsys/blob/v7.3.1/docs/extensibility/entity-extension.md) as annotation cannot be easily overriden (even though we managed to [get that working on our demoshop by overriding `LoadORMMetadataSubscriber` class](https://github.com/shopsys/demoshop/blob/master/src/Shopsys/ShopBundle/Component/EntityExtension/LoadORMMetadataSubscriber.php)).

### Expected result
There are no default values defined using the ORM, or their correct usage is documented (if there is a valid reason for that).

Default values are only defined on the DB level in migrations and the the end of the migrations, they are removed.

---

https://github.com/shopsys/shopsys/blob/aef43bab59ad65d8f0cfecd80b563ab3a91c35a4/packages/framework/src/Model/Product/Product.php#L187-L192
https://github.com/shopsys/shopsys/blob/aef43bab59ad65d8f0cfecd80b563ab3a91c35a4/packages/framework/src/Model/Product/Product.php#L221-L233
https://github.com/shopsys/shopsys/blob/aef43bab59ad65d8f0cfecd80b563ab3a91c35a4/packages/framework/src/Model/Newsletter/NewsletterSubscriber.php#L39-L43
https://github.com/shopsys/shopsys/blob/aef43bab59ad65d8f0cfecd80b563ab3a91c35a4/packages/framework/src/Component/Cron/CronModule.php#L28-L33

**Comment by PetrHeinz** [comment]
Maybe we could create a sniff for that (possible inspiration: `OrmJoinColumnRequireNullableFixer`)...

**Comment by pk16011990** [comment]
.

**Comment by pk16011990** [comment]
.

**Comment by imhimanshuk** [comment]
Hi @PetrHeinz,

I hope that will work for your entity class. Use the default values in your entity class like this.

 ```
/** 
  * @var bool 
  * 
  *[@ORM\Column(type:"boolean", options:["default" => true])]
  */ 
  protected $recalculateAvailability; 
```

**Comment by mindaugasvcs** [comment]
It's suggested to use Entity Lifecycle Callbacks with Dependency Injection to get a default value for things like resource location BUT if such properties are on a User Entity it can be problematic as User can be loaded from session AND / OR using custom queries skipping Doctrine and Entity Lifecycle events altogether.

**Comment by grossmannmartin** [comment]
@imhimanshuk  
The issue is about the opposite. The default option in the doctrine annotations is not a fit for the application, as the correct state of the entity depends on the roundtrip to the database.
That's why we decided to drop the `default` option in favor of the default value set by the code. 

@mindaugasvcs 
Lifecycles may have a proper usage, but I don't think obtaining the default value is the one. 
If a complex logic needs to be evaluated to get the default value, the Factory pattern is usually a better choice.
