### ISSUE TITLE
DailyFeedCronModule Call to a member function sleep() on null -  shopsys 7.0.0

### ISSUE THREAD

**Issue by jan-oliva** [shopsys/shopsys#1253]
**I have problem with DailyFeedCronModule**

Error output

BUILD FAILED
/var/www/projects/pixeldesign.cz/bikerstyle-cz-beta/project-base/build.xml:174:85: Task exited with code 1

Total time: 1.2841 second

12:24:11 DEBUG     [cron] Feed "zbozi" generated on domain "bikerstyle.cz CZ" into "/web/content/feeds/jGC2l1XEhu_zbozi_1.xml".

12:24:11 ERROR     [app] Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function sleep() on null (uncaught exception) at /var/www/projects/pixeldesign.cz/bikerstyle-cz-beta/packages/fram
ework/src/Model/Feed/DailyFeedCronModule.php line 107 while running console command `shopsys:cron` ["exception" => Symfony\Component\Debug\Exception\FatalThrowableError { …}]

12:24:11 ERROR     [console] Error thrown while running command "shopsys:cron". Message: "Call to a member function sleep() on null" ["exception" => Error { …},"command" => "shopsys:cron","message" => "Call to a
 member function sleep() on null"]

12:24:11 ERROR     [app] Command `shopsys:cron` exited with status code 1
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function sleep() on null in /var/www/projects/pixeldesign.cz/bikerstyle-cz-beta/packages/framework/src/Model/Fee
d/DailyFeedCronModule.php:107

Stack trace:

#0 /var/www/projects/pixeldesign.cz/bikerstyle-cz-beta/packages/framework/src/Component/Cron/CronModuleExecutor.php(52): Shopsys\FrameworkBundle\Model\Feed\DailyFeedCronModule->sleep()

#1 /var/www/projects/pixeldesign.cz/bikerstyle-cz-beta/packages/framework/src/Component/Cron/CronFacade.php(130): Shopsys\FrameworkBundle\Component\Cron\CronModuleExecutor->runModule(Object(Shopsys\FrameworkBund
le\Model\Feed\DailyFeedCronModule), false)

#2 /var/www/projects/pixeldesign.cz/bikerstyle-cz-beta/packages/framework/src/Component/Cron/CronFacade.php(99): Shopsys\FrameworkBundle\Component\Cron\CronFacade->runModule(Object(Shopsys\FrameworkBundle\Compon
ent\Cron\CronModuleExecutor), Object(Shopsys\FrameworkBundle\Component\Cron\Config\CronModuleConfig))

#3 /var/www/projects/pixeldesign.cz/ in /var/www/projects/pixeldesign.cz/bikerstyle-cz-beta/packages/framework/src/Model/Feed/DailyFeedCronModule.php on line 107

BUILD FAILED
/var/www/projects/pixeldesign.cz/bikerstyle-cz-beta/project-base/build.xml:174:85: Task exited with code 255

------------------------
Output of
**php bin/console** 
Symfony 3.4.29 (kernel: app, env: prod, debug: false)

**php -v**
PHP 7.3.3-1+0~20190307202245.32+stretch~1.gbp32ebb2 (cli) (built: Mar  7 2019 20:22:46) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.3, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.3-1+0~20190307202245.32+stretch~1.gbp32ebb2, Copyright (c) 1999-2018, by Zend Technologies

**Comment by vitek-rostislav** [comment]
Hi, I am sorry for the late response, is this problem still bothering you? If so, could you please tell me which version of the framework are you using? 

It seems like you are in some weird invalid state, as I see that `$this->currentFeedExport` is null in `sleep()` method, however, `iterate()` method that is run in the first place initializes the `$currentFeedExport` property :thinking: see https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Component/Cron/CronModuleExecutor.php#L43-L52

**Comment by grossmannmartin** [comment]
#1651 could be cherry-picked into next 7.3.x patch as it's not BC break.

**Comment by grossmannmartin** [comment]
closed as it was backported and released in v7.3.5
