### ISSUE TITLE
Change product attributes sellingFrom and sellingTo to datetime

### ISSUE THREAD

**Issue by simara-svatopluk** [shopsys/shopsys#1258]
### What is happening

Product attributes `sellingFrom` and `sellingTo` are currently `date`. But API requires datetime for import. This state is confusing becuase you can import `2000-01-16T12:34:56+00:00`, but database will contain only `2000-01-16` and when you fetch the product via API, you'll get `2000-01-16T00:00:00+00:00`.

### Expected result

Product owner suggested to change `sellingFrom` and `sellingTo` to `datetime`, so import works correctly. We don't have to do anything with administration - it can use dates only.

This change is problably BC, because we'll extend `date` to `datetime`.

**Comment by pk16011990** [comment]
`sellingFrom` and `sellingTo` are `date` for easier recalculation of product visibilities. Recalculation is necessary only after midnight. `datetime` will come with complication when do the recaclulation or `sellingFrom` and `sellingTo` have to be check during request...

Is there an important reason for `datetime` in API instead simple `date`?

**Comment by grossmannmartin** [comment]
Changed in #1343
