### ISSUE TITLE
Overriding services with many dependencies

### ISSUE THREAD

**Issue by malyMiso** [shopsys/shopsys#1261]
I would like to simplify working with overriding services with many dependencies (e.g `ProductFace`) in projects.

### What is happening
When you want override a service with a new custom service, you have to override constructor with all its dependencies. I don't even need them, but it has to be done to be able to call parent constructor. 

E.g if you override `ProductFacade` it adds about 20+ dependecies, after that you can add your new dependency.
It looks like:
```
class Project\ProductFacade extends SSFW\ProductFacade
{
    /**
     @var Project/MyOwnService
    **/
    private $mos;

    public function __construct(
        Doctrine\EntityManagerInterface $em,
        SSFW\ProductRepository $productRepository,
        ....
        Project/MyOwnService $mos;
     ) {
        parent::__construct($em,$productRepository,....);
        $this->mos = $mos;
     }
}
```
If service from framework contains a lot of depdencies, it is a little bit difficult to read the code and identify which services are from SSFW and which is from project itself.

### Expected result

I was thinking about wrapper for services (maybe for those, which contain a lot of dependecies ?) from SSFW. Something like
```
class SSFW\ProductFacadeDependecy
{
    /**
     @var Doctrine\EntityManagerInterface
    **/
    protected $em;
    
    /**
     @var SSFW\ProductRepository
    **/
    protected $productRepository;

    public function __construct(
        Doctrine\EntityManagerInterface $em,
        SSFW\ProductRepository $productRepository,
        ....
     ) {
        $this->em = $em;
        $this->productRepository = $productRepository;
        ....
     }
}

class Project\ProductFacade extends SSFW\ProductFacade
{
    /**
     @var Project/MyOwnService
    **/
    private $mos;

    public function __construct(
        SSFW\ProductFacadeDependecy $pfd
        Project\MyOwnService $mos;
     ) {
        parent::__construct($pfd);
        $this->mos = $mos;
     }
}
```
IMHO it will clean a code little bit and become much more friendly for PRG :slightly_smiling_face: 

What do you think ?

**Comment by vitek-rostislav** [comment]
Hi, to me, it makes sense, however, it would probably require some deeper investigation and research to decide which classes deserve such a dependency wrapper. If you have any suggestions besides the `ProductFacade`, it will be nice if you mention them here. The implementation itself should be really easy :+1:

**Comment by malyMiso** [comment]
Hi @vitek-rostislav, This gave me an idea, what about to define a new standard for checking it (just for SSFW, not for projects). If service has more than e.g. 5 dependencies (some constant), coding standards check will fail. Suggestion can be shown to programmer how to solve that, or if it is easy to create sniffer for it, it will be absolutely great. 
It would help you to find out other services like `ProductFacade`. 

If you are not interested, I can look into our projects and look for other services

**Comment by vitek-rostislav** [comment]
Hi @malyMiso, thanks for the suggestion, it might be a solution (however, I can imagine we would need to exclude some classes from the checks but why not, it is doable :slightly_smiling_face:) 

As the solution seems quite complicated either way, I have created a user story and I am sending it to evaluation. I will let you know once there is any progress with that :wink:

**Comment by grossmannmartin** [comment]
I'm not a fan of the wrapper of dependencies. I think it just hides the bad design of a class.
I would like to see ProductFacade separated into several classes instead of one god-facade. But I understand it's convenient now just use one facade when I need to work with products.

Maybe we could inject dependencies in the framework with setter injection (https://symfony.com/doc/current/service_container/calls.html) and leave the constructor free for extensibility.
