### ISSUE TITLE
Promo code is custom instance of OrderItem

### ISSUE THREAD

**Issue by malyMiso** [shopsys/shopsys#1263]
This issue was discussed once, in https://github.com/shopsys/shopsys/issues/355, it was closed and today we can create new instance of `OrderItem` with new order item type for promo code. 
### What is happening

Promo codes are still used in SSFW and have type `OrderItem::TYPE_PRODUCT`, it is confusing. 

It is worth to mention one more point:
There is no relation between promo code `OrderItem` and product `OrderItem` to which it belongs to. From my experience with working with promo codes, there should exists such a relation.

Why ?
Many projects, which we implemented, work with discount per product. We should send them product and its discount. Now we have to override working with promo codes from stabil. 
1. add new order item type
2. allow have a relation between order items

one more example from project, we are currently implementing: gifts. 
Some products can have associated gift with special price. So we created new order type, but also we had to define relation between order items (if you remove main order items, its gift shoul be also removed).  

### Expected result
1. there exists new order type item `OrderType::TYPE_PROMO_CODE`
2. there exists relation between order items (promo code discount is related to certain product)

If you are interested, maybe we can provide PR for this issue, from project, where we solved it

**Comment by vitek-rostislav** [comment]
Hi, the PR would be awesome :grin:

**Comment by pk16011990** [comment]
Stale bot, #1563 solves this issue...

**Comment by pk16011990** [comment]
It's related with https://github.com/shopsys/shopsys/pull/1563 and I should be resolved in this PR. -> I'm closing this issue as a duplicate.
