### ISSUE TITLE
Inline editation doesn't match ours needs

### ISSUE THREAD

**Issue by malyMiso** [shopsys/shopsys#1267]
### What is happening

In current state promo codes are edited by inline editation. Many projects, we have been working on, require advanced promo codes. Usually we meet with requirements like:
- different types of promo codes (promo code by percentage or nominal value)
- validity of promo code
- usage limit for promo code (unlimited, one time usage, ...)
- other limitations (maximum of usage, minimal nominal value...)
- etc.
It is not very user friendly to edit all this settings by inline editation.

### Expected result

I think it would be great to change promo code inline editation to classic form editation (edit promo code on detail page) in SSFW itself. It will save a lot of time to programmers to switch from inline edition to classic form editation

**Comment by vitek-rostislav** [comment]
Hi, thanks for reporting, this seems to me to be very reasonable and I am voting for the change :+1:
