### ISSUE TITLE
Resetting filter in pop-up product picker in administration leads to end of product picking

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/shopsys#1274]
### What is happening
Administration > Product > Product Detail I am trying to add new accessories. I click to "Add Products", open "Advanced Filter" and click "Reset Filter". Then the content of popup window reloads and standard product overview appears in the popup so I am not allowed to finish assigning accessories. 

### Expected result
After clicking on "Reset Filter" the content of pop up should remain the same, just the condition of advanced filter should be removed. And I should be able to continue in assigning accessories.

**Comment by PetrHeinz** [comment]
Fixed in #1311.
