### ISSUE TITLE
Use AdvancedUserInterface instead of UserInterface

### ISSUE THREAD

**Issue by sspooky13** [shopsys/shopsys#1275]
### What is happening
Why we don't use [AdvancedUserInterface ](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/User/AdvancedUserInterface.php) instead of [UserInterface](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/User/UserInterface.php)?
If we used [AdvancedUserInterface ](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/User/AdvancedUserInterface.php) then we could simplify logic for logout administrators, e.g. [here](https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Model/Administrator/Security/AdministratorUserProvider.php#L81-L88).
I agree it's not extra additional value but why not use it when it's an official option, right? 😁 
And IMHO this functionality doesn't complicate user login logic and future developers can use this option when they need to log out users, block users, etc.

What do you think?

### Expected result
[User](https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Model/Customer/User.php) or [Administrator](https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Model/Administrator/Administrator.php) implements [AdvancedUserInterface ](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/User/AdvancedUserInterface.php) instead of [UserInterface](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/User/UserInterface.php)

**Comment by sspooky13** [comment]
By the way If we use [AdvancedUserInterface](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/User/AdvancedUserInterface.php) then we can remove [TimelimitLoginInterface](https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Model/Security/TimelimitLoginInterface.php) 😁

**Comment by vitek-rostislav** [comment]
Hi, makes sense to me :+1:

**Comment by sspooky13** [comment]
Hmm, now I have more experience with SS7+ so you can expect PR in the near future for this feature 😊

**Comment by TomasLudvik** [comment]
@sspooky13 that would be great! Thank you

**Comment by sspooky13** [comment]
Hello,
[AdvancedUserInterface](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/User/AdvancedUserInterface.php) doesn't work as I expected 😐. He checks user is enabled/expired/... only when signing in. Of course, he uses it always but I don't understand what exactly does 🤔☹.
I can modify that somehow, however, Symfony set [AdvancedUserInterface](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/User/AdvancedUserInterface.php) as deprecated and in Symfony 5.0+ is removed as you can read here https://symfony.com/blog/new-in-symfony-4-1-deprecated-the-advanceduserinterface.

For that, I think it makes no sense to edit [User](https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Model/Customer/User.php) or [Administrator](https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Model/Administrator/Administrator.php) since that interface will be deleted.
But if you're still interested or make sense for you I can finish my edit for those entities but I don't recommend it because although we delete [TimelimitLoginInterface](https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Model/Security/TimelimitLoginInterface.php) he brings a few hacks 😐. If you don't want this, close this issue.

Thanks 🤝
