### ISSUE TITLE
Adding requiement in advanced search in administration leads to graphic glitch with selectboxes

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/shopsys#1279]
### What is happening
Administration > Product Overview: when I use the advanced search and add a requirement, there appears a new row but it is broken and cannot be used. see below
<img width="1005" alt="Snímek obrazovky 2019-08-02 v 10 53 04" src="https://user-images.githubusercontent.com/33071107/62357617-bb20b600-b513-11e9-861e-154ece73f8e4.png">

### Expected result

It looks good and I can use more requirements in the advanced filter 😄

**Comment by PetrHeinz** [comment]
Fixed by #1307
