### ISSUE TITLE
How to create and maintain custom Elasticsearch indexes?

### ISSUE THREAD

**Issue by pk16011990** [shopsys/shopsys#1287]
### What is happening
I need to create new index in Elasticsearch for my project. SSFW has prepared some methods for creating/migrating/deleting indexes, however there is only command `product-search-migrate-structure`. 

1. Name of this command is wrong. The command doesn't apply to searching only

2. When I want another index rather than products in Elasticsearch, I can not use command `product-search-migrate-structure`. It does not support neither easy extension nor automatic loading of all definitions in `project-base/src/Shopsys/ShopBundle/Resources/definition/*/*.json`

Automatic loading would have a problem with non-multidomain indexes... :-/

### Expected result
Existing target for all Elasticsearch structure migrations (like DB migrations)

**Comment by pk16011990** [comment]
.

**Comment by grossmannmartin** [comment]
resolved with #1622 
Also, you can check new cookbook (https://docs.shopsys.com/en/latest/cookbook/adding-a-new-elasticsearch-index/) how to create a new elasticsearch index
