### ISSUE TITLE
Link to advanced product search on dashboard is not working

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/shopsys#1293]
### What is happening
Administration > Dashboard: Next to wuick product search there is a link to advanced search. It is not clickable any more.

<img width="1228" alt="Snímek obrazovky 2019-08-05 v 14 23 59" src="https://user-images.githubusercontent.com/33071107/62464512-1c9f8980-b78d-11e9-9bd0-73687a6b8026.png">

### Expected result
After clicking to "Advanced search" I should be redirected to Product Overview with opened advanced search tab. This functionality worked before 8.0.0 release.

**Comment by TomasGottvald** [comment]
This issue is acctually resolved on master branche. Closing.
