### ISSUE TITLE
In administration popups the headings are not centered

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/shopsys#1297]
### What is happening
In administration popups: if there is a heading is not centered to a popup box, but centered between left end of box and closing cross.

This type of box appears in in-line edition when you delete the item that is assigned to some entity e.g. status of order.

<img width="525" alt="Snímek obrazovky 2019-08-05 v 14 46 11" src="https://user-images.githubusercontent.com/33071107/62465911-5625c400-b790-11e9-9d3a-0f8d30aa5092.png">

### Expected result
The heading should be centered to a box.

**Comment by TomasGottvald** [comment]
We should resolve it

**Comment by TomasGottvald** [comment]
I just tested this popup on respo version. 

![image](https://user-images.githubusercontent.com/35454496/80320406-82014200-8816-11ea-87b9-950d21b72e4e.png)

Seems to be ok. I added new status, when I want to delete it - there is no title. Maybe we should unify this popup content.
