### ISSUE TITLE
unnecessary protected attributes in data fixtures

### ISSUE THREAD

**Issue by pk16011990** [shopsys/shopsys#1315]
### What is happening
Data fixtures (eg. `Shopsys\ShopBundle\DataFixtures\Demo\CurrencyDataFixture`) have protected class attributes. I think that is unnecessary. It is a remnant of the time when it was part of `shopsys/framework`.

### Expected result
Attributes in project-base data fixtures are private. 

If you agree I will create PR.

**Comment by vitek-rostislav** [comment]
Hi, from the best-practices point of view, it makes sense to me :+1: :slightly_smiling_face:

**Comment by LukasHeinz** [comment]
We will be happy if you create this PR.

**Comment by pk16011990** [comment]
reopen, because PR #1640 is still open

**Comment by grossmannmartin** [comment]
closed, because PR #1640 is merged
