### ISSUE TITLE
Admin>Product detail: when validation fails, there are no categories

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/shopsys#1331]
### What is happening
1. Admin > Products: I click on create new product
2. I click "Create" in the fixed/floating footer
3. The page refreshed and I see Product detail with info "Please check the correctness of all data filled." (I didn't choose availability)
4. In "Assign to category" there are no categories available
![Snímek obrazovky 2019-08-16 v 10 14 45](https://user-images.githubusercontent.com/33071107/63153490-b299a680-c00e-11e9-8097-38812b481aad.png)

### Expected result
The categories should be there as was before validation failed.

**Comment by TomasLudvik** [comment]
The main problem here are that data, sent by the user do change data in collection and this leads to differently displayed CategoriesType after submit. ProductData->categoriesByDomainId should be used only for checking checkboxes in form but not for rendering form type itself. Rendering should be done via template.

We tried to fix handling of data in #1394 with @sspooky13 but it lead to other problems with Collection in ProductParameterValueType. 

It is possible, that after reworking CategoiesType we might be able to drop our changed implementation of ResizeFormListener and CollectionType.

**Comment by LukasHeinz** [comment]
ping
