### ISSUE TITLE
Admin > Product detail: availability validation is not in popup notification

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/shopsys#1332]
### What is happening
1. Admin > Products: I click on create new product
2. I click "Create" in the fixed/floating footer
3. The page refreshed and I see Product detail with info "Please check the correctness of all data filled." (I didn't choose availability)

Generally, when validation is not passing after I click create, there is popup notification what part of form (what inputs or sections) is not valid. To reproduce, just change "Use stocks:" to Yes and submit form again.

### Expected result

The information that avaliablity is not set up should be in popup notification as the rest of form.

**Comment by LukasHeinz** [comment]
It’s a bug...

**Comment by grossmannmartin** [comment]
Already fixed
