### ISSUE TITLE
Duplicate flash message in error pop-up windows

### ISSUE THREAD

**Issue by tmandok** [shopsys/shopsys#1341]
### What is happening
A duplicate flash message appears if "ENTER" key is pressed in error pop-up window (steps are described in the screenshot below).

![_bug-flashmessage](https://user-images.githubusercontent.com/54270897/63331715-90699680-c336-11e9-86c4-b98d68c980f4.png)

Screenshot URL: https://prnt.sc/ouzvwx

Tested on:
- Windows 10 Pro (version 1903) 64-bit
- Google Chrome 76.0.3809.100, Firefox 68.0.2, Microsoft Edge 44.18362.267.0

### Expected result
Only one validation error message is displayed.

**Comment by LukasHeinz** [comment]
Thank you for reporting this issue. I tested it and I confirm your experience.

**Comment by sspooky13** [comment]
Don't close this if is still not fixed 😠😁

**Comment by s3tezsky** [comment]
Fixed in #1970
