### ISSUE TITLE
default 'access_denied_url' in security.yml

### ISSUE THREAD

**Issue by DavidOstrozlik** [shopsys/shopsys#1347]
### What is happening
We don't have defaultly set `access_denied_url` in `security.yml` so every time user or administrator doesn't have right to access something he is redirected to 404 page and that shouldn't happen

### Expected result

`access_denied_url` should be set for some default controller action that adds flash message about not having the rights for that

**Comment by grossmannmartin** [comment]
Closing as it's resolved in #1504 and merged into the next major version (9.0).
