### ISSUE TITLE
Messy links in sections in admin

### ISSUE THREAD

**Issue by DavidOstrozlik** [shopsys/shopsys#1348]
### What is happening
There is a mess with links in sections in administration.
Every page in product section has url like "/admin/product/*"
but there are other product related pages with urls like "/admin/product/top-product/list/" in the marketing section so it makes it harder to restrict administrator for accessing the whole section (eg. /admin/product/ as you restrict him from other pages in other sections as well (/admin/product/top-product/list/)

### Expected result

URLs should be prefixed with what section they are at (eg. /admin/marketing/top-product/list/)

**Comment by LukasHeinz** [comment]
I like this idea not only for the security part but also for making the structure clear. What do you think @PetrHeinz ?

**Comment by PetrHeinz** [comment]
That would make sense :+1:

**Comment by DavidOstrozlik** [comment]
ping
