### ISSUE TITLE
roles are not saved to administrator

### ISSUE THREAD

**Issue by DavidOstrozlik** [shopsys/shopsys#1349]
### What is happening
Right now administrator can have one of 2 roles (Admin/Superadmin). 
If you want to add more roles to administrator you need add new `roles` field to administrator so you can work with them (eg. assign them when editing administrator)

eg. [admin restriction prototype](https://github.com/shopsys/project-base/commit/7a1c3c56d096f045383725a263f445b76fbed2ab)

### Expected result

Do we want to work with roles the same way as before or do we want to have them saved to administrator for it could be easily extended?

**Comment by grossmannmartin** [comment]
Closing as it's resolved in #1504 and merged into the next major version (9.0).
