### ISSUE TITLE
Unique identification of error 500 on error page

### ISSUE THREAD

**Issue by thirdknown** [shopsys/shopsys#1365]
It is very sad when PO or client tell me "There was 500, we did this and that..." without specifying date and time (nobody knows it), then I must search it in logs and I don't know what and where to find.

Better solution: show unique identification of error (e.g. "4cfd564fd5sdf") on error page. PO or client could tell me "4cfd564fd5sdf" and I could find it in logs.

**Comment by PetrHeinz** [comment]
This might not be as straight-forwarward as it seems as error pages get served from generated html... This is to avoid further errors during error handling (eg. no access to DB). But I think there could be some way to resolve it 🙂
