### ISSUE TITLE
Fixer to ensure new line at the end of file

### ISSUE THREAD

**Issue by grossmannmartin** [shopsys/shopsys#1367]
### What is happening
We have a common rule to end each file with a new line and often it's reminded during CR.

Such a rule should be enforced automatically with coding standards.

Fixers exist as `\PHP_CodeSniffer\Standards\Generic\Sniffs\Files\EndFileNewlineSniff` and `\PhpCsFixer\Fixer\Whitespace\SingleBlankLineAtEofFixer`but they don't check all files but PHP only (yaml, less, md files should be checked too).

_Note: Why to end files with a new line: 
https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file 
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline_
_Note: PHPStorm can be configured to do that_

### Expected result
Newline at the end of every file should be checked during `standards` check.

**Comment by sspooky13** [comment]
Please don't close this, I will be glad if this issue will be solved.
