### ISSUE TITLE
Admin> Product Detail: main URL is not marked

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/shopsys#1375]
### What is happening
Admin> Product Detail: the main URL for each domain should be marked (as selected radio button). But it isn't:
![Snímek obrazovky 2019-09-05 v 15 10 26](https://user-images.githubusercontent.com/33071107/64344796-7810a180-cfef-11e9-91fc-ac7036b42fb6.png)

I believe it is a bug after the introduction of new radio button design

### Expected result
The main URL for each domain is marked

**Comment by TomasGottvald** [comment]
I tried to add attribute checked="checked" to hidden input, result was OK. Can anyone check if there is correctly assigned attribute checked?

**Comment by henzigo** [comment]
Hello @TomasGottvald, have you plan to do something with this issue?

**Comment by TomasGottvald** [comment]
Yes, we should resolve it to next major version.

**Comment by grossmannmartin** [comment]
on a current master, the main URL is rendered bold. Is it enough to close this issue?

**Comment by LukasHeinz** [comment]
In my point of view it is not enough. There are radiobutton control element and it should have default value. When it is empty it is confusing (plus there is missing any description). Or at least hide it until someone wants to edit it. 

If this is a problem then i suggest to move URL control to separate popup or even somewhere else - it is problematic component and it is not used often.
