### ISSUE TITLE
Only front-end translated texts should be in project-base translation files

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/shopsys#1383]
### What is happening
When you want to translate your frontend to a different language - let's say German - you translate the messages in .po files in project-base. 

The problem is that some messages are not translated. Only one we found are those for sorting product list in category:
- TOP
- alphabetically A -> Z
- alphabetically Z -> A
- from the cheapest
- from most expensive

And do not want to translate the whole administration to have a new language for front-end.

### Expected result
Step 1: the sorting product list are moved to project-base
Step 2: only front-end texts are in project-base .po files or it is clear what to translate if you want to translate only FE.

**Comment by LukasHeinz** [comment]
Just for reference: the German translation for one of the front-end domains is in progress in https://github.com/shopsys/demoshop/pull/71

**Comment by pk16011990** [comment]
It depends. Project base can translate only frontend, sometimes only admin and sometimes both.

We use this features on projects:
Command for extracting transaltions exclude admin templates - using for new language for frontend.
Command for extracting transaltions exclude frontend templates - using for new language for admin.
Command for merging translations - project base has only one file for frontend and admin and we need add translations eg. only from frontend.

**Comment by pk16011990** [comment]
remove stale

**Comment by grossmannmartin** [comment]
resolved by #2337
