### ISSUE TITLE
Recalculations are called in deploy target even if there is not new domain

### ISSUE THREAD

**Issue by henzigo** [shopsys/shopsys#1387]
### What is happening

In `build-deploy-part-2-db-dependent` there is `domains-data-create` target that creates domain data for newly created domain and runs `shopsys:recalculations` command even if there is no new domain. 

This can increase deployment time which is undesirable.

### Expected result

`shopsys:recalculations` command should be run in `domains-data-create` target only if there are some new domains.

**Comment by s3tezsky** [comment]
In my point of view there are two solutions:

1. Creating new phing target called `shopsys:domains-data:update`
    - which will respect current data and process only differences
2. Change `shopsys:domains-data:create` to behave like the `...:update` above
    - what will result in drastical change of behavior of this target (not good for me)
    - target name will be confisung according to it's purpose

Also it will need to require to extend `shopsys:recalculations` to accept parameter with domain ID (?) or hide this login into `shopsys:domains-data:update` target.

I would decide for creating new phing target for domains update and extend recalculations with an argument.

Before implementation I will need a PIA with some one else.

**Comment by vitek-rostislav** [comment]
Hi guys, we would really appreciate if you solved this :slightly_smiling_face:

**Comment by s3tezsky** [comment]
Hi @vitek-rostislav, I have to dissappoint you. We are still keeping it in our buffer with lower priority. Maybe we could get it done in a month but cannot guarantee anything.

**Comment by s3tezsky** [comment]
closed by #1669
