### ISSUE TITLE
Selectboxes in adminsitration in the end of page are not displayed

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/shopsys#139]
**Current state:**
Administration > Products > Categories > Editing category
![snimek obrazovky 2018-05-25 v 11 57 37](https://user-images.githubusercontent.com/33071107/40538833-1d5f879e-6013-11e8-82e7-a0b5c5527efc.png)

**Expected Behavior:**
The slecectbox options should be visible.

**Comment by boris-brtan** [comment]
Fixed
