### ISSUE TITLE
Necessary to override two methods in *DataFactory instead of one

### ISSUE THREAD

**Issue by henzigo** [shopsys/shopsys#1397]
### What is happening

When I want to override some data object for an entity, there is a need to override also DataFactory class. Unfortunately, you need to override two methods instead of one. (eg. [first](https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Model/Country/CountryDataFactory.php#L39) and [second](https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Model/Country/CountryDataFactory.php#L27)).

### Expected result

There is some method that only creates data object and then that method will be used across DataFactory class.

**Comment by PetrHeinz** [comment]
Do I understand correctly that the expected result would be to have a protected method `createInstance` that would be used from both `create` and `createFromEntity` methods?

```php
