### ISSUE TITLE
Explain environment variables of SSFW

### ISSUE THREAD

**Issue by PetrHeinz** [shopsys/shopsys#1409]
### What is happening

We have a few env variables that modify the behavior of SSFW (namely `REDIS_PREFIX`, `ELASTIC_SEARCH_INDEX_PREFIX`, and `IGNORE_DEFAULT_ADMIN_PASSWORD_CHECK`, along with `GOOGLE_CLOUD_PROJECT_ID` and `GOOGLE_CLOUD_STORAGE_BUCKET_NAME` in `shopsys/google-cloud-bundle`).

The usage of env vars is not consistent, only some the variables are described in the docs (in [Application Configuration](https://docs.shopsys.com/en/latest/installation/application-configuration/)). Docs are missing info how to change the actual env vars (eg. in `docker-compose.yml`).

Until #1408, some values were overwritten in the default Docker image. 

### Expected result

Usage of env vars is consistent (I'd recommend to define default values just in `parameters_common.yml` in `shopsys/framework`, remove it from `Dockerfile` and `parameters.yml.dist` in `shopsys/project-base`.)

Documentation describes all env variables used by SSFW, possible values, and examples of usage.

Documentation explains how to work with environment variables (via Docker Compose, Kubernetes, and natively using `export`). Good references on the topic could be the [Symfony docs](https://symfony.com/doc/current/configuration.html#config-env-vars) or [12factor app](https://12factor.net/config).

**Comment by PetrHeinz** [comment]
A nice example of how to set up a env variable using the different tools can be found in upgrade note of #1360:

- production environment disallow administrators to log in with default credentials [#1360](https://github.com/shopsys/shopsys/pull/1360)
    - register `user_checker` in  `app/config/packages/security.yml`
        ```diff
        administration:
            pattern: ^/(admin/|efconnect|elfinder)
        +   user_checker: Shopsys\FrameworkBundle\Model\Security\AdministratorChecker
            anonymous: ~
            provider: administrators
            logout_on_user_change: true
        ```
        - in case you need to disable this functionality (e.g. to allow easier logging in to a deployed application on your CI server)
        there is an environment variable `IGNORE_DEFAULT_ADMIN_PASSWORD_CHECK` which needs to be set to `1` (for **SECURITY** reasons **DO NOT EVER** do this in real production environment)
            - when you are using kubernetes on CI server change your configuration of:
                - `kubernetes/kustomize/overlays/ci/kustomization.yaml`
                ```diff
                        path: ./ingress-patch.yaml
                +   -   target:
                +           group: apps
                +           version: v1
                +           kind: Deployment
                +           name: webserver-php-fpm
                +       path: ./webserver-php-fpm-patch.yaml
                configMapGenerator:
                    -   name: nginx-configuration
                ```
                - create `kubernetes/kustomize/overlays/ci/webserver-php-fpm-patch.yaml` containing
                ```diff
                +-   op: add
                +    path: /spec/template/spec/containers/0/env/-
                +    value:
                +        name: IGNORE_DEFAULT_ADMIN_PASSWORD_CHECK
                +        value: '1'
                ```
            - when using docker containers without kubernetes add the environment variable to the `docker-compose.yml` file to `php-fpm` definition like in example below
                ```diff
                    php-fpm:
                        build:
                            context: .
                            dockerfile: docker/php-fpm/Dockerfile
                            target: development
                            args:
                                www_data_uid: 1000
                                www_data_gid: 1000
                        container_name: shopsys-framework-php-fpm
                        volumes:
                            - shopsys-framework-sync:/var/www/html
                            - shopsys-framework-vendor-sync:/var/www/html/vendor
                            - shopsys-framework-web-sync:/var/www/html/web
                        ports:
                            - "35729:35729"
                +       environment:
                +           - IGNORE_DEFAULT_ADMIN_PASSWORD_CHECK=1
                ```
            - without containers you must set environment variable on the host machine, typically in unix like OS by executing
                ```
                export IGNORE_DEFAULT_ADMIN_PASSWORD_CHECK=1
                ```

**Comment by s3tezsky** [comment]
It would be great to have this done.

**Comment by pk16011990** [comment]
remove stale...

**Comment by grossmannmartin** [comment]
related to #1615
