### ISSUE TITLE
Validation error alert in forms is misplaced in case of checkbox element

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/shopsys#142]
On front-end form when there is checkbox option that user have to check there is problem with displaying validation error alert. See examples below:
![snimek obrazovky 2018-05-25 v 12 07 16](https://user-images.githubusercontent.com/33071107/40539265-792f998c-6014-11e8-8c57-5ad969451c59.png)
<img width="446" alt="snimek obrazovky 2018-05-25 v 11 35 05" src="https://user-images.githubusercontent.com/33071107/40539272-7cb03b48-6014-11e8-8aa2-3f2f35edbb77.png">

It should be fixed on all forms. There is list:
- 3rd step of order 
- contact form on title page on left column
- newsletter subscription above footer
- registration form

**Comment by LukasHeinz** [comment]
Some work is in progress on branch https://github.com/shopsys/shopsys/tree/tg-bug-2036

**Comment by kulincz** [comment]
Ok, this problem should be fixed:
![image](https://user-images.githubusercontent.com/29253585/44648417-3c58fa00-a9e1-11e8-8d9f-04056f2d5890.png)
![image](https://user-images.githubusercontent.com/29253585/44648427-42e77180-a9e1-11e8-94e2-1c1b75385573.png)

**Comment by PetrHeinz** [comment]
@kulincz Those screenshots are from a different repository [shopsys/demoshop](https://github.com/shopsys/demoshop). We need to fix it in here as well...
