### ISSUE TITLE
Symfony toolbar should link to Shopsys docs website

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#1429]
### What is happening
In the Symfony toolbar, there is the Shopsys section containing a link to the docs (see https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Resources/views/Components/Collector/shopsysFramework.html.twig), however, the link leads to github - I believe it should lead the docs website - http://docs.shopsys.com/

It can be tricky as not all branches are deployed on the docs website.

### Expected result
I believe the link to docs should lead to the docs website

**Comment by grossmannmartin** [comment]
Closing as it's resolved in #1502
