### ISSUE TITLE
Error 500 in order if the product is sold out

### ISSUE THREAD

**Issue by KadelaKuba** [shopsys/shopsys#1438]
### What is happening

When you add product to cart (for example 22" Sencor SLE 22F46DM4 HELLO KITTY). After that administrator change the stock quantity to "0".  When the customer goes to the next step in order (Shipping and Payment) an error 500 appears.  

### Expected result

Display some flash message to customer instead of error.

**Comment by pk16011990** [comment]
Hi, #1494 is merged and It looks like solved...?

**Comment by pesektomas** [comment]
Hello @pk16011990, you are right, I closed this issue, thak you.
