### ISSUE TITLE
Unable to set different rounding for different currencies

### ISSUE THREAD

**Issue by TomasLudvik** [shopsys/shopsys#1444]
### What is happening
If I have two domains one with euro and second one with Czech crown I am not able to set different rounding for each currency. This means that I will have all prices rounded to whole numbers which does not make sense for euro or I will have all prices rounded to cents which does not make sense for Czech crowns.

### Expected result
I should be able to set rounding for each currency / domain separately.

**Comment by grossmannmartin** [comment]
It's related to #1027?

**Comment by sspooky13** [comment]
I want just notice you, that https://github.com/shopsys/shopsys/pull/1487 did not close this issue, maybe `closes #XXX #XXX` works only with first number 🤷‍♂️

**Comment by pesektomas** [comment]
@sspooky13 Thank you, I close this issue.

**Comment by vitek-rostislav** [comment]
yes, you need to write `closes #XXX closes #XXX` :wink:
