### ISSUE TITLE
weird work with DeliveryAddress and BillingAddress

### ISSUE THREAD

**Issue by DavidOstrozlik** [shopsys/shopsys#1456]
### What is happening

We work with DeliveryAddress and BillingAddress in CustomerFacade and everything with them is strictly tied to a User/Customer (they have no facades/repositories).
If you want to change the structure or edit/get just one DeliveryAddress you need to create a lot of things to be able to.

### Expected result
I think that the best way would be to add Billing(Delivery)AddressFacade/Repository and unify the way that we work with them like we have with other entities.
I'm glad to here other ideas on how to approach this and if you think that this would be a good idea.

**Comment by pk16011990** [comment]
Is it solved by #1543?

**Comment by pk16011990** [comment]
@s3tezsky, is it solved in #1543

**Comment by s3tezsky** [comment]
Another hard work was done in #1700, but AFAIK the BilingAddress was refactored only.
