### ISSUE TITLE
folders for overwriting eg. templates in framework bundle

### ISSUE THREAD

**Issue by DavidOstrozlik** [shopsys/shopsys#1458]
### What is happening
When you want to overwrite eg. template in framework you need to create `ShopsysFrameworkBundle` and `views` folders in every new project

### Expected result

`ShopsysFrameworkBundle` and `views` should be added so developers don't need to create them everytime

**Comment by sslt** [comment]
Lets open this one, we need to address this issue.

**Comment by sslt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [folders for overwriting eg. templates in framework bundle #1458](https://trello.com/c/XOy0zr0R/18-folders-for-overwriting-eg-templates-in-framework-bundle-1458)

**Comment by henzigo** [comment]
This issue is already solved by @pk16011990. You can close it @sslt

**Comment by sslt** [comment]
Closing, problem solved here
https://github.com/shopsys/shopsys/pull/1641
