### ISSUE TITLE
Javascript validation in 3rd step of order throws error in console

### ISSUE THREAD

**Issue by TomasLudvik** [shopsys/shopsys#1460]
### What is happening
Have random product in cart, get to 3rd step of order, change Country and click on Finish the Order. You will get error in console:

```Error: Can not find a "[object Object],validateTransportPaymentRelation" callback for the element id="transport_and_payment_form" to validate the Callback constraint.```

### Expected result
As transport and payment are not part of form in 3rd step of order there should be no such validation.

**Comment by vitek-rostislav** [comment]
Hi, I have the same problem on multiple pages in administration (almost anywhere the `Callback` constraint is used). Could you please take a look at it? It is really frustrating as I have no clue what to do about it, and it really complicates my life - when the error is thrown, the JS validation stops working :sob:

**Comment by vitek-rostislav** [comment]
> Hi, I have the same problem on multiple pages in administration (almost anywhere the Callback constraint is used). Could you please take a look at it? It is really frustrating as I have no clue what to do about it, and it really complicates my life - when the error is thrown, the JS validation stops working :sob:

Hi again, it seems that my problem in admin was not connected with the original issue - the error message is the same, however, it is probably caused by missing callback definition in javascript validation. So please accept my apologies, you do need to take worry about that when solving the original issue :slightly_smiling_face:

**Comment by TomasLudvik** [comment]
Hello, this issue has been solved during fix of validation in email templates, closing.
