### ISSUE TITLE
Simplification of .form-group separation

### ISSUE THREAD

**Issue by jakubhavlak** [shopsys/shopsys#147]
When using multiple .form-group elements we always had to add separators manually via .wrap-border
This is tiresome, error-prone and leads to complicated ifs when .form-groups are added dynamically (see plugins on product detail)
Some pages even had extra divs with .wrap-border (see order detail)

I have tried to simplify it using CSS adjacent sibling combinator in **ph-form-group-separation**, please check it out and:

- validate that changes to group.less make sense
- update CHANGELOG.md, UPGRADE.md and CSS documentation
- fix excessive gap after Images section on product detail (issue is also in master, separate commit)
- manually check as much pages in admin to see that forms are OK (especially if they contain mix of .form-groups and other elements)
- break changes Order/edit.html.twig into separate commits to make the changes clear
- check that .wrap-border makes sense as it creates the separation AFTER the element, not BEFORE it - is that best practice?

**Comment by boris-brtan** [comment]
@topolanekmartin hello i reopened this issue since it should be implemented soon.

**Comment by boris-brtan** [comment]
here we have the mentioned branch from issue https://github.com/shopsys/shopsys/compare/ph-form-group-separation
