### ISSUE TITLE
Unclear work with injected annotations and typehinted properties in tests

### ISSUE THREAD

**Issue by grossmannmartin** [shopsys/shopsys#1496]
### What is happening
In #1392 were introduced inject annotations to avoid getting dependencies from the DI container.

It's not clear how to work with cases similar as in https://github.com/shopsys/shopsys/blob/9.0/project-base/tests/FrontendApiBundle/Functional/Product/ProductTest.php

To properly use injection annotation I have to create a separate property (not a big deal)
```php
/**
 * @var \Shopsys\ShopBundle\Model\Product\Product
 */
private $product;

/**
 * @var \Shopsys\FrameworkBundle\Model\Product\ProductFacade
 * @inject
 */
private $productFacade;

protected function myMethod(): void
{
    $this->product = $this->productFacade->getById(1);
```

But then PHPStan starts to understand code a little more and fails on 
```
 Property ...ProductTest::$product (Shopsys\ShopBundle\Model\Product\Product) does not accept Shopsys\FrameworkBundle\Model\Product\Product.
```
as `Shopsys\FrameworkBundle\Model\Product\ProductFacade` (not overridden in ShopBundle) claims to return `Shopsys\FrameworkBundle\Model\Product\Product`.

But in the end, thanks to [Entity Extension](https://docs.shopsys.com/en/8.0/extensibility/entity-extension/), `Shopsys\ShopBundle\Model\Product\Product` is returned and PHPStan has no clue.

### Expected result

A preferred way should be known.

**Comment by s3tezsky** [comment]
Hi @grossmannmartin, I see 4 solutions for now:
1. Get product into local variable, annotate it by `\Shopsys\ShopBundle\Model\Product\Product` and then assign into property
    - requires one more line and variable allocation but I can live with that (and others too I guess)
2. Annotate property by ` \Shopsys\FrameworkBundle\Model\Product\Product`
    - a bit dirty and mistificating also as it is not true
3. Do not use property and define product in each test again
    - this goes agains DRY and might get too annoying in future
4. Ignore PHPStan error
    - please avoid it until it will be the last possible solution

Or maybe it can be solved by using some PHPStan extension to make understand these? If not I'm totaly for **option 1** if you guys do not know about other solution.

**Comment by vitek-rostislav** [comment]
I am voting for 

> 1. Get product into local variable

:wink:

**Comment by pesektomas** [comment]
I vote for first variant. Until class casting will be in php.

**Comment by ondrejmirtes** [comment]
How is the problem created in the first place? Why are you assigning `Shopsys\FrameworkBundle\Model\Product\Product` into `Shopsys\ShopBundle\Model\Product\Product` and consider it being okay?

**Comment by vitek-rostislav** [comment]
Hello @ondrejmirtes, well, in fact, there is a kind of magic behind that - in framework, we use our custom `EntityManagerDecorator` that works with "entity extension map". See https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Component/EntityExtension/EntityManagerDecorator.php 

So for example, when we call `$this->entityManager->getRepository(Shopsys\FrameworkBundle\Model\Product\Product::class)`, it looks into the map and returns repository for the extended class (`Shopsys\ShopBundle\Model\Product\Product`) instead. This was introduced in https://github.com/shopsys/shopsys/pull/95.

I hope the explanation helped :slightly_smiling_face:

**Comment by ondrejmirtes** [comment]
And do you use `Shopsys\FrameworkBundle\Component\EntityExtension\EntityManagerDecorator` with this typehint or do you also inject it as `Doctrine\ORM\EntityManager`? If it's the former, you could write a really cool dynamic return type extension for `getRepository` that resolves the call to the correct type :) (Or I could do that for you as paid commission.)

**Comment by vitek-rostislav** [comment]
AFAIK, `EntityManagerInterface` is used for typehints :grin: The return type extension would be awesome, however, there is more magic in the decorator, it is able to resolve the proper extended entity names in more places than just `getRepository`. 

@grossmannmartin, @sslt  - the decision is up to you, guys :wink:

**Comment by grossmannmartin** [comment]
Thank you, guys! Sure we will discuss it internally, but return type extension sounds really nice 👍

**Comment by ondrejmirtes** [comment]
We could even make it work with the Doctrine interfaces, if I made the same extension in phpstan-doctrine overridable.

**Comment by simara-svatopluk** [comment]
Hi, I'd suggest local variables. And the problem disappears

**Comment by s3tezsky** [comment]
Hi @grossmannmartin,
I thing it is not necessary to wait for staling this issue again. What is your plan with it now?

I see many of us are voting for annotated local variables. Do you want to have it written in docs/contributig guide? Or do you have any tips where it is not used this way already and want to fix these?

**Comment by grossmannmartin** [comment]
Currently, it seems like the local variable is the solution for now.
I suggest checking, whether in any test can be this kind of problem (but I don't think so) and mention it in the article about entities or extending
