### ISSUE TITLE
Admin: Order transport and payment are not updated in order preview

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#1507]
### What is happening
When I change a transport or a payment of an order, the data are not updated on the order preview (the popup on orders list in admin). 

The problem is that the data for the preview are taken from `$order(Data)->orderPayment->name`, resp. `$order(Data)->orderTransport->name` but these are not updated in `ProductFacade::edit()` method. This is connected to #1272...

### Expected result
The changes of transport and payment are reflected in order preview

**Comment by s3tezsky** [comment]
Solved in mentioned PR
