### ISSUE TITLE
Use Rector instead upgrade instructions

### ISSUE THREAD

**Issue by simara-svatopluk** [shopsys/shopsys#1513]
### What is happening
I remember that writing upgrade instructions was pain in the ass when I worked on Shopsys fulltime. The effort I see in https://github.com/shopsys/shopsys/pull/1392/files#diff-a4d6ec2e06658383faceb19b46922267 had to be enormous. I remember that it is very, very difficult to write reasonable (still not perfect) upgrade instructions.

### Expected result
I would like to recommend using Rector rules instead of upgrade instructions. It is similarly difficult to write them both (once you understand Rector), and the benefit is mostly for users of Shopsys - they upgrade instantly and don't do the repetitive manual work.

**Comment by sslt** [comment]
Nice. Thanks Svata, we will  look into it.

**Comment by TomasLudvik** [comment]
@s3tezsky looked at working with Rector and had some problems with it - David can you describe here what problems have you encountered?

**Comment by s3tezsky** [comment]
Hi, it could not be done about month and half ago. It is described here https://github.com/shopsys/shopsys/pull/1392#issuecomment-558747955.

Now I see that many changes were done and we might use it now. Thanks to solved issue which is mentioned in the thread.

**Comment by simara-svatopluk** [comment]
So.. Conflicts should be solved https://github.com/rectorphp/rector-prefixed
