### ISSUE TITLE
quantity in AddProductFormType is TextType

### ISSUE THREAD

**Issue by DavidOstrozlik** [shopsys/shopsys#1515]
### What is happening

quantity in AddProductFormType is TextType so you need to change the type of it every time you want to do some operation with it.

### Expected result

If TextType doesn't have any meaningful purpose change it to IntegerType

**Comment by pk16011990** [comment]
note: `IntegerType` allows to enter numbers in many strange formats (eg. `1e1`).

**Comment by pk16011990** [comment]
maybe it is time for custom deciaml form type. It should be ready for quantities in decimal numbers

**Comment by pk16011990** [comment]
It's irrelevant because the form type is not used anymore with FE API.
