### ISSUE TITLE
spinbox + with minimal value

### ISSUE THREAD

**Issue by DavidOstrozlik** [shopsys/shopsys#1516]
### What is happening

In spinbox, if you set `data-spinbox-min` eg. to `10`, then rewrite the value on frontend to eg. `5` and click on `+` it adds up to `6` even though the minimal value is set to be higher.

### Expected result

The behavior should be the same as when you click on `-` so that if you have value that is lower the minimal one and click `+`, the value should be set to the minimal one.

**Comment by s3tezsky** [comment]
fixed in #1979
