### ISSUE TITLE
Wrong msgid of translation

### ISSUE THREAD

**Issue by thirdknown** [shopsys/shopsys#1518]
There is translation `msgid` `Password cannot be longer then {{ limit }} characters`. In fact it is used in Length Constraints to validate minimal (!) length of password. So `msgid` should be e.g. `Password must be {{ limit }} characters long or longer`. Czech translation is correct and is according to reality.

![len](https://user-images.githubusercontent.com/25673907/69221914-a88cc400-0b78-11ea-8d40-1a06aae4450c.png)

**Comment by sspooky13** [comment]
Hello, I created [PR](https://github.com/shopsys/shopsys/pull/1478) time ago and I hope this will be resolved 😄

**Comment by thirdknown** [comment]
Thank you

**Comment by sspooky13** [comment]
You didn't have to close this issue 😄 I could add `closes #1518` to PR and this issue would be closed after merge that PR. So, next time.

Or somebody from SSFW can do this.
