### ISSUE TITLE
Dump is not working properly

### ISSUE THREAD

**Issue by henzigo** [shopsys/shopsys#1535]
### What is happening

As Symfony programmer, I know that Symfony has global method `dump()` for debugging. Unfortunately, this method is not working well in SSFW. It's because of Tracy that is loaded before Symfony and registers his own method. 

This problem bothers the community because they do not know about our custom method `d();`

### Expected result

`dump()` is working properly and I can use it for debugging

**Comment by grossmannmartin** [comment]
One solution that works is the composer plugin that allows to exclude file from autoloading.
https://packagist.org/packages/mcaskill/composer-exclude-files

then it's enough to add Tracy's shortcuts.php file as excluded into `composer.json`
```diff
    "license": "proprietary",
    "autoload": {
+       "exclude-from-files": [
+           "tracy/tracy/src/Tracy/shortcuts.php"
+       ],
        "psr-4": {
```

Another thing that works is to extra include Symfony's shortcuts in `app/autoload.php` file. Like (condition is for monorepo/project difference)
```diff
  use Doctrine\Common\Annotations\AnnotationRegistry;

+ file_exists(__DIR__ . '/../vendor/symfony/var-dumper/Resources/functions/dump.php') ? require __DIR__ . '/../vendor/symfony/var-dumper/Resources/functions/dump.php' : require __DIR__ . '/../../vendor/symfony/var-dumper/Resources/functions/dump.php';

  /* @var \Composer\Autoload\ClassLoader $loader */
  $loader = file_exists(__DIR__ . '/../vendor/autoload.php') ? require __DIR__ . '/../vendor/autoload.php' : require __DIR__ . '/../../vendor/autoload.php';
```
