### ISSUE TITLE
Admin: rendering Money type in Grid cell with default currency always

### ISSUE THREAD

**Issue by thirdknown** [shopsys/shopsys#1539]
Let's say we have an admin grid. We want to add a column with Money type, e.g. `price`. This `price` is in CZK currency and on another domain in € currency (admin uses `AdminDomainTabsFacade` to switching between domains in admin). But block `grid_value_cell_type_Shopsys_FrameworkBundle_Component_Money_Money` renders its value (`price`) in domain's default currency always.

https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Resources/views/Admin/Grid/Grid.html.twig#L371:

    {% block grid_value_cell_type_Shopsys_FrameworkBundle_Component_Money_Money %}
        {{ value|priceWithCurrencyAdmin }}
    {% endblock %}

**Comment by vitek-rostislav** [comment]
> in domain's default currency always.

I believe it should have been "in admin's default currency" :slightly_smiling_face:

**Comment by grossmannmartin** [comment]
I agree. Currency in grid should be configurable somehow.

**Comment by vitek-rostislav** [comment]
As a good start, `priceWithCurrencyAdmin` filter might take into account the value of `AdminDomainTabsFacade::getSelectedDomainId()` :thinking:

**Comment by grossmannmartin** [comment]
What about a new filter dependent on domain tabs facade and this one can be used in proper grid twig templates. 
Because in the documentation we are very specific about purpose of `priceWithCurrencyAdmin` (= default administration currency).

**Comment by TomasLudvik** [comment]
I wanted to work on this issue, but I did not find any grid in administration with currency combined with domain tabs and right now I cannot think of any current use case, we could apply that to. 

It should not be hard for developers to extend PriceExtension class, add new filter and then use it in listGrid.html.twig or overwrite it for all grids in Grid.html.twig. 

What do you think guys?

**Comment by grossmannmartin** [comment]
In customer list is grid with price combined with domain tabs. see #2021
