### ISSUE TITLE
update demo advert in footer

### ISSUE THREAD

**Issue by malyMiso** [shopsys/shopsys#1546]
### What is happening
After removing left panel, demo advert has been moved to another position (`footer`). Advert image is hardly visible.
![footer](https://user-images.githubusercontent.com/2991752/71170888-b196b100-225c-11ea-93d5-ab3f24e2d17d.png)

### Expected result
Advert position called `footer` contains bigger image, which is better visible and identifies better advert position

**Comment by grossmannmartin** [comment]
resolved with #1590
