### ISSUE TITLE
Tooltip for percent in Vat inline editing is not visible

### ISSUE THREAD

**Issue by malyMiso** [shopsys/shopsys#1556]
### What is happening
1. Go to Pricing > VAT and rounding
2. Edit the first vat rate
3. Hover mouse over icon "i"
4. Tooltip for edited vat rate is not whole 
![vats](https://user-images.githubusercontent.com/2991752/71171449-17376d00-225e-11ea-89a7-968e57935407.png)

### Expected result
Tooltip in the first edited vat rate is whole

**Comment by TomasGottvald** [comment]
Closed by https://github.com/shopsys/shopsys/pull/1599
