### ISSUE TITLE
Uploaded image with wrong extension causes 500

### ISSUE THREAD

**Issue by TomasLudvik** [shopsys/shopsys#1558]
### What is happening
When you upload image with wrong extension like "test.exe" uploading will end by ImageNotFoundException. This is throwed in ImageProcessor::createInterventionImage().

### Expected result
There is some user friendly error displayed.

**Comment by sslt** [comment]
Furthermore, it is possible to change and submit existing filename to empty string, which cases errors with this functionality.

**Comment by tmandok** [comment]
This issue applies to files uploader as well.
Additionally, once a file with the wrong extension is uploaded (and the button "Save changes" is clicked), a pop-up window "Please check the entered values." appears every time the user tries to save the changes - even after fixing or deleting all the files.

I would expect a validation immediately after selecting a particular file (or files).

**Comment by vitek-rostislav** [comment]
> Furthermore, it is possible to change and submit empty string filename for existing file, which causes errors with this functionality.

this should be covered by https://github.com/shopsys/shopsys/pull/1728 @sslt

**Comment by vitek-rostislav** [comment]
There is yet another problem with the file upload validation - no validation errors are displayed on the field after the invalid form is submitted, so user has no idea, what is wrong. And as @tmandok mentioned, it is not possible to fix the validation errors after the invalid form is submitted :confused:

**Comment by vitek-rostislav** [comment]
Maybe we could have created a separate issue for that, however, I believe someone should revise the file/image upload completely, so maybe it is better that all problems are here in one place

**Comment by vitek-rostislav** [comment]
Hi, up to date information - the problem mentioned by @tmandok (https://github.com/shopsys/shopsys/issues/1558#issuecomment-594452805) is already fixed in the current master

**Comment by vitek-rostislav** [comment]
However, I "discovered" one new minor problem - the "Uploading" flash message won't disappear after the file upload fails on exceeded file size.
See https://prnt.sc/rhnuj8

**Comment by pesektomas** [comment]
I am very confused about this issue. Could you please write down the points that currently bother you (with the references to PR which you mention here)? :smile:

**Comment by TomasLudvik** [comment]
I have summarized the problems mentioned in all comments:

- uploading file with the wrong extension causes 500
- saving file with no filename filled (https://github.com/shopsys/shopsys/pull/1728)
- "Uploading" flash message does not disappear after file upload fails on exceeded file size
- validation errors for the uploadedFilenames and currentFilenamesIndexedById are not displayed

**Comment by sslt** [comment]
There is one more @TomasLudvik, it's #1639 Form cannot be saved when file with wrong type is uploaded

**Comment by pesektomas** [comment]
> * validation errors for the uploadedFilenames and currentFilenamesIndexedById are not displayed 

* validation errors for the uploadedFilenames and currentFilenamesIndexedById are not displayed 
( #1772)
