### ISSUE TITLE
Product parameters - after deleting parameter value and adding some new parameter value, this parameter value is not added to product

### ISSUE THREAD

**Issue by KadelaKuba** [shopsys/shopsys#1562]
### What is happening

In this scenario, the added parameter value is not saved and administrator loses the added parameter.

1) Add new parameter to product
2) Remove this added parameter
3) Add new parameter again

### Expected result

All parameter values added to product are saved and assigned to product.

### A possible solution
Do not drop array indexes of parameters in ```ProductParameterValueToProductParameterValuesLocalizedTransformer```. It causes accidental deletion of the parameters.

**Comment by sslt** [comment]
Maybe it is related to other entities when using similar collection logic. Lets investigate too.

**Comment by grossmannmartin** [comment]
closed with #2249
