### ISSUE TITLE
Price filter is confusing

### ISSUE THREAD

**Issue by TomasLudvik** [shopsys/shopsys#1571]
### What is happening
Price filter input has placeholder including currency code and its behavior is confusing when you click inside and cannot delete numbers.

<img width="231" alt="price-filter" src="https://user-images.githubusercontent.com/5638367/71899033-29207780-315b-11ea-8f8f-86ce0cc655d5.png">

### Expected result
Inputs do not have placeholders but values and without currency code. Maybe font could be smaller

**Comment by TomasGottvald** [comment]
I think smaller font could not resolve this issue, bcs there should be 10000 CZK and others.

**Comment by grossmannmartin** [comment]
What about different color of placeholder text (gray) + on click remove placeholder value?
And, personally, I don't like I don't see a currency code when I'm writing a value.

I recorded video, it may be more descriptive.
https://share.getcloudapp.com/qGudvobW

**Comment by henzigo** [comment]
I would remove that currency code completely from that input place it before or after that inputs.

Or maybe that currency code could be after `Price` label.

**Comment by s3tezsky** [comment]
This one is really nasty and should be resolved.

Use currency symbol/code as a label after input - as @henzigo described - will do fine and should not take much of effort.

**Comment by grossmannmartin** [comment]
closed with #2226
