### ISSUE TITLE
Admin: Validation for free shipping is inconsistent

### ISSUE THREAD

**Issue by jakubhavlak** [shopsys/shopsys#158]
An inline message in front of the field appears instead of an explanation icon:
![image](https://user-images.githubusercontent.com/31988844/40614458-2f3728a6-6283-11e8-8607-a0a704543246.png)

**Comment by LukasHeinz** [comment]
This issue was resolved in https://github.com/shopsys/shopsys/commit/f15e42f7fc5a9aba9ff388a507bc0df46d3b5fca
