### ISSUE TITLE
build.xml: diff-files target always checks changed files against origin/master

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#1583]
### What is happening
in `diff-files` phing target, there is the hardcoded value (`origin/master`) that is used for computation of changed files, see https://github.com/shopsys/shopsys/blob/master/packages/framework/build.xml#L332

In some scenarios (your branch is based on other than master branch), it is not suitable and sometimes (when there are lots of changes), it can even cause a weird error when running `*-diff` phing targets, e.g.:

```
Shopsys Framework > phplint-diff:

PHP 7.3.9 | 10 parallel jobs
Path 'est/Codeception/Module/StrictWebDriver.php' not found
```

The reason behind that is that git displays a warning which breaks the list of changed files:
```
...
tests/App/Test/Codeception/Helper/WebDriverHelper.php
tests/App/Test/Codeception/Module/Db.php
tests/App/Twarning: inexact rename detection was skipped due to too many files.
warning: you may want to set your diff.renameLimit variable to at least 745 and retry the command.
est/Codeception/Module/StrictWebDriver.php
...

```

### Expected result
- The `diff-files` target is able to detect the base, against which the diff should be computed (probably it should the branch that is the base for the current one).
- However, the described problem might occur even if the base branch is detected properly - basically whenever there are too many changes. Maybe it would be nice if the command was able to detect this problem and show an understandable error message instead of sending the broken output further (i.e. setting the `git.files.changed` property)

Discussed and discovered with @grossmannmartin, thanks for your help :ok_hand:

**Comment by vitek-rostislav** [comment]
as a workaround, one can use non-diff variations of the check commands on the given project...

**Comment by grossmannmartin** [comment]
I`m not sure whether is an easy way, how to get a parent branch properly with git (see https://community.atlassian.com/t5/Bitbucket-questions/Knowing-from-which-branch-the-current-branch-was-created-from/qaq-p/570135)
