### ISSUE TITLE
Multi dimensional picture element

### ISSUE THREAD

**Issue by tomshopsys** [shopsys/shopsys#159]
### What is happening
We have usually request to have more than one dimension of image. Now we are using only one e.g. in product detail, which is set to maximum size of parent element and centered. 

But now we have new possibility: use picture element

```
<picture>
  <source media="(min-width: 650px)" srcset="img_pink_flowers.jpg">
  <source media="(min-width: 465px)" srcset="img_white_flower.jpg">
  <img src="img_orange_flowers.jpg" alt="Flowers" style="width:auto;">
</picture>
```

Source with description:
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_picture

We have to just think about picture dimensions for desktop, tablet, mobile, retina etc.

### Expected result
For frontend developers there will be no change - bcs this element can be generated by twig function `image`

**Comment by vitek-rostislav** [comment]
Another source :) http://responsiveimages.org/

**Comment by PetrHeinz** [comment]
We plan to implement this via optional attribute `additionalSizes` in `images.yml`:
```yaml
-   name: product
    class: Shopsys\FrameworkBundle\Model\Product\Product
    multiple: true
    sizes:
        -   name: ~
            width: 550
            height: ~
            additionalSizes:
                -   { width: 1100, height: ~, media: "(min-width: 1200px)" }
                -   { width: 275, height: ~, media: "(max-width: 480px)" }
            crop: false
            occurrence: 'Front-end: Main image in product detail'
```

which would make `{{ image(product, { itemprop: 'image' }) }}` Twig call render an image via `<picture>` element like this (instead of just the inner `<img>`):

```html
<picture>
    <source media="(min-width: 1200px)" srcset="https://127.0.0.1:8000/content/images/product/default/13_additional_0.png">
    <source media="(max-width: 480px)" srcset="https://127.0.0.1:8000/content/images/product/default/13_additional_1.png">
    <img itemprop="image" alt="" title="" src="https://127.0.0.1:8000/content/images/product/default/13.png" class="image-product">
</picture>
```

Internally, the images in additional sizes would work in the same way as images currently work - they would generate on the first request and so on.
