### ISSUE TITLE
[docs] problem after mail spooling is disabled

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#1593]
### What is happening
http://docs.shopsys.com/en/8.0/introduction/faq-and-common-issues/#why-are-e-mails-sent-before-end-of-the-script-and-not-immediately mentions that it is possible to disable mail spooling by removing the option from  swiftmailer.yml config. However, this causes the application to fail as https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Model/Mail/Mailer.php is dependent on `@swiftmailer.transport.real` service that is not defined when the spooling is off (see https://stackoverflow.com/questions/21074756/symfony2-monolog-to-email-errors-why-swiftmailer-transport-real-is-non-existent)

On my project, defining the service this way helped:
```
swiftmailer.transport.real:
        class: Swift_SmtpTransport
        arguments: ['%mailer_host%']
```

### Expected result
The FAQ article mentions that you need to define `swiftmailer.transport.real` yourself when you disable spooling

**Comment by pk16011990** [comment]
remove stale label

**Comment by grossmannmartin** [comment]
Spooling is no longer supported after #2470. closing
