### ISSUE TITLE
Difficult to add icon into submit button

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#161]
### What is happening
When a coder wants to add icon into particular submit (eg. :arrow_forward: for "Proceed in order" button), there is no easy way to do so because the submit is rendered via `form_widget(form.save)` function. The coder is often forced to generate the HTML and then copy and modify the final HTML structure.

Coders use icons via `<i>` tag and particular css classes.

### Expected result
There should be an option that enables adding icon into submit buttons, coders would like to specify somehow whether the button should have icon and also specify the css class for the icon. 

Also, there should be demonstrative extension of a HTML button in project-base or in documentation so the coders can see the rel usage.

**Comment by kulincz** [comment]
I prepared a little tweak and now you can put icon to submit button via these classes:
`btn--with-inject-icon btn--with-inject-icon--left [btn--with-inject-icon--right] svg-cart`
![image](https://user-images.githubusercontent.com/29253585/44462451-ebc65300-a614-11e8-9707-66373617e862.png)
as you can see there is option left or right and well known class (and generated by grunt) svg-iconname.
Let me know if this solve your problems.
I made PR here: https://github.com/shopsys/shopsys/pull/425
