### ISSUE TITLE
phpstan phing target fails on memory

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#1614]
### What is happening
When I try to run phpstan phing target on my project, with `phpstan.level` property set to 4, the target fails on memory and the only way that I am able to increase the memory limit is overriding the whole target.

### Expected result
There should be a phing property that allows project developers to increase the memory limit for phpstan phing target OR/AND the memory consumption itself should be examined.

**Comment by ondrejmirtes** [comment]
The project should set the PHPStan's `--memory-limit` CLI option to something that's tested to suffice. It doesn't even have to be user-configurable.

Right now it's just relying on the user having some high memory limit in their own `php.init`.

**Comment by grossmannmartin** [comment]
Thanks, @ondrejmirtes for the response!

Set `memory-limit` seems reasonable. But it should be user-configurable, to be more precise project-configurable. 
I don't know the scope of the final project, so the only value that I can be sure is enough is `unlimited`.

**Comment by grossmannmartin** [comment]
resolved in #1732 (memory limit increased to 2048M in phing target + property to set memory limit exists)
