### ISSUE TITLE
UUID extension must be installed to Postgres

### ISSUE THREAD

**Issue by henzigo** [shopsys/shopsys#1617]
### What is happening

I have to install UUID extension (`uuid-ossp`) to my Postgres database even when I'm not using Backend API.
This is confusing because I do not use any UUID id (and Shopsys framework do not use it too).

### Expected result

UUID should not be required for installing Shopsys Framework.

**Comment by grossmannmartin** [comment]
Hi,
`uuid-ossp` is required for `Version20190521071335.php` and `Version20190930140221.php` migrations. 

But according to https://www.postgresql.org/docs/10/uuid-ossp.html, the `gen_random_uuid()` from pgcrypto should be used instead. 

T.Hanks for the point!

**Comment by henzigo** [comment]
Yes, I know that UUID is required because of one column in Product entity, but this is weird because that column is not even use in framework so that column should not be here 😊

**Comment by grossmannmartin** [comment]
I see, well the idea behind this is to make the first step. UUIDs are used not just in backend-api (which is not a part of a project by default), but in frontend-api too and this one is installed by default. 

Another option is to have a guide for adding UUIDs into the project, but I find it tedious to maintain and for a specific project it's extra work to do.

**Comment by henzigo** [comment]
Hello @grossmannmartin, as I heard that you want to replace internal `id` with `UUID` I found Rector scripts that actually do that. Maybe that can help you with it.

 https://github.com/rectorphp/rector/tree/master/config/set/doctrine

**Comment by grossmannmartin** [comment]
Nice, thanks for that

**Comment by TomasLudvik** [comment]
Hello @henzigo, we use UUIDs for Backend and Frontend API. UUIDs have potential to be used for in many other use cases, that is why it is implemented in the framework, so it is implemented once, even when it is not directly used there.

Do you have any other questions or can we close this issue?

**Comment by s3tezsky** [comment]
Hi @henzigo I have created a new issue for replacing function for generating UUID. I am closing this issue as it is not relevant.
