### ISSUE TITLE
Admin : The action button is hidden behind the symfony debug bar.

### ISSUE THREAD

**Issue by adamtyron** [shopsys/shopsys#1631]
### What is happening

![deepin-screen-recorder_Select area_20200129145639](https://user-images.githubusercontent.com/2077971/73362854-e4928280-42a7-11ea-83fd-666c70bed868.gif)

Google Chrome Verze 79.0.3945.130 (Oficiální sestavení) (64bitový)

**Comment by pesektomas** [comment]
Hello @adamtyron, it also annoys me. What do you thing about this #1632?
