### ISSUE TITLE
Form cannot be saved when file with wrong type is uploaded

### ISSUE THREAD

**Issue by pk16011990** [shopsys/shopsys#1639]
### What is happening
On branch 9.0-dev... When I upload file (eg. CSV) as product image to galery, form contains error after click on save button. It is ok, I choose wrong file -> I'll delete it from form, but error `Image can be only in JPG, GIF or PNG format` is still here and the form cannot be sent.

### Expected result
After remove invalid file, form can be sent

**Comment by henzigo** [comment]
This is probably fixed in #1626. Am I correct @pesektomas ?

**Comment by pesektomas** [comment]
Hello, yes, I added for type `ImageUploadType` accept attribute `'accept' => 'image/*',` and removed error message after image file is deleted. Is this solution ok, @pk16011990?

**Comment by TomasLudvik** [comment]
This should be already solved by #1626 and #1756
