### ISSUE TITLE
Upgrade of commerceguys/intl

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#164]
### What is happening
We are not using the latest version (ie. `v0.7.5`) of `commerceguys/intl` library but we should. The new version drops the support for BYR currency so our unit test `IntlCurrencyRepositoryTest` must be modified accordingly.

In the past, we already upgraded the library to the new version but as we were not sure which other changes were made in the new version (there is no changelog), we reverted that upgrade in 5cb2404c7403b7ed73a0e46ccaa42e05d7a0c6cc.

### Expected result
The changes since `v0.7.4` of `commerceguys/intl` are reviewed and the library is required in the latest version.

**Comment by vitek-rostislav** [comment]
Please do not close this issue, I believe we really want to upgrade the library :slightly_smiling_face:

**Comment by PetrHeinz** [comment]
There is version `1.0.0` released already, it should be a good time to upgrade.

**Comment by Miroslav-Stopka** [comment]
This need to be solved as the US probably. Between version 0.7.4 and 1.0.0, there is > 500 changed files.
