### ISSUE TITLE
admin: missing FE links and visibilities on domains on product detail page

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#1657]
### What is happening
During admin facelift in https://github.com/shopsys/shopsys/pull/906, the section with links to FE (along with visibilities on the given domains) was removed from admin product detail - it was placed under the left menu. We really miss this feature, it was widely used by us, as well as by customers. The box is displayed on hover in admin product list (in "visibility" column) so it should not be hard to put it on the detail page).

### Expected result
There is a section links to FE domains and displayed visibilities on the domains on admin product detail once again :slightly_smiling_face:

**Comment by sslt** [comment]
Thanks vitek-rostislav. We will address this issue at the beginning of Q2/2020. Please be patient.
