### ISSUE TITLE
Broken styling of the maintenance page

### ISSUE THREAD

**Issue by jakubhavlak** [shopsys/shopsys#167]
The maintenance page has been broken since the execution of some redesigned graphics (there is an immense 6000x4000px image).

Note: on / off maintenance - phin maintenance-on and phing maintenance-off

**Comment by LukasHeinz** [comment]
We are aware that maintenance page is issue and we will address this problem but this is currently not our priority and will resolved in the future.

**Comment by boris-brtan** [comment]
https://github.com/shopsys/shopsys/blob/v7.0.0-alpha1/project-base/web/assets/frontend/images/maintenance.png
