### ISSUE TITLE
Missing attribute $promoCodeDiscountPercent data type check

### ISSUE THREAD

**Issue by RostislavKreisinger** [shopsys/shopsys#1686]
### What is happening
class OrderPreview
has an inadequately treated $ promoCodeDiscountPercent attribute data type that allows you to insert a string. In the next code is counted with float, then it falls in the order with the promo code. When I extend OrderFacade in App. The reason is using strict type in App.

**Comment by s3tezsky** [comment]
the same issue us open #1876
