### ISSUE TITLE
weird behavior of build-demo-ci

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#1688]
### What is happening
When using phing target build-demo-ci, my build fails on smoke tests. The reason is that `ProductRenameRedirectPreviousUrlTest` renames the product with ID 1 and product with URL `webserver/rename` then can not be found in smoke tests (404 fail for `front_product_detail` that uses the product with ID 1 as well).

### Expected result
`ProductRenameRedirectPreviousUrlTest` should either rename product with any other ID than 1, or even better, data should be restored before smoke tests are run.

**Comment by grossmannmartin** [comment]
Can you test the behavior when the test extends `TransactionFunctionalTestCase` instead of `FunctionalTestCase`?

**Comment by s3tezsky** [comment]
Hi @vitek-rostislav is this still relevant?

**Comment by sslt** [comment]
@vitek-rostislav can you let us know, whether this issue is still relevant for you please?
