### ISSUE TITLE
 Improve UX work with URL in admin

### ISSUE THREAD

**Issue by jakubhavlak** [shopsys/shopsys#169]
It would be nice to add some explanation to set up the main URL in the administration (for the product, article, ...) - from the point of view of admin now I have some URLs, I can add more, there are some radiobuttons, but I do not even know what will actually happen when I choose the other radiobutton :) Another thing - would the add can be done in ajax style? "add URL" action button is a bit confusing - after adding a new URL, it makes me think that I'm going to save it. I feel we've probably solved it before, but I do not remember, how it actually happened, or I could not find any US.

**Comment by kulincz** [comment]
From my point of view – if I fully understand the problem – the solution can be checked option which is default URL (bold text can remain) .. maybe there could be good to have a little info text about that Choosen option: „Choosen option is default URL which is loaded after user click from the main menu in e-shop and another URLs are just for SEO purpose and redirects to the default“ ... 
Please, correct me if I understand it wrong :-)
