### ISSUE TITLE
ImageConfig doesn't accept extended entities

### ISSUE THREAD

**Issue by RostislavKreisinger** [shopsys/shopsys#1693]
### What is happening
When I use the following function with extended entity (entity has different class name). This will throw the exception. The class name of extended entity isn't among the registered entities.

`$imageViews = $this->imageViewFacade->getForEntityIds(Product::class, $productIds);`

`
array:10 [▼
  "Shopsys\FrameworkBundle\Model\Payment\Payment" => ImageEntityConfig {#205 ▶}
  "Shopsys\FrameworkBundle\Model\Category\Category" => ImageEntityConfig {#238 ▶}
  "Shopsys\FrameworkBundle\Model\Product\Product" => ImageEntityConfig {#153 ▶}
  "App\Model\Product\Series\ProductSeries" => ImageEntityConfig {#135 ▶}
  "Shopsys\FrameworkBundle\Model\Slider\SliderItem" => ImageEntityConfig {#124 ▶}
  "Shopsys\FrameworkBundle\Model\Transport\Transport" => ImageEntityConfig {#121 ▶}
  "Shopsys\FrameworkBundle\Model\Advert\Advert" => ImageEntityConfig {#104 ▶}
  "Shopsys\FrameworkBundle\Model\Product\Brand\Brand" => ImageEntityConfig {#107 ▶}
  "App\Model\Blog\Category\BlogCategory" => ImageEntityConfig {#102 ▶}
  "App\Model\Blog\Article\BlogArticle" => ImageEntityConfig {#95 ▶}
]
`

**Comment by vitek-rostislav** [comment]
I believe this could be fixed by using `EntityNameResolver` in `ImageConfig` service.

As a workaround, is it possible to pass the original entity, @RostislavKreisinger?

**Comment by RostislavKreisinger** [comment]
Yes, the solution to the problem is obvious. 

but using:
`$productClassName = 'Shopsys\FrameworkBundle\Model\Product\Product';
        $imageViews = $this->imageViewFacade->getForEntityIds($productClassName, $this->getIdsForProducts($products));`
is realy stupid.

**Comment by grossmannmartin** [comment]
Thanks for reporting the issue 👍

**Comment by grossmannmartin** [comment]
fixed in #1777
