### ISSUE TITLE
Missing livereload.js on dev mode

### ISSUE THREAD

**Issue by TomasGottvald** [shopsys/shopsys#1694]
### What is happening

After adding webpack, I can't find liverload.js - which is responsible for reloading webpage after twig or less changes

### Expected result

Add these lines in base.htm.twig before </body> tag

        {% if app.environment == 'dev' %}
            <script async src="//localhost:35729/livereload.js"></script>
        {% endif %}

**Comment by TomasGottvald** [comment]
@pesektomas can we fix wepback-dev-server or we should add 
https://www.npmjs.com/package/webpack-livereload-plugin

What coders needs:
After change in less files, webpack builds new files and automaticaly relaods css in borwser without manually refresh page.

**Comment by pesektomas** [comment]
Probably yes, it is look like easy pick
