### ISSUE TITLE
Update composer dependencies

### ISSUE THREAD

**Issue by pesektomas** [shopsys/shopsys#1697]
### What is happening
When I run composer install I can see this errors:

`Package robloach/component-installer is abandoned, you should avoid using it. Use oomphinc/composer-installers-extender instead.`

`Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.`

`Package zendframework/zend-eventmanager is abandoned, you should avoid using it. Use laminas/laminas-eventmanager instead.`

`Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.`

`Package facebook/webdriver is abandoned, you should avoid using it. Use php-webdriver/webdriver instead.`

`Package guzzlehttp/streams is abandoned, you should avoid using it. No replacement was suggested.`

`Package guzzlehttp/ringphp is abandoned, you should avoid using it. No replacement was suggested.`

### Expected result
We can replace packages from error log.

**Comment by grossmannmartin** [comment]
none of these libraries is a part of the codebase anymore :)
