### ISSUE TITLE
Different coding standards between framework and project base

### ISSUE THREAD

**Issue by pk16011990** [shopsys/shopsys#1699]
### What is happening
When developer override 1:1 some code from framework, It can fail on coding standards.

When I override `Shopsys\FrameworkBundle\Model\Order\Item\OrderItemFacade::addProductToOrder()` and copy-paste exact code from framework without any changes, It causes failing phpstan:
```
Method Doctrine\Common\Persistence\ObjectManager::flush() invoked with 1 parameter, 0 required.
```
it is caused by different rules in `phpstan.neon`

### Expected result
Project base does not use stricter coding standards rules then framework.

**Comment by vitek-rostislav** [comment]
btw, I know this is offtopic, however, the failing phpstan can be resolved, see https://github.com/shopsys/shopsys/issues/1616

**Comment by pk16011990** [comment]
Next example: 

`shopsys/shopsys` contains in `phpstan.neon`:
```neon
        -
            message: '#^Method Symfony\\Contracts\\EventDispatcher\\EventDispatcherInterface::dispatch\(\) invoked with 2 parameters, 1 required\.$#'
            path: %currentWorkingDirectory%/src/*
```
It causes problem on copy paste:
```php
# file shopsys/framework/src/Command/Elasticsearch/ElasticsearchChangedDataExportCommand.php
$this->eventDispatcher->dispatch(
    new IndexExportedEvent($index),
    IndexExportedEvent::INDEX_EXPORTED
);
```

:angry: It is not good DX, We have good one idiom in czechia: `who are preaching water, but drinking wine...?`

**Comment by grossmannmartin** [comment]
Actually, it's not about more strict rules in project-base. 
It's about violation not present in project-base, but present in the framework (when they should be properly ignored). When you copy-paste, you should be aware you're adding such violation into your codebase and be ok with all consequences.
And when we add ignore rules "just in case", phpstan would fail on not-present violations anyway.

The whole concept of copy-pasting is plain wrong from my point of view and we should really think about, what to do with it.

**Comment by s3tezsky** [comment]
Hi @pk16011990 I am closing this issue because of the `phpstan.neon` cannot be 1:1.
