### ISSUE TITLE
Admin: Products: Behavior of sort by name is platform specific

### ISSUE THREAD

**Issue by jakubhavlak** [shopsys/shopsys#170]
When I view the / admin / product / list / page on my computer (Czech 64bit Linux) or on CI, the first products in the series starting with A (Apple iPhone 5S 64GB, gold).

When I do the same with Peter Heinz on his laptop (Windows, maybe 32 bit), the first products in the series starting with alphabet (something like "100 Czech crowns ticket").

We have confirmed that sorting is different on different platforms. This is a known PostgreSQL issue because sorting currently depends on the implementation of collations in the OS.

This should be solved in PostgreSQL v10, when the sorting will be solved by the independent ICU library platform https://blog.2ndquadrant.com/icu-support-postgresql-10/ 

Another problem is that the grid does not even call ORDER BY xxx COLLATE. This will then have to be added to sort the language in which the names appear.

**Comment by Miroslav-Stopka** [comment]
Solved in #278
