### ISSUE TITLE
UploadedFile with name including Chinese characters cannot be downloaded on frontend in Chrome

### ISSUE THREAD

**Issue by TomasLudvik** [shopsys/shopsys#1714]
### What is happening
When I upload some file in admin and change its name to something like "漢字, 汉字, pinyin: Hànzì, český přepis: Chan-c', japonsky: Kandži 漢字" and then try to open this file on frontend, I will end with error "ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION"

### Expected result
I can download file with Chinese signs on frontend.

**Comment by pk16011990** [comment]
I agree, but for us, it is edge-case. Now, I'm closing it, but please feel free to create PR.
