### ISSUE TITLE
Second submit of subscription form causes error

### ISSUE THREAD

**Issue by roulajan** [shopsys/shopsys#1716]
### What is happening
After I sucessfully signed up to newsletter and I want immidietly sign up with another e-mail address, there is no second ajax call after form submit. There is only POST request which causes error because route accepts only ajax requests.

### Expected result
I am able to submit newsletter form again

**A possible solution:**
In src/Shopsys/ShopBundle/Resources/scripts/frontend/newsletterSubscriptionForm.js 
LINE 10 change bind event from 'ajaxSubmit' to 'submit'
and add e.preventDefault(); before Shopsys.ajax call

![nl_submit_form_bug](https://user-images.githubusercontent.com/37144957/75780866-6f114a80-5d5c-11ea-90e0-ded5b2a29399.png)

**Comment by grossmannmartin** [comment]
Hi, thank you for reporting the error. 
This issue is fixed in development version 9.0.0-dev. 

We consider backporting the fix also into future 7.3.x patch

**Comment by s3tezsky** [comment]
Hi @roulajan I am closing this issue as it was already fixed.
