### ISSUE TITLE
Potential bug in CustomerUserFacade::edit

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#1724]
### What is happening
You can see that [here `$customerUserUpdateData->deliveryAddressData->customer` is approached](https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Model/Customer/User/CustomerUserFacade.php#L217), even though `deliveryAddressData` is nullable.

Btw, a few lines below, [the is a check for not nullability of `$customerUserUpdateData->deliveryAddressData`](https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Model/Customer/User/CustomerUserFacade.php#L219), however, honestly, I am a little bit confused with this condition, should not `$deliveryAddress` itself be checked for nullability here? It seems to be working here, but I would say it would be more readable this way, and more resistant against individual changes on projects (e.g. on our project, `$customerUserUpdateData->deliveryAddressData->addressFilled` is always `true`)

### Expected result
- `CustomerUserFacade::edit` is examined for potential issues and the issues are fixed.

**Comment by paolo42** [comment]
Bug or not, it is wrong either way. At the very least it is inconsistent - you already mentioned that a few lines under this, a property of `$customerUserUpdateData->deliveryAddressData` is accessed only after asserting it is not null. This is the same case, only the assertion is missing here.

I would recommend to make this issue only about missing assertion before accessing `customer` attribute of nullable object `$customerUserUpdateData->deliveryAddressData`. Then you can create a second issue about possibly needed check for `$deliveryAddress` nullability.

**Comment by grossmannmartin** [comment]
closed by #2199
