### ISSUE TITLE
Translations dump error message wrong

### ISSUE THREAD

**Issue by CarabineSK** [shopsys/shopsys#1727]
When dumping translations for new domain, you can get strange message. 

### What is happening

Steps to reproduce:
- add domain into `domains_urls.yml.dist`, but **not** into `domains_urls.yml`
- run `php phing translations-dump`

I get this build fail result:
```
/var/www/html$ php phing translations-dump
Buildfile: /var/www/html/build.xml
 [property] Loading /var/www/html/build/build.local.properties
 [property] Unable to find property file: /var/www/html/build/build.local.properties... skipped

Shopsys Framework > domains-info-load:


Shopsys Framework > translations-dump:

sh: 1: Syntax error: "(" unexpected

BUILD FAILED
/var/www/html/build.xml:18:85: Task exited with code 2

Total time: 0.5149 seconds
```

### Expected result

There could be some message that tells what is happening, like:
  `Not all domains found in domains_urls.yml`

**Comment by grossmannmartin** [comment]
Hi @CarabineSK,

thanks for the report. I tried to reproduce this error on the current master, but I did not get the error you describe.

I have a running project, I added 
```
    -   id: 3
        url: http://asd.dd
```
into `domains_urls.yml.dist` and I ran `php phing translations-dump`.

What version of SSFW do you use? Can you please describe more your setup (what OS?, are you running in docker?, can you reproduce the error on the current master?)
