### ISSUE TITLE
CategoryFormType locale caching (category list without category names)

### ISSUE THREAD

**Issue by CarabineSK** [shopsys/shopsys#1729]
In `CategoryFormType.php`, there is this code:
```
       if ($options['category'] !== null) {
            $parentChoices = $this->categoryFacade->getTranslatedAllWithoutBranch($options['category'], $this->domain->getCurrentDomainConfig());
        } else {
            $parentChoices = $this->categoryFacade->getTranslatedAll($this->domain->getCurrentDomainConfig());
        }
```
in that uses `DomainConfig`. Since this form is in Admin and we are building multi-domain, we have Admin locale set not 'cs', but 'en'.

### What is happening

`CategoryFacade::getTranslatedAllWithoutBranch` & `CategoryFacade::getTranslatedAll` used in admin `CategoryFormType` use current domain config instead of admin locale. It causes a problem (category list without category names) when current domain has locale different from default admin locale ( en )
![image](https://user-images.githubusercontent.com/6003253/76632208-223f2800-6543-11ea-9694-7edc8ebcdc6c.png)

### Expected result

Functions `CategoryFacade::getTranslatedAllWithoutBranch` & `CategoryFacade::getTranslatedAll` use parameter locale instead of `DomainConfig`

-------------
#### Details:
We've created `CategoryFormTypeExtension.php` and changed this to locale:
```
        if ($options['category'] !== null) {
            $parentChoices = $this->categoryFacade->getTranslatedAllWithoutBranchByLocale($options['category'], $this->localization->getAdminLocale());
        } else {
            $parentChoices = $this->categoryFacade->getTranslatedAllByLocale($this->localization->getAdminLocale());
        }
```
plus creating new functions in `Facade`:
- `CategoryFacade::getTranslatedAllWithoutBranchByLocale`
- `CategoryFacade::getTranslatedAllByLocale`

and subsequently in `Repository`:
- `CategoryRepository::getTranslatedAllWithoutBranchByLocale`
- `CategoryRepository::getTranslatedAllByLocale`

The first load of form in `CategoryFormType` created cache for locale ( cz ), then in `CategoryFormTypeExtension` the query with locale ( en ) resulted in NULL names.

#### Our solution

- option 1: removing `$this->addTranslation($queryBuilder, $domainConfig->getLocale());` in `CategoryRepository::getTranslatedAllWithoutBranch`, but leaving this row in our new `CategoryFacade::getTranslatedAllWithoutBranchByLocale` (so that the query/result is not cached from `CategoryFormType` to `CategoryFormTypeExtension`). 
- option 2: clearing `EntityManager` in Facade.

**Comment by s3tezsky** [comment]
fixed in #1982
