### ISSUE TITLE
OrderNumberSequence::getNextNumber() return value

### ISSUE THREAD

**Issue by CarabineSK** [shopsys/shopsys#1743]
`OrderNumberSequence::getNextNumber()` is anotated with wrong return value

### What is happening

`OrderNumberSequence::getNextNumber()` returns **int**:
```    
/**
 * @return int
 */
 public function getNextNumber()
```
is the definition, but in `OrderFacade::createOrder()` there is `orderFactory->create()` that accepts **string**:
```
      $orderNumber = $this->orderNumberSequenceRepository->getNextNumber();
        $orderUrlHash = $this->orderHashGeneratorRepository->getUniqueHash();
        $toFlush = [];

        $this->setOrderDataAdministrator($orderData);

        $order = $this->orderFactory->create(
            $orderData,
            $orderNumber,
            $orderUrlHash,
            $customerUser
        );
```

Additionally, I believe that we no longer use these two classes:
`OrderNumberSequenceFactory`
`OrderNumberSequenceFactoryInterface`

### Expected result

```    
/**
 * @return string
 */
 public function getNextNumber()
```

+ remove (if not necessary)
`OrderNumberSequenceFactory`
`OrderNumberSequenceFactoryInterface`

**Comment by grossmannmartin** [comment]
Hi, thanks for the issue.

You're right about the type inconsistency. This part deserve some decent refactoring.
In `OrderSequenceRepository::getNextNumber`
```php
// getNumber() returns string
$lastNumber = $orderNumberSequence->getNumber();

if ($requestedNumber <= $lastNumber) {
    // string + int
    $requestedNumber = $lastNumber + 1;
}

// whole method returns int
```

`OrderNumberSequenceFactory(Interface)` truly seems unused.
