### ISSUE TITLE
DRY in entities (edit vs construct)

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#1746]
### What is happening
In many entities, you can find a nice example of DRY violation. Constructor and `edit` method often contain duplicated lines for setting entity properties from the class data. This might lead to mistakes and it also hardens extending.

It is easy to fix this problem - the common properties settings can be moved into a separate method.

### Expected result
DRY violations in entities are reduced using a protected method (named eg. `fillCommonProperties`)

**Comment by grossmannmartin** [comment]
Hi @vitek-rostislav,
thanks for filling this issue. I agree the code duplication should be avoided where possible.
