### ISSUE TITLE
adding new mail templates is developer-unfriendly

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#1749]
### What is happening
When a project developer adds a new mail template, he/she has to copy-paste the whole https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Resources/views/Admin/Content/Mail/template.html.twig in order to add a few lines with `mailTemplate` macro call with his/her new mail template

Might be related to https://github.com/shopsys/shopsys/issues/724
### Expected result
It is not necessary to copy paste the whole template from framework in order to add new mail template in admin
- the referenced template could be structured into block better so a developer is able to override only a part of the template
- or even better, there could a be a registry of the mail templates so it is not necessary to override the framework Twig template at all

**Comment by grossmannmartin** [comment]
Hi, thanks for reporting. 
True, this should be refactored and macro should be in a separate file.
