### ISSUE TITLE
Duplicate information in several installation guides

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#175]
### What is happening

In installation guides, the first step (`composer create-project`) is the same for almost all platforms, ie. the same changes need to be done in multiple files from time to time (see eg. https://github.com/shopsys/shopsys/pull/162) and that can cause problems when some of the files is accidentally omitted. Also, modifying multiple files with the same change is quite annoying :slightly_smiling_face: 

### Expected result
It would be nice if the same information could be written only once in one file and that could be included to or linked from all the places.

*Notes:*
- *It seems there is no natural way of inculding `md` in each other (https://stackoverflow.com/questions/4779582/markdown-and-including-multiple-files)*
- *I do not like linking the first step to another file because going through installation guide would mean too many clicking back and forth.* :slightly_frowning_face:
- *I am little bit worried about SEO in the current state, because in fact, the first step is duplicit content and including the information from one file would not solve this issue.* :thinking:

**Comment by PetrHeinz** [comment]
Is SEO really a thing to think about when writing documentation?

**Comment by LukasHeinz** [comment]
I do not feel SEO as a issue - I am more concerned about maintainability of same information on different pages.
