### ISSUE TITLE
more information about read model impacts on application behavior

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#1751]
### What is happening
Read model usage impacts might be an unpleasant surprise for project developers
- eg when a product is sold-out and then hidden/disbaled for sale, it does not take an effect on FE until the export to Elastic is executed (in 5 minutes CRON)

### Expected result
Read model dos are extended

**Comment by grossmannmartin** [comment]
The same applies to currently developed Frontend API. 
It's tied more with Elasticsearch as a source of data, than read model itself.

**Comment by vitek-rostislav** [comment]
True indeed :ok_hand:

**Comment by pk16011990** [comment]
We are working on a queue system, and it will help with this behavior. Queues should be documented.
