### ISSUE TITLE
ManyToMany relation to Domain class causes error

### ISSUE THREAD

**Issue by ondrej-petr** [shopsys/shopsys#1759]
### What is happening
When I create a relation ManyToMany from ProductDomain to Flags, I got error during tests / build. 

Ver. 9.0.0-dev

Create relation in ProductDomain class
```   
    /**
     * @var \App\Model\Product\Flag\Flag[]|\Doctrine\Common\Collections\ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="App\Model\Product\Flag\Flag")
     * @ORM\JoinTable(name="product_domain_flags")
     */
    protected $flags;

```

Run tests -> error occured:
```ERROR     [app] Symfony\Component\Debug\Exception\ContextErrorException: Notice: Undefined index: joinColumns (uncaught exception) at /var/www/html/vendor/shopsys/framework/src/Component/Doctrine/NotNullableColumnsFinder.php line 55 while running console command `shopsys:domains-data:create` ["exception" => Symfony\Component\Debug\Exception\ContextErrorException { …}]```

### Expected result
Tests should pass through

### Solution
Add condition `array_key_exises` to NotNullableColumnsFinder::getNotNullableAssociationColumnNames
`if (array_key_exists('joinColumns', $associationMapping) && $associationMapping['joinColumns'][0]['nullable'] === false) {`

**Comment by pesektomas** [comment]
Hello @ondrej-petr, thak you for reported this issue. I fixed it in #1760. I hope so we can merge it early.
