### ISSUE TITLE
Product's visibility recalculation after category removal

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#1763]
### What is happening
When a category is removed, products' visibility is not recalculated nor scheduled for recalculation, so even though the products might not visible anymore after their category is removed, they still act as visible until all the products visibilities are recalculated in `ProductVisibilityMidnightCronModule`.

This is a problem for many reasons, e.g. imagine this scenario:
1. you remove a category
1. products in this category are still "visible" from the application point of view
1. you generate a feed (that takes only visible products)
1. in your feed, there are also products that return 404 on their URL

Or, the generation of your feed might fail (when you try to access something like `$product->getCategory()->getName()`)

Etc.

### Expected result
When a category is removed, all the affected products are scheduled for immediate visibility recalculation.

**Comment by vitek-rostislav** [comment]
I will probably create a PR soon :wink:

**Comment by grossmannmartin** [comment]
Thanks for reporting! PR would be great ;)

**Comment by s3tezsky** [comment]
Fixed by #2180
