### ISSUE TITLE
required wrong version of snc/redis-bundle in composer.json

### ISSUE THREAD

**Issue by s3tezsky** [shopsys/shopsys#1775]
In our `composer.json` we are requiring `"snc/redis-bundle": "^2.1.8"`.<br/>It is a bit tricky because we are using method [`\Snc\RedisBundle\Client\Phpredis\Client::unlink()`](https://github.com/snc/SncRedisBundle/blob/6144d228fb6aace9287200369504bdf0008f83a6/Client/Phpredis/Client.php#L245) which was introduced in version `2.1.10`.<br/>A bit more tricky is the fact there is a bug from this version in method [`\Snc\RedisBundle\Client\Phpredis\Client::scan()`](https://github.com/snc/SncRedisBundle/blob/9ac8d92c0479dad8ef37d43c2edcc170e2c27c2d/Client/Phpredis/Client.php#L1483) which was resolved in version `3.1.1`. As the version 2 is unmaintained we cannot expect it will be fixed.<br>Besides we have classes [`RedisVersionsFacade`](https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Component/Redis/RedisVersionsFacade.php) and [`RedisCleanCacheOldCommand`](https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Command/RedisCleanCacheOldCommand.php) which seems to use the simillar logic implemented in two places.

### Expected result
We will require a proper version of `snc/redis-bundle` and create a fix of original method `scan()` based on `shopsys/framework 7.3`<br>Consider refactoring of `RedisVersionsFacade` and `RedisCleanCacheOldCommand`

**Comment by grossmannmartin** [comment]
Thank you for the issue. We do our best to process this for the upcoming major, although the issue should be closed after branch 7.3 is also resolved.

**Comment by s3tezsky** [comment]
This issue was already resolved and merged.
