### ISSUE TITLE
Grid does not support Drag&Drop with inline editation

### ISSUE THREAD

**Issue by pk16011990** [shopsys/shopsys#179]
### What is happening
When Drag&Drop is allowed in Grid and GridInlineEdit is setted, creating of new row fails.

For example in `Shopsys\ShopBundle\Model\Product\Flag\FlagGridFactory` add `$grid->enableDragAndDrop(Flag::class);` and click to button [+ Create flag] causes:

```
Exception:
Type error: Argument 1 passed to Shopsys\ShopBundle\Component\Grid\Grid::getValueFromRowBySourceColumnName() must be of the type array, null given, called in C:\html\example.com\src\Shopsys\ShopBundle\Component\Grid\Grid.php on line 300
```

### Expected result
* new row in grid table (do not forget save in right order )
* or documented unsupported behaviour and throw understable exception immediately on set GridInlineEdit and set Drag&Drop concurrently

**Comment by Miroslav-Stopka** [comment]
Solved in #274
