### ISSUE TITLE
Multiple popup windows in administration after repeated article order save

### ISSUE THREAD

**Issue by roulajan** [shopsys/shopsys#1802]
Multiple popup windows in administration will appear after repeated article order save

### What is happening
As administrator in "shopsys 9.0.x-dev" if I change articles order in admin/article/list/ , I  save the order and after that I immediately (no page reload) change articles order again and press save again, multiple popup windows will apper. There are 2,4,8,16 popup windows after every save.

The problem is probably in GridMultipleDragAndDrop.js where GridMultipleDragAndDrop.init is called in callback. So after every ajax callback, new GridMultipleDragAndDrop is initialized.

`(new Register()).registerCallback(GridMultipleDragAndDrop.init, 'GridMultipleDragAndDrop.init');`

### Expected result
It should be only one popup window with information "Order saved".

**Comment by pesektomas** [comment]
Hello @roulajan,

I think so your issue waas fixed in #1795. Could you look at it? 

Thank you.

**Comment by roulajan** [comment]
Hello @pesektomas , yes, that fixes the issue. Thank you. Closing.

**Comment by pesektomas** [comment]
You're welcome.
