### ISSUE TITLE
do not create OrderPreview twice in cart and order

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#1805]
### What is happening
Hello, I am thinking about this:
- in the cart (on many projects) and in the order, there is a panel with order preview, that is rendered as a subrequest (and updated by ajax)
- we create `OrderPreview` instance in `OrderController::previewAction` (which is called as a subrequest of the following two actions) and also in both `OrderController::indexAction` and in `CartController::indexAction` (on many projects)
- as a result, the `OrderPreview` instance is created twice in each step of the order process
- it is weird and worsens the performance
- I think it is possible to pass the `OrderPreview` instance in the request, e.g. in `Order/step2.html.twig` (of course, you need to pass the instance to the template from controller):
```diff
<div id="js-order-preview" class="box-order__cart" data-url="{{ url('front_order_preview') }}">
                    {{ render(controller('App\\Controller\\Front\\OrderController:previewAction', {
                        transportId: transport is empty ? null : transport.id,
                        paymentId: payment is empty ? null : payment.id
+						orderPreview: orderPreview
                    })) }}
                </div>
```
- I tried to prototype this on my project, the concept seems to be working, however, `preview.js` needs to be modified probably as the preview is not updated by the ajax properly when I select transport and payment in the second step of the order process

What do you guys think about that? :thinking: 

https://prnt.sc/s5rqn7

**Comment by vitek-rostislav** [comment]
Stale is not the answer I was looking for :smile:

**Comment by grossmannmartin** [comment]
Hi @vitek-rostislav,
I'm sorry for the delay. 

The idea itself seems really nice and make sense. I dig a little deeper into a problem and I found following

I too tried to prototype the behavior you describe and it's not a groundbreaking performance gain on the current master. I'm talking about a few milliseconds improvement and 3 DB queries less. 
Do you know about the scenario on any project, where the performance gain could be much better? 

It's not necessary to update `orderPreview.js`, in `previewAction` we can check the nullability of `orderPreview`. First render accept passed already calculated object, AJAX calls pass null and `orderPreview` is calculated then.


Working implementation could be following

<details>
 <summary>Click to show</summary>

```diff
diff --git a/project-base/src/Controller/Front/OrderController.php b/project-base/src/Controller/Front/OrderController.php
index 6cd2ec5d4..79dc9bea8 100644
--- a/project-base/src/Controller/Front/OrderController.php
+++ b/project-base/src/Controller/Front/OrderController.php
@@ -251,6 +251,7 @@ class OrderController extends FrontBaseController
             'transport' => $transport,
             'payment' => $payment,
             'payments' => $payments,
+            'orderPreview' => $orderPreview,
             'transportsPrices' => $this->transportPriceCalculation->getCalculatedPricesIndexedByTransportId(
                 $transports,
                 $currency,
@@ -295,6 +296,7 @@ class OrderController extends FrontBaseController
     {
         $transportId = $request->get('transportId');
         $paymentId = $request->get('paymentId');
+        $orderPreview = $request->get('orderPreview');
 
         if ($transportId === null) {
             $transport = null;
@@ -308,7 +310,9 @@ class OrderController extends FrontBaseController
             $payment = $this->paymentFacade->getById($paymentId);
         }
 
-        $orderPreview = $this->orderPreviewFactory->createForCurrentUser($transport, $payment);
+        if ($orderPreview === null) {
+            $orderPreview = $this->orderPreviewFactory->createForCurrentUser($transport, $payment);
+        }
 
         return $this->render('Front/Content/Order/preview.html.twig', [
             'orderPreview' => $orderPreview,
diff --git a/project-base/templates/Front/Content/Order/step2.html.twig b/project-base/templates/Front/Content/Order/step2.html.twig
index 1374df1ad..fdaf06c3c 100644
--- a/project-base/templates/Front/Content/Order/step2.html.twig
+++ b/project-base/templates/Front/Content/Order/step2.html.twig
@@ -107,7 +107,8 @@
                 <div id="js-order-preview" class="box-order__cart" data-url="{{ url('front_order_preview') }}">
                     {{ render(controller('App\\Controller\\Front\\OrderController:previewAction', {
                         transportId: transport is empty ? null : transport.id,
-                        paymentId: payment is empty ? null : payment.id
+                        paymentId: payment is empty ? null : payment.id,
+                        orderPreview: orderPreview
                     })) }}
                 </div>
             </div>
diff --git a/project-base/templates/Front/Content/Order/step3.html.twig b/project-base/templates/Front/Content/Order/step3.html.twig
index 22cade3dd..ee1ee966c 100644
--- a/project-base/templates/Front/Content/Order/step3.html.twig
+++ b/project-base/templates/Front/Content/Order/step3.html.twig
@@ -120,7 +120,8 @@
                 <div id="js-order-preview" class="box-order__cart" data-url="{{ url('front_order_preview') }}">
                     {{ render(controller('App\\Controller\\Front\\OrderController:previewAction', {
                         transportId: transport is empty ? null : transport.id,
-                        paymentId: payment is empty ? null : payment.id
+                        paymentId: payment is empty ? null : payment.id,
+                        orderPreview: orderPreview
                     })) }}
                 </div>
             </div>
```

</details>


But I'm not sure if it's worth it.

**Comment by vitek-rostislav** [comment]
Hi @grossmannmartin, thanks for the response and for your investigation :+1: I tried to apply the changes to our project and it saves around 20 DB queries in each order step :blush: 

Moreover, this change helps with debugging because you see fewer dumps :smile:

**Comment by pk16011990** [comment]
We are currently working on refactoring the order process - https://github.com/shopsys/shopsys/pull/3084

I hope it will be better.
