### ISSUE TITLE
Range price slider doesn't work correct on touch devices

### ISSUE THREAD

**Issue by Srnka392** [shopsys/shopsys#1815]
### What is happening

It is not possible move with handle on touch devices. 
This bug can be fix with plugin https://refreshless.com/nouislider/ instead of jquery UI slider.

### Expected result
Move with handle on all devices.

**Comment by pesektomas** [comment]
Hello @Srnka392,

this issue may be resolved in #1811.

**Comment by TomasLudvik** [comment]
Hello @Srnka392, this issue should have been solved in #1811, can you check it please?

**Comment by Srnka392** [comment]
Hello @TomasLudvik, yes it looks fine. thank you for your answer.
