### ISSUE TITLE
Error during install: Service 'php-fpm' failed to build...

### ISSUE THREAD

**Issue by pabloneruda1** [shopsys/shopsys#1816]
Step 30/32 : RUN if [ -n "$www_data_uid" ]; then deluser www-data && (addgroup --gid $www_data_gid www-data || addgroup --gid 33 www-data) && adduser --system --home /home/www-data --uid $www_data_uid --disabled-password --group www-data; fi;
 ---> Running in 6dca3c0153df
Removing user `www-data' ...
Warning: group `www-data' has no more members.
Done.
addgroup: The GID `0' is already in use.
Adding group `www-data' (GID 33) ...
Done.
adduser: The UID 0 is already in use.
Warning: The home dir /home/www-data you specified already exists.

**ERROR**: Service 'php-fpm' failed to build: The command '/bin/sh -c if [ -n "$www_data_uid" ]; then deluser www-data && (addgroup --gid $www_data_gid www-data || addgroup --gid 33 www-data) && adduser --system --home /home/www-data --uid $www_data_uid --disabled-password --group www-data; fi;' returned a non-zero code: 1

Ubuntu 18.04.4 LTS
installed demo app via "sudo ./scripts/install.sh"

How to solve?

**Comment by grossmannmartin** [comment]
Hi, the install script should not be run as root. 
I suggest allowing user to run docker (see https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user) and install the app with `./scripts/install.sh`

**Comment by grossmannmartin** [comment]
@pabloneruda1 Did you have time to look at it? Did it help?

**Comment by sslt** [comment]
As we have not received response, we are closing this issue.
