### ISSUE TITLE
stylelint - npm vs phing confusion

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#1835]
### What is happening
When building assets using npm, stylelint checks are included (https://github.com/shopsys/shopsys/blob/master/project-base/webpack.config.js#L102) - is this connected with `stylelint-(fix)` phing targets anyhow? 

I am confused, as my npm build failed on the checks - so I tried to run `stylelint-fix` but it failed on `Error: No files matching the pattern "/var/www/html/src/**/*.less" were found`

If these checks are the same as the ones used in npm build, it would be nice to make their path configurable for project-base. Otherwise, one of the checks should be removed. (I vote for the ones in nmp build and adding `stylelint(-fix)` phing target as a dependency for `standards(-fix)` target.

### Expected result
- it is possible to fix stylelint errors automatically
- npm build does not include stylelinter, or, a programmer knows what to do when npm build fails on stylelint errors
- there is only one way of checking and fixing styling errors and it is usable from project-base

**Comment by s3tezsky** [comment]
fixed in #1988
