### ISSUE TITLE
Multiple ckeditors on page slows page rendering significantly

### ISSUE THREAD

**Issue by grossmannmartin** [shopsys/shopsys#1852]
### What is happening
Each ckeditor field renders its own javascript and initializes the component.
When there are many ckeditor fields on the page (10 domains and another rich field renders 20 ckeditors on the product detail) page rendering is really slow.

Maybe this https://symfony.com/doc/current/bundles/FOSCKEditorBundle/usage/loading.html can help.

### Expected result
Page rendering is not affected by number of ckeditor fields on the page (that much :))

**Comment by s3tezsky** [comment]
fixed in #2177
