### ISSUE TITLE
Are ProductEditFormTypes still relevant

### ISSUE THREAD

**Issue by MattCzerner** [shopsys/shopsys#186]
## What is happening
After removal of `*EditData` it seems like `*EditFormTypes` are not needed, we should stick with only entity `FormTypes` to make form types easier to use and to not confuse devs with many undocumented types of `FormTypes`

### Problem
There is already many of `buildForm()` methods that needs to have `@ExcessiveLengthMethod` annotation because of length of method.

#### Possible solution
We should make FormTypes more modular, for example, ProductFormType has many of sections like 'Basic Information' or 'Display and availability', we could make FormType for each of them so methods arent so long as now.

**Comment by PetrHeinz** [comment]
We should wait with solving this issue until #375 is merged.

**Comment by vitek-rostislav** [comment]
I would remove all `*EditFormTypes` (i.e. `Product`, `Transport` and `Payment`)

**Comment by TomasVotruba** [comment]
Tip to automate closing of issues: https://help.github.com/articles/closing-issues-using-keywords/

E.g. closes #186
