### ISSUE TITLE
Product detail available in ReadModel

### ISSUE THREAD

**Issue by grossmannmartin** [shopsys/shopsys#1863]
### What is happening

In previus releases, a new layer (ReadModel) was introduced. Working with it is really nice and helps to keep responsibilities separated and twig templates more readable.

I think it would be really nice to introduce read model in product detail too because currently, product detail uses a different (direct) approach of rendering data than product list and it can lead to the necessity to copy-paste some blocks of code when implementing a project.

### Expected result
Can you consider adding product detail into read model layer (with all necessary dependencies – parameters, etc.)?

**Comment by pesektomas** [comment]
Hello @grossmannmartin, this is good point. I think so we should start with remove experimental tag from read model. What do you think? Or it is too early yet?

**Comment by grossmannmartin** [comment]
Personally, I like separation made with read model. 
And to me, it makes sense to use it. I understand it can bring higher complexity, to the application, but when used properly and properly extended on a specific project, I feel it's really a way to go.

So yes, I'm for removing experimental tag from read model.

**Comment by sslt** [comment]
We are planning to process this issue in minor 9.1.0
