### ISSUE TITLE
jQuery 3.5.1 breaks ElFinder

### ISSUE THREAD

**Issue by ondrej-petr** [shopsys/shopsys#1872]
New version of jQuery 3.5.1 develivered with framework 9.0.0 is not compatible with ElFinder bundle (helios-ag/fm-elfinder-bundle)

### What is happening
ElFinder doesnt display icons of files od dirs correctly

Go to wysiwyg editor (blog, product, ...), click to "add image" icon, click button "Find on server". If you already have any files uploaded, you should see the bug. Otherway upload some images first

Version of jQuery 3.4.1 works fine - tested.

**Comment by TomasLudvik** [comment]
Hi @ondrej-petr, major problems have been solved in #1899.
