### ISSUE TITLE
Product export to elastic takes too long time on older SSWF versions

### ISSUE THREAD

**Issue by sspooky13** [shopsys/shopsys#1873]
### What is happening
In version [7.3](https://github.com/shopsys/shopsys/blob/7.3/packages/framework/src/Resources/config/services/cron.yml#L7-L9) is exported all products to elastic every hour and in version [8.1](https://github.com/shopsys/shopsys/blob/8.1/packages/framework/src/Resources/config/services/cron.yml#L7-L9) every 5 minutes. The problem is one unnamed project which is in 8.1 version, has 10 932 products and 3 domains and export to elastic take approx 2-3 minutes. If customer adds next approx 10 000 products or several domains then cron for export products to elastic will take whole 5 minutes and he does not every nothing else.

### Expected result
In versions 8.x and 7.x are exported to elastic only changed products

**Comment by grossmannmartin** [comment]
Hi @sspooky13,

you can easily override the cron settings to match your needs (see example in https://github.com/shopsys/shopsys/blob/8.1/project-base/src/Shopsys/ShopBundle/Resources/config/services/cron.yml). 
Or you can separate exporting products into [separate cron instance](https://docs.shopsys.com/en/7.3/introduction/cron/#multiple-cron-instances) to prevent the problem you described.

Version 7.3 now gets only patches and we don't plan to include any new features into that branch, just bugfixes.

I don't think any more minor releases are planned in 7.x and 8.x versions, maybe @sslt can confirm or denied that.

**Comment by sspooky13** [comment]
Hello @grossmannmartin,
I understand and in future that mentioned project will be upgraded to 9. version (I hope) but I would glad to resolve this issue for other companies.

Other companies/programmers don't have to know about this issue and then they will be surprised why crons don't run.

Maybe add at least info somewhere about recommending add this cron to separated cron instance 🤷.

**Comment by grossmannmartin** [comment]
I see, but this can be tricky as you need to run export to elastic after changes in your products are made (eg. after import from IS, after visibility/availability/price recalculations, and other product-related cron modules specific for the project).

I tried to summarize the behavior in #1973. Can you please take a look if the behavior is clear from the text or suggest an improvements? 

Thanks

**Comment by sspooky13** [comment]
Hello @grossmannmartin,
I don't know how exactly you work with version but your text info is merged to 7.3 where is written about `services.yaml` but this file doesn't exist but `services.yml` already exists. Next, you write about CronModuleExecutor is declared in `services.yml` but it's not true because in 7.3 is executor called in [CronFacade](https://github.com/shopsys/shopsys/blob/7.3/packages/framework/src/Component/Cron/CronFacade.php#L59) not is declared as service. 
In the end, that text is maybe good but I expected info about export product to elastic can you eat whole time to run cron and others cron instances don't have to run so we recommend separate that cron to next cron instance, now it's mentioned as side scenario. I don't know how you write your docs, it can be well written and my expectation is very different 🤷

PS: that PR was merged and this issue is still open, so if you are satisfied with that text you can close this issue.

**Comment by grossmannmartin** [comment]
Hi @sspooky13,
thanks for pointing out the mistakes in the text. I wrote it in 9.0 branch and didn't realize changes made in the process. My bad. I fixed it in #1975.

About the cron export. The way I see it's a more general problem than just export to elastic. On <different unnamed project> we had the same problem on version 9 and with different cron module, so I tried to summarize the limitations in a more general way.

**Comment by sspooky13** [comment]
Hello @grossmannmartin,
I didn't know another cron module has same issue 🤔 In that case I am ok with that "common way". Anyway is still better as without that info 😁.

BTW: if this issue is in next SSFW versions so I recommend you add this info to master and don't forgot close this issue after merging your PR ☝

**Comment by grossmannmartin** [comment]
Thanks for reminding me. I added the info into all documented versions and closing this issue as done. Thanks again for your contribution.
