### ISSUE TITLE
javascript translations do not work properly

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#1875]
### What is happening
Even though there is `bazinga-translator` and its function `Translator.trans` used in the javascript (see e.g. https://github.com/shopsys/shopsys/blob/master/packages/framework/assets/js/admin/components/CategoryDeleteConfirm.js#L11), I still see the texts in English after setting `shopsys.admin_locale: cs` in `parameters_common.yml` and running `php phing npm`. See https://prnt.sc/spich2

Tested on the clean project-base installation. It seems that the problem is only in administration, it works on the frontend.

### Expected result
Translations in javascript work

**Comment by grossmannmartin** [comment]
translations in init and construct methods are tricky, but this should be solved with #1841 (https://github.com/shopsys/shopsys/pull/1841/files#diff-828c624aa251f843e7cb5cb23b875403)

**Comment by pesektomas** [comment]
Hi @grossmannmartin, I think so Víta has it there, I have to look at it

**Comment by TomasLudvik** [comment]
This has been solved in #1880, closing
