### ISSUE TITLE
Command shopsys:administrator:change-password did not hash password

### ISSUE THREAD

**Issue by ondrejbohac** [shopsys/shopsys#1881]
Hello, i used command shopsys:administrator:change-password and figure out password is saved to DB in plain format. Probably there is missing hashing function. 

### Expected result
Hashed password :))

**Comment by s3tezsky** [comment]
Hi @ondrejbohac you have to use `security:encode-password` command first. Then copy the hash into input of `shopsys:administrator:change-password`.

I agree with you to make the command more straightforward so I leave this issue opened.

**Comment by ondrejbohac** [comment]
Hello @s3tezsky, ok, I get it now :). 
I am sorry if I missed any description somewhere, but if it missing I think it will be great to add it since this functionality could not be changed.

**Comment by TomasLudvik** [comment]
Hi @ondrejbohac, this has been fixed in #1901.
