### ISSUE TITLE
Functional tests fails when Frontend API is enabled

### ISSUE THREAD

**Issue by Swejzi** [shopsys/shopsys#1883]
### What is happening
Enable Frontend API on SSFW 9.0 on first domain and run `./phing tests-functional`

```
There were 2 errors:

1) Tests\FrontendApiBundle\Functional\Login\LoginTest::testLoginMutation
ErrorException: Notice: Undefined index: data

/var/www/html/tests/FrontendApiBundle/Functional/Login/LoginTest.php:21

2) Tests\FrontendApiBundle\Functional\Logout\LogoutTest::testLogoutMutation
ErrorException: Notice: Undefined index: data

/var/www/html/tests/FrontendApiBundle/Functional/Logout/LogoutTest.php:23
/var/www/html/tests/FrontendApiBundle/Functional/Logout/LogoutTest.php:14
```

### Expected result
Success functional tests

**Comment by s3tezsky** [comment]
Hello @Swejzi,

I tried to reproduce these error without succes. Probably it was fixed already.
During investigation I found different issue in ChangePasswordTest - I created #1091.

Could you verify the original issue is resolved please? I would like to close this one.

**Comment by s3tezsky** [comment]
I am closing this issue. In case you get these errors again feel free to reopen.
