### ISSUE TITLE
Export (changed) products to Elasticsearch is infinite

### ISSUE THREAD

**Issue by pk16011990** [shopsys/shopsys#1884]
Version 9.0.0

Crons `ProductExportCronModule` and `ProductExportChangedCronModule` do not mark exported products as exported. It means that once marked products are still exported by next run of  `ProductExportChangedCronModule`.

My personal opinion from debuging this: solution by events it is crazy and for me it has not good DX.

Expected result: Product is marked as exported ASAP after export (not after whole export - it can take tens minutes)

**Comment by pk16011990** [comment]
It needs a bigger rework of the code. We want to use queues (eg. Symfony Messenger and MeseRabbitMQ). But it will in version 14 and higher probably. PR is welcomed.

**Comment by grossmannmartin** [comment]
resolved by #2917
