### ISSUE TITLE
Admin header wrapping without buttons

### ISSUE THREAD

**Issue by CarabineSK** [shopsys/shopsys#1887]
### What is happening

The text is wrapping in admin header.

![image](https://user-images.githubusercontent.com/6003253/83846604-27a7ab00-a70b-11ea-8902-0010ac7b333a.png)

### Expected result
I believe that we should not have the empty div for buttons (if it is empty)
![image](https://user-images.githubusercontent.com/6003253/83846782-6c334680-a70b-11ea-95b6-556c537b255b.png)
maybe that would help a bit.

![image](https://user-images.githubusercontent.com/6003253/83846682-473ed380-a70b-11ea-8c8c-f0eb6c13198c.png)

**Comment by s3tezsky** [comment]
fixed in #1986
