### ISSUE TITLE
Bestselling products - hard coded number of products in form

### ISSUE THREAD

**Issue by KadelaKuba** [shopsys/shopsys#1889]
### What is happening

For showing bestselling products on FE is used constant `MAX_RESULTS = 10`. But in administration number of products in form is hard coded. So when you need to change the number of products o n FE, you need to extend the form type in admin a change it here too. 

```
for ($i = 0; $i < 10; $i++) {
    $builder->get('products')
        ->add($i, ProductType::class, [
            'required' => false,
            'placeholder' => null,
            'enableRemove' => true,
        ]);
}
```

### Expected result

Avoid unnecessary overriding an admin form type. Use constant instead for example.

**Comment by s3tezsky** [comment]
Solved in mentioned PR
