### ISSUE TITLE
Installation on windows - some phing targets not working correctly

### ISSUE THREAD

**Issue by CarabineSK** [shopsys/shopsys#1890]
I'm running Windows with native symfony server `symfony server:start` for php-fpm, but other like redis, postgresql, elasticsearch are still in docker. I have done this because I want to get rid of docker-sync. 
It was quick to make the change to make it work correctly on 127.0.0.1:8000.
What is the issue is that some phing targets are crashing on errors.

### What is happening

1. running `php phing npm` causes issue with scripts in package.json
```
"copy-assets": "./assets/js/bin/copyAssets.js",
"trans": "./assets/js/bin/trans.js",
"trans:dump": "./assets/js/bin/transDump.js",
```

2. 
Php phing targets in ecs (ecs-diff, ecs-fix, ecs-fix-diff) have wildcard `<arg path="${path.root}/*.md"/>` that does not work. In my Cmder, bash on windows or similar terminals it works. It looks like phing (or php exec) is running the commands in cmd, so it does not use the wildcards correctly in argument list.
```
    <target name="ecs-fix-diff" description="Checks and fixes automatically fixable coding standards in changed files by PHP easy coding standards." hidden="true">
        <exec executable="${path.ecs.executable}" logoutput="true" passthru="true" checkreturn="true">
            <arg value="check"/>
            <arg value="--fix"/>
            <arg path="${path.app}"/>
            <arg path="${path.src}"/>
            <arg path="${path.tests}"/>
            <arg path="${path.root}/*.md"/>
            <arg path="${path.root}/docs"/>
        </exec>
    </target>
```

### Expected result / How to solve it

1. I have fixed in our team the first issue like this:
I have added `node` to three scripts. It seems to work on both windows and linux
```
"copy-assets": "node ./assets/js/bin/copyAssets.js",
"trans": "node ./assets/js/bin/trans.js",
"trans:dump": "node ./assets/js/bin/transDump.js",
```

2. I have used quick fix that I'm naming all .md:
    `<arg path="${path.root}/CONTRIBUTING.md"/>` etc.
There are some options how to fix it. php function glob() for example can chew even wildcards.
Also, there might be different approach in phing that lists all files in argument list. I could not find that myself quickly.

**Comment by sslt** [comment]
Currently this is not very urgent issue from our perspective, we will look into this problem as soon as we have some spare time. Any help is welocme.
