### ISSUE TITLE
Wrong argument sent to OrderItemNotFoundException

### ISSUE THREAD

**Issue by LuKillman** [shopsys/shopsys#1898]
### What is happening

Class `Shopsys\FrameworkBundle\Model\Order\Order` attempts to throw `OrderItemNotFoundException` on line 725 but it supplies `array` instead of `string|null` as the first argument so `TypeError` is thrown instead. 

### Expected result

Either `OrderItemNotFoundException` should override its parent construct to accept `array` as the first argument or `string` should be supplied as the first argument.

**Comment by sslt** [comment]
will be closed with release of patch version 9.0.1

**Comment by s3tezsky** [comment]
Solved in mentioned PR
