### ISSUE TITLE
 Admin: Product detail: JS validation does not work for the newly added parameter

### ISSUE THREAD

**Issue by jakubhavlak** [shopsys/shopsys#190]
**How to reproduce:**

1. Open the iPhone editing in administration
2. Add a new parameter and leave the values ​​blank
3. Get out of the box
4. Submit a form

**What will happen:**

When you leave the box, nothing happens.
The form can be sent even though the parameter is not filled in.

**What should happen:**

When leaving the box, a validation message should pop up.
The form should not be sent.

**Note:**

Once the form has been submitted, JS validation for that parameter works.

**Comment by boris-brtan** [comment]
Part of the issue with unwanted saving of form was moved into #374
