### ISSUE TITLE
Product side menu duplicated on error save

### ISSUE THREAD

**Issue by CarabineSK** [shopsys/shopsys#1907]
When editing product and you get error message, side menu is duplicated.

### What is happening
Try to edit product and save product with 2 same parameters like this:
![image](https://user-images.githubusercontent.com/6003253/86102411-c8477b80-babb-11ea-91d7-7c60e5f8f75b.png)

Then after save the side menu is duplicated:
![image](https://user-images.githubusercontent.com/6003253/86102503-e319f000-babb-11ea-9d4e-198609893983.png)

### Expected result

Side menu remains the same, does not duplicate.

**Comment by s3tezsky** [comment]
Resolved in mentioned PR
