### ISSUE TITLE
Recalculation of prices might not be executed

### ISSUE THREAD

**Issue by jakubhavlak** [shopsys/shopsys#191]
When editing product, it is flagged for price recalculation and depends on service ProductPriceRecalculationScheluderer that in the end of request runs the recalculation. If however is product edited in CLI (like transfers) recalculation does not run and the product has wrong prices set.

**Comment by Miroslav-Stopka** [comment]
Hi Jakub, thank you for your notice. 

This problem is already being solved in issue #202
