### ISSUE TITLE
Translation in shopsys/framework displayed on frontend are hard to translate.

### ISSUE THREAD

**Issue by TomasLudvik** [shopsys/shopsys#1911]
### What is happening
There are several translations in framework, for example in `ProductListOrderingModeForListFacade::getProductListOrderingConfig()` where sorting options are.

Developers of project have to find way to find all these translations and add them to translation files in project-base, so they are then able to translate them.

### Expected result
Frontend translations in `shopsys/framework` and ultimately all packages are dumped into `project-base` translation files.

**Comment by grossmannmartin** [comment]
I would like to split admin and frontend translation into separate domains, so it's easier to translate only parts I need for my project. 
Then it's not much of a problem when translation stays in the original package as they can be easily identified.
