### ISSUE TITLE
[monorepo-tools] Merge PRs from subrepos? 

### ISSUE THREAD

**Issue by mikob** [shopsys/shopsys#1914]
The docs mentioned that it would be difficult to merge PRs from subrepos. It's pretty important for me to allow for contributions in the subrepos, and it's the big reason I use them (to keep parts of my project public).

Can someone help me figure out how we could get this to work?

I think another script like `merge_branch_from_remote.sh [git repo@branch]` would be the right UX.

How it would work:
* Add a remote of where the PR lives
* ??? somehow merge the PR branch into the monorepo 
* Remove the temporary remote
* (optional) `monorepo_split.sh` to push changes into remote subrepos

**Comment by henzigo** [comment]
Hello,
I thought about it and probably it can be done. Probable first, your script needs to copy changes from that PR to your local monorepo (but you need to configure paths for each subrepository). After that, your script could create commit or PR in your monorepo.

What do you think about it?

**Comment by mikob** [comment]
@henzigo Although straightforward, the issue with that is that we lose the info about the contributor :/

**Comment by grossmannmartin** [comment]
Hi @mikob,
sorry for the late response.
As I understand, you need a bidirectional synchronization between monorepo and split repositories, is it right?

You need to merge changes into a subdirectory (I found some SO topic on this https://stackoverflow.com/questions/6426247/merge-git-repository-in-subdirectory). But I'm not really sure how will it then behave when you split the repo back.

Also, I see a potential problem when only some repositories are public and/or PR's are made in split repositories. When they're somehow connected, you may easily end up with PR that breaks some functionality in the monorepo (and author of the PR has absolutely no clue about it and even cannot fix it). So then it's still up to you to make things right (after the merge? then it's broken at some point. Before the merge? you need to do it in monorepo by yourself and include changes from a subrepo).
And maybe repositories are not related together at all, but then I don't think the monorepo is the right way to go.

From this reason, I think it's not the use case, that should be supported, but if you come up with the solution, I gladly check the PR, though :)

**Comment by sslt** [comment]
We are closing this issue for now, if you feel like proposing solution using pull request, feel free so.
