### ISSUE TITLE
Broken design in confirmation box when module "Accessories in purchase confirmation box" is enabled

### ISSUE THREAD

**Issue by sslt** [shopsys/shopsys#1925]
### What is happening
When the module "Accessories in purchase confirmation box" is enabled, there seem to be problem with design of modeal window after adding product to cart. See https://prnt.sc/tgub3g

To reproduce: 
1. enable "Accessories in purchase confirmation box"
2. Go to frontend to product with defined accessories
3. Add product to cart
4. in confirmation modal window you can see broken design (no images, suspicious design)

### Expected result
Design is not broken for accessories in modal window after adding product to cart

**Comment by TomasGottvald** [comment]
There were problem with new content in popup window - we have to add call registerNewContent - to enable all js functions for lazyload and spinbox functionality.

https://github.com/shopsys/shopsys/pull/1995

**Comment by s3tezsky** [comment]
fixed in #1995
