### ISSUE TITLE
Missing documentation or better exception for `DisplayOnlyType`

### ISSUE THREAD

**Issue by pk16011990** [shopsys/shopsys#1943]
FormType

### What is happening
`Shopsys\FrameworkBundle\Form\DisplayOnlyType` has very specific behaviour in few edge-cases. 

My situation:
ProductFormType has collection of custom compound form type. This compound form type has following field:
```php
->add('futureProductQuantity', DisplayOnlyType::class, [
    'mapped' => true,
])
```
There cannot be option `data`, because data of this field is depend on data of whole collection in `ProductFormType`.

Form is rendered right, but when it is send with invalida data (exists custom validator without JS implementation), action in controller tries to render this form with submitted form data. However developer get fatal error with: 
```
Twig\Error\RuntimeError

An exception has been thrown during the rendering of a template ("Notice: Array to string conversion") in "@ShopsysFramework/Admin/Form/displayOnlyFields.html.twig".
```
It is caused by missing data in submitted data (`DisplayOnlyType` does not  use any html input) and in combination that `DisplayOnlyType` has parent form type `FormType` which is compound. It means that data for `FormType` is array. 

Set `DisplayOnlyType`'s compound option  as FALSE is only suppression, not solution -> renderwith empty data.

### Expected result
I do not know, how to solve it. It looks like unresolvable for collections. But It shoud be documented or It should have more descriptive Exception. Maybe exception can be thrown in creating form, not only rendering invalid form (harder to detect).

**Comment by grossmannmartin** [comment]
closed by #2184
