### ISSUE TITLE
it is not possible to exclude a file from annotation-check command

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#1958]
### What is happening
I would like to have an option for skipping a particular file from these checks as now, my build is broken because of a typo in the framework and I am not able to fix it easily. (I had to implement the "skip" functionality on my project to solve my problem)

### Expected result

It is possible to exclude files from annotation-check and annotation-fix commands

**Comment by vitek-rostislav** [comment]
I can create a pull request for that but it will take some time as I am pretty busy these days :smile:

**Comment by grossmannmartin** [comment]
Hi @vitek-rostislav,
thanks for the issue, PR would be super-helpful as we have many points to improve that is more important from my point of view, what do you think? 

And if there are some typos in the framework, please let us know and we try to fix it preferably
