### ISSUE TITLE
Product Search does not work with characters like slash and others

### ISSUE THREAD

**Issue by jakubhavlak** [shopsys/shopsys#196]
As mentioned in !24 
- if product name (or other ts_vector searched text) contain slash, product is not possible to find by exactly same text
- there are other characters which should be considered as part of searched token/word for TSQUERY

creating tokens should be done via Postgres to get 100% functioning results.

For example TsQueryFactory::getTsqueryWithOrConditions() could do something like this: SELECT to_tsquery(regexp_replace(plainto_tsquery('english', 'The Fat Rats&cats the|wonderful / beasts ABC/123 XX-11 YY - 22')::text, E'&', '|', 'g'));

Merge request can be found here:
https://git.shopsys-framework.com/shopsys/shopsys-framework/issues/42

**Comment by PatrikBajer** [comment]
Still pending for example I have product ABC/123 whisperer doesn't show me relevant product. http://prntscr.com/jufar7 

Same as other characters. @boris-brtan

**Comment by boris-brtan** [comment]
thx, seems that is works also with | & ....

**Comment by LukasHeinz** [comment]
BV done

**Comment by vitek-rostislav** [comment]
solved in #300
