### ISSUE TITLE
Admin product accessories - the chosen product is added to form more than once

### ISSUE THREAD

**Issue by KadelaKuba** [shopsys/shopsys#1962]
### What is happening

In this scenario if you choose product as product accessory for example, this product is added to form more than once. 

1. Go to product edit page in admin
2. In `Acessories` section click on button `+ Add product`
3. In popup window click on `Advanced search` tab
4. Change filter rule to `Catalogue number` forexample and do not fill catnum
5. Do not click on `Search` and choose some product as accessory product
6. After that, the product is added to form more than once

After saving the product, the duplicated products disappears (because of `RemoveDuplicatesFromArrayTransformer`).

### Expected result

Add product to form only once, as the user would expect.

**Comment by TomasLudvik** [comment]
Fixed in #1963 that is already merged
