### ISSUE TITLE
Doctrine fails to hydrate non-unique rows when using iterator

### ISSUE THREAD

**Issue by mposchl** [shopsys/shopsys#1968]
### What is happening
When you run `Shopsys\FrameworkBundle\Model\Pricing\Vat\VatDeletionCronModule`, you can get error in ObjectHydrator:536. It is due to fact, that doctrine cannot hydrate rows, while query used in iterator. Bug in Doctrine [here](https://github.com/doctrine/orm/issues/7496).

### Expected result
Select only distinct products (as these are the same) in `\Shopsys\FrameworkBundle\Model\Product\ProductRepository::getProductIteratorForReplaceVat`

**Comment by s3tezsky** [comment]
fixed in #1967
