### ISSUE TITLE
Admin: reset.less: disable scrollbar normalization in order to fix problems with jQuery UI drag&drop

### ISSUE THREAD

**Issue by jakubhavlak** [shopsys/shopsys#198]
@marek.fiser reported an issue in Chrome that caused misaligned cursor and dragged item when using drag&drop on *Articles overview* in administration.

![2017-12-13__1__li](https://user-images.githubusercontent.com/33071107/41108263-624f6eda-6a74-11e8-98f3-199506922869.jpg)
*(the red cross shows position of the cursor)*

It is a well known issue of *necolas/normalize.css* fixed in this commit: https://github.com/necolas/normalize.css/commit/6ef5b9e78a0eb13b7799fa7e0ad284d065f84e7f

I also reviewed our `admin/core/reset.less` which was hard to maintain because it was based on some old version of https://github.com/necolas/normalize.css and mixed with custom rules so I was not sure what code was from upstream and which were our customizations. So I divided it to `reset.less` which contains only upstream code from *necolas/normalize.css* and `reset-custom.less` that contains our custom rules.

I also checked the most of the pages in Administration side-by-side with the previous `reset.less` in Firefox 57 and it matches almost perfectly. The only difference is that previously pages that were shorter than the screen height (eg. administration login page) had a visible grayed out vertical scrollbar and now the scrollbar is not visible on such pages .

I recommend to check it in browsers other than Firefox before merging.

Merge request can be found here:
https://git.shopsys-framework.com/shopsys/shopsys-framework/merge_requests/21

**Comment by PatrikBajer** [comment]
Still, you can see fix in pull request. @boris-brtan
