### ISSUE TITLE
Invalid HTML output due to image lazyload

### ISSUE THREAD

**Issue by xTommy** [shopsys/shopsys#1980]
### What is happening
When using twig image macro with lazyload, i.e. `{{ image(product, { itemprop: 'image', alt: product.fullname }) }}` which is defined in `vendor/shopsys/framework/src/Twig/ImageExtension.php` in method `getImageHtmlByEntityName`- and when you using lazyload (attr lazy) then **src is set to empty string**, but this output is **invalid according to W3C**, src cannot be empty. For lazyload I'm solving this by using base64 data-uri image, but i cannot change this file and i cannot set src attribute in image macro also (it's overriden in getImageHtmlByEntityName method).

### Expected result
Possibly two options:

1. Add some image placeholder by default (in src - so src attribute will not be empty) - base 64 data-uri seems to be an option (make this possible to be overriden please).

1. Allow us to define src attribute in twig macro (now it's always set to empty string, when you using lazy attr) - i.e. `{{ image(product, { src: 'placeholder.svg' }) }}` - just modify the condition for lazyload in `getImageHtmlByEntityName`, thanks.

**Comment by TomasLudvik** [comment]
While solving this it would be also great to think how this lazyload and possible solution of this issue influence SEO (images indexing...)

**Comment by sslt** [comment]
Perhaps there is third and preferred option....
we could use othe element for images to be lazyloaded, say "dataimg" and next to it would be hidden in "noscript" element original link to valid image. Lazyload javascript would replace "dataimg" with "img".
