### ISSUE TITLE
Phing target stylelint not working after webpack update

### ISSUE THREAD

**Issue by TomasGottvald** [shopsys/shopsys#1981]
### What is happening

I tried to check less syntax via command line `php phing stylelint` it shows error - 
`error: No files matching the pattern "/var/www/html/src/**/*.less" were found. 
`. Seems to be logic, we changed less path to assets. So i tried to change path in build.xml from `${path.src}` to `${path.assets}/styles/`.
Error disappeared, output of stylelint is green, but even if code contains error (tried manualy add spaces and other stuff)

### Expected result

Fixed path for *.less files with full functionality of stylelint and stylelint-fix

**Comment by TomasLudvik** [comment]
Duplicity of #1835

**Comment by s3tezsky** [comment]
fixed in #1988
