### ISSUE TITLE
Standard for yaml files are alphabetically sorted

### ISSUE THREAD

**Issue by jakubhavlak** [shopsys/shopsys#199]
Hello, i create library for check yaml files are alphabetically sorted. U can add directory and all file by finded recursive or u can add path to file for check. U can add too path to file, which will be exclude for check. I sort only all service files and path file in project because i dont know what u want check. That library is located in https://github.com/sspooky13/yaml-alphabetical-checker. If you want more information, you know where to find me :)

I will glad every feedback. Thank you for approve this.

Also mentioned in:
https://git.shopsys-framework.com/shopsys/shopsys-framework/merge_requests/19

**Comment by sspooky13** [comment]
Please do not close this issue, I believe, I finish my checker soon, then I send pull request with a description and with implemented checker.

Thanks

**Comment by TomasVotruba** [comment]
@sspooky13 I'm just curious, in what way it differs from https://github.com/mhujer/yaml-sort-checker ?

**Comment by PetrHeinz** [comment]
Hi @sspooky13, any update on the checker you've mentioned?

**Comment by sspooky13** [comment]
Hello @PetrHeinz, i am glad, you are interested. I need finish a fix command and maybe make little refactoring. I think in a few days will be released and then i create pull request on shopsys framework.

**Comment by sspooky13** [comment]
Hello, @PetrHeinz i create finally pull request with this checkers, which you are interested. You can see in this pull request #539.

**Comment by boris-brtan** [comment]
hi @vitek-rostislav ,
would it be possible to continue with #539 PR in the near future ?

**Comment by vitek-rostislav** [comment]
> hi @vitek-rostislav ,
would it be possible to continue with #539 PR in the near future ?

Hi @boris-brtan, well, hopefully in the next sprint within 2 weeks, it is not planned in the current sprint...

**Comment by LukasHeinz** [comment]
There has to be a lot of conversation in related PR so I create short summary for this issue:
The library https://github.com/sspooky13/yaml-alphabetical-checker has been made part of SSFW but only for check of indentation in YAML files. The alphabetical order check has not been used due to a missing fixer. 

Because this issue is mainly about alphabetic checks, I leave it open with a reminder that PR for resolving this issue should contain also a fixer.

**Comment by sspooky13** [comment]
If will you have more patience I finish sometimes fixer for alphabetical checker (it's last one wich missing 😊) but I need more time 😐

**Comment by pk16011990** [comment]
project base without alphabetic sorting contains totaly mess in services.yml. Please fix it :(

**Comment by pesektomas** [comment]
I think so it could be an easy pick, we have updated the yaml-standards library, so we should just add a checker to https://github.com/shopsys/shopsys/blob/master/yaml-standards.yaml and https://github.com/shopsys/shopsys/blob/master/project-base/yaml-standards.yaml

**Comment by s3tezsky** [comment]
Hi @jakubhavlak and @sspooky13,

I am not really sure if we are ready for this huge change. The most annoying thing is primary the `services(_test).yaml` (where `_test` is going to be pretty much reduced).

Here I have some troubles I ran into while trying to apply the rule:
1. I am missing a fixer for sorting in the library. It will be such a pain to reorder each yaml file.
2. The checker checks all yaml files (parameters, travis, kubernetes files and others) which I personally do not like. (e.g. I do not want parameters to be sorted alphabetically as the parameters are orginizes into ligocal parts and renaming parameters now is not an option how to solve it).

**Comment by TomasLudvik** [comment]
I got info from @sspooky13, that fixed might be available until end of the year, so we have to wait for it, I am changing milestone to 9.2.
