### ISSUE TITLE
Excluding product from sale by admin causes error in existing cart

### ISSUE THREAD

**Issue by roulajan** [shopsys/shopsys#1991]
shopsys/framework": "9.0.0"

### What is happening
I add items to cart as customer. Then admin excludes product from sale. If I have this excluded product already in cart, it causes error 500, if exluded item is not last in my cart (in array index).

1. Add product to cart
2. Add another product to cart 
3. Sign in as admin and exclude product from sale (with lower array index)
4. load cart page

class CartWatcherFacade uses checkNotListableItems function to remove not listable items. The process is handled by removeItemById function which causes array index mismatch. Items in carts are indexed as:
[0 => Product1, 1 => Product2, 2 => Product3] If Product1 is removed by CartWatcherFacade, the indexes for other products stay same [1 => Product2, 2 => Product3]. That causes mismatch in CartController in indexAction for $cartItems vs. $cartItemPrices

$cartItems: [**1** => Product2, **2** => Product3]
$cartItemPrices: [**0** => Product2Price, **1** => Product3Price]

### Expected result
function removeItemById should rearrange array indexes after any element is removed

**Comment by s3tezsky** [comment]
Fixed in #2185
