### ISSUE TITLE
Unusable CategoryFacade::editOrdering for larger data sets

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#1993]
### What is happening
When there are several hundreds of categories, it is quite impossible (takes too much time and consumes too much memory) to use drag&drop ordering in admin (`CategoryFacade::editOrdering`). The Gedmo/NestedSet extension is not suitable for that, so on a few projects, there is a kind of hack for solving this: 

There is a new attribute `Category::$position` that is set in the `CategoryFacade::editOrdering`:
```diff
- $this->em->flush($category);
- $this->categoryRepository->moveDown($category, CategoryRepository::MOVE_DOWN_TO_BOTTOM);
+ $category->setPosition($position++);
```

Then, the attribute is used for ordering, basically instead of `c.lft` in query builders:
```diff
- ->orderBy('c.lft')
+ ->orderBy('c.position, c.lft')
```

I do not like the fact that we need to maintain another attribute to be able to get the tree properly (that is what the `lft` and `rgt` are for), and it might be kind of confusing that lft and rgt attributes are not taking the order into account, however, to make the drag and drop usable, this "hack" is probably justified.

### Expected result
It is possible to use categories D&D in admin even for larger data sets and the existence of from the first point of view unnecessary `$position` attribute is documented (if you decide to implement it this way :slightly_smiling_face: )

**Comment by grossmannmartin** [comment]
resolved by #2328
