### ISSUE TITLE
[cs] remove docs that are already typehinted, pre-PHP7 prepare

### ISSUE THREAD

**Issue by jakubhavlak** [shopsys/shopsys#200]
I'm upgrading packages on Github to PHP 7/PHP7.1 with automated tools:

- https://github.com/Symplify/EasyCodingStandard
- https://github.com/RectorPHP/Rector

It's very fast upgrade that does 80 % work for you.

I'd like to try it here when decide to do so, starting with this dummy PR.

Let me know what you think :)

(I didn't run tests yet. I'd do it so and fix false positives after/if this gets a go).

Merge request available here:
https://git.shopsys-framework.com/shopsys/shopsys-framework/merge_requests/17

**Comment by TomasVotruba** [comment]
Especially this 1 fixer: 
https://www.tomasvotruba.cz/blog/2017/12/17/new-in-symplify-3-doc-block-cleaner-fixer/

**Comment by Miroslav-Stopka** [comment]
Hi,
we discussed it with several developers, and we decided to annotate everything. This is the most standard way, and at the same time makes the annotation clear and consistent. Problem will be solved in #417. I'm closing this issue.
