### ISSUE TITLE
Deleting CustomerUser fails if the cart is not empty

### ISSUE THREAD

**Issue by CarabineSK** [shopsys/shopsys#2008]
You get error 500 when deleting customer user with filled cart. Found on 9.0.1.

### What is happening

When you have CustomerUser with items in cart, you will see error on delete such customer from admin.

1. I have CustomerUser, I log in as user and add 1 product to cart.
2. I then go back to administration and click delete on Customer users overview.
3. I get this crash:

![image](https://user-images.githubusercontent.com/6003253/91540492-2a392b80-e91b-11ea-99fe-41eeda99efba.png)

### Expected result

It should delete customer instead with his cart being removed together with cart items (I think).

**Comment by s3tezsky** [comment]
fixed in #2010
