### ISSUE TITLE
monorepo-tools: changing commit message

### ISSUE THREAD

**Issue by SirWindfield** [shopsys/shopsys#2015]
I have some repositories that use conventional commits. I was looking for a tool that could merge them together into one repository. Additionally I wanted to change the commit message so that the scope component of it refers to the mono repo package, basically overwriting any existing value in it.

I am no gut expert, but is it possible to modify the script so that it changes the message (which should be relatively easy) and keep the same hashes as the single repo ones? 

I think that this is impossible as iirc the hash is calculated based on the content and the message itself, so changing the message would inevitably change the hash as well.

In that case, what would be a Good approach to still allow for splitting and upstream pushes to the old repositories? Since the hashes differ now it's not possible to match commits to their old repositories.

Thanks for taking your time for helping me out! Have a great week!

**Comment by simara-svatopluk** [comment]
Hi,
> I think that this is impossible as iirc the hash is calculated based on the content and the message itself, so changing the message would inevitably change the hash as well.

That's correct. Changing commit message means change in the hash.

Sorry, I don't understand what are You trying to achieve in global....

So, You would like to change the commit message, this is possible, but results in changed hash. Then if You try to push to the old repository, well You'll get a conflict. One solution could be to force push all the work to old repositories, and then continue with changed hashes. Is this a solution to Your situation?

You can achieve changing commit messages automatically by forking the monorepo-tools, and adding `--msg-filter` into this `filter-branch` https://github.com/shopsys/monorepo-tools/blob/master/rewrite_history_into.sh#L18
It's additional work, but I believe it's possible

**Comment by SirWindfield** [comment]
Thanks for the explanation! Your solution would definitely work. I can change the commit message back as well, as I just append one line of text to each.
