### ISSUE TITLE
Wrong currency in Customers overview Orders value

### ISSUE THREAD

**Issue by CarabineSK** [shopsys/shopsys#2021]
Customers overview grid column Orders value have wrong currency in it.

### What is happening

For example on master heimdall you can see this on domain 2:  
![image](https://user-images.githubusercontent.com/6003253/92100687-674e6380-eddc-11ea-9fa3-64f1d0387e9f.png)

but when you look at the customer, the story is different. It is in CZK not euro:  
![image](https://user-images.githubusercontent.com/6003253/92100752-79c89d00-eddc-11ea-863f-505b17dbae0f.png)

 (btw format here in orders overview is not very nice  as well)
![image](https://user-images.githubusercontent.com/6003253/92100825-8f3dc700-eddc-11ea-8611-358387efa522.png))

### Expected result

MoneyConvertingDataSourceDecorator is not doing its job here. I would expect to see usage of QueryBuilderWithRowManipulatorDataSource or fix it in any different way, just to see correct currencies.

**Comment by grossmannmartin** [comment]
related to #1539
