### ISSUE TITLE
Inconsistent indentation size

### ISSUE THREAD

**Issue by jakubhavlak** [shopsys/shopsys#205]
Issue#38 Inconsistent indentation size
https://git.shopsys-framework.com/shopsys/shopsys-framework/issues/38

All php, js, less and twig files have 4 spaces indentation, but yml uses only 2 spaces.

It will be big BC break, but I think, that It should be changed until the beta version will be ended, in my opinion.

**Comment by simara-svatopluk** [comment]
* I will solve all files - php, js, less, twig, yml
* Everyhting will have 4 spaces indentaion
* I'll check if there is a sniff that can monitor this

**Comment by TomasVotruba** [comment]
I think you already know & use this, but just in case:

- https://github.com/Symplify/Symplify/blob/master/.editorconfig
- https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.12/src/Fixer/Whitespace/IndentationTypeFixer.php - might be usable for Twig as well
 
Btw, if you find some rule/packages that enforces this on YAML level, I'd like to know. I use them quite often and would love to have this checked by CI

**Comment by vitek-rostislav** [comment]
I believe it is loosely connected with https://github.com/shopsys/shopsys/pull/539 - there are some checkers/fixers for yaml files implemented

**Comment by simara-svatopluk** [comment]
don't stale me, don't stale me, no more

**Comment by pk16011990** [comment]
...

**Comment by vitek-rostislav** [comment]
The original problem with YAML indentations is resolved by https://github.com/shopsys/shopsys/pull/539
