### ISSUE TITLE
JS error when using NotBlank constraint with radiobuttons

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#2054]
### What is happening
When you use `NotBlank` constraint for a radio button (i.e. `ChoiceType` with `'multiple' => false, 'expanded'  true`), you get a JS error (see the screen below) on the input change - see `/admin/advert/new/`

![Screenshot from 2020-09-30 11-40-50](https://user-images.githubusercontent.com/10401898/94703477-285df000-033f-11eb-882c-530676bcb8ea.png)

Because of that, you are able to submit the invalid form and server-side validation needs to handle the situation.

During the investigation with @grossmannmartin, we have found out that the problem is in `isExpandedChoiceEmpty` function in `customizeBundle.js` (introduced in [this commit](https://github.com/shopsys/shopsys/commit/69e31e14909b955905f68804fae955f384a5732a#diff-705d2c91614b0f939230fdb251a75240R295)). The `value` that is passed there from the radio is a simple string. On the other hand, when you use checkboxes, the value is array indeed but therefore, checkbox will never meet [this condition](https://github.com/shopsys/shopsys/blob/master/packages/framework/assets/js/common/validation/customizeBundle.js#L180). So this raises a question, for what is this good for? Is not it possible to simply remove [this extension](https://github.com/shopsys/shopsys/blob/master/packages/framework/assets/js/common/validation/customizeFpValidator.js#L203)? It looks like the "not blank" JS validation works just fine on checkboxes and radio buttons without that :thinking: @pk16011990 might have some additional thoughts on this topic :slightly_smiling_face: 

### Expected result
No JS error on the "not-blank constrained" radio button change.

**Comment by grossmannmartin** [comment]
closed by #2223
