### ISSUE TITLE
Wrong exchange rate after changing default currency

### ISSUE THREAD

**Issue by dostrozlik** [shopsys/shopsys#2059]
### What is happening
On v9.0, there is a problem with exchange rates after changing the default currency in admin.
After you change the default currency the exchange rate of old default currency is set to 1 instead of the correct value that should be calculated and exchange rates of other currencies are not correct as well.

eg.
CZK - default currency
EUR - exchange rate - 27,12 Kč per 1 €
GBP - exchange rate - 29,92 Kč per 1 £

after changing default currency to EUR

CZK - exchange rate - 1 € per 1 Kč
EUR - default currency
GBP - exchange rate - 29,91 € per 1 £

### Expected result
after changing default currency the exchange rate of old default currency should be calculated by the exchange rate.

from eg.
CZK - exchange rate - 0,037 € per 1 Kč
EUR - default currency
GBP - exchange rate - 1,10 € per 1 £

**Comment by grossmannmartin** [comment]
closed with #2332
