### ISSUE TITLE
Revising instalation on windows with Docker

### ISSUE THREAD

**Issue by dostrozlik** [shopsys/shopsys#2060]
### What is happening

There a few changes with the introduction of WSL2 by Windows so the current documentation need few more steps/checks to work properly. (Docker uses WSL2 by default, Debian installs itself as WSL2 as well which causes issues)

### Expected result

It would be best do a revision of instalation guide for windows with docker to add those steps/checks.
Or it would be good to try instalation with WSL2 as its maybe not necessary not have Windows pro and higher versions to be able to install SSFW.

**Comment by pk16011990** [comment]
Installation on Windows with WSL2 has been updated in https://github.com/shopsys/shopsys/pull/2272

I'm closing the issue. If there is a specific problem with the installation, please create an issue with a description of the problem.
