### ISSUE TITLE
Allow to configure connection to external services with URL string

### ISSUE THREAD

**Issue by s3tezsky** [shopsys/shopsys#2072]
### What is happening

In current state we are connecting to external services (such as database, mailer) by configuring all parameters separately (host, port, user, password). Developer would like to use URL string (e.g.: `mysql://db_user:db_password@127.0.0.1:3306/db_name`) instead.

### Expected result

It is considered to keep both ways of setting connection to external service (url strings overrides partial parameters - [same as in doctrine configuration](https://symfony.com/doc/current/reference/configuration/doctrine.html#doctrine-dbal-configuration)). The ENV variables `<SERVICE>_URL` are introduced and used for connection to database, mailer and maybe others services.

**Comment by pk16011990** [comment]
During an internal discussion, we concluded that we will not implement this change. The benefits are not sufficient for us.

If someone wants to create a PR, feel free. We will dedicate internal capacity to other features.
