### ISSUE TITLE
Search box not trimmed

### ISSUE THREAD

**Issue by CarabineSK** [shopsys/shopsys#2073]
When you search for some specific info, for example EAN you will not find it if you have space around search term.

### What is happening

When you type for example `"8845781245930"` you will find product.
When you type `"    8845781245930    "` you will not find it since the autosearch input is not trimmed.

### Expected result

I would expect search box to be trimmed, or at least ean code and similar found when copied from elsewhere with whitespace after the search term.

**Comment by grossmannmartin** [comment]
closed by #2187
