### ISSUE TITLE
FeedItemInterface - dependency of tag content to model and feed generation process

### ISSUE THREAD

**Issue by jakubhavlak** [shopsys/shopsys#208]
Issue#31 FeedItemInterface - dependency of tag content to model and feed generation process
https://git.shopsys-framework.com/shopsys/shopsys-framework/issues/31

FeedItemInterface contain method getId() which is used in \Shopsys\ShopBundle\Model\Feed\FeedFacade::generateFeed() for storing last seeked ID of product.

value of getId() from FeedItemInterface is often used in feed implementation as tags/attributes which represents ID of eshop Products.

This is hidden dependency of FeedItem->id to FeedFacade logic AND application model (Product->id)

There should be mentioned in FeedItemInterface implementations that using getId may cause not-obvious problem if you want to use this method/value for retrieving different value than Product->id

**Example:**

client request was: use in HeurekaCz/HeurekaSk/Google feeds our ID from IS instead of your ID (SSFW Product id - Product->id)
we implemented it by passing ID from IS to construct of FeedItemInterface as id
because the IDs from IS was almost same, nobody notice that some of items were not present in feed
this was caused by that ID from IS was used for storing lastSeekedId in FeedFacade and other logic in of feed generation use this ID as it was Product->id - but it was not
Possible Solutions:

**possible solutions to fix this problem were:**

change all FeedItemInterface implementations and store both values - our ID and ID from IS - and use ID from IS only on output
change implementation of all repositories which retrieve products and change SOME of columns to use ID from IS - but still some other columns use Product->id
in the end we choose 2) solution, because we want in feeds only product which have this ID form IS because eshop can have Product without ID from IS - so we change both of this things in repositories

but generally I think the 1) solution is better

**Proposal:**

I suggest to use some kind of naming convention for methods and properties names in implementations of FeedItemInterface

getTagProductName
getTagDescription
getTagItemId
getAttributeGift
getAttributeId
getAttributeDelivery etc.
note that getTagItemId / getAttributeId AND getId(from interface) may contain completely different values

**Summary:**

the main point behind this issue is that there is not-obvious logic and dependency of: model, feed generation process AND view(feed content)

**Comment by PetrHeinz** [comment]
Resolved in #271, seek ID and ID rendered in the feed are separated concepts.
