### ISSUE TITLE
Login as user at first does not work after db-demo

### ISSUE THREAD

**Issue by grossmannmartin** [shopsys/shopsys#2097]
### What is happening

Steps to reproduce:
1. run `./phing db-demo`
2. login to admin in the customer section
3. edit customer on the second domain
4. click login as user

After the first click, you are not logged in, but you stay in the admin. The second click works fine.

See the screen recording https://vimeo.com/474958284

### Expected result
We know why this is happening and we can login after the first click.

**Comment by pk16011990** [comment]
I can't reproduce it on versions 14 and 15-dev.
