### ISSUE TITLE
Option multipleForm generates wrong labels attribute "for" and "id" of input

### ISSUE THREAD

**Issue by jakubhavlak** [shopsys/shopsys#210]
Issue#29 Option multipleForm generates wrong labels attribute "for" and "id" of input
https://git.shopsys-framework.com/shopsys/shopsys-framework/issues/29

Option {{ form_start(form, {attr: {'multipleForm': true}}) }} in forms causes wrong relation between label and input.

For example login form has "Remember me login" checkbox, but the label is not clickable :(

Html of this form is:

<input type="checkbox" name="front_login_form[rememberMe]" class="id__front_login_form_rememberMe" value="1">
<label for="front_login_form_rememberMe">Remember my login</label>

**Comment by vitek-rostislav** [comment]
There is a user-story -for fixing this issue - https://app.yodiz.com/plan/pages/detail.vz?cid=10273#/us-3947
