### ISSUE TITLE
OrderProductFacade does not refresh product entities after recalculations

### ISSUE THREAD

**Issue by malyMiso** [shopsys/shopsys#2108]
### What is happening
[OrderProduct::runRecalculationsAfterStockQuantityChange](https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Model/Order/Item/OrderProductFacade.php) runs product recalculations (visibility, selling denied, availability, etc.). All recalculations are run as native SQL queries.
After that run product entity is not refreshed.  What it means during active/running request is that the product is still visible even when it was sold out.

In SSFW itself it causes no problems. 
It can be a problem after extending functionality. It is hard to find out, why product is still visible, even when it was sold out. In source code, everything looks fine. It is a bit mysterious, isn't it ? 

Because of this mysterious behavior, another issue was discovered and solved in #2084 

### Expected result
All product data become actual after recalculations during running request.

**Comment by sslt** [comment]
Thank you @malyMiso, could you please provide example of code so we can simulate the behaviour you describe here.

**Comment by grossmannmartin** [comment]
Hi @malyMiso,
I created a test case and fix in #2202. Can you please check if it solves the problem you described?

**Comment by s3tezsky** [comment]
Fixed in #2202
