### ISSUE TITLE
Wrong usage of Doctrine native queries

### ISSUE THREAD

**Issue by henzigo** [shopsys/shopsys#2121]
## Describe the bug

Native queries should be used only for SELECT queries. In SSFW codebase there are a lot of native queries with insert/update/delete behavior. This can be a problem for large projects that need database replication because native queries are queried to replica databases. That will throw an exception.

Doctrine native query documentation: https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/native-sql.html
Additional info about replication doctrine: https://github.com/doctrine/dbal/blob/2.12.x/lib/Doctrine/DBAL/Connections/PrimaryReadReplicaConnection.php#L19

### Expected behavior

Native queries should be checked and adjusted to avoid run destructive SQL operations with `createNativeQuery`

PS: If you need more information, please contact me :)

**Comment by sslt** [comment]
Thanks @henzigo . We will adress this issue before release of upcoming 9.1.0.
