### ISSUE TITLE
Preparation of read model on product detail for extension

### ISSUE THREAD

**Issue by pesektomas** [shopsys/shopsys#2130]
## Describe the expected outcome of your requested feature

We have a lot of classes ready for extension on the project in the framework  (for example the Product entity, his data class and factory). I think it would be nice to have data prepared in this way for the use of the read model. Maybe not just for use on product detail.

This is something that is overloaded on every project (in my opinion)

**Comment by pesektomas** [comment]
Hello @sslt,

when a read model for product detail is added in version 9.1, why are extension classes in project-base that work better with it only added in 9.2? :smile_cat:

**Comment by grossmannmartin** [comment]
Hi @pesektomas,

unfortunately, we don't have enough time we would like to solve all problems. 
This was postponed as it's not a bc break and therefore it's not absolutely necessary to release in the same version with read model product detail.

I understand the bitterness of such a decision but put everything in one release means this version will never be released and sometimes a hard choice has to be made.

Hope you understand

**Comment by pesektomas** [comment]
Hi, I understand, but it's a shame. For each project, the product detail is modified. The logic of the work is completely changed in version 9.1 and to prepare 2-3 classes (empty classes, without any logic), which would make work easier for everyone from the beginning, comes as a nice helping hand to implementation teams ;)

**Comment by pesektomas** [comment]
It's just a pity that if we have an extension ready for a product entity, data class and data class factory we do not have classes ready for the read model. But I understand that day have 24 hours only.

**Comment by pk16011990** [comment]
Read-model will not be maintained after version 13.0.0 (FE API replaces it).

Version 12 will be LTS; if it's still relevant for some projects to this version, feel free to create PR.
