### ISSUE TITLE
Better extensibility and work with ProductDetailView object

### ISSUE THREAD

**Issue by pesektomas** [shopsys/shopsys#2147]
I think the properties in ProductDetailView should be set using setters and not just by a constructor.

Why do I think that?

Ad 1. ProductDetailView object will have many and many properties during implementation and if we set properties by setters, we would avoid errors of type `Argument 37 passed to App \ Model \ Product \ Detail \ ProductDetailView :: __ construct () must be of the type int, string given`

Ad 2. I think it could improve the extensibility of the object. The object factory could be have the `createInstance` and` fillFrom * `methods and I think if the data was set in the` fillFrom * `method and you added an attribute there, I wouldn't have to worry about it at all during promotion, because this method would solve it for me. Currently I would have to extend the constructor and add a new attribute to the correct place in the `parent :: __ construct` call.

Please consider it. I really like reading objects and they make sense to me. With the described modification, it would be possible to work with them even better on the implementation. Or so I think. If you perceive it differently, we can talk about it.

**Comment by sslt** [comment]
Thank you @pesektomas, currently we are undecided, whether to use this  approach. We will contact you  to further discuss and argue the "correct way".

**Comment by pesektomas** [comment]
Thank you, I understand.

**Comment by pk16011990** [comment]
Read-model will not be maintained after version 13.0.0 (FE API replaces it).

Version 12 will be LTS; if it's still relevant for some projects to this version, feel free to create PR.
