### ISSUE TITLE
Manual how to add icon in few easy steps

### ISSUE THREAD

**Issue by jakubhavlak** [shopsys/shopsys#216]
Example: lists in the administration has standardly icons for edition and deletion. I want to add a new function with no icon presented in SSFW.  I don't know where to look for SVG icons and don't know the way to edit them so they can be used in SSFW. 

Also would be nice a list of used icons because for example on Windows I can't see the detail of icon in explorer and I'm forced to open them in editor one by one.

**Comment by LukasHeinz** [comment]
Due to the current refactoring of forms in administration this issue is no longer relevant. I do not suppouse that adding icon to the form in admin will be major issue around beta. Nevertheless supported changes in admin forms will be documented.
