### ISSUE TITLE
Changing the parameter name does not affect the product detail

### ISSUE THREAD

**Issue by pesektomas** [shopsys/shopsys#2160]
## Describe the bug
If I change the name of the parameter, then after the introduction of loading the product detail from the elastic, the change will not take effect until all products have been exported to ES

### Expected behavior
When I change a parameter, products with this parameter should be marked for export to the ES.

I think so in MarkProductForExportSubscriber is missing catch a ParameterEvent :: UPDATE event that already exists.

**Comment by grossmannmartin** [comment]
Good catch! thank you. 
This will be probably related to #2090

**Comment by grossmannmartin** [comment]
closed with #2251
