### ISSUE TITLE
It is not possible to delete/rename file in elfinder

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#2162]
### To Reproduce

1. Go to https://github.com/shopsys/shopsys/blob/master/project-base/config/packages/fm_elfinder.yaml#L16 and allow uploading other files than images (`upload_allow: ['all']`)
2. Go to product detail in admin
3. go to a wysiwyg (e.g. product description)
4. click on add link - https://prnt.sc/w3y56f
5. choose on the server - https://prnt.sc/w3y5mv
6. upload a pdf file
7. try removing/renaming the file
8. see error "File not found at path: web/content/wysiwyg/_thumbnails/..."

### Expected behavior
It is possible to remove/rename uploaded file on the server

### Environment (please complete the following information)
 - OS: Ubuntu
 - Browser: Chrome 
 - Version: 87.0.4280.66 (Official Build) (64-bit)
 - Device laptop

### Additional context
I think the problem is related to https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Component/Filesystem/Flysystem/VolumeDriver.php

**Comment by grossmannmartin** [comment]
Thank you for reporting!

**Comment by sslt** [comment]
Solved, merged, we are closing this one.
