### ISSUE TITLE
Should not CsvReader use abstract filesystem?

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#2171]
## Describe the expected outcome of your requested feature
https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Component/Csv/CsvReader.php uses functions like `file_exists` or `is_readable` - but these are unusable when the files are stored in an external filesystem, e.g. S3 that we use in our cloud.

Uploading a CSV to S3 is a common use-case when migrating data from an old eshop.

Should not this component work with `FilesystemInterface` instance for the filesystem functions? :thinking:

**Comment by grossmannmartin** [comment]
Hi @vitek-rostislav,
thanks for the tip.

I'm looking at the AwsS3Adapter (used by projects to connect to S3 as you mentioned). 
https://github.com/thephpleague/flysystem-aws-s3-v3/blob/4e25cc0582a36a786c31115e419c6e40498f6972/src/AwsS3Adapter.php#L461

It seems to me I cannot use `read` method as it looks like it loads the whole file to memory (which you really don't want to do). 
So maybe `readStream` can be used, but I'm not sure about performance impact. In the end, I will be streaming a file over HTTP while processing. Is it equally fast?

Rewrite this class is a huge BC break, so probably another one should take place instead. But this class is not used in framework, so should really be created? (and this one kept as it's not used as well)?

TBH, current CSVReader does not make sense to me.
- It's more a "helper" class to me and as such, the method could be static and class should not be a service.
- It cannot be used for larger CSV files as it loads the whole content to the memory (as one big array).
- Same method exists in the PHP itself https://www.php.net/manual/en/splfileobject.fgetcsv.php#example-4816


So what I'm suggesting is
- deprecate this class in favor of `SplFileObject::fgetcsv()`
- (possibly) create new streamed csv reader able to handle big CSV files (without loading into memory) and one that accept  `FilesystemInterface` instance

What do you think?

**Comment by sslt** [comment]
Hello @vitek-rostislav . Perhaps it would be better to download relevant file to local filesystem a process it from there? We plan to deprecate this helper anyway as it is not used at all in SSFW.
