### ISSUE TITLE
Problem with locks in elfinder

### ISSUE THREAD

**Issue by pesektomas** [shopsys/shopsys#2172]
## Describe the bug
The elfinder library uses some kind of file locks to detect that a abort command has completed. This lock file is created by storing the path in the `$abortCheckFile` variable and using the php function `touch()` to create a file according to this path. 

The file is created either in the folder defined in the connectionFlagsPath settings, or in the folder defined in the commonTempPath settings or in the `sys_get_temp_dir folder` (see https://github.com/Studio-42/elFinder/blob/master/php/elFinder.class.php#L2515). 

The problem is that the elfinder works with the server through ajax, so it may happen that one request creates a lock, the other request has to check it, but the check does not take place because the other request takes place on another pod (see https://github.com/Studio-42/elFinder/blob/master/php/elFinder.class.php#L5031).

In the access log, it looks like this (date, path, status code):

```
Dec 16, 2020 @ 09:50:52.000	/elfinder?CKEditor=category_form_description_descriptions_1&CKEditorFuncNum=1&langCode=cs	200
Dec 16, 2020 @ 09:50:53.000	/efconnect?cmd=open&target=fls1_d2ViL2NvbnRlbnQvd3lzaXd5Zy9rYXRlZ29yaWUvc3dpbVNwYQ&init=1&tree=1&_=1608108653178	200
Dec 16, 2020 @ 09:50:54.000	/efconnect?cmd=abort&id=1766abebf4231a&reqid=1766abec0c53d9	200
Dec 16, 2020 @ 09:50:54.000	/efconnect?cmd=editor&name%5B%5D=ZohoOffice&name%5B%5D=ZipArchive&name%5B%5D=OnlineConvert&method=enabled&reqid=1766abebcf33ce	200
Dec 16, 2020 @ 09:50:55.000	/efconnect?cmd=abort&id=1766abebd5e4a&reqid=1766abec0ca39	200
Dec 16, 2020 @ 09:50:55.000	/efconnect?cmd=abort&id=1766abebf433a6&reqid=1766abec0cb2b2	200
Dec 16, 2020 @ 09:50:55.000	/efconnect?cmd=abort&id=1766abebf4657&reqid=1766abec0cc205	200
Dec 16, 2020 @ 09:50:55.000	/efconnect?cmd=open&reload=1&target=fls1_d2ViL2NvbnRlbnQvd3lzaXd5Zy9rYXRlZ29yaWUvc3dpbVNwYQ&tree=1&compare=&reqid=1766abebf4231a	200
Dec 16, 2020 @ 09:50:55.000	/efconnect?cmd=open&target=fls1_d2ViL2NvbnRlbnQvd3lzaXd5Zw&tree=1&init=1&reqid=1766abec0c5365	200
Dec 16, 2020 @ 09:50:57.000	/efconnect?cmd=parents&target=fls1_d2ViL2NvbnRlbnQvd3lzaXd5Zy9rYXRlZ29yaWUvc3dpbVNwYQ&reqid=1766abebd5e4a	500
```

### To Reproduce
It's terribly difficult to simulate, because we have to have a multi pods application and ensure that the lock is created on one pod and control on the other, all in the right order and at the right time.

### Expected behavior
cancel locks in the elfinder, or move to a shared environment, or silence an error (?!)

### Environment (please complete the following information)
Our cloud

### Additional context
You can contact me ;)

**Comment by grossmannmartin** [comment]
In #2259 we silenced thrown `elFinderAbortException` (thanks @pesektomas for the inspiration) so error 500 is not raised and it will not spam the logs. 
We would like to solve this issue properly (= it's safe to run application on multiple php-fpm workers) and the first step is issue Studio-42/elFinder#3272
