### ISSUE TITLE
Administration-> Goods-> Editing-> If I insert a picture as a reference into the description (wysiwygu), the frontend will not appear, an error will appear in the console.

### ISSUE THREAD

**Issue by jakubhavlak** [shopsys/shopsys#219]
The image from the file is loaded and appears on Frontend.
![image](https://user-images.githubusercontent.com/31988844/41040835-cea478fa-699d-11e8-84e6-9d671b0e6877.png)

**Comment by PatrikBajer** [comment]
Seems right, you can close.@boris-brtan

**Comment by boris-brtan** [comment]
Great news.
