### ISSUE TITLE
Administrator can log in himself as a customer on different domain

### ISSUE THREAD

**Issue by s3tezsky** [shopsys/shopsys#2198]
## Describe the bug

As an administratort I can login as a user on different domain than user is registred to.

### To Reproduce

1. Go to Administration -> Customers -> switch to second domain -> click on any customer
2. Copy link from `login as customer` (`http://127.0.0.1:8000/admin/sso/2?originalReferer=http://127.0.0.2:8000/admin/customer/login-as-user/8/`), change url to `http://127.0.0.1:8000/admin/sso/2?originalReferer=http://127.0.0.1:8000/admin/customer/login-as-user/8/` and paste it into your browser.
3. Now you are logged in as second domain user on first domain

### Expected behavior

You can login as customer on his domain only.

**Comment by grossmannmartin** [comment]
resolved by #2323
