### ISSUE TITLE
It's possible to buy product for zero price

### ISSUE THREAD

**Issue by grossmannmartin** [shopsys/shopsys#2205]
## Describe the bug
Under some circumstances is possible to have a product with zero price and I'm able to buy this product.

### To Reproduce

1. Remove from DB all prices for product from table `product_manual_input_prices`
2. Remove from DB all prices for product from table `product_calculated_prices`
3. Export data to Elasticsearch
4. See product with zero price on the frontend you're able to buy

### Expected behavior
**It should not be possible to buy a product with zero price under any circumstances.**

### Additional context
This is not the only scenario, but merely easy steps to simulate the behavior. 
It does not matter how, even if it's programmer error or not executed recalculation, the product should not be buyable with zero price.

**Comment by s3tezsky** [comment]
Fixed in #2239
