### ISSUE TITLE
Breadcrumbs are not translated

### ISSUE THREAD

**Issue by ondrej-petr** [shopsys/shopsys#2231]
Items from `Shopsys\FrameworkBundle\Model\Breadcrumb\SimpleBreadcrumbGenerator` are not translated. During the translation (`Shopsys\FrameworkBundle\Component\Translation\Translator::staticTrans`) of breadcrumbs when no `$domain` and no `$location` is set, code works with default location (CS in my case) instead of SK location.

**Comment by grossmannmartin** [comment]
Hi,
thanks for filling the issue. 

I checked the functionality on the current version and did not notice any problems on the first nor second domain. 
Can you please provide steps to replicate the bug or minimum reproducible code?

**Comment by ondrej-petr** [comment]
Hi Martin,
you are right, it works OK. The wrong behavior was caused by another modification.
