### ISSUE TITLE
H1 title in the logo is unnecessary

### ISSUE THREAD

**Issue by Srnka392** [shopsys/shopsys#2243]
## Describe the bug
H1 title is in the header as a parent element for the logo. H1 title cannot be in the header, because if there is another one in the content it will be probably ignored by SEO robots.H1 title has to be only one per page and H1 relevant for content of the page is more important than generic H1 in the logo.

### Expected behavior
Delete H1 from the header.

**Comment by grossmannmartin** [comment]
may be related to #2048

**Comment by grossmannmartin** [comment]
closed with #2048
