### ISSUE TITLE
Elasticsearch exceptions should be separated

### ISSUE THREAD

**Issue by s3tezsky** [shopsys/shopsys#2245]
## Describe the expected outcome of your requested feature

When working with Elasticsearch structure we are creating different exception of type `ElasticsearchIndexException` (see https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Component/Elasticsearch/Exception/ElasticsearchIndexException.php). This may lead to dificult catching of those exception.

Class `ElasticsearchIndexException` should be split into many children to improve cachins specific exceptions.

**Comment by grossmannmartin** [comment]
closed by #3003
