### ISSUE TITLE
Do not allow to partial export to Elasticsearch when there is not correct structure created

### ISSUE THREAD

**Issue by s3tezsky** [shopsys/shopsys#2247]
## Describe the expected outcome of your requested feature

In #2233 we had changed the way how elasticsearch data are expoorted. In case we there is no structure created in ES the export command creates one or when the structure is not up to date it is migrated to new one.

This is not applied for partial export (for exportiing changed data). In case anyone try to export partial data when ES structure is not up to date or even exist the export should fail onn exception with recommendations what to do (run migrate command).

**Comment by sslt** [comment]
Solved, merged, closing
