### ISSUE TITLE
Cannot create unaccent extension in Google Cloud SQL 

### ISSUE THREAD

**Issue by rudolfmedula** [shopsys/shopsys#2257]
Hi,

I'm having trouble running migrations on Google managed Cloud SQL Postgres database.
This piece of code
`// Extensions are created in schema "pg_catalog" in order to be able to DROP
  // schema "public" without dropping the extension.
  // We do not want to DROP the extension because it can only be created with
  // "superuser" role that normal DB user does not have.
  $this->getConnection()->exec('CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA pg_catalog');`

As I understand it Cloud SQL does not allow superusers so it cannot create this extension in pg_catalog

Is this something perhaps your DevOps team has encountered with some deployments? Any help would be appreciated, for now I just create this extension in the public schema, but this requires changing the vendor files or creating custom commands, wondering if there is a better way. Thank You

**Comment by grossmannmartin** [comment]
Hi, thanks for the question.

You're right, this is tricky. 

I found some info in the documentation – https://cloud.google.com/sql/docs/postgres/extensions. But I presume it's not possible to create an extension in schema `pg_catalog` with the user with a role `cloudsqlsuperuser`. Can you confirm or deny it?

Maybe you can skip the migration `Version20180603135340` and replace it with your custom (almost identical, except for the name of the schema) and then override `CreateDatabaseCommand`. 
That should do the trick and allows you to create extensions in the current schema without altering vendor files.

I'm not aware of an easier solution. 

Maybe @henzigo will have some ideas?

**Comment by rudolfmedula** [comment]
@grossmannmartin thank you for the reply. I can confirm that `cloudsqlsuperuser` role did not allow me to create extensions in pg_catalog. Overriding the migrations and command is nice workaround and will have to work with it then. One caveat is that some of the commands like `db-demo` I believe drop the public schema and then there is a problem that the functions like unaccent does not exist and I guess that is why you have it in the pg_catalog in the first place. Point is one has to be very cautious when deploying to Cloud SQL. Anyway thank you for your help. This issue is maybe something to think about since in the framework and lot of the documentation mentions Google Cloud Platform and seemed to me like preferred cloud provider (with the terraform files and such). Either way good job it was very good experience working with the framework  🚀

**Comment by grossmannmartin** [comment]
Yes, db-demo drop the public schema, so extra caution is in place. 
We're experiencing similar troubles with our (different) cloud platform, where user is allowed to delete the schema, but cannot create it. 
I believe working with DB should be updated with the newest experience.
I can imagine rework cleaning DB, so it's not necessary to drop the whole schema, move extensions into the schema.
But right now it's just thoughts and I cannot make any promises for the implementation in the nearest future.

Thank you for really useful points 👍
