### ISSUE TITLE
OpCache parameters improvement doesn't seem to improve performance

### ISSUE THREAD

**Issue by simara-svatopluk** [shopsys/shopsys#226]
### We improved OpCache parameters, but our testing tell us the performance got worse.

* Happend in commit https://github.com/shopsys/shopsys/commit/5ae21b61054f5ca7e8ed549b13b555aab610d69f
* Performance testing tell us the performance got worse by 5.3% what is unexpected and strange

**Comment by vitek-rostislav** [comment]
We should spend some time to explore whether some of the OpCahce parameters are not just simply set badly. If not, we can improve the performance by reverting the commit...The performance should be measured before and after that.

**Comment by grossmannmartin** [comment]
Is this still relevant?

**Comment by grossmannmartin** [comment]
Running performance checks before commit 5ae21b6

**Comment by boris-brtan** [comment]
are they still running?

**Comment by LukasHeinz** [comment]
Now we are preparing a reliable performance testing environment on Google Cloud. After it will be ready, we will test the different settings of opcachce once more.

**Comment by simara-svatopluk** [comment]
Looking forward to see results! :-)

**Comment by LukasHeinz** [comment]
Me too :-)

**Comment by hacfi** [comment]
Just from a quick glance: I think you're missing

```
opcache.validate_timestamps=0
```

because as you have

```
opcache.revalidate_freq=0
```

it will check scripts every single request.

**Comment by LukasHeinz** [comment]
Thank you for your insight @hacfi 

We are currently experiencing some unreliability in the performance testing environment. Once it will be fixed (probably until the end of the month). We will look into this again.
