### ISSUE TITLE
MethodAnnotationsFactory::getMethodParameterNamesWithTypes() cannot generate default values

### ISSUE THREAD

**Issue by PetrHeinz** [shopsys/shopsys#2273]
## Describe the bug

Phing target `annotations-fix` cannot generate @method annotations with default values. This can be considered an edge case, but it may produce warnings if you override a particular class (see below).

### To Reproduce

1. Override `UploadedFileDataFactory` service and `UploadedFileData` data object.
2. Run phing target `annotations-fix`.
3. See `@method \App\Component\UploadedFile\UploadedFileData createByEntity(object $entity, string $type)` appear in your new class, even though the `string $type` is optional.
4. Call the method without the second parameter elsewhere in your project.
5. Run phing target `phpstan`
6. Build fails.

### Workaround
Add a ignore into your `phpstan.neon` and ignore warnings in your IDE:
```neon
        -
            # Annotations check is unable to comprehend @method annotations with optional parameter.
            message: '#^Method App\\Component\\UploadedFile\\UploadedFileDataFactory::createByEntity\(\) invoked with 1 parameter, 2 required\.$#'
            path: *
```

Or override the method in question without really doing anything:
```php
    /**
     * @param object $entity
     * @param string $type
     * @return \App\Component\UploadedFile\UploadedFileData
     */
    public function createByEntity(
        object $entity, 
        string $type = UploadedFileTypeConfig::DEFAULT_TYPE_NAME
    ): BaseUploadedFileData {
        return parent::createByEntity($entity, $type);
    }
```

### Expected behavior

Default parameter values should be marked as such in `@method` annotations.

This can be achieved with such modification of the `MethodAnnotationsFactory::getMethodParameterNamesWithTypes()`:
```php
    /**
     * @param \Roave\BetterReflection\Reflection\ReflectionMethod $reflectionMethod
     * @return string
     */
    protected function getMethodParameterNamesWithTypes(ReflectionMethod $reflectionMethod): string
    {
        $methodParameterNamesWithTypes = [];
        foreach ($reflectionMethod->getParameters() as $methodParameter) {
            $methodParameterNamesWithTypes[] = sprintf(
                '%s $%s%s',
                $this->annotationsReplacer->replaceInParameterType($methodParameter),
                $methodParameter->getName(),
                $methodParameter->isDefaultValueAvailable() ? '=' . json_encode($methodParameter->getDefaultValue()) : ''
            );
        }

        return implode(', ', $methodParameterNamesWithTypes);
    }
```

But this will duplicate the `@method` annotations after running `annotations-fix`, eg.:
```diff
  * @method __construct(\App\Component\UploadedFile\UploadedFileFacade $uploadedFileFacade)
  * @method \App\Component\UploadedFile\UploadedFileData create()
  * @method \App\Component\UploadedFile\UploadedFileData createByEntity(object $entity, string $type)
+ * @method \App\Component\UploadedFile\UploadedFileData createByEntity(object $entity, string $type="default")
  */
 class UploadedFileDataFactory extends BaseUploadedFileDataFactory
 {
```

Seems that the command cannot parse the annotations correctly so it appends the annotation instead of replacing it. That needs fixing as well.

### Additional context

If you can get the fix into next patch releases, I would find the time to make a PR with a fix. I would add test cases to cover this new functionality.

This issue is probably there since the `annotation-fix` phing target was introduced.

**Comment by sslt** [comment]
Hi @PetrHeinz, thank you for this issue. We will be adding this issue to next patch version (9.1.2), kindly provide suggested PR and tests please. :)
