### ISSUE TITLE
Support PHP 8.0

### ISSUE THREAD

**Issue by vasilvestre** [shopsys/shopsys#2282]
I need https://github.com/shopsys/coding-standards to allow PHP 8.0 install. I do not see any CI playing with PHP version in this repo, I can simply add || ^8.0 to composer.json but that wouldn't help a lot.

Where to start ? :)

**Comment by grossmannmartin** [comment]
Hi, thanks for the PR and issue. 
Unfortunately, this is not yet possible as there are dependencies in shopsys/coding-standards that does not allow PHP 8.0 (symplify/easy-coding-standard, friendsofphp/php-cs-fixer)

This first requires upgrading those libraries.

**Comment by vasilvestre** [comment]
symplify/easy-coding-standard supports PHP 8 on tag ^9.0
friendsofphp/php-cs-fixer supports PHP 8 from tag 2.17.0

**Comment by grossmannmartin** [comment]
You're right, It's not a matter of increase the number in composer. 
At least symplify/easy-coding-standards introduce a bunch of bc breaks that need to be addressed (this may be related to #2209) and we want to take into consideration how will this affect the projects that want to upgrade in the future.

**Comment by vasilvestre** [comment]
> You're right, It's not a matter of increase the number in composer.

Sure it's not :) But I'm working on libraries that need help as much as possible these last time and helping here is fine!

> At least symplify/easy-coding-standards introduce a bunch of bc breaks that need to be addressed (this may be related to #2209) and we want to take into consideration how will this affect the projects that want to upgrade in the future.

ECS may be faster to upgrade using Rector and Simplify rules: https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md

**Comment by sslt** [comment]
Hello Vasilvestre, we would like to look into this issue in more depth and ideally in the context of whole monorepo. Currently we have other priorities, we are estimating, we will start during summer months.

**Comment by grossmannmartin** [comment]
Upgraded to PHP 8.1 in #2430
