### ISSUE TITLE
Order - confusing "Finish order" button disabling

### ISSUE THREAD

**Issue by KadelaKuba** [shopsys/shopsys#2291]
### To Reproduce

1. Go to 3. step in order.
2. Fill required personal data. Click on checkbox "I buy on company behalf", do not fill company data and click on button "Finish the order".
4. The window with validation errors appears (missing company data). So you decide to not to fill company data and uncheck the checkbox "I buy on company behalf". After this you wanted to create order and wanted to click on button ""Finish the order".
5. But this button is disabled (attached screenshot). This behavior is confusing, because if you click on this button, the order is created. 

Same problem with delivery address checkbox.
### Expected behavior

If some form fields contains validation errors and these fields are hidden, button for creating order is not disabled. 

### Screenshots
![finishOrder](https://user-images.githubusercontent.com/33977915/114534502-59ed3780-9c4f-11eb-8a1b-9223a72dd9e3.png)

### Environment (please complete the following information)
 - OS: macOs
 - Browser: Chrome
 - Version: 89.0.4389.114
 - Device: Desktop computer

**Comment by grossmannmartin** [comment]
closed by #2329
