### ISSUE TITLE
Installation guide for linux should stress out the importancce of Docker post install steps

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#2297]
## Describe the expected outcome of your requested feature
This guide should be linked - https://docs.docker.com/engine/install/linux-postinstall/

### Is your feature request related to a problem?
Problems with brand new installation of SSFW-based project

### Additional context
Otherwise, it is very problematic to run the installation script

**Comment by grossmannmartin** [comment]
Hi @vitek-rostislav, 
thanks for pointing it out! Does #2298 sufficiently address this issue?

**Comment by vitek-rostislav** [comment]
Hi @grossmannmartin, sorry for the late response, yes, it does :slightly_smiling_face: :+1:

**Comment by grossmannmartin** [comment]
resolved by #2298
