### ISSUE TITLE
Node.js 10.x is no longer actively supported

### ISSUE THREAD

**Issue by PetrHeinz** [shopsys/shopsys#2307]
## Describe the bug
During installation of `shopsys/shopsys` (the monorepo) using `project-base/scripts/install.sh`, specifically during `Step 4/33 : RUN curl -sL https://deb.nodesource.com/setup_10.x | bash` in `php-fpm` Docker image build, I've run into a deprecation warning for Node.js 10.x. This version will not receive security or critical stability updates.

### To Reproduce

0. Make sure you have no relevant Docker images in your cache
1. Clone `shopsys/shopsys` repository
2. Run `./project-base/scripts/install.sh`
3. Choose 1
4. Wait for the warning to appear (it will be shown for 20 seconds, then disappear in the ocean of log messages)

### Expected behavior

Used Node.js version is actively supported (at least it gets security fixes).

### Screenshots
```
================================================================================
================================================================================

                              DEPRECATION WARNING                            

  Node.js 10.x is no longer actively supported!

  You will not receive security or critical stability updates for this version.

  You should migrate to a supported version of Node.js as soon as possible.
  Use the installation script that corresponds to the version of Node.js you
  wish to install. e.g.

   * https://deb.nodesource.com/setup_12.x — Node.js 12 LTS "Erbium"
   * https://deb.nodesource.com/setup_14.x — Node.js 14 LTS "Fermium" (recommended)
   * https://deb.nodesource.com/setup_15.x — Node.js 15 "Fifteen"
   * https://deb.nodesource.com/setup_16.x — Node.js 16 "Gallium"

  Please see https://github.com/nodejs/Release for details about which
  version may be appropriate for you.

  The NodeSource Node.js distributions repository contains
  information both about supported versions of Node.js and supported Linux
  distributions. To learn more about usage, see the repository:
    https://github.com/nodesource/distributions

================================================================================
================================================================================

Continuing in 20 seconds ...
```

### Environment (please complete the following information)
 - OS: Ubuntu 20.04.2 LTS
 - Browser: GNU bash
 - Version: version 5.0.17(1)-release-(x86_64-pc-linux-gnu)
 - Device: HP ProBook 450 G7

**Comment by grossmannmartin** [comment]
resolved by #2336
