### ISSUE TITLE
Cron overview - incorrect last run time

### ISSUE THREAD

**Issue by LuKillman** [shopsys/shopsys#2310]
## Describe the bug
https://github.com/shopsys/shopsys/blob/1c0ca51b25aa0245ff092e72dacac87b494b1e93/packages/framework/src/Controller/Admin/DefaultController.php#L297
When a cron lasted for over an hour the cron overview shows incorrect time.

### Expected behavior
Cron overview either shows hours or minutes over 60 when needed. 

### Screenshots
![image](https://user-images.githubusercontent.com/26909433/117940081-fd8e3e00-b308-11eb-8545-f513bc0ad9d1.png)
The second cron lasted 121 minutes but shows 1 minute.

### Environment (please complete the following information)
 - OS: Ubuntu 20.04.2 LTS
 - Browser: Chromium
 - Version: 90.0.4430.93
 - Device: Lenovo ThinkPad E490

**Comment by grossmannmartin** [comment]
resolved by #2334
