### ISSUE TITLE
JS validation for dynamicly added subforms with validation groups is not working

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/shopsys#232]
Reported by @pk16011990 

**Situation**
In form A I have collection of form B. Form B contains elements  with validation groups (e.g. if checkbox is checked then it is not mandatory).

Form B looks like this:

->add('answer', FormType::TEXT, [
   'required' => true,
   'constraints' => [
      new Constraints\NotBlank(['message' => 'Vyplňte prosím název článku']),
   ],
])
->add('hasHint', FormType::CHECKBOX, [
   'required' => false,
])
->add('hintTitle', FormType::TEXT, [
   'required' => true,
   'constraints' => [
      new Constraints\NotBlank([
         'message' => 'Vyplňte prosím nadpis pro nápovědu',
         'groups' => [self::VALIDATION_GROUP_HAS_HINT],
      ]),
   ],
])
->add('hintText', FormType::TEXTAREA, [
   'required' => true,
   'constraints' => [
      new Constraints\NotBlank([
         'message' => 'Vyplňte prosím text nápovědy',
         'groups' => [self::VALIDATION_GROUP_HAS_HINT],
      ]),
   ],
])

Into this collection I will add via JS new instance of form B and call:

SS6.validation.addNewItemToCollection('#adviser_step_form_newChoices', index);

to activate JS validation on this subform.

I have tried to activate validation groups on every new added element:

$item.jsFormValidator({
 'groups': function () {
  var groups = [SS6.constant('\\SS6\\ShopBundle\\Form\\ValidationGroup::VALIDATION_GROUP_DEFAULT')];
  if ($item.find('.js-adviser-step-has-hint-checkbox').is(':checked')) {
   groups.push(SS6.constant('\\SS6\\ShopBundle\\Form\\Admin\\Adviser\\AdviserStepChoiceFormType::VALIDATION_GROUP_HAS_HINT'));
  }

  return groups;
 }
});

Nevertheless if we try to activate JS valdation (blur on some input, submit form), JS validation throws exception right after first element of form B, because it cannot find validation group for this element. It looks like this:

fp_js_validator.js:489 Uncaught TypeError: Cannot read property 'groups' of null
    at Object.validateElement (fp_js_validator.js:489)
    at FpJsFormElement.validate (fp_js_validator.js:29)
    at fp_js_validator.js:248
    at Object.each (fp_js_validator.js:869)
    at Array.FpJsCustomizeMethods.validate (fp_js_validator.js:229)
    at jQuery.fn.init.$.fn.jsFormValidator (fp_js_validator.js:2263)
    at HTMLInputElement.<anonymous> (customizeBundle-v1489241964.js:50)
    at HTMLInputElement.dispatch (jquery.min.js:3)
    at HTMLInputElement.r.handle (jquery.min.js:3)

We tried to resolve this for an hour but we give up and we have to deactivate JS validation for whole subform B. I found out only that in data prototype which are send to JS validation there is _FpJsFormElement.data.form.groups = "__name__"_ I feel that it is not right and JS validation cannot work with prototypes and sends wrong data about prototype in those cases.

**Comment by PetrHeinz** [comment]
This issue might be resolved by #644.

**Comment by DavidOstrozlik** [comment]
This issue is not resolved by #644 because FpJsValidator calls getParentElementById with ID from prototype which has placeholder __name__ in it.

**Comment by LukasHeinz** [comment]
ping (prevent stale)

**Comment by DavidOstrozlik** [comment]
ping (prevent stale)

**Comment by LukasHeinz** [comment]
Ping
