### ISSUE TITLE
Sliders Positions not being respected in admin 

### ISSUE THREAD

**Issue by ouredma** [shopsys/shopsys#2333]
## Describe the bug
Sliders Positions not being respected in admin or frontend. They are listed by position in database as there is no ordering parameter in SliderItemRepository::getAllVisibleByDomainId or SliderController:listAction(). On adding new slider it has position NULL (SliderItemFacade::create() set position by highest postion for domain)

### To Reproduce

1. Go to sliders in admin
2. Change their position so they dont corespond to order in DB 
3. See error

### Expected behavior
Sliders show by order set in admin
I fixed it like this : https://diffy.org/diff/1b387074c1dba

### Environment (please complete the following information)
 - OS: any
 - Browser: any
 - Version:  any
 - Device: any

**Comment by s3tezsky** [comment]
Hello @ouredma, this issue should be resolved by this PR #2271. The fix will be part of version 9.1.2 soon.

**Comment by sslt** [comment]
Hello @ouredma, as per previous comment, this issue will be resolved in upcoming 9.1.2, so I am closing this issue. If you encounter this or similar problem, please let us know. Thank you for your time.
