### ISSUE TITLE
Multiple translation of validation messages in JS validation

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/shopsys#234]
Reported by @PetrHeinz 

### What is happening
If same instance of Constraints is used in several form inputs, its messages will be translated several times in JS validation.

It happens on homeepage (default constrain Empty in HoneyPotType) and in product editation (7 messages).

The problem lies in  Fp\JsFormValidatorBundle\Factory\JsFormValidatorFactory::parseConstraints() during creation of jsModelu. It is caused by changing public property of the contraint object (line 535: $item->{$propName} = $this->translateMessage($propValue);).

### Expected result
Editing Contraint object should be restricted.

Hotfix: clone instances of Contraints before changes of properties by the translation within parseConstraints

**Comment by pk16011990** [comment]
ping (prevent stale)

**Comment by pk16011990** [comment]
ping (prevent stale)

**Comment by pk16011990** [comment]
ping (prevent stale)

**Comment by henzigo** [comment]
bump

**Comment by sslt** [comment]
This problem has been resolved by adopting Webpack, so with great sadness we are closing this one forever.
