### ISSUE TITLE
Admin - select2 hidden disabled option

### ISSUE THREAD

**Issue by TomasGottvald** [shopsys/shopsys#2343]
## Describe the bug
When we want to use <option disabled="disabled"> the option is hidden. 

According to this change - https://github.com/shopsys/shopsys/pull/1803
We should use another attribut for #1803 and let us to use disabled option.

Styles are ready for disabled option.

### Expected behavior
Disabled option in select2 element will NOT dissapear.

**Comment by sslt** [comment]
To be honest, we are not sure, if we understand you.... could you please format  this issue as per community guide? Better yet, could you give us steps to reproduce.... or even better, could you please make Pull request for us?
