### ISSUE TITLE
Wrong translation of Free in email sent from administration

### ISSUE THREAD

**Issue by ouredma** [shopsys/shopsys#2345]
## Describe the bug
After changing the status in admin the locale is used from admin and not the order which results into wrong translation in emails 
Function priceTextWithCurrencyByCurrencyIdAndLocaleFilter in PriceExtension.php it should be like 

` if ($price->isZero()) {
            return t('Free', [], 'messages', $locale);
        }`

### To Reproduce

1. Go to admin
2. Click on storno order ( thats has diferent locale that admin locale)
3. Check email

### Expected behavior
The order language is used for translation of Free

**Comment by grossmannmartin** [comment]
resolved by #2357
