### ISSUE TITLE
Stop translating CSS documentation

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/shopsys#236]
### What is happening
In administration there is page with CSS docuemntation. All text there are exported for translation into .po files. It doesn't make any sence because it is developer documentation.

It can be found in administration when logged as superadmin in Settings > Superadmin > Css documentation

### Expected result
Texts in cssDocumentation.html.twig will not be translated - do not use trans() and remove messages form .po files

**Comment by PetrHeinz** [comment]
I'm reopening this as it is easy to do and has a lot of value when translating a project to another language.

**Comment by henzigo** [comment]
CSS documentation page is not translating from 7.0.0-alpha2 so im closing this.
