### ISSUE TITLE
Nonexisting SQL function NORMALIZE in db migrations on localhost

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/shopsys#237]
Reported by @pk16011990 

### What is happening
I needed to create index on new atribute in DB. I wanted to add to migration something like:

CREATE INDEX order_delivery_email_normalize_idx ON orders (NORMALIZE(delivery_email))

but I encounter error "function normalize(character varying) does not exist", because this function is created in DataFixuters

I resolved by creating migration with this (tested only on Postgres 9.5.):

$this->sql('CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA pg_catalog');
$this->sql('CREATE OR REPLACE FUNCTION immutable_unaccent(text)
   RETURNS text AS
   $$
   SELECT unaccent(\'unaccent\', $1)
   $$
   LANGUAGE SQL IMMUTABLE');

$this->sql('CREATE OR REPLACE FUNCTION normalize(text)
   RETURNS text AS
   $$
   SELECT lower(immutable_unaccent($1))
   $$
   LANGUAGE SQL IMMUTABLE');

And deleting DbFunctionsDataFixture.

### Expected result
It is important to reevaluate what in DataFixtures is demodata and what is not. For example SettingValues does not belong there (or it should only edit values e.g. set limit for free shipment). In result developers are confused.

**Comment by LukasHeinz** [comment]
@PetrHeinz Will this be resolved in some user story in DataFixtures Epic?

**Comment by vitek-rostislav** [comment]
The solution is in progress (US-4162) - it should be solved till the end of current sprint (within 10 days :slightly_smiling_face:)

**Comment by vitek-rostislav** [comment]
The issue was resolved in #285 - all base data fixtures were removed and the data creation was moved either into database migrations (e.g. database functions and triggers) or into demo data fixtures.
