### ISSUE TITLE
Crop settings for the image is ignored

### ISSUE THREAD

**Issue by pesektomas** [shopsys/shopsys#2371]
## Describe the bug
I have the following image settings in images.yaml:

```
- name: my-image
  width: 80
  height: 60
  crop: false
  occurrence: 'My image'
```

And even though I say in the settings that I don't want to crop the image (crop: false) I get a cropped image

### Expected behavior
When I have the crop: false, I shouldn't get a cropped image.

### Screenshots
![image](https://user-images.githubusercontent.com/1737966/130411546-665f1e46-de75-4abb-9c5f-5f810d34e3cc.png)

I think there is a mistake in the implementation of the Intervention library. In the ImageProcessor class, we have a resize method that depending on the crop setting, calls either the fit or resize method, but the resize method is called with three parameters, which, according to an example from the documentation, preserves the original ratio.

See:
```
// resize the image so that the largest side fits within the limit; the smaller
// side will be scaled to maintain the original aspect ratio
$ img-> resize (400, 400, function ($ constraint) {
     $ constraint-> aspectRatio ();
     $ constraint-> upsize ();
});
```

**Comment by grossmannmartin** [comment]
images are handled by a separate service since #2924
