### ISSUE TITLE
Annotations Fixer: extending classes from other than framework namespaces

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#2372]
## Describe the expected outcome of your requested feature
I noticed that in some classes in my project, the annotations are not fixed when running `php phing annotations-fix`. This is because I extend classes from [FE API Bundle](https://github.com/shopsys/frontend-api). I believe such namespaces should be included in the tool for fixing annotations as well (maybe all the Shopsys vendor namespaces?) or, it should be possible to configure the namespaces that I am extending in my project so the annotations are fixed properly then.

AFAIK, the `Shopsys\FrameworkBundle` namespace is hardcoded in 2-3 places now:
- https://github.com/shopsys/shopsys/blob/master/packages/framework/src/DependencyInjection/Compiler/RegisterProjectFrameworkClassExtensionsCompilerPass.php#L34
- https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Component/ClassExtension/ClassExtensionRegistry.php#L32
- https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Component/ClassExtension/ClassExtensionRegistry.php#L72

**Comment by TomasLudvik** [comment]
Do not forget to update `\Tests\FrameworkBundle\Unit\Component\ClassExtension\AnnotationsReplacerTest` to ensure that this functionality is working correctly.
