### ISSUE TITLE
Annotations fixer: default values in @method annotations

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#2374]
## Describe the bug
When the `@method` annotation is generated, it is missing default values for the parameters. As a result, `phpstan` reports an error when the method is then used without the optional parameter:

### To Reproduce
```php
class BaseClass
{
    public function doSomethingWithParameter(?int $param = 0): AnotherBaseClass
    {
        ....
    }
}
```

```php
class MyAnotherClass extends AnotherBaseClass{}
```
After running `php phing annotations-fix`, you get:
```php
/**
 * @method \AnotherBaseClass doSomethingWithOptionalParameter(int|null $param)
 */
class MyClass extends BaseClass{}
```

And when you the call `$this->myClass->doSomethingWithOptionalParameter()`, you got the error because the method expects 1 parameter now.

### Expected behavior
The following annotation is generated:
```php
/**
 * @method \AnotherBaseClass doSomethingWithOptionalParameter(int|null $param = null)
 */
class MyClass extends BaseClass{}
```

**Comment by s3tezsky** [comment]
Hi @vitek-rostislav, the issue has proposed PR #2308. Is there anything you are missing?

**Comment by vitek-rostislav** [comment]
Hi, ah, great, I totally forgot that we already have the issue and PR, closing this one :blush:
