### ISSUE TITLE
FE API: Price resolver has incorrect alias

### ISSUE THREAD

**Issue by grossmannmartin** [shopsys/shopsys#2384]
## Describe the bug
Price resolver in `Shopsys\FrontendApiBundle\Model\Resolver\Price\PriceResolver` has defined wrong alias in method `getAliases()`. 

see documentation: https://docs.shopsys.com/en/9.1/frontend-api/introduction-to-frontend-api/#resolvers

### Expected behavior
`getAliases` should contain all possible resolvers with meaningful aliases

**Comment by TomasLudvik** [comment]
This has been solved by automatic alias registration
