### ISSUE TITLE
Currency rounding is hard-coded

### ISSUE THREAD

**Issue by abecko47** [shopsys/shopsys#2389]
## Describe the expected outcome of your requested feature
Right now rounding types of currency are hard-coded. There are two classes now `Currency` and `Rounding`. For some reason rounding types are static constants in `Currency`, and this strings are hard written in database as a property of `currency`:
```
    public const ROUNDING_TYPE_HUNDREDTHS = 'hundredths';
    public const ROUNDING_TYPE_FIFTIES = 'fifties';
    public const ROUNDING_TYPE_INTEGER = 'integer';
```
And `Rounding` class acts like it is a service and should be called `RoundingService` (or `RoundingFacade`? or `RoundingManager`?), it is not Model.

### Is your feature request related to a problem?
I want to add new rounding type for HUF currency and have to extend everything related to this: order flow, cart flow, prices recalculation, etc, because I only added new constant to `Currency` and new case to `Rounding`. HUF currency only rounds to 5 (they don't have cents) an 1..4 HUFs do not exist. I have to explain my management why 'round forints to 5 is huge task'.

### Additional context
I believe this violates project architecture.

**Comment by pk16011990** [comment]
Now we are refactoring the creation of order https://github.com/shopsys/shopsys/pull/3084 It should be more flexible and extendable.
