### ISSUE TITLE
Configurable cookie consent

### ISSUE THREAD

**Issue by rudolfmedula** [shopsys/shopsys#2391]
## Describe the expected outcome of your requested feature

Hi,

I was wondering if there is a plan to make the configurable cookies (necessary for function, marketing, ..) as mandated by EU law
part of the framework (if yes would it be possible to add to the 7 version as well?). Thanks

### Additional context

I've seen you have already done it in one of your projects thats why I'm asking if it can be made available for all :)
<img width="1163" alt="Screenshot 2022-01-21 at 8 40 17" src="https://user-images.githubusercontent.com/43743546/150486748-339552a9-0825-4b76-802a-54fe4edd05a0.png">

**Comment by sslt** [comment]
Hello rudolfmedula, we are planning to add cookie consent functionality to SSFW in near future, however at this moment we intend to do so only for SSFW 9+. In the mean time.
In case you need it now or you need to implement it on older versions, it should be relatively easy to implement such functionality using 3rd party tool.

**Comment by pk16011990** [comment]
We already have cookie consent from version 13, now it is renaming to Consent https://github.com/shopsys/shopsys/pull/3181
