### ISSUE TITLE
Position for the e-shop domains icon window

### ISSUE THREAD

**Issue by martinkuchshopsys** [shopsys/shopsys#2392]
## Describe the bug
Incorrect position for the popup window when an administrator tries to select an icon to identify e-shop domains

### To Reproduce

1. Go to 'Administration -> Settings -> E-shop identification'
2. Click on 'edit icon button'
3. See the popup window at the very bottom of the screen

### Expected behavior
The popup window is located in the center of the user screen 

### Screenshots
![obrázok](https://user-images.githubusercontent.com/98525802/151347922-9cb4abc0-566c-41bc-9c60-b64a1a6a8315.png)

### Environment (please complete the following information)
 - OS: win 10
 - Browser: firefox, chrome
 - Device: Desktop

**Comment by pk16011990** [comment]
It should be solved by calling method moveToCenter() at https://github.com/shopsys/shopsys/blob/d9806a0bf2ed602fdb7d7118e7f35a345b14d865/packages/framework/assets/js/admin/utils/Window.js#L135 

However, why it's not called or called too early, I don't know.

**Comment by grossmannmartin** [comment]
I was unable to replicate this issue. Moving to the center works as expected. 

If you are able to replicate the issue on the clean framework, don't hesitate to reopen this issue with the test scenario thoroughly described.
