### ISSUE TITLE
Incomplete docs for 9.1 read model

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#2401]
## Description of the situation
There is a cookbook for adding a new attribute to an entity (https://docs.shopsys.com/en/9.1/cookbook/adding-new-attribute-to-an-entity/) and there is the following note:
> If you want to display your new attribute on the frontend product list, you need to extend the [read model layer](https://docs.shopsys.com/en/9.1/model/introduction-to-read-model/) as well. You can find instructions in [Extending Product List](https://docs.shopsys.com/en/9.1/cookbook/extending-product-list/).

However, since `9.1` version, even product detail uses the read model layer with data populated from Elasticsearch. This information is not included in the docs so it might be confusing.

### Suggested solution

We should rewrite the note in the "Adding New Attribute to an Entity" cookbook so it is clear that even product detail uses the read model and further steps are necessary to see the new attribute on the frontend. We should consider making the "Extending Product List" cookbook more general, or maybe even better, create a new cookbook - something like "Extending Product Detail" (the common parts with the "Extending Product List" article could be extracted into another new article :slightly_smiling_face: )

**Comment by pk16011990** [comment]
Read-model is no longer part of Shopsys Platform after integration FE API and JS Storefront
