### ISSUE TITLE
ArrayCollections: use getValues() instead of toArray()

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#2409]
## Describe the expected outcome of your requested feature
We use Doctrine `ArrayCollection` for collections in entities and often call `toArray` in the getters, e.g. see https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Model/Customer/Customer.php#L114 - this might be problematic as after deleting items from the collection, `toArray` might return bad keys.

## Suggested solution
We should use `ArrayCollection::getValues` instead of `toArray()`

### Additional context
I see we use a slightly different approach in `Cart::getItems` - `array_values($this->collection->toArray())` (see https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Model/Cart/Cart.php#L105) which might be also legit solution for the problem, however, `getValues()` is more straightforward :slightly_smiling_face:

**Comment by RobinDvorak** [comment]
Hello,
`array_values($this->collection->toArray())` is legit use case and it is exactly what `getValues()` do. See
https://github.com/doctrine/collections/blob/1.6.x/lib/Doctrine/Common/Collections/ArrayCollection.php#L281
