### ISSUE TITLE
Fulltext triggers are triggered even when given fields are not changed at all

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#245]
### What is happening
All the triggers defined in `FulltextTriggersDataFixture` do not take into account real changes of given fields - the corresponding function is triggered even for queries that actually do not change anything (i.e. the new value equals the old value)

### Expected result
All the functions should be triggered only when there is an actual change in the given field.

**Comment by TomasLudvik** [comment]
Some help might be found here: https://git.shopsys-framework.com/ssfw/ab-com.cz/blob/master/src/Shopsys/ShopBundle/Migrations/Version20180528163543.php#L21-27

**Comment by MattCzerner** [comment]
Hi, fixed in (#342)
