### ISSUE TITLE
monorepo-tools: Branches from other repos are not copied into monorepo

### ISSUE THREAD

**Issue by nbelakovski** [shopsys/shopsys#247]
### What is happening

Pulling several repos into a monorepo using script from 2850796 from https://github.com/shopsys/monorepo-tools

Only branches from the first repository listed are copied into the monorepo, not branches from others

### Expected result

I'd expect all branches to be copied. I see that in the script on line 32 you copy over branches from the first repo and not others and that this is done intentionally. Is there a particular reason this is done and what steps could be taken/what modifications could be made to include all branches?

Also, thank you for making that tool, it's really great! We liked it better than tomono since it keeps the history of all files.

**Comment by PetrHeinz** [comment]
Hello @nbelakovski and thank you for appreciation.

Basically, there are two reasons for not coping all branches from all repositories:

1) There could be conflicts and they would have to be resolved somehow.
2) Only master branches are merged - all branches would contain only the files in that particular package. For each non-master branch you would get only a single package.

Even though, we needed to continue working on our feature branches in our main repository, so we implemented coping all branches from one package, avoiding risks of conflicts and confusion.

You could mitigate the problems by implementing some kind of prefixing (remote branch `package-alpha/feature-branch` could be copied as eg. 'package-alpha--feature-branch'). This would both avoid almost all conflicts, and communicate that the branch contains only a single package. But, up to this point, there was no need to implement it.
