### ISSUE TITLE
Doctrine/ORM v2.13.0 is not compatible

### ISSUE THREAD

**Issue by grossmannmartin** [shopsys/shopsys#2504]
## Describe the bug
Currently, we allow installing doctrine/orm with any minor updates. Version 2.13.0 significantly improves phpdoc for ClassMetadataInfo causing our build to fail.

### To Reproduce
1. install latest version of all libraries
1. run `php phing phpstan`
1. see error

### Expected behavior
Code is validated and fixed

**Comment by pk16011990** [comment]
Doctrine/orm 2.14.0 works fine. Close
