### ISSUE TITLE
Update heureka/overeno-zakazniky package

### ISSUE THREAD

**Issue by LuKillman** [shopsys/shopsys#2517]
## Describe the expected outcome of your requested feature
Update heureka/overeno-zakazniky composer package from 2.0.6 to 4.0.1 for version 9.1.3 of SSFW. 

### Is your feature request related to a problem?
Old version of the package doesn't have any timeout set for requests which causes problems when sending orders to Heureka. Timeout had been added recently in version [4.0.1](https://github.com/heureka/overeno-zakazniky/pull/33). 

### Additional context
If orders are sent to Heureka immediately as Heureka wants it, in case of outage on their side we send them order and wait indefinitely for their response. It eventually throws RequesterException with message "cURL error: [7] Failed to connect to api.heureka.cz port 443: Connection timed out" but before that customers start refreshing page and creating duplicate orders.

**Comment by pk16011990** [comment]
This issues has been resolved by linked PR.
