### ISSUE TITLE
Main variant's price and visibility calculation is cycled

### ISSUE THREAD

**Issue by prochazkabs** [shopsys/shopsys#2538]
The main variant's price and visibility calculation is cycled.

### To Reproduce
1. Build project-base with demo DB
2. Check out that main variants are marked for recalculate_price (for example product id: 149)
3. Run ProductPriceCronModule
4. Check out that main variants are now marked for recalculate_visibility  (for example product id: 149)
5. Run ProductVisibilityImmediateCronModule/ProductVisibilityMidnightCronModule
6. Main variants are marked for recalculate_price again

### Expected behavior
Main variants are recalculated and not marked for recalculate_price again.

### Environment (please complete the following information)
 - OS: Ubuntu 20.04.4 LTS 
 - Browser: Chrome, Firefox, Mozilla
 - Version: project-base 10.0
 - Device: Server, Notebook, no matter

**Comment by grossmannmartin** [comment]
closed by #2917
