### ISSUE TITLE
Remove X-Powered-By header

### ISSUE THREAD

**Issue by eyeskiller** [shopsys/shopsys#2552]
## Describe the expected outcome of your requested feature
Remove X-Powered-By header from requests. It is potential security problem while we are actively disclosing what system is our build on. It is not even good for marketing - nobody is watching for headers. Or at least give us possibility to disable it in framework. Outcome should be remove (or add switch to turn off) this line

` $event->getResponse()->headers->set('X-Powered-By', 'Shopsys Framework');` 

in

`src/Component/HttpFoundation/ResponseListener.php`

**Comment by pk16011990** [comment]
I understand that, however, this is more of a business decision. However, it is perfectly fine to remove this on your project by overwriting this listener, creating a new one or directly in the webserver configuration. This is not a violation of the license terms and we are not preventing this in any way. However, we will consider from a best practice perspective to have this in the default.
