### ISSUE TITLE
Hide progress bars in CI logs

### ISSUE THREAD

**Issue by techi602** [shopsys/shopsys#2676]
It is often inconvenient to browse logs filled with hundreds of lines with just dots and progress bars. Those are useful for interactive command line but not for CI logs.

![image](https://github.com/shopsys/shopsys/assets/1529526/1a3a067a-1b46-44e8-adab-2b4fc6479988)

It would be nice, if build.xml will check some variable from ENV which will disable progress bar in various tools.

For example it would include `--no-progress` parameter to phpstan etc.

**Comment by pk16011990** [comment]
Sometimes the progress bar is useful. You can override execution on CI in build.xml, or make it configurable by environment (CI, local, etc.)

Currently, we don't have any plans to do it. Or feel free to do PR with some kind of configurable build.
