### ISSUE TITLE
Admin: Product edit: unclear message for non-unique parameters

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#268]
### What is happening - steps to reproduce
1. Go to admin edit page of a product with ID 76
2. Add parameter (keep the default "Screen size") and fill in it's translations
3. Submit form

You see that form was submitted but there is an error flash message with the text "Please check the correctness of all data filled.". However, when you scroll down the page, there is no error highlighted so you have no clue what is wrong. Then, when you try to submit the form once more, you get a JS validation error that tells you that your parameters are not unique. (see https://prnt.sc/ouj0k3)

### Expected result
JS validation for new parameters is performed right away.

**Comment by vitek-rostislav** [comment]
Oh, now I see, the error is caused by non-uniqueness of the added parameter :laughing: I did not get it from the general error message. It should be more specific :slightly_smiling_face:

**Comment by vitek-rostislav** [comment]
related to https://github.com/shopsys/shopsys/issues/213

**Comment by pk16011990** [comment]
ping (prevent stale)

**Comment by pk16011990** [comment]
pong

**Comment by LukasHeinz** [comment]
The issue does not occur any more on the current master. 

Tested flow:
1. Admin > Products: I click on create new product
2. I choose availability "Out of the stock"
3. I click "Add another parameter" (it creates parameter "Screen size) and fill Czech and English translation with "test"
4. Finishing creation of a product with "Create" 
5. I am redirected to product overview and new product is created.

Closing issue.

**Comment by vitek-rostislav** [comment]
Hi, the problem is still there actually, the issue was not described well (I have added new information in https://github.com/shopsys/shopsys/issues/268#issuecomment-399594666.)

I have rewritten the headline and the description @LukasHeinz :wink:
