### ISSUE TITLE
Order detail in admin has no order number

### ISSUE THREAD

**Issue by PetrHeinz** [shopsys/shopsys#279]
### What is happening

There is a field without label and widget on the form detail in administration:
![image](https://user-images.githubusercontent.com/10008612/41959302-e0be11f4-79ec-11e8-8e8f-b97468b143b8.png)

### Expected result

The order number should be displayed as a read-only field, from which the order number can be copied easily. Screenshot from previous version, in which the field is rendered as expected:
![image](https://user-images.githubusercontent.com/10008612/41959291-d2ea6fc8-79ec-11e8-895c-725f2ed02b9c.png)

**Comment by Miroslav-Stopka** [comment]
Solved in #289
