### ISSUE TITLE
Migrations for framework entity in framework bundle is outside in another bundle

### ISSUE THREAD

**Issue by mposchl** [shopsys/shopsys#2795]
Is there any reason, why migrations for `\Shopsys\FrameworkBundle\Component\Image\ImageTranslation` are located outside the framework bundle - in the `shopsys/product-feed-google`? Why am I pushed to install this bundle just to make the framework work?

**Comment by grossmannmartin** [comment]
That was a mistake probably. You can copy the migration into your project and skip the installation of the `shopsys/product-feed-google` package.

It's tricky to retro-fix the migrations. We try to think of a proper solution

**Comment by TomasLudvik** [comment]
Yes, that was a mistake, we have moved this migration to the framework package (#2870) and this fix will be released in version 13.0
