### ISSUE TITLE
monorepo-tools: rewrite_history_into.sh has a non-portable implementation of tab

### ISSUE THREAD

**Issue by lukaso** [shopsys/shopsys#281]
### What is happening
On OS X, the `sed` command's tab declaration is interpreted as a `t`.

File names unexpectedly have the sub directory substituted after the first `t`

### Expected result
The tab should be interpreted as a tab.

I will submit a pull request shortly.

**Comment by PetrHeinz** [comment]
#282 fixed this issue along with other problem with OS X compatibility

Thanks, @lukaso!
