### ISSUE TITLE
Property phpdoc typehint doesn't match with usage

### ISSUE THREAD

**Issue by simara-svatopluk** [shopsys/shopsys#288]
### What is happening
Some objects' properties have a `string` phpdoc typehint, but they are used with `int` variable/constant
* `CurrencyData::exchangeRate`
* `PricingGroupData::coefficient`

### Expected result

We have to decide what type really are these properties and change the typehint or usage accordingly.

**Comment by simara-svatopluk** [comment]
this issue should not be closed

**Comment by pk16011990** [comment]
ping (prevent stale)
