### ISSUE TITLE
DataFactory is dependent on Facade

### ISSUE THREAD

**Issue by simara-svatopluk** [shopsys/shopsys#290]
### What is happening
Couple of `*DataFactory` are dependent on `*Facade`.
* Facade should be on top of our model architecture, but now it is used from inside
* Can cause a circular dependency `Facade -> Repository -> Factory -> Facade`

Occurences:
* `ArticleDataFactory`
* `CategoryDataFactory`
* `UserDataFactory`
* `PaymentDataFactory`
* `ProductDataFactory`
* `BrandDataFactory`
* `TransportDataFactory`

### Expected result

Factories shouldn't depend of Facades. Ideally they should be completely independent. But if they cannot be, then this should be at least documented.

**Comment by simara-svatopluk** [comment]
this issue should not be closed

**Comment by henzigo** [comment]
Stale bot go home, you are drunk.

**Comment by henzigo** [comment]
Nice try stale bot, but I'm watching you!

**Comment by simara-svatopluk** [comment]
What is a purpose of one and half years old issue that is constantly closed/staled by a bot and constantly reopened by people?

So... is this important? Do real activity - propose solution, do investigation.... Isn't it important? close it.
Or change the stalebot policy if it doesn't suit You...

Well the only reason it bothers me is that I can see it in the github profile :-P
