### ISSUE TITLE
Unnecessary SQL queries on category detail in admin

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#291]
### What is happening

When accessing page with category editing or creating in admin, as many SQL queries are executed, as many categories I have in my eshop. This is caused by selectbox for setting parent (ancestor) category - it contains all categories loaded by `$this->categoryFacade->getAllWithoutBranch()`, resp. by `$this->categoryFacade->getAll()` which loads categories but without translations which are loaded for each category in separate query.

### Expected result

Category translations are loaded in the same query as categories themselves so there are no more unnecessary queries on admin category detail pages.

**Comment by Miroslav-Stopka** [comment]
Solved in #304
