### ISSUE TITLE
Architecture diagram in README.md

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#292]
### What is happening
The diagram do not match the one in https://github.com/shopsys/shopsys/blob/master/docs/introduction/basics-about-package-architecture.md where is also stated that some of the modules are just examples (there is no payment method module yet).

Also, the box with coding-standards module is twice in the diagram.

### Expected result

The diagram in `README.md` is fixed by the one in `basics-about-package-architecture.md` including the note about examples.

The diagram in `basics-about-package-architecture.md` is replaced with the fixed one from `README.md` that reflects the new corporate identity.

**Comment by LukasHeinz** [comment]
Thanks for noticing. Marketing has been notified and they fill prepare correct image.
