### ISSUE TITLE
wrong namspace for migrations Version20230220115918 

### ISSUE THREAD

**Issue by stanoMilan** [shopsys/shopsys#2946]
## Describe the bug
migration Version20230220115918 is in product feed bundle but enitity ImageTranslation is in framework package, if project not use product feed bundle , this migration missings 

### Expected behavior
migrations Version20230220115918  is in framework package

**Comment by vitek-rostislav** [comment]
Hi Milan, I believe this is already fixed by https://github.com/shopsys/shopsys/pull/2870, is not it?

**Comment by grossmannmartin** [comment]
Yes, yes it was.
