### ISSUE TITLE
Makefile: `docker-compose` V1 is deprecated and useless for people with newly installed `docker compose` V2 version

### ISSUE THREAD

**Issue by basicvector** [shopsys/shopsys#2960]
I have installed the new version V2 of Docker Compose on my PC and I could not use `docker-compose` in Makefile anymore. So I was thinking the solution thinking that there are people working with me, who have V1 version. So on the project I created `Makefile-v2` file with only `docker compose`, which is used by me by typing `make -f Makefile-v2 <makefile target>` (this solution is not ideally, I know). The second solution is let the only `Makefile` file and duplicate make targets (for both groups of people - with `docker-compose` and `docker compose`). The third solution could be to make (Linux) alias `docker-compose` for `docker compose` maybe. There could be more solutions of the problem.

I don't know the correct and ideal solution, but I know that this problem will must be solved, because there will be more people with V2 version (not only me) in the future and there still will be some people with old V1 version.

BTW - the content of current Makefile https://github.com/shopsys/shopsys/blob/14.0/Makefile is mix of `docker-compose` (V1, can't be installed, deprecated) and `docker compose` (V2, the only version to be newly installed).

**Comment by basicvector** [comment]
One of the solutions is to install Docker Compose standalone - https://docs.docker.com/compose/install/standalone/. Then both `docker-compose` and `docker compose` work.

**Comment by techi602** [comment]
JFYI when running `install.sh` or `docker-compose` in GitHub Actions can also fail because [GitHub have recently removed `docker-compose` from `ubuntu-latest` images](https://github.com/orgs/community/discussions/116610)

Changing to `docker compose` solves this problem.

https://github.com/shopsys/shopsys/blob/15.0/project-base/scripts/install.sh

**Comment by henzigo** [comment]
This was already fixed in [here](https://github.com/shopsys/shopsys/commit/d3a457b9c44900c22f53322942c73bfab8524b18)
