### ISSUE TITLE
Correct doctrine annotations for collections

### ISSUE THREAD

**Issue by techi602** [shopsys/shopsys#2971]
Currently Shopsys is declaring collection this way:
```
   /**
     * @var \App\Model\Order\PromoCode\PromoCode[]|\Doctrine\Common\Collections\ArrayCollection
     */
    private $promoCodes;
```
but [correct way to declare doctrine collection](https://www.doctrine-project.org/projects/doctrine-orm/en/2.17/tutorials/getting-started.html#adding-bug-and-user-entities) is 
```
   /**
     * @var \Doctrine\Common\Collections\Collection<int, \App\Model\Order\PromoCode\PromoCode>
     */
    private Collection $promoCodes;
```

[Since 2019 PHPStan supports generics.
](https://phpstan.org/blog/generics-in-php-using-phpdocs)
You can also enforce it using  `checkGenericClassInNonGenericObjectType: true` in your `phpstan.neon` config.

[PhpStorm supports generics as well](https://blog.jetbrains.com/phpstorm/2021/12/phpstorm-2021-3-release/#improved_support_for_doctrine_collections). So when you access collection it knows what entity is inside (even inside `foreach` loop) without additional annotation. Meaning that the hack with array annotation is no longer needed and it is actually incorrect since `ArrayCollection` instance is always set in the constructor. 

Are there any plans to change this in future releases?

**Comment by grossmannmartin** [comment]
Hi, 
thanks for the feedback. Yes, it's planned for the future release. 
The phpstan config seems useful, I will take a look.

**Comment by grossmannmartin** [comment]
created a PR #3000. 
I did not add a PhpStan config as it enforces generics on classes where it's not useful (transformers) and not on the collections.
