### ISSUE TITLE
coding standards: speed up ecs check

### ISSUE THREAD

**Issue by boris-brtan** [shopsys/shopsys#303]
On linux OS it was noticed that next build-demo-dev phing targets are slower with ecs for packages than with the checkers there were before (php_cs....).
### What is happening

Ubuntu 18, i7-8550, 16GB RAM, SSD

#### Steps
```sh
version=v7.0.0-alpha2  # v7.0.0-alpha3
git checkout 
composer update
./phing clean db-create test-db-create
for i in 1 2 3
do
./phing build-demo-dev
done
```

Ecs is using symfony cache and if `composer install` is triggered the cache is invalidated.
### Expected result

Optimalization of spped of ecs target and solved the issue with cache would be great if possible.

**Comment by boris-brtan** [comment]
Splendid,
thanks to @TomasVotruba  for the new release of https://github.com/Symplify/EasyCodingStandard/releases/tag/v4.5.0

**Comment by TomasVotruba** [comment]
> Ecs is using symfony cache and if composer install is triggered the cache is invalidated.

Yes, I fixed this in https://github.com/Symplify/Symplify/pull/958

**Comment by vitek-rostislav** [comment]
Verified :+1:
