### ISSUE TITLE
Demo data - currencies on domains

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#305]
### What is happening

The prices on the first (eng) domain are in CZK currency and prices on the second (czech) domain are in EUR currency.

### Expected result

There should be CZk currency on the second domain and EUR currency on the first domain

**Comment by MattCzerner** [comment]
Hello, I tried to solve this problem in https://github.com/shopsys/shopsys/tree/mc-default-currency.

There was many problems so i scratched it. Right now there is a problem with data fixtures of orders, where Czech customers orders on english domain with prices in czech crown.

Another problem is falling database tests.

I think that this problem will be solved with complete refactoring of data fixtures which is planned in future. I would close this issue for now. After approval from @LukasHeinz I will close it.

**Comment by Miroslav-Stopka** [comment]
Hi @MattCzerner,
is this issue still in implementation?

**Comment by LukasHeinz** [comment]
StaleBot, please open this issue. I want it to be resolved. Thank you

**Comment by henzigo** [comment]
bump

**Comment by henzigo** [comment]
Will be this issue solved any soon?

**Comment by pk16011990** [comment]
It is solved in #1542
