### ISSUE TITLE
Travis build is failing for shopsys/framework

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#306]
### What is happening

https://travis-ci.org/shopsys/framework
It seems that the problem was caused by https://github.com/shopsys/shopsys/commit/9c28d1527ca362d849c05bf2ea9e2b0aa82c5880
- the `composer.json` should probably require `ext-redis` extension and also probably `snc/redis-bundle` package.

### Expected result

Travis build is passing.

**Comment by Miroslav-Stopka** [comment]
Solved in #317
