### ISSUE TITLE
db migrations fail (trigger already exists)

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#310]
### What is happening

In https://github.com/shopsys/shopsys/pull/285, base data fixtures were removed and triggers creation moved to migrations. But some triggers were already defined in some previous migration so the new migration fails when running  the new migrations on existing database (with previous migrations installed). The problem is in https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Migrations/Version20180603135340.php where the triggers are redefined.

### Expected result

All triggers redefined in migration `Version20180603135340` should be dropped if possible before they are recreated (using `DROP TRIGGER IF EXISTS` statement).
*Note: This means the particular migration must to be fixed in order to get the framework working*

**Comment by vitek-rostislav** [comment]
This should definitely resolved before the next release.

**Comment by MattCzerner** [comment]
Hey @vitek-rostislav. I just created PR that solves it, I even tested it on failing master-staging by switching build branch to mc-migratons-trigger, which passed without errors.

**Comment by Miroslav-Stopka** [comment]
Solved in #314
