### ISSUE TITLE
Master single domain fails

### ISSUE THREAD

**Issue by Miroslav-Stopka** [shopsys/shopsys#319]
Master single domain fails

### What is happening
Build fails on a single-domain configuration. It seems that the problematic step of the build is the test.

### Expected result
Build on single-domain configuration finished successfully.

**Comment by PetrHeinz** [comment]
Is it fixed already, @Miroslav-Stopka?

**Comment by Miroslav-Stopka** [comment]
@PetrHeinz, yes it is. Fixed in #372 . Close.
