### ISSUE TITLE
[Insight] Missing use statement should be avoided - in packages/…/examples/ValidClass.php, line 17

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/shopsys#324]
**[in packages/coding-standards/examples/ValidClass.php, line 17](https://github.com/shopsys/shopsys/blob/f0212bec7fa7d1ae1ce1b5e5feb78b3b4593dc11/packages/coding-standards/examples/ValidClass.php#L17)**

> The `Type` type hint resolves to the following classes: `PHPStan\Type\Type` or `PharIo\Manifest\Type` or `phpDocumentor\Reflection\Type` or `Doctrine\DBAL\Types\Type` or `PHPUnit\Util\Type` or `Symfony\Component\PropertyInfo\Type` or `Symfony\Component\Validator\Constraints\Type`.
Did you forget to add a corresponding use statement for one of them?

```php
    /**
     * @var Type
     */
    private $parameterCamelCase;

    public function method(Type $parameterCamelCase)
    {
        $this->parameterCamelCase = $parameterCamelCase;
    }
}

```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/3b647b6b-ff37-406c-ae0a-e004328ef47f/analyses/1?status=violations)_

**Comment by LukasHeinz** [comment]
This is output from SensioLabs Insight and it is only suggestion. Please consider it.

**Comment by MattCzerner** [comment]
Hello @LukasHeinz, class represented in this issue is actually example class that shows in which format and standards should be class written. 

With approval from @vitek-rostislav, im closing this issue without resolving the problem.
