### ISSUE TITLE
[Insight] Public directory should not contain PHP files - in project-base/web, line 0

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/shopsys#325]
**[in project-base/web](https://github.com/shopsys/shopsys/blob/f0212bec7fa7d1ae1ce1b5e5feb78b3b4593dc11/project-base/web#L0)**

> Public directory `project-base/web` contains PHP file `project-base/web/index.php`.

```

project-base/web/
├── assets/
├── favicon.ico
└── index.php
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/3b647b6b-ff37-406c-ae0a-e004328ef47f/analyses/1)_

**Comment by LukasHeinz** [comment]
This is output from SensioLabs Insight and it is only suggestion. Please consider it.

**Comment by Miroslav-Stopka** [comment]
Hi @LukasHeinz,

in this case, everything is all right :) . The web directory is the home of all of your application's public and static files, including images, stylesheets and JavaScript files. It is also where the front controllers (app.php and app_dev.php) live (see https://symfony.com/doc/3.4/setup/web_server_configuration.html). So when only this single file `index.php` is in the folder, it's ok

Probably the reason why Insight consider this as a problem is a fact, that the default Symfony directory structure contains file `app.php` and we renamed this file to `index.php`
