### ISSUE TITLE
[Insight] The EntityManager should not be flushed within a loop

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/shopsys#326]
**[in packages/product-feed-heureka/src/Model/Product/HeurekaProductDomainFacade.php, line 77](https://github.com/shopsys/shopsys/blob/f0212bec7fa7d1ae1ce1b5e5feb78b3b4593dc11/packages/product-feed-heureka/src/Model/Product/HeurekaProductDomainFacade.php#L77)**

> Calling `flush` is a resource intensive operation, especially when a lot of entities are managed by Doctrine. You should avoid flushing inside a loop.

```php
    {
        $heurekaProductDomains = $this->heurekaProductDomainRepository->findByProductId($productId);

        foreach ($heurekaProductDomains as $heurekaProductDomain) {
            $this->em->remove($heurekaProductDomain);
            $this->em->flush();
        }
    }

    /**
     * @param $productId
```

**[in packages/product-feed-zbozi/src/Model/Product/ZboziProductDomainFacade.php, line 136](https://github.com/shopsys/shopsys/blob/f0212bec7fa7d1ae1ce1b5e5feb78b3b4593dc11/packages/product-feed-zbozi/src/Model/Product/ZboziProductDomainFacade.php#L136)**

> Calling `flush` is a resource intensive operation, especially when a lot of entities are managed by Doctrine. You should avoid flushing inside a loop.

```php
    {
        $zboziProductDomains = $this->zboziProductDomainRepository->findByProductId($productId);

        foreach ($zboziProductDomains as $zboziProductDomain) {
            $this->em->remove($zboziProductDomain);
            $this->em->flush();
        }
    }
}

```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/3b647b6b-ff37-406c-ae0a-e004328ef47f/analyses/1)_

**Comment by MattCzerner** [comment]
Hi, fixed in (#352)
