### ISSUE TITLE
migrations Version20240108154625 use attribute redirect_to and redirect_code from project base 

### ISSUE THREAD

**Issue by stanoMilan** [shopsys/shopsys#3297]
Hello,

I would like to report a bug related to the FriendlyUrl entity.

The FriendlyUrl entity has attributes redirectTo and redirectCode in the project base at [FriendlyUrl.php](https://github.com/shopsys/shopsys/blob/v14.0.0/project-base/app/src/Component/Router/FriendlyUrl/FriendlyUrl.php).

However, the migrations in the framework package use these attributes: [Version20240108154625.php](https://github.com/shopsys/shopsys/blob/v14.0.0/packages/framework/src/Migrations/Version20240108154625.php).

This inconsistency causes issues when upgrading to the new version 14.

**Comment by pk16011990** [comment]
Closed by https://github.com/shopsys/shopsys/pull/3368
