### ISSUE TITLE
phing target db-fixtures-demo fails due to new redis bundle 2.1.5

### ISSUE THREAD

**Issue by boris-brtan** [shopsys/shopsys#336]
There were new release of redis bundle and now shopsys:fixtures:load --fixtures fails on incompatibility error.
### What is happening

this log emerged in console
Command `shopsys:fixtures:load` exited with status code 1 
Warning: Redis::set() expects at most 3 parameters, 4 given
[Issue](https://github.com/snc/SncRedisBundle/issues/443)
### Expected result

there will be no incompatibility problem with redis bundle during fixtures loading

**Comment by PetrHeinz** [comment]
I did a hotfix for this in my branch in 91943b762a8a106ff249b6b19d26cbd89e73a09e.

We should probably take a look at why this happens and possibly create an issue in their repository. The downgrade could be merged into master, ideally with a better commit message (with a link to the issue etc.). If this is their fault, I'd suggest downgrading it permanently and updating the version manually as it seems they do release code without proper testing...

**Comment by MattCzerner** [comment]
This is solved in #339 . This will be fully solved after phpredis releases new version, to which we will upgrade to during our release process.
