### ISSUE TITLE
Remove flags from product domain after enable login on ProductDomain

### ISSUE THREAD

**Issue by stanoMilan** [shopsys/shopsys#3378]
## Describe the bug
After enabling logging on the ProductDomain entity, an unexpected behavior occurs when submitting the product form without making any changes. Specifically, all flags associated with the product (such as "new", "bestseller", etc.) are removed upon submission. This happens even when no modifications have been made to the product data.

### To Reproduce

Steps to Reproduce the Issue:
Set Up the Environment:

Enable Logging:

Enable logging on the Product and ProductDomain entity. Make sure the logging is active and correctly configured.
Exmaple commit https://github.com/stanoMilan/shopsys/commit/c13622886d4032cb6224b68624929ecb22068a56
Access the Admin Interface:

Log in to the application's admin interface.
Find a Product:

Select any existing product that already has some flags assigned (e.g., "new", "bestseller", etc.).
Open the Product Edit Form:

Click on the product to open the form for editing it.
Submit the Form Without Changes:

Without making any changes in the form, simply click the submit button (e.g., "Save" or "Submit").
Check the Flags:

After submitting the form, check if the flags are still assigned to the product.
If the issue occurred, the flags should have been removed even though no changes were made.
Review the Logs:

Check the logs to verify if the removal of the flags was recorded and investigate why it happened.
Expected Result:
The flags should remain assigned to the product as long as no changes were made in the form.

Actual Result:
The flags are removed, even though no changes were made in the form.

**Comment by pk16011990** [comment]
CLosed by https://github.com/shopsys/shopsys/pull/3406
