### ISSUE TITLE
Consider to modify accessibility of private properties and methods in Model for extensibility of shipping method for DemoShop

### ISSUE THREAD

**Issue by boris-brtan** [shopsys/shopsys#348]
In the process of extensibility for adding a new type of shipping method, there were need for modifying private property like `$domain` in Transport Entity to protected because of constructor overriding (some of the other entities got already `$domain` property protected) and also method `private function prefillTransportAndPaymentFromOrder`
### Expected result

All properties and methods that are used for extensibility will be protected.

**Comment by TomasLudvik** [comment]
Hello @boris-brtan,

thank you for reporting this. It has been already solved in current master, so I am closing this issue.
