### ISSUE TITLE
Extensible/configurable CreateAppDirectoriesCommand

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#349]
Reported by @swejzi and @jDolba
### What is happening

`CreateAppDirectoriesCommand` creates folders that are vital for the application during the application build but the directories names are hardcoded in the command and there is no easy way how to configure the list of the directories that are created.

### Expected result
A developer can easily configure list of folders for creation during the application build.

**Comment by jDolba** [comment]
:(

**Comment by PetrHeinz** [comment]
@jDolba: What kind of extensibility would you like? Would triggering an event (name suggestion: `shopsys.create_dirs`) suffice? Should the event class contain access to both the flysystem and the local filesystem (same as the properties `$filesystem` and `$localFilesystem` of `CreateApplicationDirectoriesCommand`)?

**Comment by boris-brtan** [comment]
should be fixed by #781
