### ISSUE TITLE
Ability of running multiple cron-jobs

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#356]
Reported by @jDolba.
### What is happening
It is not possible to create multiple independent cron-jobs but it is vital for larger projects as they run lots of transfers from/into ERP systems and these transfers could block other cron processes.

### Expected result

A developer is able to define multiple cron-jobs that can be run concurrently easily.

**Comment by pk16011990** [comment]
I want this feature and I dont want stale this request. We have some implementations in Shopsys agency, but not PR...

**Comment by boris-brtan** [comment]
+1
