### ISSUE TITLE
productList.AjaxMoreLoader component should be more general

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#357]
Reported by @swejzi.
### What is happening
Ajax "load more" paginator component (`productList.AjaxMoreLoader`) is tailored for products so the usage for any other entity is cumbersome.
Also the usage is difficult when there are more paginators on one page.

### Expected result
Ajax paginator component is generalized enough to enable easy usage for any entity a developer wants, even when there are more paginators on one page.

**Comment by vitek-rostislav** [comment]
created new user-story - https://app.yodiz.com/plan/pages/board.vz?cid=10273#/backlog/us-4478

**Comment by Swejzi** [comment]
:-(
