### ISSUE TITLE
Ability of temporal hiding of info bar with mail setting

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#358]
### What is happening

With some special mail setting is enabled (e.g. master mail is set), there is red bar on the top of the page with the information.
![image](https://user-images.githubusercontent.com/10401898/43266935-de698dd6-90ec-11e8-8263-c2b96d675a67.png)

This is disturbing when custom design is presented to customers.

### Expected result
In the bar, there is a link that allows to hide the whole information bar for 24 hours.

**Comment by vitek-rostislav** [comment]
@PetrHeinz you are right, one or two hours should be enough :+1:

**Comment by TomasLudvik** [comment]
I might even like some possibility to hide it in some sort of configuration.
