### ISSUE TITLE
Network errors while developing on "local" PC

### ISSUE THREAD

**Issue by basicvector** [shopsys/shopsys#3594]
Hope this will help someone with same problem with network on dev PC.

# Environment
- Linux Ubuntu 22.04
- Docker 27
- SSFW 14

# Problem
Sometimes, my web browser showed a "network reset" error. Pages would not load, large downloads would fail ("network failed"), Kibana would not load completely, and ChatGPT could not send full responses etc.

# Potential causes
I checked many possible causes, but none of these were the problem:
- Internet provider issues
- Faulty router
- WiFi connection issues
- PC hardware issues
- IPv6 settings
- Custom DNS setup (Dnsmasq and Unbound)
- Firewall rules
- Modifying NetworkManager.conf did not fix it: `unmanaged-devices=interface-name:veth*,interface-name:docker*,interface-name:br-*`.

# Cause
The Docker container php-consumer was restarting every 60 seconds. This caused Ubuntu's Network Manager to restart because new veth interfaces were being added and removed all the time.

# Temporary Fix
I commented out these lines in docker-compose.yml for the php-consumer container like this:

    entrypoint:
        - /bin/sh
        - docker/php-fpm/consumer-entrypoint.sh

This is not a perfect solution, but it helps.
Now, the network on my PC does not restart every minute, and I can work normally.
For development, I now run the consumer manually like this:

    docker exec -it shopsys-framework-php-consumer sh -c "./docker/php-fpm/consumer-entrypoint.sh"

**Comment by vitek-rostislav** [comment]
Hi, thanks for sharing, I have the same network problems as you describe :pray:

**Comment by henzigo** [comment]
@thirdknown Could you test this PR if it helps you?
