### ISSUE TITLE
Phing target standards-fix-diff does not fix wrong order of uses

### ISSUE THREAD

**Issue by TomasLudvik** [shopsys/shopsys#360]
### What is happening
This target reported:
`1) /var/www/html/tests/ShopBundle/Database/EntityExtension/EntityExtensionTest.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -13,8 +13,8 @@
 use Shopsys\FrameworkBundle\Model\Order\Item\OrderProduct;
 use Shopsys\FrameworkBundle\Model\Order\Item\OrderTransport;
 use Shopsys\FrameworkBundle\Model\Payment\Payment;
+use Shopsys\FrameworkBundle\Model\Transport\Transport;
 use Shopsys\ShopBundle\Model\Product\Product;
-use Shopsys\FrameworkBundle\Model\Transport\Transport;
 use Tests\ShopBundle\Database\EntityExtension\Model\CategoryManyToManyBidirectionalEntity;
 use Tests\ShopBundle\Database\EntityExtension\Model\CategoryOneToManyBidirectionalEntity;
 use Tests\ShopBundle\Database\EntityExtension\Model\CategoryOneToOneBidirectionalEntity;

    ----------- end diff -----------

Applied checkers:

 - PhpCsFixer\Fixer\Import\OrderedImportsFixer`

It looks like it was fixed and everything is alright, but it is not. The order has not been fixed and the second run of this target does not even report it again. 

### Expected result
The order is fixed and if it is not, the second run of this phing target should report this problem again.

**Comment by PetrHeinz** [comment]
@TomasLudvik: Isn't this just an issue with the sync of the source codes in your IDE / Docker volume? From what you described it looks like the fixed did its job but you don't see the results.

**Comment by PetrHeinz** [comment]
@TomasLudvik: Could you please verify this is really an issue of Shopsys Framework and provide additional information to reproduce? I wasn't able to reproduce this behavior - uses were sorted as expected. For this reason I've removed the Priority tag.

**Comment by TomasLudvik** [comment]
Hello @PetrHeinz,

it seems that the problem was something else, maybe docker-sync. I am closing the issue.
