### ISSUE TITLE
Javascript validation of form in popup window

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#361]
Reported by @swejzi and @jDolba.
### What is happening
When there are some javascript validation errors while submitting a form, a popup window with list of the errors is displayed. This is standard feature for all forms. But when the form is displayed in popup window, then the popup with errors overwrites the original window with the form. Normally, this is also wanted feature as we do not want to open multiple popups. 

### Expected result
Javascript validation of form in popup is resolved somehow nicely from UX point of view. The solution should be discussed with @LukasHeinz beforehand.

**Comment by jDolba** [comment]
:( :7

**Comment by Swejzi** [comment]
:'(

**Comment by TomasLudvik** [comment]
:(

**Comment by vitek-rostislav** [comment]
Hi @TomasLudvik, thanks for the reminder :+1: we are having pre-planning of the upcoming sprint in a half hour, I believe I can "enforce" this into the sprint :wink:

**Comment by vitek-rostislav** [comment]
So, we discussed it, sadly, it is not planned into the current sprint due to others priorities, I am sorry :disappointed:

**Comment by vitek-rostislav** [comment]
@DavidOstrozlik is working on that :tada:
