### ISSUE TITLE
Not all constraint translation is in file with translation

### ISSUE THREAD

**Issue by sspooky13** [shopsys/shopsys#369]
### What is happening
After run `phing dump-translations` command are not in validators files all translatable constraints. For example this translate https://github.com/shopsys/shopsys/blob/3efb92d99dad0fabe05c3bb797f9fd2e7818a45b/project-base/src/Shopsys/ShopBundle/Form/Front/Order/TransportAndPaymentFormType.php#L104 missing in files with translation.

### Expected result
All constraints messages, violations, simply all text which is located on FE should be in files with translations.

I am willing to help with this problem but i need help with this functionality. @PetrHeinz, will you have time today?

**Comment by simara-svatopluk** [comment]
Related issue https://github.com/shopsys/shopsys/issues/215

**Comment by sspooky13** [comment]
Thanks @PetrHeinz for consulting with this issue. I try fix this issue in evening and i hope that i send pull request in the near future.
Thanks for your patience.

**Comment by PetrHeinz** [comment]
Removing `stale` tag as the implementation is already in progress...

**Comment by Miroslav-Stopka** [comment]
Hi @PetrHeinz,

i see that there was already merged some modification connected to this ISSUE. Is this ISSUE solved? Or something more is missing?

**Comment by PetrHeinz** [comment]
@Miroslav-Stopka: After @sspooky13's original #448 and the new #564 were merged, there are no known translations that are not extracted at the moment (see #218).

I would suggest closing this issue. If there are any new unextracted translations found, I would create a new issue and implement a new message extractor. I've also closed #215 with the same reasoning.

**Comment by Miroslav-Stopka** [comment]
@PetrHeinz Exactly :) Thank you for this confirmation and close.
