### ISSUE TITLE
Admin: Product detail: JS validation doesn't prevent form from submitting

### ISSUE THREAD

**Issue by boris-brtan** [shopsys/shopsys#374]
if we click on checkbox for flag group in js console we can see 
`The choices "2" were not found. at SymfonyComponentFormExtensionCoreDataTransformerChoicesToBooleanArrayTransformer.reverseTransform`

**How to reproduce:**

1. Open the iPhone editing in administration
2. Make some required field empty
3. Get out of the box
4. Submit a form

**What will happen:**

The form is sent with invalid fields.

Porbably because of choiceType multiple for flags and brands problem

**What should happen:**

When something in form is invalid error box should appear and the form should not be sent.

**Comment by PetrHeinz** [comment]
Attempt to fix it can be found in 3771de6.

**Comment by LukasHeinz** [comment]
Report form testing - the problem occurs on product ID 72 when I leave blank input sorting priority. In same scenario on product ID 76 the problem does NOT occur.

**Comment by Swejzi** [comment]
:-(

**Comment by LukasHeinz** [comment]
I want this.

**Comment by vitek-rostislav** [comment]
closed by #891
