### ISSUE TITLE
SmokeTesting should use PHPUnit-Bridge instead of PHPUnit

### ISSUE THREAD

**Issue by DavG** [shopsys/shopsys#380]
Hello,

I am currently trying your SmokeTesting library and it's a really nice thing I would like to generalize in my company.

But we follow the new Symfony guidelines, and they say we should require the symfony/phpunit-bridge instead of phpunit/phpunit.

Doing this has a lot of benefits I will not detail here.

So I think this library should rely on it too, and remove the phpunit/phpunit dependency.

What do you think ?

Regards,

**Comment by TomasVotruba** [comment]
Hey DavG, 

I think package should depend on as few projects as possible, unless there is valid reason for the opposite.
Using `symfony/phpunit-bridge` bring me many WTFs to my life.

> Doing this has a lot of benefits I will not detail here.

What are the benefits? Mainly in context of what would change for you if the dependency in `composre.json` would change.
