### ISSUE TITLE
"php phing ecs" checks too few files

### ISSUE THREAD

**Issue by TomasVotruba** [shopsys/shopsys#383]
This is follow up to #382, but not releated, so I rather create a new issue than to mix 2 different topics.

When I run:

```bash
php phing ecs
```

it checks **only 272 files**:

![better](https://user-images.githubusercontent.com/924196/43763458-153bc24c-9a2b-11e8-8742-99c6e6bc1b17.png)

<br>

Which seems to few for such a big project, right?

So I tried to run ECS the direct way:

```bash
vendor/bin/ecs check packages project-base
```

and I get **2202** files:

![image](https://user-images.githubusercontent.com/924196/43763311-be640b1e-9a2a-11e8-83c0-d18eb7edf028.png)

I'm I running wrong command? (I'm very lame at using phing, so I might be :))

**Comment by PetrHeinz** [comment]
I don't think it's wrong - it seems that you've installed Shopsys Framework via [shopsys/project-base](https://github.com/shopsys/project-base), so the `ecs` only checks the files in your repository. It avoids checking PHP files of dependencies in vendor directory - even if there were violations, you wouldn't be able to fix them.

To check the coding standards in all files, you should clone the main repo [shopsys/shopsys](https://github.com/shopsys/shopsys) and run `standards` there.

**Comment by PetrHeinz** [comment]
OK, my bad. You are running it from the monorepo, right? The thing is that we haven't overriden all targets for standards (`ecs`, `twig-lint`, `yaml-lint`, ...). Instead, we've [overriden the `standards` target](https://github.com/shopsys/shopsys/blob/master/build.xml#L36) and added `standards-packages` as a new dependency. There, we [run all the checks inside a single target](https://github.com/shopsys/shopsys/blob/master/build.xml#L65-L95). This was done to avoid overriding so many targets, but it leads to such unexpected behavior...

We basically never run the specific targets such as `ecs` or `eslint-check`, but mostly just `standards`. Maybe we should have organized the phing targets a bit differently...
