### ISSUE TITLE
Improvement of FE product search results

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/shopsys#398]
### What is happening
When I search "8800" I get as result for example product with EAN 8845781243207. It is because it fing match in n-gram of search entry and n-gram of atribute value. It is wierd.

Same with name - when I look for "apple" it also look into "appliance" (because of the same n-gram of both expressions ("app")

### Expected result
When I search "8800" I should get only results with EAN , partno or catalogue number starting with searched entry e.g. "8800123" or "880000258". Suggested change - do not create n-gram frem search entry but only on product attributes. 

Generaly - the functionality of search should match the documentation - https://github.com/shopsys/shopsys/blob/master/docs/introduction/product-search-via-elasticsearch.md

**Comment by LukasHeinz** [comment]
@simara-svatopluk please feel free to expand my description.

**Comment by LukasHeinz** [comment]
I disagree with marking as stale.

**Comment by simara-svatopluk** [comment]
Do not analyze input for EAN
