### ISSUE TITLE
monorepo-tools as a part of a monorepo

### ISSUE THREAD

**Issue by rybakit** [shopsys/shopsys#405]
### What is happening

If I add monorepo-tools into a monorepo (no matter if I add it as a submodule or subtree or just commit bash files directly):

```bash
my-monorepo/bin/monorepo-tools
my-monorepo/app/foobar
```
and then run 

```bash
$ bin/monorepo-tools/monorepo_split.sh app/foobar
```
I get:

```bash
/my-monorepo/bin/monorepo-tools/rewrite_history_from.sh: line 57: /my-monorepo/bin/monorepo-tools/tag_refs_move_to_original.sh: No such file or directory             
Splitting repository for the remote 'app/foobar' failed! Not pushing anything into it.
/my-monorepo/bin/monorepo-tools/monorepo_split.sh: line 41: /my-monorepo/bin/monorepo-tools/original_refs_restore.sh: No such file or directory         
```

I guess this happens because `monorepo_split.sh` rewrites/removes files in the main repository and therefore it deletes itself.

### Expected result

Be able to ship monorepo-tools within a monorepo.

**Comment by PetrHeinz** [comment]
Hi @rybakit and thanks for reporting. I don't see much value in solving this, as it would increase the complexity of the tool. This can be achieved quite easily by copying the monorepo-tools directory elsewhere before the split itself (eg. to /tmp). Or am I missing something? Do you have a particular solution in mind?

Maybe we should just document this behavior so it's explicitly stated.

**Comment by PetrHeinz** [comment]
FYI: I've created an issue #408 in which I describe how we split the monorepo on our CI - we, mainly for performance reasons, use a slightly different approach than `monorepo_split.sh`. It might be helpful for you as it is splitting the repository in a different directory allowing for using the tools from inside the monorepo.

**Comment by rybakit** [comment]
> Do you have a particular solution in mind?

Well, the only solution that comes to my mind is do what you're already mentioned - copy the monorepo-tools directory in /tmp and run scripts from there. That can be done either by the tool itself (implicitly) or by a user. For latter, it would be nice to document the current behaviour, it took me a while to figure out why does `monorepo_split.sh` work if I call it from outside of the monorepo directory but doesn't otherwise.

> FYI: I've created an issue #408 in which I describe how we split the monorepo on our CI

Cool, thanks for sharing this. At first I implemented the similar approach using Makefile, but ran into git index.lock issues and gave up splitting repos in parallel. Your version with cloning repositories into a separate directory is a nice solution for the issue. :+1:

**Comment by PetrHeinz** [comment]
I'd say that just documenting the behavior would suffice.
