### ISSUE TITLE
remove option is_container_group from form types

### ISSUE THREAD

**Issue by PetrHeinz** [shopsys/shopsys#414]
### What is happening

All form types have a custom option `is_container_group` which controls whether or not to render it as a group. This should be behavior of `FormGroup` (which was introduced later, via setting this option to true).

Otherwise, we're basically implementing the same thing using two approaches at the same time. I would assume there is no need for any other form type that `FormGroup` to have `is_container_group = true` and there is no need for `FormGroup` to have `is_container_group = false` - they are basically equivalent.

### Expected result

There is no `is_container_group` option.

`FormGroups` and other form types are still rendered the same as now.

**Comment by vitek-rostislav** [comment]
Hi, this was already implemented in 3aa843fba999b5548c55651984777c56c672a2a4. Next time please check the code before reporting the issue :wink:
