### ISSUE TITLE
Order flow fix - function call on string

### ISSUE THREAD

**Issue by jDolba** [shopsys/shopsys#419]
In OrderFlow (\Shopsys\ShopBundle\Form\Front\Order\OrderFlow::changeRequestToStep) is called function on string

this is wrong method usage since upgrade from Symfony 2

alse see:  https://github.com/symfony/form/commit/08f76324a8e2c19b140dbdda9bce6cea328ff38a#diff-b828a8e3d29bb649e85781718cb9fbe4
 - method getName does not exists in FormTypeInterface anymore

### What is happening

in some circumstances, fatal error (Call to a member function getName() on string) might occur 

I was not able to reproduce this problem myself, I noticed this only in error log few times

### Expected result

 - do not throw fatal error and 500 error page in order process

**Comment by TomasVotruba** [comment]
This should be reproted by PHPStan. Is the build broken or PHPStan missed it?

**Comment by jDolba** [comment]
this "bug" was there since SSFW upgrade from symfony 2.8 to symfony 3+

so PHPStan missed it

**Comment by jDolba** [comment]
this "bug" was there since SSFW upgrade from symfony 2.8 to symfony 3+

so PHPStan missed it

**Comment by vitek-rostislav** [comment]
I'll take care of it :wink:
