### ISSUE TITLE
composer.json - use patches instead of forks

### ISSUE THREAD

**Issue by MattCzerner** [shopsys/shopsys#421]
### What is happening
Using forks as dependency in composer.json is very slow and maybe even cause need to authenticate yourself on github

### Expected result
Use patches instead.

**Comment by TomasVotruba** [comment]
I was about to write similar issue into "stable requirements". Temp commit-locks like these are fine for development
       - https://github.com/shopsys/shopsys/blob/6d6772f34ef4cab096c6029141b22428859836a0/composer.json#L97
       - https://github.com/shopsys/shopsys/blob/6d6772f34ef4cab096c6029141b22428859836a0/composer.json#L108
       - https://github.com/shopsys/shopsys/blob/6d6772f34ef4cab096c6029141b22428859836a0/composer.json#L142

But they make install time into insanse times and causes bugs like https://pehapkari.cz/blog/2017/01/20/jak-snadno-a-rychle-upravovat-soubory-ve-vendoru/tps://github.com/TomasVotruba/shopsys-spryker-and-sylius-analysis/pull/16#issue-209768449

E.g. this package https://github.com/ddmaster/PostgreSearchBundle is just 5 files and can be easily integrated to Shopsys core 

There is also another hacky solution https://pehapkari.cz/blog/2017/01/20/jak-snadno-a-rychle-upravovat-soubory-ve-vendoru/ but it can be broken; I'd still recommend fast and safe approach

**Comment by PetrHeinz** [comment]
The patches were a pretty unstable solution, the Composer installation was sped up using proper package forking instead (by publishing the fork on Packagist and using Composer `replace` config, see #490).
