### ISSUE TITLE
Upgrade to Postgres 10 seems to have a bad impact on the application performance

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#426]
### What is happening
After upgrading to Postgres 10 (https://github.com/shopsys/shopsys/pull/378), the application performance decreased for all pages that are tested by our performance tests (roughly from -1% to -10%)

### Expected result
The performance impact of Postgres 10 should be examined more deeply as we were expecting performance enhancement, not degradation. We should find out what to do in order to improve the Postgres performance.

*Note: This article might be useful - https://amplitude.engineering/how-a-single-postgresql-config-change-improved-slow-query-performance-by-50x-85593b8991b0*

**Comment by simara-svatopluk** [comment]
**PIA**
* consult wheather the performance testing server configuration is similar to my computer configuration
* try to improve postgreSQL performace generally, do not focus on 9.5 vs 10
* try improvements locally
* measure improvements on the performance testing server

**Comment by boris-brtan** [comment]
@vitek-rostislav @simara-svatopluk is this still open?

**Comment by vitek-rostislav** [comment]
No no, closed by #444 :slightly_smiling_face:
