### ISSUE TITLE
monorepo-tools: splitting to an existing repository with signed commits

### ISSUE THREAD

**Issue by dominikkaluza** [shopsys/shopsys#435]
### What is happening
It's not possible to split to an existing repository if the repository contains commits signed by GitHub (typically init commit or merge commits from pull requests).

#### How to reproduce:
- Crate a new repository on GitHub with `Initialize this repository with a README` option checked
- Build a monorepo from this repository
- Try splitting the monorepo

#### Result:
`monorepo_split.sh` fails when trying to push to this repository

#### Workaround:
- edit line 36 in `monorepo_split.sh` and change `git push --tags $REMOTE master` to `git push --tags --force $REMOTE master` (this is needed only for the first split, `--force` flag can be removed after that)

### Expected result
`monorepo_split.sh` re-signs the commits and pushes them to the existing repository without using the `--force` flag

**Comment by vitek-rostislav** [comment]
Hi @dominikkaluza, thanks for reporting the issue. We had the same problem in the past and solved it exactly the same way as you describe - by using `push --force`. At least, we should probably document this behavior :thinking: 

`monorepo_split.sh` could sign the commit using the same GPG key (https://help.github.com/articles/signing-commits-using-gpg/) that is used in the original github repository but this would work only if all the commits in the original repository were signed by the key.

**Comment by PetrHeinz** [comment]
I suppose it is theoretically possible to store all data about the signature into the commit msg during building the monorepo and then use this data to recreate exactly the same signed commit during the splitting. I haven't looked into it yet, but it should be possible to store all raw data of the commit encoded in the commit msg ([it's possible to store 100MiB there](https://stackoverflow.com/questions/9733757/maximum-commit-message-size)) and during splitting restore the exact commit...

This could be a messy and time-consuming workaround, I would suggest to just document this behavior instead. We could leave this issue open if someone from the community want to take a look at it.
