### ISSUE TITLE
Problems during clean installation on Windows

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/shopsys#441]
### What is happening
I started to install clean project base according to Installation guide and I cannot install it.

### Expected result
I should be able to install it without major issues.

**Comment by LukasHeinz** [comment]
Problem #1:
 I got stucked on step https://github.com/shopsys/shopsys/blob/master/docs/installation/installation-using-docker-windows-10-pro-higher.md#4-compose-docker-container

Docker compose up is not working (micoreservices are not present). I suppose (advice of @vitek-rostislav ) that this step should follow after I set up microservices in next steps. So probably just change order of steps will be enough.

**Comment by PetrHeinz** [comment]
The Problem 1 was probably fixed during #430, can you please check the installation again? Thanks!

**Comment by PetrHeinz** [comment]
It seems you're installing the latest released version (`7.0.0-alpha5`), installing microservices via pre-built images is resolved only in master. Either wait for `7.0.0-alpha6` to be released or install the project by running
```
composer create-project shopsys/project-base --stability=dev --no-install --keep-vcs
```
instead of 
```
composer create-project shopsys/project-base --stability=alpha --no-install --keep-vcs
```

That should do the trick.

**Comment by LukasHeinz** [comment]
Problem 1 resolved.

**Comment by LukasHeinz** [comment]
Problem 2: Error during build-demo-dev

Shopsys Framework > microservice-product-search-delete-structure:

20:50:01 ERROR     [app] GuzzleHttp\Exception\ServerException: Server error: `DELETE http://microservice-product-search-export:8000/1` resulted in a `500 Internal Server Error`

Detailed info in attachement
[install_error.txt](https://github.com/shopsys/shopsys/files/2368362/install_error.txt)

**Comment by LukasHeinz** [comment]
Issue 3:
During installation I encounter two times situation where installation froze for serveral minutes (>20). I resolved it by pressing Esc button. Installation after that went on as nothing happened and finished sucessfuly.
It is not a problem but a bit strange behaviour. It might be good to make some note about it.

**Comment by PetrHeinz** [comment]
For debugging *Problem 2* please provide application logs. You can output them into a file by running `docker-compose logs > all-containers.log` or `docker-compose logs microservice-product-search-export > microservice.log`.

The only information in the provided `install_error.txt` is that the microservice failed during the call, its logs could provide info about why.

Ad *Problem 3*: Do you know in which parts of the application it froze? If you've clicked in the CLI window, it might have been stopped by a Windows 10 feature that helps you select text. See https://stackoverflow.com/questions/33883530/why-is-my-command-prompt-freezing-on-windows-10/33883532#33883532 for details.

**Comment by LukasHeinz** [comment]
Problem 2 UPDATE:
I run it again but now the error appeared somewhere else:

Shopsys Framework > microservice-product-search-create-structure:
In CurlFactory.php line 185:

  [GuzzleHttp\Exception\ConnectException]
  cURL error 28: Operation timed out after 1001 milliseconds with 0 bytes received (see http://curl.haxx.se/libcurl/c
  /libcurl-errors.html)

Detailed info here - [install_error.txt](https://github.com/shopsys/shopsys/files/2372002/install_error.txt)
Log here (13 MB) - [all-containers.log](https://github.com/shopsys/shopsys/files/2372019/all-containers.log)

**Comment by LukasHeinz** [comment]
Problem 3 UPDATE - it did not occure any more...

**Comment by LukasHeinz** [comment]
Problem 2 UPDATE
After two more runs I was able to execute build-demo-dev

I supose it is performance problem...

**Comment by LukasHeinz** [comment]
My experience SSFW performance:
- build-demo-dev (on 4th try): 50 minutes
- first load of homepage: 46 sec
- second (and next) load of homepage: 20 sec (but about 7 sec it is loading Symfony bar)
- first load of "Search results for "app"": 

My setup:
- Win 10 Pro 64bit
- CPU Intel i5 2,5 GHz
- 4 GB RAM
- SSD disc
- Docker settings: 2 CPU, 1792 MB RAM, 1024 Swap,

**Comment by LukasHeinz** [comment]
TRYOUT 2 - Docker setting changed

- build-demo-dev: 51 minutes
- first load of homepage: 49,5 sec
- second (and next) load of homepage: 50sec

My setup:
- PC samo as above
- Docker settings: 3 CPU, 2048 MB RAM, 2048 Swap

**Comment by LukasHeinz** [comment]
Problem 4:
I downloaded new version of SSFW (after Kubernetes) and tried to install it again. I encounter problem with GitHub token. The token I put into dockre-compose.yml file do not work any more (I did it same way as before). During composer install I was prompted to enter it manually. I tried to repeat it severel times (different tokens, new project, docker up&down) but still same. When I entered the token manually, it worked...

**Comment by PetrHeinz** [comment]
We have added a cache warmup which should eliminate the Problem 2, or at least significantly reduce the odds of failure in #463.

The Problem 4 you describe is pretty weird, I have no clue what could have caused it, as there wasn't much changed during #393... On which commit were you previously and on which commit did you upgrade? Was it the `composer install` in the `php-fpm` container? Can you provide your `docker-compose.yml`? (you should obfuscate your secrets using asterisks while keeping the format intact: `password` => `p******d`)

**Comment by LukasHeinz** [comment]
Problem 5 (@vitek-rostislav ):
I cannot install new version alpha6. For more see attachement - ![install_error_ms](https://user-images.githubusercontent.com/33071107/45600288-82124c80-b9fa-11e8-9d44-6092cfaa8a0a.PNG)

**Comment by vitek-rostislav** [comment]
@LukasHeinz I see, The tag is not released, maybe the reason is that there is a typo in the version number, it should be prefixed with `v` according to our checklist. I will look into it tomorrow.

**Comment by PetrHeinz** [comment]
Just as @vitek-rostislav said, there is a typo in the version. Just replace `7.0.0-alpha6` by `v7.0.0-alpha6` in your `docker-compose.yml` and it should work as intended.

We should probably either release `7.0.0-alpha6.1` with the fixed tags in config files, or release a duplicate tag `7.0.0-alpha6` for our Docker images tagged as  `v7.0.0-alpha6` to fix the installation...

**Comment by vitek-rostislav** [comment]
Hi, @LukasHeinz - we released the duplicate tag `7.0.0-alpha6` for the image on Docker hub so the installation should be fixed now. I am going to test it on my Ubuntu now...

**Comment by vitek-rostislav** [comment]
Hi @LukasHeinz, we have released the tags `7.0.0-alpha6` (duplicate for `v7.0.0-alpha6`) for both microservices on Docker hub so the installation should be fixed. I am going to test it on Ubuntu now.

**Comment by vitek-rostislav** [comment]
I have tested it on Ubuntu and it works :tada: @LukasHeinz please test it on Mac and Windows and let me know here, thank you.

**Comment by LukasHeinz** [comment]
Everything is working just fine. 

Performance issue will be tackled in another issue #477
