### ISSUE TITLE
docker-compose templates in project-base missing microservice-product-search-export

### ISSUE THREAD

**Issue by simara-svatopluk** [shopsys/shopsys#443]
### What is happening

Docker templates in project-base are missing definition of container for microservice microservice-product-search-export, so it is probably impossible to install project.

### Expected result

Copy-paste configs from monorepo and test installation

**Comment by TomasVotruba** [comment]
Not sure if that's released, but I tried to install the project on Docker ~10 days ago and failed for missing microservice.

**Comment by LukasHeinz** [comment]
I have install project via docker week ago and again yesterday with no problems. @simara-svatopluk please, can you confirm there is really problem?

**Comment by PetrHeinz** [comment]
This was fixed as a part of #430 in 0961a4d330dce964bb72565d90363cc0d63c3962.

It will be a part of the `v7.0.0-alpha6` release, currently it should be installable via our installation guides, as they temporarily recommend installing `dev-master` version.
