### ISSUE TITLE
Repeated Symfony Flex installation in microservices 

### ISSUE THREAD

**Issue by PetrHeinz** [shopsys/shopsys#450]
### What is happening

`symfony.lock` is git-ignored in our microservices (along with `composer.lock`). The original motivation stemmed from our work with shopsys/project-base and `composer.lock` - we wanted to keep the dependencies up-to-date without manual updates.

Missing `symfony.lock` leads to repeated Symfony Flex installation when `composer installed` is executed for the first time, and it creates some uncommited changes (eg. adds some `.gitignore` files).

We should definetely reconsider the way we work with lock files or fix this situation some other way.

### Expected result

User has no uncommited changes after installation of microservices.

**Comment by boris-brtan** [comment]
+1

**Comment by MattCzerner** [comment]
Seems like it should be resolved by #793

**Comment by MattCzerner** [comment]
Solved by #793. Closing
