### ISSUE TITLE
The docs are missing FAQ section

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#452]
### What is happening
There is much information missing from our documentation. It is true that we are planning to document many features but it might take a while so creating the FAQ section could bring the developers a great value for less effort. There are already things that could be described in a sentence or two and therefore could be explained in such section...E.g. (thanks to @pk16011990 for reporting):
- What are data fixtures good for?
- How to perform a change of URL (e.g. when swithćhing application to production)
- How to use migrations and why the developers should use `shopsys:migrations:generate` instead of the default Doctrine one
- what are the `diff` versions of coding standards check commands and what are their limits
-  is the application https ready or does it need some extra setting?
- what about translations and language constants export and import?
- what about deploy and production server setting?

I believe we could come up with a few more others, based on consultation with White and Pink team or based on questions that were asked on slack for example.

### Expected result
There is a FAQ section in the docs that briefly answers various common questions and makes Shopsys Framework usage clearer. Even if there are already more descriptive information on a given question, the FAQ could link to the separate article at least to make the information more reachable.

**Comment by vitek-rostislav** [comment]
Another one - what are the differences between "listable", "sellable", "offered" and "visible" products?

**Comment by PetrHeinz** [comment]
Visibility of products and categories should be explained as well (and the `calculated_*` convention for materialized data)

**Comment by vitek-rostislav** [comment]
Another question - how do I change the environment? - files `PRODUCTION`, `DEVELOPMENT`, and `TEST`. Related PR - https://github.com/shopsys/shopsys/pull/546/files

**Comment by PetrHeinz** [comment]
Maybe a remainder that `phing cron` should be executed every 5 minutes to run background jobs? Only mention in the docs is https://github.com/shopsys/shopsys/blob/v7.0.0-beta2/docs/introduction/phing-targets.md#cron
