### ISSUE TITLE
Changes between project-base and monorepo installation should be more clear

### ISSUE THREAD

**Issue by PetrHeinz** [shopsys/shopsys#454]
### What is happening

To start an e-commerce project, developers should install the `shopsys/project-base` repository and use other packages as Composer dependencies. To contribute and develop Shopsys Framework, developers should install the `shopsys/shopsys` monorepository and run it as a single application.

We have mentions of this concept in our [README.md](https://github.com/shopsys/shopsys/blob/v7.0.0-alpha5/README.md#how-to-start-a-new-project) and our [installation guides](https://github.com/shopsys/shopsys/tree/v7.0.0-alpha5/docs/installation) are written from the point of view of a user without mentioning the monorepo installation.

Currently, we have an article named [Monorepo](https://github.com/shopsys/shopsys/blob/v7.0.0-alpha5/docs/introduction/monorepo.md) that should explain the distinction. This article is updated only sparsely and does not hold all needed info, eg. it doesn't mention microservices and how to work with them (it doesn't even mention the new repositories).

### Expected result

The [article about monorepo](https://github.com/shopsys/shopsys/blob/v7.0.0-alpha5/docs/introduction/monorepo.md) should be updated and it should describe the distinctions between Docker Compose configuration.

The two distinct ways of installing should be clearly described in the [installation guides](https://github.com/shopsys/shopsys/tree/v7.0.0-alpha5/docs/installation).

The fact that contributors should probably use the monorepo approach should be described in the [contributing guide](https://github.com/shopsys/shopsys/blob/v7.0.0-alpha5/CONTRIBUTING.md).

*I'm linking docs of latest release `7.0.0-alpha5`, current `master` might be different when you read this.*

**Comment by vitek-rostislav** [comment]
Please do not close this issue, I think it is important
