### ISSUE TITLE
.md files contains trailing whitespace

### ISSUE THREAD

**Issue by simara-svatopluk** [shopsys/shopsys#457]
### What is happening
.md files contains trailing whitespace. This causes problems when your IDE automatically removes trailing whitespaces - this is a correct behavior in my opinion.

### Expected result
Remove trailing whitespaces from .md files and create an automatic sniff/fixer for it.

**Comment by TomasVotruba** [comment]
@gabrielcaruso helped me to solve this with this bash script: https://github.com/Symplify/Symplify/blob/master/bin/clear_readmes.sh

**Comment by TomasVotruba** [comment]
@carusogabriel helped me to solve this with this bash script: https://github.com/Symplify/Symplify/blob/master/bin/clear_readmes.sh

**Comment by PetrHeinz** [comment]
I would like to point out that two spaces at the end of line have a special meaning in markdown - they indicate a line break. Removing them automatically may cause issues.

**Comment by Miroslav-Stopka** [comment]
So what is the result @PetrHeinz? Shoud we remove trailing whitespace as @simara-svatopluk suggests?

**Comment by PetrHeinz** [comment]
@Miroslav-Stopka: I would recommend removing any whitespace from blank lines, a single spaces at the end of any line and leaving at most two spaces at the end.

Basically a [regex replace of `(?:^|(  )?) *$` by `\1`](https://regex101.com/r/d8LVmI/2) (not considering tabs).

**Comment by PetrHeinz** [comment]
#580 fixed the issue and introduced new automated fixer
