### ISSUE TITLE
Add parameter and return type-hints

### ISSUE THREAD

**Issue by thexpand** [shopsys/shopsys#462]
`composer.json` requires PHP version `^7.1`, which means that the project could make use of type-hinting.
Do you plan to refactor?

**Comment by vitek-rostislav** [comment]
Hi @thexpand, thanks for your question. 

We usually use typehints in newly added code and yes, we want to refactor the whole application to use the typehints but it is not as easy as it might seem and it is not our priority at the moment. 

We were also discussing converting annotations into typehints in https://github.com/shopsys/shopsys/pull/390 and decided to stick with using annotations as there are use cases where the annotations contain useful information that can not be in type hint (e.g. `\Shopsys\FrameworkBundle\Model\Product\Product[]` vs `array`).

**Comment by thexpand** [comment]
@vitek-rostislav 
Personally, I type-hint new code and add annotations only if there is something more to say than just `array`, as you pointed out + `@throws` and method description. I understand that this is not a top priority, but it would be good to keep it in mind, because type-hinting is one of the things that makes the good code a great code.

**Comment by vitek-rostislav** [comment]
I do agree with you and we talk about type-hinting quite often :slightly_smiling_face: We also discussed the possibility of adding annotations only when they have some additional value but the reason for the decision to annotate everything was that this is the simplest rule and having no exceptions from that makes it easy to follow and review.
