### ISSUE TITLE
First step improvement of administration security

### ISSUE THREAD

**Issue by thirdknown** [shopsys/shopsys#471]
Path /admin should be available only from dev mode.

### What is happening
Path /admin is one of the worst URLs for administration due to it's existence could be very easy detected by bots, because it is typical path for administration.

### Expected result
I recommend to implement first step of security called "Security through obscurity" (which is not good if it is used alone) - make path /admin available only from dev mode.
In production mode there will be available some generated pseudo-random path, e.g. /admin8f4w2fdf6d2, which will be known only for "shop owners" and will be unique for each instance of SSFW.
And do not let "shop owners" using hazardous developer's administration login "admin" with password "admin123" in production mode.

**Comment by boris-brtan** [comment]
Hello, this [commit](https://github.com/shopsys/demoshop/pull/24/commits/1b4ecf9745f64ce7fc32ff0993470a02a9878779) from demoshop could help to solve this.

**Comment by LukasHeinz** [comment]
This is a real issue, stalebot, go somewhere else...

**Comment by thirdknown** [comment]
How is it going?

**Comment by LukasHeinz** [comment]
Guys, security is important...

**Comment by s3tezsky** [comment]
> And do not let "shop owners" using hazardous developer's administration login "admin" with password "admin123" in production mode.

Has been implemented in #1360

**Comment by TomasLudvik** [comment]
Right now you can get inspired from our demoshop, where it has been implemented https://github.com/shopsys/demoshop/pull/24

**Comment by pk16011990** [comment]
From version 13.0, It is possible by configuration `parameters.admin_url` and depends on the configuration of a project.
