### ISSUE TITLE
tests for strength of admin credentials

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#489]
### What is happening
There are no automated tests for checking the strength of admin credentials on production so project maintainers are not forced to change the default ones.

### Expected result
Project maintainers should not be allowed to use default admin credentials on production, or, at least, should be strongly discouraged from using them.

*Note: this might be slightly related to #471*

**Comment by PetrHeinz** [comment]
So it's not about strength of the password, but about not using the default one, right?

Can't we just explicitly disallow logging into admin with `admin123` in `prod` environment?

**Comment by PetrHeinz** [comment]
@LukasHeinz So when you login as admin in `prod` environment with a default password, a flash message with a warning is added and you're immediately logged out?

Mentioning our undocumented Symfony command `shopsys:administrator:change-password` in the warning might be a good idea...

**Comment by LukasHeinz** [comment]
Flash message sounds good for me. I would even go the way that if this password is used there would be no attempt to log in administrator and just info that "Oh, you just tried to log in using default credentials. We do not allow that on production environment. If you are random hacker, please go somewhere else. If you are authorized user, please use another account or contact developers and change password during deployment. "

**Comment by LukasHeinz** [comment]
no stale, I need it
