### ISSUE TITLE
Terminology - Continuous "integration" vs "delivery"

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#492]
### What is happening
We use the terminology "continuous integration" (e.g. https://github.com/shopsys/shopsys/blob/v7.0.0-beta1/docs/kubernetes/continuous-integration-using-kubernetes.md) for our process of building the application, running the tests and coding standards checks, and running the application instance for every pushed Git branch on the test server. The process should be probably called "continuous delivery" even though we do not speak about production.

An interesting source of information - https://www.atlassian.com/continuous-delivery/ci-vs-ci-vs-cd
We also discussed the topic on our internal slack - https://shopsys-agency.slack.com/archives/G99RXJZ70/p1536047411000100

### Expected result
We should use the right namings in our internal communication as well as in communication with the community, in articles and documentation.

**Comment by MattCzerner** [comment]
I think that the delivery is right term, we are currently able to deploy application at any point on any cluster that gives us kubernetes config.
