### ISSUE TITLE
Use shell files for installation

### ISSUE THREAD

**Issue by MattCzerner** [shopsys/shopsys#495]
To install the application there is several commands you must execute to do that. These commands are written in documentation, but they could be stored into shell files to make installation really easy.

### How it could look like 

To set up default and simple development infrastructure you can do it by:

```
cp app/config/parameters.yml.dist app/config/parameters.yml
cp app/config/parameters_test.yml.dist app/config/parameters_test.yml
cp app/config/domains_urls.yml.dist app/config/domains_urls.yml
cp docker/conf/docker-compose.yml.dist docker-compose.yml
docker-compose up -d
```

To install the application you can do:

```
docker exec -it shopsys-framework composer install
docker exec -it shopsys-framework ./phing build-demo-dev
```
*How about to copy these common commands to shell files and allow users to install the application on once click?*

I would like to see some opinions on that.

**Comment by vitek-rostislav** [comment]
I love it :heart: Of course, you would have to detect the correct `docker-compose` template by your operating system in the script.

**Comment by MattCzerner** [comment]
Or just leave it as an option to fill.

something like 
```
Choose your operating system:

1) Linux
2) Windows
3) Mac
```

**Comment by MattCzerner** [comment]
Install script implemented, closing
