### ISSUE TITLE
Information about extending entities in cookbook

### ISSUE THREAD

**Issue by TomasLudvik** [shopsys/shopsys#507]
### What is happening
Since alpha6 there are some extended entities in project-base and information how to do this was removed from https://github.com/shopsys/shopsys/blob/v7.0.0-alpha5/docs/cookbook/adding-new-attribute-to-an-entity.md#extend-framework-product-entity (step 4). This information should be returned with some info, that most used entities are already extended. 

### Expected result

Documentation is much clearer.

**Comment by vitek-rostislav** [comment]
I have already created a similar issue - https://github.com/shopsys/shopsys/issues/453

**Comment by TomasLudvik** [comment]
Hello Mr. stale[bot],

this issue is still actual :-)
