### ISSUE TITLE
Remove github auth token

### ISSUE THREAD

**Issue by simara-svatopluk** [shopsys/shopsys#518]
### What is happening
After cleaning `composer.json` from custom repositories, `composer install` speeded up rapidly due to not checking half of the internet. This also means that `composer install` performs much less request to github, and it seems that github doesn't require auth token anymore.

### Expected result
Check if the `composer install` doesn't require auth token anymore. If so, remove it from `docker-compose.yml` templates, `Dockerfile`(s), documentation, `.travis` configs, build processes on heimdall and travis... just from everywhere as it is no longer needed

**Comment by boris-brtan** [comment]
Maybe there will be no requests to https://github.com and just the download request to https://packagist.org/

**Comment by boris-brtan** [comment]
any progress?

**Comment by boris-brtan** [comment]
https://travis-ci.org/shopsys/framework.svg?branch=bb-wip-github-token

**Comment by Miroslav-Stopka** [comment]
@boris-brtan, are you solving this issue or not?

**Comment by boris-brtan** [comment]
not right now.

**Comment by boris-brtan** [comment]
now it is in progress
