### ISSUE TITLE
Update of documentation for native installation and make it great again! or remove support for native installation

### ISSUE THREAD

**Issue by boris-brtan** [shopsys/shopsys#531]
in the requirements https://github.com/shopsys/shopsys/blob/master/docs/installation/native-installation.md there are postgres-9.5 but in parameters table with default values there is 10.5
### What is happening

There is also problem with `composer require-dev` and also composer as such for microservices because there is needed to define more `ENV` variables and also there were some changes from symfony server to nginx and more changes due to mainly docker support.
### Expected result

to have postgres 10.5 everywhere and solved functional natively installed app
Think about creating `.travis.yml` script for testing microservices functionality based on this docs

**Comment by boris-brtan** [comment]
i found out that it is possible to test on travis almost everything and via many OS.

**Comment by Miroslav-Stopka** [comment]
Hi @boris-brtan,

what about this issue? Is there some progress?

Thank you :)

**Comment by vitek-rostislav** [comment]
Hi @Miroslav-Stopka, I am trying to push this into sprint :wink:

**Comment by vitek-rostislav** [comment]
Hi, the result of today's planning is that this will not be solved during the upcoming sprint.

**Comment by Miroslav-Stopka** [comment]
Hi @vitek-rostislav,

thank you for your status update :) 

I see, I have only one last question: Is actual native installation functional? I mean, is it possible to install SSFW following this guide?

**Comment by vitek-rostislav** [comment]
:+1: I will push it further, we will see.

> Is actual native installation functional? I mean, is it possible to install SSFW following this guide?

Well, it is not tested nor up-to-date, however, @grossmannmartin has the framework installed natively on his Mac :wink:

**Comment by Miroslav-Stopka** [comment]
👍for "I will push it further"

👎 for "it is not tested nor up-to-date". I think that too many people use this guide for the creation of their production servers.

**Comment by vitek-rostislav** [comment]
> I think that too many people use this guide for the creation of their production servers.

Yes, another reason for pushing this issue :slightly_smiling_face:

**Comment by boris-brtan** [comment]
Hi mr. @Miroslav-Stopka, 
who use that guide for creation production servers?

**Comment by boris-brtan** [comment]
Itried it now and there are many things missing that are used via Dockerfile installation and so...also i can see no mention about MEMORY_LIMIT for composer and such stuff....

**Comment by vitek-rostislav** [comment]
Hi, a new user story has been created and evaluated (US-5407 for those who have access to internal backlog), now it depends on our sprint planning :slightly_smiling_face:
