### ISSUE TITLE
Missing links to production installation

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/shopsys#532]
### What is happening
In documention there are no links to productiuon installation of SSFW

### Expected result
There should be in readme and docekr install page.

**Comment by vitek-rostislav** [comment]
Is this still relevant? We have links to our prod. installation guide in here - https://github.com/shopsys/shopsys/blob/master/docs/index.md

**Comment by LukasHeinz** [comment]
In other files like https://github.com/shopsys/shopsys/blob/master/docs/installation/installation-using-docker.md or readme.md the guide is reffered as "the installation". But since production installation there are two types of installation - developement and production. These two should be more clearly separated and linked together.

**Comment by LukasHeinz** [comment]
This issue has been resolved in previous months.
