### ISSUE TITLE
Diff files throws sh: syntax error: unexpected "("

### ISSUE THREAD

**Issue by TomasLudvik** [shopsys/shopsys#536]
### What is happening
During phing diff-files target there is error `Diff files throws sh: syntax error: unexpected "("`

### Expected result
The error does not occur.

**Comment by PetrHeinz** [comment]
I've even tried replacing http://github.com/shopsys/shopsys by http://github.com/shopsys/project-base with the same result.

**Comment by TomasLudvik** [comment]
@PetrHeinz it happened on a clean installation of project-base in version beta1. It happened to me and even to guys during the testing online workshop.

**Comment by PetrHeinz** [comment]
@TomasLudvik I've replaced `shopsys/shopsys` by `shopsys/project-base`, `beta2` by `beta1` and `~` by my actual GitHub token in the script above and still the same result. I've even added and modified a PHP script (in the `src/Shopsys/ShopBundle/Controller/Front/` dir) to get the `diff-files` to do some work and tested it with `phplint-diff`, everything works correctly:

```
Buildfile: /var/www/html/build.xml
 [property] Loading /var/www/html/build/build.local.properties
 [property] Unable to find property file: /var/www/html/build/build.local.properties... skipped

Shopsys Framework > diff-files:


Shopsys Framework > phplint-diff:

PHP 7.2.11 | 10 parallel jobs
X.                                                           2/2 (100 %)


Checked 2 files in 0 seconds
Syntax error found in 1 file

------------------------------------------------------------
Parse error: src/Shopsys/ShopBundle/Controller/Front/PersonalDataController.php:29
    27|      * @var \Shopsys\FrameworkBundle\Component\Domain\Domain
    28|      */
  > 29|     private $domain;
    30| 
    31|     /**
Unexpected 'private' (T_PRIVATE), expecting ',' or ';'

BUILD FAILED
/var/www/html/build-dev.xml:293:12: /var/www/html/build-dev.xml:303:17: Task exited with code 1

Total time: 0.1264 seconds
```

Can you provide clear steps to reproduce, please?

**Comment by TomasLudvik** [comment]
Hello @PetrHeinz,

this issue can be found even in monorepo. I just saw it on current master :)

Maybe is this issue only on Mac, but it would be weird because we all use Docker.

**Comment by PetrHeinz** [comment]
@TomasLudvik Without clear steps to reproduce, I cannot help any further. You can investigate the cause by yourself and create a PR with a fix.

**Comment by TomasLudvik** [comment]
@PetrHeinz on my computer is a very easy way to reproduce it: `./phing diff-files`

**Comment by PetrHeinz** [comment]
Oh I see... The problem is on Mac (since #468) and Windows (since #499) - there is no git repository mounted in the container, so `diff-files` has no way to compute the diffs.

We can echo a message if it is called outside a git repository (with a hint that it's because of exclude in sync, and that you should use the target without `-diff` instead), remove the sync exclude (significantly reducing performance on non-Linux platforms), or we can remove the `-diff` targets altogether (personally, I prefer this option, as they are proving quite difficult and are not as useful as they were historically).

**Comment by grossmannmartin** [comment]
This issue became more pressing with planned Releaser tool (see #623). Releaser needs git repository to work properly. 

As a workaround, we can add a new docker-sync volume just for git, but I'm not sure if it will be stable. I'm testing it now and so far so good.

**Comment by PetrHeinz** [comment]
@TomasLudvik May I resolve this issue by adding an error message *"Searching for changed files requires Git to be installed and the .git directory to be available."* when git is not available during the execution of the phing target?

**Comment by TomasLudvik** [comment]
@PetrHeinz add some more info like "On Windows and Mac .git is excluded in docker-sync.yml file in order to deliver better synchronization performance and stability."

**Comment by PetrHeinz** [comment]
@TomasLudvik That would be a very specific info about OSs and running in Docker containers... I prefer not to include such notes which might not be applicable. In this

**Comment by TomasLudvik** [comment]
@PetrHeinz I think that docker-sync will be main reason for this error. When you install project natively you will have .git folder in your repository so...
