### ISSUE TITLE
Test your docker configuration with docker killer

### ISSUE THREAD

**Issue by boris-brtan** [shopsys/shopsys#548]
### What is happening

from the description of this docker image `Docker image for Docker stress and Docker orchestration testing` we can see that these tools should be helpful in improvements of  configs
### Expected result

test docker configuration with docker image [docker killer](https://hub.docker.com/r/monitoringartist/docker-killer/) and fix all findings.

**Comment by Miroslav-Stopka** [comment]
1. "from the description of this docker image" - which docker image?

2. What are the real benefits? For example?

**Comment by PetrHeinz** [comment]
Is this really related to security? Maybe I got it wrong, but it seems just like a way to ensure that the infrastructure can handle failures well while maintaining high availability.
