### ISSUE TITLE
Update snc/redis package

### ISSUE THREAD

**Issue by boris-brtan** [shopsys/shopsys#549]
### What is happening

In PR #339 we removed ^ notation. There should be already fixed version of this with the new redis php extension 4.1.1
### Expected result

return ^ notation into composer.json file

**Comment by PetrHeinz** [comment]
The package `snc/redis-bundle` in version `>= 2.1.4` doesn't work with `phpredis` extension `< 4.1.1`, but this conflict is not mentioned in their `composer.json`, so it could pose a problem with native installation (in Docker, we would just increase the installed version in `php-fpm`'s Dockerfile). This should be taken into consideration when upgrading.

**Comment by boris-brtan** [comment]
update to version 4.1.1 was done in https://github.com/shopsys/shopsys/pull/815/files
and caret should solve #831
