### ISSUE TITLE
Check whether use of log-pipe could be removed for microservice packages

### ISSUE THREAD

**Issue by boris-brtan** [shopsys/shopsys#550]
### What is happening

For php-fpm container we implemented `/tmp/log-pipe`, mkfifo system for monolog logging because we launch phing targets via console and we wanted all logs be transfered into docker logging system.
### Expected result

If microservices are not used the same way as php-fpm container, log-pipe should be erased and logs can be redirected into /dev/STDOUT or /dev/STDERR

**Comment by grossmannmartin** [comment]
Microservices was removed in #793
