### ISSUE TITLE
Use of imports of template macros in twig templates

### ISSUE THREAD

**Issue by boris-brtan** [shopsys/shopsys#561]
It seems like some imports for macros in some templates are redundant.
https://github.com/shopsys/shopsys/blob/9a9c7d586b4354e7592de6ae61ddd037f746b0e5/project-base/src/Shopsys/ShopBundle/Resources/views/Front/Content/Product/list.html.twig#L4

https://github.com/shopsys/shopsys/blob/9a9c7d586b4354e7592de6ae61ddd037f746b0e5/project-base/src/Shopsys/ShopBundle/Resources/views/Front/Content/Product/listByBrand.html.twig#L3

https://github.com/shopsys/shopsys/blob/9a9c7d586b4354e7592de6ae61ddd037f746b0e5/project-base/src/Shopsys/ShopBundle/Resources/views/Front/Content/Product/search.html.twig#L4

https://github.com/shopsys/shopsys/blob/9a9c7d586b4354e7592de6ae61ddd037f746b0e5/packages/framework/src/Resources/views/Admin/Content/Article/detail.html.twig#L3

https://github.com/shopsys/shopsys/blob/9a9c7d586b4354e7592de6ae61ddd037f746b0e5/packages/framework/src/Resources/views/Admin/Content/Brand/detail.html.twig#L2

https://github.com/shopsys/shopsys/blob/9a9c7d586b4354e7592de6ae61ddd037f746b0e5/packages/framework/src/Resources/views/Admin/Content/Category/detail.html.twig#L2

https://github.com/shopsys/shopsys/blob/9a9c7d586b4354e7592de6ae61ddd037f746b0e5/packages/framework/src/Resources/views/Admin/Content/Product/detail.html.twig#L3

**Comment by boris-brtan** [comment]
+1

**Comment by vitek-rostislav** [comment]
closed by #1284
