### ISSUE TITLE
Shopsys full of legacy code

### ISSUE THREAD

**Issue by simara-svatopluk** [shopsys/shopsys#569]
### What is happening
Shopsys is full of legacy code.

#### One example

Thanks to #567 I found interfaces: [`TimelimitLoginInterface`](https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Model/Security/TimelimitLoginInterface.php) [`UniqueLoginInterface`](https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Model/Security/UniqueLoginInterface.php)

What are responsibilities of these interfaces?
When I tried to review #567 I realized that code present in [`AdministratorUserProvider`](https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Model/Administrator/Security/AdministratorUserProvider.php#L65L80) is the responsibility. There should be something like `$administrator->checkLogin(...maybe a dependeny...)`, and the responsibility can be extracted into an interface that has this method `checkLogin`. And this interface can be implemented in two ways.

This all results in explicit responsibilities and reduces legacy code.
And removes horrible `if ($administrator instanceof UniqueLoginInterface)`

### Expected result

Less legacy code.

**Comment by PetrHeinz** [comment]
Hi @simara-svatopluk, please try to define a specific scope for this issue. There are legacy parts to almost every non-trivial project. With the expectation of "less legacy code", this issue can be closed after any refactoring; but you could open up an identical issue the very next moment - it's not particularly helpful.

As I see it, you can either define exactly what "legacy code" is and how to find it or reduce the scope of the issue on the example you provided.

Thanks.

**Comment by simara-svatopluk** [comment]
This issue was created as a result of frustration that we, developers of shopsys framework, keep the PHP in state "as it is" and not working on major improvements. Day by day, the php becomes more and more legacy and we keep it rotting.

The situation changed, we started to work on refactorings and while working on #595 we even started to remove code :tada:
