### ISSUE TITLE
FormTypes setDefault does not support multi-dimensional arrays

### ISSUE THREAD

**Issue by TomasLudvik** [shopsys/shopsys#583]
There cannot be set default values for form types using multi-dimensional arrays.

### What is happening
Let us take DisplayOnlyUrlType for example.
```
$resolver
    ->setDefaults([
        'mapped' => false,
        'required' => false,
        'attr' => [
            'readonly' => 'readonly',
        ],
        'data' => [
            'route_name' => '',
            'id' => null,
            'name' => '',
        ],
    ]);
```

Default values for $data['route_name'] and other keys will be set only in the case that data set to this form are empty. If somebody sets $data['route_name'] in form definition, then the default value for id and name will not be used and the array passed to the twig template will consist only of the route_name key.
### Expected result
Expected default values should be applied until they are overwritten during the creation of the form type.

**Comment by TomasLudvik** [comment]
This function is supported since Symfony 4.2 https://github.com/symfony/symfony/pull/27291

**Comment by TomasLudvik** [comment]
Hello @PetrHeinz,

it is not a bug in Symfony, but the way it is used on Shopsys Framework leads to confusion. For example, a lot of form types uses the default value for novalidate attribute. When you are using this FormType in your form, you probably do not know this default attributes and you can set your own ones that leads to removing this. This is bad behavior in my opinion and could be classified as buggy.

**Comment by PetrHeinz** [comment]
@TomasLudvik: But this is the behavior of Symfony forms. Symfony is not even planning to have merging array values from setDefault as default behavior and I think neither should we. 

Can you provide an example where it's used wrong and leads to bugs? These should definitely be fixed, but I don'T think we can do something about it in general (as described in the issue).

 The `'attr' => ['novalidate' => 'novalidate']` is used as a default only in the whole front-end forms (`Shopsys\ShopBundle\Form\**FormType`) and we never overwrite the `attr` option.
