### ISSUE TITLE
Admin form allows to submit form several times

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/shopsys#584]
### What is happening
In admin category detail I click Save and then click it several times again. Then the page reload and I see category overview and I can see that category was created multiple times - I have four same categories.

Maybe this happens to other admin forms.

### Expected result
I should be able to submit form only once even if I click button sever times.

**Comment by LukasHeinz** [comment]
I want this, do not close it please

**Comment by henzigo** [comment]
.
