### ISSUE TITLE
It is quite hard to change admin locale

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#589]
### What is happening
When I want to change admin locale, I need to overwrite `Localization::getAdminLocale()` (see https://github.com/shopsys/shopsys/blob/master/docs/introduction/how-to-set-up-domains-and-locales.md#36-locale-in-administration). To me, it means many unnecessary steps for such a tiny change.

### Expected result

It should be possible to set administration locale without the need of extending a framework class. E.g. using `parameters.yml` or any other config file for that purpose would be nice

**Comment by PetrHeinz** [comment]
If it's done using a DIC parameter, it would be nice to check whether the requested admin locale is among `Localization::getLocalesOfAllDomains()`, and throw an exception if it's not. There is implicit assumtion about this in many parts of Shopsys Framework and it would be nice to have it explicitly said.
