### ISSUE TITLE
*Services should have protected attributes

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#590]
### What is happening
It is not possible to extend any behavior of *Service classes easily - they have private methods and properties.

### Expected result
*Service classes should have protected attributes and methods instead of the private ones.

**Comment by vitek-rostislav** [comment]
created US-4970 in internal backlog

**Comment by simara-svatopluk** [comment]
This will not be longer an issue as we are removing the whole `Service` layer

**Comment by simara-svatopluk** [comment]
We removed the `Service` layer in #627, so this issue is doesn't make sense anymore - there is simply nothing to extend
