### ISSUE TITLE
DX - prepared classes for framework extending

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#591]
### What is happening
When extending the framework behavior, there are some steps that could be prepared beforehand.
Example scenario - I need to find brands by their name so I have to:
- extend `BrandRpository` (i.e. create a new class)- add new method `findByName()`
- register my new class as an alias for the one from the framework in `services.yml`
- extend `BrandFacade` (i.e. create a new class) - add new method `findByName()`
- again, register my new class in `services.yml`

In https://github.com/shopsys/shopsys/pull/409, we prepared following empty extended classes in `project-base` for the most commonly extended entities:
- entities themselves
- data objects
- data object factories
- form extensions

**I believe we should prepare yet two more empty classes:**
**- facades**
**- repositories**

### Expected result

There are less necessary steps when a developer wants to extend the framework bahavior.

**Comment by Miroslav-Stopka** [comment]
Hi @vitek-rostislav,
1) one of the nice features of the glassbox approach is that you dont have to maintain and a lot of unmodified files (old/core files). In my opinion, if you will prepare all facades and all repositories, this nice feature will be gone :/

2) register FACADE in services.yml
- are you sure this is necessary? I think that all facades are already registered.

3) register REPOSITORY in services.yml
- this is the only thing of your suggestions that I agree with

**Comment by vitek-rostislav** [comment]
Hi @Miroslav-Stopka, thanks for the reply. 

ad 1) This is a good point - it should not be a problem for most of the time - you would just have simple empty classes in your project ready for your use if necessary. However, it is true that it might make the upgrading harder in some scenarios.

ad 2) oh, sure, you are right :+1: 

What do the others think? :slightly_smiling_face:

**Comment by vitek-rostislav** [comment]
I would just add that this problem was reported by developers from Barton studio. 

For them, it seemed like too many steps for achieving such a simple modification.

**Comment by PetrHeinz** [comment]
Creating an empty Facade and Repository layer for the basic entities (those we extended in the project-base) seems like a good idea to me.

Ad 2) and 3) The manual registering of the facades and repositories is necessary if you want to use your extended services instead of the original ones. Eg. when you create `MyProductFacade extends ProductFacade` and want it to be autowired to all services that require `ProductFacade` in the constructor. This requires a service alias to be created. The autoregistration would register both services independently.

I think that having those classes prepared in the project-base would serve as an explanation of how Shopsys Framework is intended to be used.

I am a bit worried about the horrendous parameters of the constructor methods in some of the facades (eg. `ProductFacade` or `CategoryFacade`)...

**Comment by TomasVotruba** [comment]
Hey guys, have you tested this solution with entities that are locked to repositories? (see Doctrine doc for [@Entity annotation](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/annotations-reference.html#entity)):

```php
/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Prouct
{
}
```

When this is mixed with [repository as service](https://www.tomasvotruba.cz/blog/2017/10/16/how-to-use-repository-with-doctrine-as-service-in-symfony/):

```php
class ProductRepository
{
    public function __construct(EntityManagerInterface $entityManager)
    {
        $entityManager->getRepository(Product::class);
    }
}
```

it will call:

- repository to get `Product` entity in `getRepository()`
- entity to get `Product` repository mentioned in annotatoin
- repository to get `Product` entity in `getRepository()`
- ....

These approaches are mutually excluded and it's very difficult to find this out, php just stucks, there is no circular check in Doctrine unfortunately.

I'd mention this in upgrade docs:

```diff
 /**
- * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
+ * @ORM\Entity
  */
 class Prouct
 {
 }
```

**Comment by pk16011990** [comment]
remove stale label...

**Comment by TomasLudvik** [comment]
Hello guys,

I do not agree with @Miroslav-Stopka in this one. It would be so much easier to build project when there would be as much classes extended as possible in default project-base. I am just working on new project and it is bit annoying to extend all classes and even more when you have more functionalities in development and all of them need to extend for example ProductFacade. You need to do this more than one time and in the end you need to solve merge conflicts. 

@vitek-rostislav suggested to add facades and repositories of already extended class. I would go even further to extend all entities or at least add some more. I would also love to have already extended classes, that are most likely to be extended on every project like:
- FrontBreadcrumbResolverFactory
- FriendlyUrlDataProviderRegistry
- ...

**Comment by PetrHeinz** [comment]
@TomasLudvik: Maybe I'm missing something obvious, but why would you nee to extend `FriendlyUrlDataProviderRegistry`?

I would much rather change the implementation and configuration of `FrontBreadcrumbResolverFactory` to work similarly to `FriendlyUrlDataProvider`s - via a shared interface, autoconfigured tagging and constructor dependency injection. I'd rather remove the need for excessive extension that provide empty extending classes.

**Comment by TomasLudvik** [comment]
@PetrHeinz you are right with `FriendlyUrlDataProviderRegistry`... My point is that there are some other classes that you need to extend right now like `CronModuleFactory` etc. It would be nice to do some research and include everything that people might need to extend.

**Comment by vitek-rostislav** [comment]
Hi guys, I am thinking whether some code generator would be a possible solution for this, something like 
```
php bin/console shopsys:class:extend Shopsys\FrameworkBundle\Model\Product\ProductFacade
```
 that would take care of everything boring? :thinking: 

I have created a user story to solve this issue, so we need to evaluate it and then plan it to a sprint. I will let you know about the progress :slightly_smiling_face:

**Comment by henzigo** [comment]
bump

**Comment by pk16011990** [comment]
remove stale...
