### ISSUE TITLE
Broken design in administration with singledomain

### ISSUE THREAD

**Issue by boris-brtan** [shopsys/shopsys#594]
### What is happening

If we have configured just one domain in administration there is some design bug
![image](https://user-images.githubusercontent.com/39240194/48403982-7f4c8300-e72f-11e8-8f9d-6233e95057cb.png)

### Expected result

singledomain admin design will be fixed

**Comment by PetrHeinz** [comment]
The issue is still occurring in `Settings >  Communication with customer >  E-mail templates`

**Comment by henzigo** [comment]
ping

**Comment by LukasHeinz** [comment]
Still happening even after facelift...

**Comment by boris-brtan** [comment]
> Still happening even after facelift...

:/

**Comment by TomasGottvald** [comment]
We should resolve it.

**Comment by TomasGottvald** [comment]
Actually tested on respo version. Seems to be OK.

![image](https://user-images.githubusercontent.com/35454496/80318865-5cbc0600-880d-11ea-9276-5e407b581741.png)
