### ISSUE TITLE
Friendly URL generation is not effective

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#607]
### What is happening
Reported by @henzigo.
When generating friendly URLs, generating the unique slug is quite unefficient as it iteratively checks the uniqueness of each slug. Thanks to the fact, e.g. importing products from IS can take a huge amount of time unnecessarilly.

See `FriendlyUrlFacade::createFriendlyUrls()`

### Expected result
Friendly URL generation is performed more effectivelly

**Comment by PetrHeinz** [comment]
The main question to answer is how the conflicts in URL should be resolved?

Currently, three urls generated for an entity named Foo will be `foo/`, `foo-2/` and `foo-3/`.

If we'd like to keep this format, we could improve the url generation by fetching all matching friendly urls (i.e. `^foo-\d+/$`) and just avoiding them without involving the costly matching using a router.

Or we could just add a random string at the end if we encounter a conflict, which would example result for into `foo/`, `foo-qg96hq/` and `foo-65fegv/`.

It would still be a good idea to include the iterative matching and using a given number of attempts as it is now - only the router knows how the urls will be resolved in the end (imagine having a `foo-2/` registered as a route in `routing_front.yml` - you would assume it's available if you only checked friendly urls in the DB, but it's not). Our goal should be minimizing the usual number of attempts when there are many identically named entities.

**Comment by PetrHeinz** [comment]
@henzigo mentioned possibility to suffix the url with the ID of the entity when encountering a conflict, which would example result for into `foo/`, `foo-420/` and `foo-1324/`.

As mentioned above, matching it with a router and increasing the suffix (or suffixing it with a incremental value) should still be implemented - imagine having a identically named entities of different type with a same ID. Then, a product named Foo with an ID 420 could have a url `foo-421/` or `foo-420-2` when the `foo-420/` is already in use.

**Comment by simara-svatopluk** [comment]
Maybe generating on friendly URLs can be postponed to later asynchronous operation

**Comment by pk16011990** [comment]
Current solution with numeric suffix has advantage that it fails on reach some maximum number. This can alert developer to the problem because it is not good have a lot of entities with same name...
