### ISSUE TITLE
Extending OrderPayment and OrderTransport Entity results in "It is not supported to define inheritance information on a mapped superclass" exception

### ISSUE THREAD

**Issue by dzarda86** [shopsys/shopsys#621]
I need to extend Model\Order\Item\OrderPayment and OrderTransport classes. I followed Adding new attribute article. Everything seem all right unless I try to submit an order. Then it throws It is not supported to define inheritance information on a mapped superclass ‘Shopsys\FrameworkBundle\Model\Order\Item\OrderItem’ exception.

### What is happening
I need to be able to set catnum attribute even for OrderTransport and OrderPayment classes due to synchronization with Pohoda (~ foreign key).

I extended both entities according to Adding new attribute article and added:
Shopsys\FrameworkBundle\Model\Order\Item\OrderPayment: Shopsys\ShopBundle\Model\Order\Item\OrderPayment

Shopsys\FrameworkBundle\Model\Order\Item\OrderTransport: Shopsys\ShopBundle\Model\Order\Item\OrderTransport

into parameters_common.yml

All is working as expected, eg. if I dump Order entity, it contains OrderPayment and OrderTransport objects of correct namespace (ShopBundle) within items and these objects are filled correctly. The problem arises when Doctrine tries to store data into DB; it throws

It is not supported to define inheritance information on a mapped superclass ‘Shopsys\FrameworkBundle\Model\Order\Item\OrderItem’

any hints? 

### Expected result

I would like the filled Order object to be stored into DB 🥇

**Comment by vitek-rostislav** [comment]
Hi, I believe you need to extend the `OrderItem ` entity as well, see https://github.com/shopsys/shopsys/blob/master/docs/wip_glassbox/entity-extension.md#orderitem-and-true-mapped-inheritance

**Comment by boris-brtan** [comment]
We have also some extensions of OrderPayment and OrderTransport Entities here in our database tests
- https://github.com/shopsys/shopsys/blob/master/project-base/tests/ShopBundle/Functional/EntityExtension/Model/ExtendedOrderPayment.php
- https://github.com/shopsys/shopsys/blob/master/project-base/tests/ShopBundle/Functional/EntityExtension/Model/ExtendedOrderTransport.php
- ....

**Comment by vitek-rostislav** [comment]
Hi @dzarda86, I see that extending `OrderItem` or its descendants is very problematic and causes unexpected problems. We are planning to address the issue and solve the order item inheritance somehow systematically. However, we are expecting this task to be very difficult and may consume a huge amount of development time so it will probably take a while until this is solved.

There is a *dirty hack* in our minds - aliasing the original classes with your extended ones (only the descendants, eg. `class_alias('Shopsys\FrameworkBundle\Model\Order\Item\OrderProduct', DreamOrderProduct::class)`) using [class_alias php function](http://php.net/manual/en/function.class-alias.php), e.g. in `app/Bootstrap.php`. 

However, we have not tried nor tested this approach yet - we will be happy if you try it and let us know whether it works for you. Nevertheless, I believe it will be solved some better way in the end.
