### ISSUE TITLE
Improve docs - non existing routes in config does not cause failed tests

### ISSUE THREAD

**Issue by simara-svatopluk** [shopsys/shopsys#64]
> Transfered from http-smoke-testing repository

@vitek-rostislav
In docs, there should be information that http smoke tests do not fail when there is a non-existing route in config.

This is caused by default PHPUnit setting where warnings do not cause fail and can be fixed by setting `failOnWarning="true"` in `phpunit.xml`

**Comment by PetrHeinz** [comment]
Thanks for noticing, @TomasLudvik added a troubleshooting section mentioning the setting.
