### ISSUE TITLE
Maintenance page - image of Bořek Stavitel

### ISSUE THREAD

**Issue by PatrikBajer** [shopsys/shopsys#643]
### What is happening
On the maintenance page I don't see image of builder at 100% of view . Image size is 6000x4000. - http://prntscr.com/lozcm2

### Expected result
On the maintenance page I want to see image of builder at 100% of view. Just set image size to 600x400 - http://prntscr.com/lozeq5

**Comment by PetrHeinz** [comment]
Hi @PatrikBajer and thanks for reporting.

The absurdly huge image was already replaced by a SVG in #618 (as of `v7.0.0-beta3`).
