### ISSUE TITLE
[shopsys/migrations] Mysql/Maria DB does not support migration DDL in transaction

### ISSUE THREAD

**Issue by simara-svatopluk** [shopsys/shopsys#65]
> Transfered from migrations

@pk16011990
Hello,

running migrations in transaction - It sounds as very good improvement instead of basic Doctrine migrations, but ... In Mysql DDL (create, alter, drop) commands are out of transaction and on rollback these changes are persist, but migraton looks like rollbacked.

In my opinion it does not have a solution, It is a feature that should be documented or It shoud be allowed on this engines.

**Comment by pablocar80** [comment]
This issue seems to be addressed here:
https://jira.mariadb.org/browse/MDEV-4259

**Comment by pk16011990** [comment]
ping (prevent stale)

**Comment by boris-brtan** [comment]
@pk16011990 do you have any commit or PR for this?

**Comment by pk16011990** [comment]
.

**Comment by pablocar80** [comment]
(╯°□°）╯︵ ┻━┻

**Comment by pablocar80** [comment]
.

**Comment by grossmannmartin** [comment]
MySQL/MariaDB is not supported by the Shopsys Framework out of the box. closing
