### ISSUE TITLE
Missing documentation for differences between the repository and standard doctrine migrations

### ISSUE THREAD

**Issue by simara-svatopluk** [shopsys/shopsys#66]
> Transfered from migrations

@vitek-rostislav 
Command `shopsys:migrations:generate` generates different migrations than standard `doctrine:migrations:diff command` do - eg. it omits the SQL commands that break backward compatibility (eg. column dropping). This should be documented.

**Comment by Miroslav-Stopka** [comment]
Hi @simara-svatopluk, this issue is already solved in #93 . Can you confirm this? Thank you

**Comment by simara-svatopluk** [comment]
You are right @Miroslav-Stopka
