### ISSUE TITLE
User::$billingAddress is missing orphanRemoval

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#663]
### What is happening

Orphan removal on `User::$deliveryAddress` was set in #627 (the function was refactored from `UserFacade`, see https://github.com/shopsys/shopsys/commit/cabf8d91ab8bfa8107bcb37183984bdfd849de4d). I believe the same setting should be used for `User::$billingAddress`

### Expected result
When a user is deleted, his billing address should be removed from the database as well (when is not used by any other user)

**Comment by boris-brtan** [comment]
@vitek-rostislav , was any progress for this ?

**Comment by vitek-rostislav** [comment]
> @vitek-rostislav , was any progress for this ?

Hi @boris-brtan :slightly_smiling_face: no prority -> no progress

**Comment by s3tezsky** [comment]
fixed in #1977
