### ISSUE TITLE
All packages should be built on travis after merge to master in monorepo

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#665]
### What is happening
When a merge to master is performed in monorepo, the monorepo is split and a build on travis is triggered only for the packages that has been actually changed. 

Imagine this scenario: In monorepo, change of `coding-standards` package is merged to master, monorepo is split and travis build is triggered for the `coding-standards` package only. No other builds are triggered, so we are not aware when the change breaks the installation of `project-base`, for example.

### Expected result
Travis build for all packages should be triggered after the merge to monorepo master is performed (and monorepo is split), no matter whether or not a particular package has been affected by the change.

**Comment by PetrHeinz** [comment]
This can be nicely solved using [Cron jobs on Travis CI](https://docs.travis-ci.com/user/cron-jobs/). This should also cover a scenario where some of the dependencies (some other than our own) of a particular package release a new version breaking our code.

**Comment by TomasVotruba** [comment]
:+1: 

Next level - [How to Test Monorepo in 3 Layers](https://www.tomasvotruba.cz/blog/2018/11/22/how-to-test-monorepo-in-3-layers/)

**Comment by vitek-rostislav** [comment]
@boris-brtan could you please push this issue? Or do you think it is not important anymore?

**Comment by vitek-rostislav** [comment]
@boris-brtan could you please push this issue? Or do you think it is not important anymore?
