### ISSUE TITLE
Sniffs and standards for orchestration related files

### ISSUE THREAD

**Issue by MattCzerner** [shopsys/shopsys#666]
Docker compose files, kustomize files and Terraform files are right in the state of anarchy, there is not single check (except funcionality) on how to write these files

### What is happening
Anybody can make mistake in indention or alphabetical order in orchestration files and our checks will not discover it.

### Expected result
Implement https://github.com/sspooky13/yaml-alphabetical-checker to check these files too?

**Comment by PetrHeinz** [comment]
Standards for YAML currently being implemented in #539 should imo cover kubernetes manifests (and kustomize overlays) as well.
Terraform has its own standard format and it can be checked or fixed automatically using [`terraform fmt`](https://www.terraform.io/docs/commands/fmt.html).

**Comment by boris-brtan** [comment]
:imp:

**Comment by MattCzerner** [comment]
bumpidy bum
