### ISSUE TITLE
[framework] Custom URL for Category

### ISSUE THREAD

**Issue by Swejzi** [shopsys/shopsys#668]
### What is happening
It is not possible to create own URL for a category

### What is happening
I am not able to create new URL for category and delete the one generated from category name.

Steps to reproduce:
1. Create a new URL for category and save.
2. Set the new URL as main and save.
3. Delete the original main URL that was generated from category name.

Once again, URL is generated from the category name and set as the main one.
Should be sufficient to remove one line from `CategoryFacade::edit()` where the new URL is generated.

### Expected result
Do not create an unwanted URL from category name.

**Comment by vitek-rostislav** [comment]
Hi @Swejzi, thx for reporting. I have created a PR with a fix. Moreover, I see there is the same problem with products, so we should probably resolve this as well.

Oh, one more thing - please, write your issue in English next time :slightly_smiling_face:

**Comment by vitek-rostislav** [comment]
Hi, @TomasLudvik 

> can you please link this issue to the PR? Thank you.

It is already linked :slightly_smiling_face: see 
![image](https://user-images.githubusercontent.com/10401898/51753234-9279b880-20b9-11e9-83ac-29d78d5431e1.png)

**Comment by boris-brtan** [comment]
was there any progress about this one?

**Comment by vitek-rostislav** [comment]
hi @boris-brtan, nope, no priority, no urgency -> no progress

**Comment by henzigo** [comment]
Open it

**Comment by Swejzi** [comment]
Ani po roce a půl není ten jeden jediný řádek ze stabilu smazaný 

https://github.com/shopsys/shopsys/pull/1886

**Comment by s3tezsky** [comment]
fixed in #1972
