### ISSUE TITLE
Old URL drop to error 500

### ISSUE THREAD

**Issue by PatrikBajer** [shopsys/shopsys#677]
### What is happening

1) create new product
2) rename that new product
3) watch in admin URL settings 
4) go to the old URL address.

I create new category/product/article - after some time I edit name of that category/product/article. System generate new URL address, but old URL address start droping to error 500.

### Expected result
Redirect me to new URL address.

**Comment by boris-brtan** [comment]
i think that all the friendly urls that are not set as main are not functional.
