### ISSUE TITLE
Images for the main variant are not displayed

### ISSUE THREAD

**Issue by DavidOstrozlik** [shopsys/shopsys#686]
### What is happening
If you create variant and select a product with images as main variant, resulting main variant has images that are not visible or the creating results in error 500.

eg.
- Select product "22" Sencor SLE 22F46DM4 HELLO KITTY " as main variant -> error 500
- Add images to some product and select it as main variant -> the images are not displayed (maybe because of route to the image "eg. http://127.0.0.1:8000/content/images/product/original/106.")

### Expected result
Main variant should have visible images and the creation of variant should not end up with error 500

**Comment by boris-brtan** [comment]
still confused but it seems to me that there are 2 different initialisations of flysystem configs during `ImageFacade::copyImages` and `DoctrineListener::postPersist---fileUpload->postFlushEntity`
![image](https://user-images.githubusercontent.com/39240194/53021552-c0a0ad00-3459-11e9-84cc-1cf175463022.png)
