### ISSUE TITLE
there should be an automatic check for undefined variables

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#689]
### What is happening
Undefined variable in Twig template was causing a 500 error, see https://github.com/shopsys/shopsys/pull/685. I was surprised that there is no automated check that prevents the application from 500 errors caused by undefined variables, not even in PHP files.

### Expected result
Our coding standards should check for undefined variables in PHP and Twig files.

**Comment by grossmannmartin** [comment]
Hi, automatic variables in PHP files can be checked with PhpStan. Even on level 0, it reports undefined variables. 
Do you have some example of code, where this is not happening?

**Comment by PetrHeinz** [comment]
There was an undefined variable in a Twig snippet in #685. Not sure how it could be checked as it's very complex - the undefined Twig variable can be in used in a translation, the string with theš Twig snippet can be passed in PHP variables etc...

Undefined variable in PHP are checked atm.
