### ISSUE TITLE
page withou vertical scrollbar move with page if there is popup window

### ISSUE THREAD

**Issue by PatrikBajer** [shopsys/shopsys#695]
### What is happening
If you go to the registration page and try sent empty form, there is popup what give you info about required data.

When the popup is show, there is some white space for vertical scroll. -> http://prntscr.com/lwyzbw

1) go to /registration/
2) sent empty registration
3) close that popup up and try again
4) you can see - page is moving from left to right

Video - https://drive.google.com/file/d/1IPZ-ohjYNYEULktGzUtLejSQuziUBMyC/view?usp=sharing

### Expected result
On page where isn't vertical scroll bar, don't make that white space.

**Comment by vitek-rostislav** [comment]
Hi @PatrikBajer, thanx for reporting :slightly_smiling_face:
