### ISSUE TITLE
Validation of e-mail in order (step 3)

### ISSUE THREAD

**Issue by PatrikBajer** [shopsys/shopsys#696]
### What is happening
Email field has bad validation.

1) add product to cart 
2) go to step 3
3) fill all fields with some value, and set e-mail field to value "aaa"
4) try finish order
5) After you make step 4 validation says - email is not in valid format. After that set valid email to field.
6) If you set correct email, field still saying "Please enter valid e-mail". - http://prntscr.com/lx0euw

### Expected result
In step 5) make validation for that e-mail field.  Because my email is not wrong anymore.

**Comment by pk16011990** [comment]
remove stale label

**Comment by TomasLudvik** [comment]
remove stale

**Comment by PatrikBajer** [comment]
remove stale

**Comment by grossmannmartin** [comment]
closing as it's already fixed on the current master
