### ISSUE TITLE
PHPStan memory consumption

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#704]
### What is happening
We ran into issues with PHPStan memory consumption so we discarded the memory limit for PHPStan, see https://github.com/shopsys/shopsys/pull/623#discussion_r244157122 and https://github.com/shopsys/shopsys/pull/694#discussion_r244189157. @boris-brtan suggests upgrading PHPStan and splitting the execution into multiple phing targets - this could be a proper solution.

### Expected result
PHPStan memory consumption problems solution is examined and the issue is solved properly - there probably should not be `memory_limit=-1`.

**Comment by boris-brtan** [comment]
i would also suggest try to use https://www.phing.info/phing/guide/en/output/chunkhtml/ParallelTask.html so standards would be processed faster since php is only singlethreaded it should run more processes at once with smaller range of data.
