### ISSUE TITLE
non-standard version restrictions in composer.jsons

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#722]
### What is happening
We have the rules that all external dependencies in `composer.json` files are defined using caret carsion (`^`), and internal dependencies can be defined as `dev-master`. See https://github.com/shopsys/shopsys/blob/master/docs/contributing/guidelines-for-dependencies.md.
However, there are dependencies on `shopsys/jparser` and `shopsys/postgres-search-bundle` that do not satisfy these rules. These dependencies are reported by `ValidateRequireFormatInComposerJsonReleaseWorker` during our release process.

### Expected result

Dependencies on `shopsys/jparser` and `shopsys/postgres-search-bundle` should be defined the standard way or mentioned in "Exceptions" section in guidelines-for-dependencies.md

**Comment by boris-brtan** [comment]
https://github.com/shopsys/shopsys/issues/549

**Comment by simara-svatopluk** [comment]
We are not planning to maintain these dependencies, so I vote for Exceptions
