### ISSUE TITLE
AllMailTemplatesData should be instantiated by factory

### ISSUE THREAD

**Issue by thirdknown** [shopsys/shopsys#724]
I see that in [Model/Mail/MailTemplateFacade.php on line 142](https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Model/Mail/MailTemplateFacade.php#L142) is instantiated class AllMailTemplatesData by 'new' keyword. It is not good practise for future overriding of AllMailTemplatesData. Please, create factory for creating instances of AllMailTemplatesData. Then programmers will override that factory, not all methods in which AllMailTemplatesData is creating. Thanks a lot.

**Comment by simara-svatopluk** [comment]
Our concept of data factories covers only data that are used by an entity (at least for now).

Do you already face the problem - that you have to override all the methods that uses the `AllMailTemplatesData`?

**Comment by pk16011990** [comment]
remove stale label

**Comment by henzigo** [comment]
bump

**Comment by vitek-rostislav** [comment]
the problem is still there - the class extension is harder (or at least "not-standard") because of the missing factory
