### ISSUE TITLE
Update docker to 18.09 and use buildkit for ci stages to speed up CI build

### ISSUE THREAD

**Issue by boris-brtan** [shopsys/shopsys#725]
### What is happening

https://docs.docker.com/develop/develop-images/build_enhancements/

### Expected result

sped up build of CI jobs

**Comment by boris-brtan** [comment]
+1?

**Comment by vitek-rostislav** [comment]
Hi @grossmannmartin, I am not expecting any reaction here, however, it seems to me this can be interesting for you :slightly_smiling_face:
