### ISSUE TITLE
check relevance of private visibility for parameters and methods in Product\Pricing classes

### ISSUE THREAD

**Issue by boris-brtan** [shopsys/shopsys#726]
### What is happening

during implementation of discount for customer we needed to extend classes with private methods and properties https://github.com/shopsys/demoshop/pull/31

### Expected result

decision or result whether it is possible to have it at least protected

**Comment by simara-svatopluk** [comment]
We created a user story in our internal system to solve also this issue https://app.yodiz.com/plan/pages/board.vz?cid=10273#/backlog/us-5213

**Comment by TomasLudvik** [comment]
For those, that cannot access yodiz:

This UserStory says, that all method and properties in Components and Model dirs will have public or protected visibility.
The reason is easier extendibility from project-base.
