### ISSUE TITLE
Weird appearence of newsletter login button after clicking

### ISSUE THREAD

**Issue by LukasHeinz** [shopsys/shopsys#727]
### What is happening
When I am on front-end (any page) and I click on Log in button for newsletter, the button enlarge itself and collapse again. See video - https://drive.google.com/open?id=1O_GJ1bh4icXI4aMYEeQZjFGxBCndRPr1

### Expected result
Button should keep it size.

**Comment by grossmannmartin** [comment]
Was already fixed in #703. Closing.
