### ISSUE TITLE
Check whether update of packages with caret (^) and lower version than 1.0 is possible

### ISSUE THREAD

**Issue by boris-brtan** [shopsys/shopsys#731]
Caret behaves differently for lower than 1.0.0 versions https://getcomposer.org/doc/articles/versions.md#caret-version-range-
now we have for instance more than one year old version of phpstan.
### Expected result

Upgrade all 0.* caret packages that can be upgraded.

**Comment by simara-svatopluk** [comment]
Well, it has a reason that `^0.X.Y` behaves differently. I recommend to try to update libraries that are in this version and add an instruction for upgrading this manually to our release instructions

**Comment by TomasLudvik** [comment]
The reason, that we have an old version of PHPStan is that in time, it was implemented, there was already a newer version, but some of our dependencies were blocking it.
