### ISSUE TITLE
Instalation guidelines should include information about minimal required version of requirements

### ISSUE THREAD

**Issue by TomasLudvik** [shopsys/shopsys#734]
### What is happening
People might encounter problems when they have installed older version of requirement like Docker in a version before multi-stage functionality has been implemented. 

### Expected result
Documentation includes minimal required versions of requirements.

**Comment by PetraPiprekova** [comment]
something was already resolved in #764

**Comment by boris-brtan** [comment]
what about native installation ? there is still postgres 9.5 is there any issue that will solve native installation in the future?
i am not sure what @TomasLudvik wanted exactly byt i see there `like Docker`. and it seems to me that this should not cover just docker but also GIT, PHP, Redis, Elasticsearch, ... in all the installation guides?
Is that right, or not?
