### ISSUE TITLE
Choosing a way to extend Data Fixtures

### ISSUE THREAD

**Issue by simara-svatopluk** [shopsys/shopsys#738]
### What is happening
We need to allow Data Fixtures extensibility.

We discussed two different ways to do it, have arguments for both ways and we would like to know more arguments. These two ways are **events** and **middlewares**. In general they both serve the same purpose - when we create Data object in DataFixtures, we need a tool that implementators can manipulate it, and also when an Entity is created in DataFixtures, we the same tool that implementator can use to manipulate it.

Example with product:
```php
$data = $this->productDataFactory->create();
???($data);
....
$entity = $this->productFactory->create($data);
???($entity);
```

### Events

The idea is dispatching an event in `???` places that can be listened by implementator, and in the listener, implementator could manipulate the object.

```php
$data = $this->productDataFactory->create();
$this->dispatcher->dispatch(new ProductDataCreatedEvent($data));
```
And the implementator will create an event listener for this
```php
class ProductDataFixtureListener {
    // ...
    public function dataCreated(ProductDataCreatedEvent $e) {
        $e->getData()->aNewProperty = 'abc';
    }
}
```
**Pros** - Event concept is well knows.
**Cons** - If there are more listeners, their order can be crucial, but event concept generally doesn't care about listeners order. Events are difficult to debug, if there are more listeners that have dependencies, debugging becames hard.

### Middlewares

The idea is to create manipulator objects that will be called in `???` and will be stacked in middlewares fashion. Implementator could implement a new middleware and add it to the stack.

```php
$data = $this->productDataFactory->create();
$this->middleware->manipulate($data);
```

And the implementator will create an middleware
```php
class ProductMiddleware implements ProductDataFixturesMiddleware {
    // ...
    public function manipulate(ProductData $data) {
        $data->aNewProperty = 'abc';
        $this->nextMiddleware->manipulate($data);
    }
}
```
To be clear - middlewares allow multiple implementations of the interface that will be called in a defined order.

**Pros** - The concept is more specific than listeners. For this use case is simpler.
**Cons** - The concept is less known than listeners.

### Expected result
As you can see, both solutions have the same value, but in our team we aren't decided what solution we will choose. We would love to hear any argument for/against any of these solutions.

**Comment by Miroslav-Stopka** [comment]
Thanks for new improvement plans :)

My suggestion: Move DataFixtures into project-base/.

**Why?**

- DataFixtures need to be modified on every bigger project (something that needs to be modified on every bigger project should be in project-base by default)
- DataFixtures are used mainly in tests - tests are out of framework package as well
- Implementation of project should be as simple as it could be - bringing complexity (Events/Middleware) into DataFixtures seems unnecessery to me

**Comment by PetrHeinz** [comment]
**Personally, I would go for Events**, as the pattern is broadly used in the Symfony environment, and it's simple to implement and describe to users.

But it's true that Middleware feels like a closer fit, and with a good design and docs it might prove to be a better solution.

Each layer should imo get Entity data as an argument (and perhaps optionally a persistent reference name) and output the created Entity. This will provide each layer with the ability to modify the data before it's passed to the next layer, and execute some code with the created Entity (i.e. generate it's image and save it).

```php
class NewPropertyProductMiddleware implements ProductDataFixtureMiddleware {
    public function manipulate(ProductData $data, ?string $reference, callable $next): Product {
        $data->aNewProperty = 'abc';

        return $next($data, $reference);
    }
}

class ImageProductMiddleware implements ProductDataFixturesMiddleware {
    public function manipulate(ProductData $data, ?string $reference, callable $next): Product {
        $product = $next($data, $reference);
        $this->createImage($product);

        return $product;
    }
}
```

The core layer (the inner-most callback) would just create the Entity using its Entity facade and use the `PersistentReferenceFacade` to save the reference, if a name is provided:

```php
// ProductDataFixture.php
$productMiddleware->manipulate($data, $reference, function (ProductData $data, ?string $reference) {
    $product = $this->productFacade->create($data);
    if ($reference !== null) {
        $this->persistentReferenceFacade->persistReference($reference, $product);
    }

    return $product;
});
```

This would cover both use cases (before and after persisting the entity) at the same time.

**Comment by vitek-rostislav** [comment]
Hi @simara-svatopluk, thanks for the nice description of the problematics and possible solution proposals :ok_hand: 

Both the solutions seem quite appealing to me, however, I do agree with @Miroslav-Stopka, we should move data fixtures to `project-base` so they are not undermining developers efforts during project implementation at all :slightly_smiling_face: I have a feeling that there is not any bigger additional value in upgadability of data fixtures and from the feedback of current projects it seems that the developers would really appreciate this approach.

**Comment by simara-svatopluk** [comment]
This is quite unexpected outcome. Moving DataFixtures to project-base hurts upgradability. Our long-term plan is to move functional tests to framework, so they cooperate with DataFixtures in framework.

All in all it is strategical decision, so we'll discuss it and we'll let you know how did we decided and what the long-term plan is.

**Comment by simara-svatopluk** [comment]
Guys, what about moving DataFixtures to project-base **temporarily**? We'll keep improving them and later when the FW is ready for moving functional tests to framework and DataFixtures are prepared for extension, then we'll move them back in a major version. What is your opinion?

**Comment by simara-svatopluk** [comment]
**So we have the final decision. We'll move Data Fixtures to project-base.**

**Thanks guys for Your arguments, You helped us a lot.** :trophy: 

This state will be temporary, we'll keep working on Data Fixtures and when the time is right, we'll move Data Fixtures back to project-base. Our long-term plan is to move also functional tests to framework, and that is possible only if Data Fixtures are in framework too.
