### ISSUE TITLE
Image thumbnails are not generated due to missing JPEG support in PHP

### ISSUE THREAD

**Issue by grossmannmartin** [shopsys/shopsys#739]
### What is happening

Version from master, probably since Debian PHP-FPM image was introduced.

Steps:
Perform a clean installation of the latest version and check the front page.
Image thumbnails are missing. 

On direct access to the URL of image thumbnail (for example http://127.0.0.1:8000/content/images/product/list/9.jpg) the following exception is thrown

`Generate image for entity "product" (type=, size=list, imageId=9) failed.`

With warning: **Warning: imagecreatefromstring(): No JPEG support in this PHP build**

### Expected result
Images are properly generated.

**Comment by boris-brtan** [comment]
missing support for [jpeg and freetype](https://github.com/exozet/docker-php-fpm/pull/4/files) that was in alpine
https://github.com/shopsys/shopsys/pull/702/files#diff-50a0e02c146dc64c2a172b42022589faL33

**Comment by grossmannmartin** [comment]
Hi @boris-brtan,
thanks for quick response. This solution seems good to me. 
Please don't forget to update upgrade file.
