### ISSUE TITLE
There are no rules for phing targets

### ISSUE THREAD

**Issue by DavidOstrozlik** [shopsys/shopsys#742]
### What is happening
We don't have any rules for phing targets so there are lots of them and they need some revision.
Some targets do almost the same thing but they have different names/nomenclature.
We don't know what targets are used and when you should use/create a phing target and when or if you should use/create symfony command.  

### Expected result

Phing targets have been revised so we know what phing targets we have and why we have them, we have some structure of phing targets (every part of bigger target should have its own target or not eg. `clean` should run `clean-dirs`, `clean-redis`,....).
We have some rules so all phing targets follow the same rules about nomenclature (`tests` runs `tests-unit` and other test targets vs `clean` that cleans up directories with cache and scripts but doesn't run other cleaning targets eg. `clean-redis`).

**Comment by TomasVotruba** [comment]
Great to open this! I get lost all the time :) 

Inspiration for some simple targets https://blog.martinhujer.cz/have-you-tried-composer-scripts/
Also Travis might help to clarify what is "simple" target.

**Comment by vitek-rostislav** [comment]
I think we need a user story for that, could you please create one, @DavidOstrozlik?

**Comment by boris-brtan** [comment]
THX

**Comment by vitek-rostislav** [comment]
I have created US-5760 in our internal backlog.
