### ISSUE TITLE
Fix Javascript form constraint validations

### ISSUE THREAD

**Issue by grossmannmartin** [shopsys/shopsys#746]
Our custom form constraint do not properly use javascript validation

### What is happening
Forms which use custom constraints behave funny, because some fields are validated with javascript, some not.

Following files are probably affected, but I'm not sure if they're all

* ShopsysShopBundleComponentConstrainsNotSelectedDomainToShow.js
* ShopsysShopBundleComponentConstraintsContains.js
* ShopsysShopBundleComponentConstraintsNotInArray.js
* ShopsysShopBundleComponentConstraintsUniqueCollection.js
* ShopsysShopBundleComponentConstraintsUniqueProductParameters.js

JS class name has to reflect namespace of a constraint, so the fix should be in renaming
`ShopsysFrameworkBundleComponentConstraintsNotInArray = function () {` to 
`ShopsysFrameworkBundleFormConstraintsNotInArray = function () {`

### Expected result
Javascript validation works properly and every constraint is properly tested.

**Comment by PetrHeinz** [comment]
This is because the the JS contraint validators have non-matching names of the JS function (eg. `ShopsysFrameworkBundleComponentConstraintsEmail`) and the PHP validators (eg. `\Shopsys\FrameworkBundle\Form\Constraints\Email`). This is fixed in #648 (d7773e199953fd298221d5047a9c8bacb7cf3d52).

**Comment by PetrHeinz** [comment]
This issue was probably fixed by #829, can anyone verify this?

**Comment by vitek-rostislav** [comment]
just needs verifying whether it has been fixed in #829

**Comment by grossmannmartin** [comment]
resolved in #829
