### ISSUE TITLE
Vulnerabilities in npm packages

### ISSUE THREAD

**Issue by topolanekmartin** [shopsys/shopsys#756]
### What is happening
After npm packages are installed in the terminal occurs sentence that informs us that there were found vulnerabilities. The terminal navigates us to fix them by run following command "npm audit fix". It must be repaired manually and the command will not do anything.

This warning is caused by packages included in dependencies of packages grunt-webfont and grunt-spritesmith. In the case of the grunt-spritesmith package, there is dependency named cwise causing vulnerability. Fixing the dependencies are already in progress.
You can track progress in following pull requests https://github.com/sapegin/grunt-webfont/pull/389 and https://github.com/scijs/cwise/pull/25

Since the faulty packages (grunt-webfont and grunt-spritesmith) are running only during deploying your project there should not be any security trouble with the packages.

This issue is related to changes made in following pull request https://github.com/shopsys/shopsys/pull/755

**Comment by PetrHeinz** [comment]
Hi @topolanekmartin, nice to see that npm packages are being updated :slightly_smiling_face: 

Could you include an upgrade note explaining how to update the packages when users of Shopsys Framework update to the next version, as the `package.json` file is in the open-box part?

**Comment by vitek-rostislav** [comment]
stalebot, do not close this!

**Comment by pesektomas** [comment]
This issue is in progress in #1668 for versions <= 8.1. In version 9 will be grunt deleted and replaced by webpack.

**Comment by pesektomas** [comment]
Close in #1668
