### ISSUE TITLE
Missing documentation about crons

### ISSUE THREAD

**Issue by henzigo** [shopsys/shopsys#757]
### What is happening

The only mention about cron is in FAQ (https://github.com/shopsys/shopsys/blob/master/docs/introduction/faq-and-common-issues.md#are-some-periodic-tasks-part-of-the-shopsys-framework-cron).

### Expected result

There should be article in Knowledge base or cookbook how to work with crons (add new cron, remove default crons from framework bundle, etc.)

**Comment by pk16011990** [comment]
Some documentation is in https://github.com/shopsys/shopsys/blob/master/docs/introduction/cron.md however how to remove/override cron modul is still missing.

**Comment by vitek-rostislav** [comment]
Stalebot, I am watching this!
