### ISSUE TITLE
Installation guide is not working

### ISSUE THREAD

**Issue by mbohal** [shopsys/shopsys#761]
The installation guide https://github.com/shopsys/shopsys/blob/master/docs/installation/installation-using-docker-linux.md is not working

### What is happening
```sh
mb@mb-laptop ~/Projects/PB/shopsys FAILED ~> composer create-project shopsys/project-base --stability=beta --no-install --keep-vcs                                                               17:06:14.680296782
Installing shopsys/project-base (v7.0.0-beta5)
  - Installing shopsys/project-base (v7.0.0-beta5): Cloning 443fcacad4 from cache
Created project in /home/mb/Projects/PB/shopsys/project-base
mb@mb-laptop ~/Projects/PB/shopsys ~> cd project-base                                                                                                                                            17:07:01.489425237
mb@mb-laptop ~/Projects/PB/shopsys/project-base ((v7.0.0-beta5) ✔) ~> cp docker/conf/docker-compose.yml.dist docker-compose.yml                                                                  17:07:06.849002616
mb@mb-laptop ~/Projects/PB/shopsys/project-base ((v7.0.0-beta5) ✔) ~> docker-compose up -d --build                                                                                               17:07:17.478530255
Building php-fpm
Step 1/41 : FROM php:7.2-fpm-stretch as base
ERROR: Service 'php-fpm' failed to build: Error parsing reference: "php:7.2-fpm-stretch as base" is not a valid repository/tag: invalid reference format
mb@mb-laptop ~/Projects/PB/shopsys/project-base ((v7.0.0-beta5) ✔) FAILED ~>
```
### Expected result
The docker container starts up with no errors.

**Comment by mbohal** [comment]
@PetrHeinz I take whatever fedora repo sends my way. Having to install docker version not provided by my distro is not something that I would be overly interested in doing.

What is the minimal docker version? I have 1.13.1.

**Comment by PetrHeinz** [comment]
@mbohal: According to the [docs](https://docs.docker.com/develop/develop-images/multistage-build/), multi-stage builds are supported in **Docker 17.05** or higher.

**Comment by PetrHeinz** [comment]
I've added mention of this to the installation guide and our troubleshooting sections so other users don't encounter the same problem, hope it'll help :slightly_smiling_face:

**Comment by mbohal** [comment]
Thanks for quick reactions.

I know I can install direct from external Docker repo, but when possible I just prefer to use packages from my distro repo. In my experience the packages from external repos sometimes break, especially after upgrading my system to a newer version (Dropbox and Slack I'm looking at you).

I guess this issue can be closed now. Ill either use some other docker image or spin up a VM with more up to date docker for testing purposes.

Is there any chance you will give up on the multistage build functionality and make it more portable? It might be years before docker 17.05 makes it to the majority of the mainstream distros.

**Comment by PetrHeinz** [comment]
Using a multistage build gives us more flexibility and it's generally considered a best practice in Docker so personally, I'd like to continue using it. You're right about the portability problems, though.

I guess that if there is a pressure from the community to support an older versions of Docker as well, we might maintain a separate Dockerfile for the `dev` environment. But it would mean maintaining an extra Dockerfile and continuously testing it...

Alternatively, we could provide a short guide on how to alter the `Dockerfile` and remove the other stages than `development` yourself.

---

It should suffice to remove the `as base` part from the first line, `FROM base as development` line and the stages `ci` and `production` - so the rest of the file under `FROM base as production`. Then remove the `target: development` from your `docker-compose.yml`.

Diff of `Dockerfile` for clarification:

```diff
-FROM php:7.2-fpm-stretch as base
+FROM php:7.2-fpm-stretch
 
 ARG project_root=.
 ENV REDIS_PREFIX=''
```

```diff
 # set COMPOSER_MEMORY_LIMIT to -1 (i.e. unlimited - this is a hotfix until https://github.com/shopsys/shopsys/issues/634 is solved)
 ENV COMPOSER_MEMORY_LIMIT=-1
 
-########################################################################################################################
-
-FROM base as development
-
 USER root
 
 # allow overwriting UID and GID o the user "www-data" to help solve issues with permissions in mounted volumes
```

```diff
 RUN chown -R www-data:www-data /home/www-data /var/www/html
 
 USER www-data
-
-########################################################################################################################
-
-FROM base as production
-
-COPY --chown=www-data:www-data / /var/www/html
-
-RUN composer install --optimize-autoloader --no-interaction --no-progress --no-dev
-
-RUN php phing composer npm dirs-create assets
-
-########################################################################################################################
-
-FROM base as ci
-
-COPY --chown=www-data:www-data / /var/www/html
-
-RUN composer install --optimize-autoloader --no-interaction --no-progress --dev
-
-RUN php phing composer-dev npm dirs-create test-dirs-create assets standards tests-static tests-acceptance-build
-
-RUN ./bin/console shopsys:environment:change prod
 ```

The resulting Docker image **should** behave the same - maybe it's worth trying if you want to avoid upgrading your Docker.

**Comment by mbohal** [comment]
This works! Thanks a bunch.

Another way to get the same advantages of multistage builds is not to commit Dockerfiles to the app, but to use pre-build images hosted on docker hub. The images can depend on each other so you do not have to maintain multiple versions of Dockerfiles.

Also there is the added benefit that users don't have to wait 20 minutes for the containers to build.  For this reason alone I personally prefer the arrangement.

**Comment by mbohal** [comment]
yes it is resolved
