### ISSUE TITLE
403 when trying to logout after my session expires

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#769]
Reported by @stanoMilan 
### What is happening
I am logged customer on FE. When my session expires (can be reproduced manually by deleting the `PHPSESSID` cookie), I am logged out automatically in the background. Then, when I click on "Logout" (without refreshing the page before), I get an error - "403 - invalid CSRF token".

Notes: 
* probably connected to #315 
* @stanoMilan has some information about a fix that was already done on one of our internal projects.

### Expected result

I (as a logged customer) do not see any error when trying to logout. The fact, that I was logged out automatically before should not cause the application to crash.

**Comment by pk16011990** [comment]
#315 doesn't solve this problem

**Comment by pk16011990** [comment]
.

**Comment by pesektomas** [comment]
I thought about this issue when I was removing the subsrition form from the error pages. There it was de facto the same thing - a form was generated once in a long time with one csfr token, which, of course, soon expired.

I thought about creating a new token request before submitting the form (or logout clicking), but I'm not entirely sure if this is the best solution. What do you guys think? Is it a completely bad idea?

**Comment by grossmannmartin** [comment]
I'm not sure. Isn't this reverting the point of CSRF? Can I include such form in my malicious website and force a user to log out? 
From what I understand, the problem occurs when my session expires and I try to log out. 
(which could be a much bigger problem if #1842 will be merged)

If I open a website and after several hours of inactivity I click to logout button, this error does not occur, or?

**Comment by sslt** [comment]
Issue will be closed with release of patch 9.0.1.

**Comment by TomasLudvik** [comment]
Hi, this has been solved in #1909, closing.
