### ISSUE TITLE
autocompletion for phing targets

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#776]
### What is happening

When using phing targets, there is no autocomplete so I have to type everything manually.

I believe the autocompletion would improve DX. There are [some tutorials](https://dzone.com/articles/autocomplete-phing-targets) available, however, I did not test them.

### Expected result

Names of phing targets are autocompleted in the bash terminal. I believe in our `Dockerfile`, we could create a phing file with autocompletion definition in `/etc/bash_completion.d/` so the autocompletion would work out of the box for Docker installations

**Comment by grossmannmartin** [comment]
I really like it, but it will work only if someone will be connected to the container.

**Comment by vitek-rostislav** [comment]
Hi,
> it will work only if someone will be connected to the container.

- this is the natural way I work so I still see it as a great enhancement :slightly_smiling_face:

**Comment by grossmannmartin** [comment]
I know and I think its completely valid 🙂 
I did quick prototyping and this should be really easy.

I thought about a way how to adapt it for people, who run phing outside of a container (= me). 
I'm not sure if it can be done as a copy-paste script for the host, but maybe some gist with a way how to do it by yourself may be nice.

**Comment by pk16011990** [comment]
I use phing outside of the docker container with alias `dphing` -> `docker exec -it shopsys-framework-php-fpm ./phing` and this works great after rename `phing` to `dphing`

Thanks!

**Comment by vitek-rostislav** [comment]
I believe this would be appreciated by many developers, please do not close it, stale-bot!

**Comment by vitek-rostislav** [comment]
I do not want to close this issue, I still think it would be appreciated by many developers

**Comment by TomasLudvik** [comment]
Hello guys, can you provide some code example how did you manage this to work? I would love to implement it, but some info from community would be appreciated.

**Comment by pk16011990** [comment]
Hi, my config file:
```bash
$ cat /etc/bash_completion.d/dphing 
# Store this file in /etc/bash_completion.d/dphing
 
_dphing () {
    local cur prev
 
    COMPREPLY=()
    buildfile=build.xml
    _get_comp_words_by_ref cur prev
 
    [ ! -f $buildfile ] && return 0

    COMPREPLY=( $( compgen -W "$( dphing -l | tr -s '\-' | sed s/^-/\|/ | tr -d '\|' \
        | sed s/\ \ .*\// \
        | sed s/Buildfile.*// | sed s/Default\ target:// | sed s/Subtargets:// \
        | sed s/Main\ targets:// \
        | tr -s ' ' \
        | sed 's/[^[:print:]]//g' | sed s/\\[.*// | tr '\n' ' ' | tr -s '\n' 2>/dev/null )" \
        -- "$cur" ) )
}
 
complete -F _dphing dphing
```

**Comment by pk16011990** [comment]
and `dphing`  is my alias. all my aliases:
```
alias dcup='docker-compose up -d --build'
alias dcdown='docker-compose down'
dssh() {
    docker exec -it ${1:-shopsys-framework-php-fpm} sh
}
dbash() {
    docker exec -it ${1:-shopsys-framework-php-fpm} bash
}
dlog() {
    docker logs ${1:-shopsys-framework-php-fpm}
}
html() {
    if [ -z "$1" ]; then
        cd /var/www/html/
    else
        cd /var/www/html/$(ls /var/www/html | grep "$1")
    fi
}
alias dclog='docker-compose logs'
alias dclean='docker kill $(docker ps -q) && docker rm $(docker ps -a -q)'
alias dkill='docker kill $(docker ps -q)'
alias drm='docker rm $(docker ps -a -q)'
alias drmi='docker rmi $(docker images -q)'
alias dexec='docker exec -it shopsys-framework-php-fpm'
alias dphing='docker exec -it shopsys-framework-php-fpm ./phing'
alias dphp='docker exec -it shopsys-framework-php-fpm php'
```

**Comment by grossmannmartin** [comment]
Thanks! 

For the implementation, I suggest two things.

1. Add the auto-completion into a docker container when someone works inside the container (that would be useful when you need to run some target on CI or devel/prod server or work in a container on your local machine). 
2. Add instructions into the documentation – how to make autocompletion work from a host machine. Something like  @pk16011990 is using. But that's OS-dependent. For example on Mac you may need to install some additional tools, plus you can have bash with a similar configuration, but newer versions of MacOS use ZSH by default, where autocompletion is done differently).
