### ISSUE TITLE
How to asure functionality of install documentation and install.sh file

### ISSUE THREAD

**Issue by MattCzerner** [shopsys/shopsys#778]
### What is happening
In #759, installation script was created, that means that we got 2 sources from which can be project installed, which can lead to one of them not working.

### Expected result
We need to decide how to keep them working all the time, I think we got couple of options to go:

1) Delete the documentation and move comments from documenations into comments of the shell script. This will lower the readability of the installation documentation but will asure that manual is executable shell script.

2) Releaser will somehow check if there was changes done in *install.sh* or *install*.md` document and inform about that human.

**Comment by PetrHeinz** [comment]
I would wait for a while to see some feedback on the script. Installation guide has some info about the technology stack (eg. explains working with containers) and we wouldn't want to have this info removed imo.

**Comment by boris-brtan** [comment]
#908

**Comment by PetrHeinz** [comment]
This was partly covered by #1342
