### ISSUE TITLE
Composer /vendor/ folder missing

### ISSUE THREAD

**Issue by cafesk8** [shopsys/shopsys#785]
Hello, I installed shopsys/project-base via docker and everything went fine until i tried to setup the application. I connected to the docker terminal with no problem, but when I run "composer install" it ends with this error:

`Package operations: 173 installs, 0 updates, 0 removals
[RuntimeException]  /var/www/html/vendor does not exist and could not be created.`

So in the next step when I try and run 

` php phing db-create` 

it says:

```
Error: /var/www/html/vendor/phing/phing/bin/phing.php not found.
Please run: composer install

```
I'm running:
Linux f15c21291026 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
Docker:

**Comment by boris-brtan** [comment]
Hi, i have one guess.
can you check result of `id` command?
![image](https://user-images.githubusercontent.com/39240194/52134804-b488b300-2644-11e9-90c7-773d1076fdff.png)

**Comment by PetrHeinz** [comment]
Hello @cafesk8,

thanks for providing enough information in your report :+1: You might have misconfigured UID and GID of your container as @boris-brtan suggests.

If it's so, the [step 3. in the installation guide](https://github.com/shopsys/shopsys/blob/v7.0.0-beta5/docs/installation/installation-using-docker-linux.md#3-set-the-uid-and-gid-to-allow-file-access-in-mounted-volumes) should help you.

**Comment by vitek-rostislav** [comment]
Hi, I believe this has been resolved in our slack - https://shopsysframework.slack.com/archives/CD4FJ05T5/p1549019161035100.

**Comment by boris-brtan** [comment]
could this be then closed as resolved?

**Comment by cafesk8** [comment]
Yes, you can close it. If anyone would be interested, I managed to get it up and running by omitting the --no-install parameter in original project-base installation.
