### ISSUE TITLE
Unexpected behavior of changing basic front-end currency on a domain

### ISSUE THREAD

**Issue by PetrHeinz** [shopsys/shopsys#791]
During prototyping of #745 we have found an unexpected behavior which may lead to an unpleasant surprise when encountered in production environment.

### What is happening
When changing a basic frontend currency on a domain in administration, the product prices are not recalculated or changed in any way. They remain the same, but in a different currency. This may happen without superadmin permission and without any warning or prompt.

**1. Front-end with CZK prices** (without any changes to demo data):
![image](https://user-images.githubusercontent.com/10008612/52273553-82c86280-294a-11e9-95dc-6f88b96d7252.png)

**2. Adminsitration -> Pricing -> Currencies** (without any changes to demo data):
![image](https://user-images.githubusercontent.com/10008612/52273609-a9869900-294a-11e9-868a-7be94f472c84.png)

**3. As an admin, I change the basic frontend currency on the first domain** (from CZK to EUR):
![image](https://user-images.githubusercontent.com/10008612/52273671-d175fc80-294a-11e9-985a-6c6b0432fd89.png)

**4. As a customer, now I can see the same prices as before, but in a different currency** (without any recalculation, which means that all products are ~25&times; more expensive):
![image](https://user-images.githubusercontent.com/10008612/52273731-f8ccc980-294a-11e9-9508-b71a1a70456b.png)

This issue might have gone unnoticed because automatic price type was a default value for products  before #595 was merged. Automatic product pricing did not suffer from this problem by being recalculated by the currency exchange rate.

### Expected result

The scenario above is either impossible or it's much more obvious that this is what will happen. I can think of some possible solutions:

- only a superadmin can make such a change
- this setting is moved to `domains.yml` instead of being editable in administration
- there is a *Are you really sure about this?* type of prompt (similar to removing a currency)
- all product prices for pricing groups on the edited domain are immediately recalculated using the currencies' exchange rates

As a side note, implementing the Money type as described in #745 might be a robust way to avoid similar situations in the future.

**Comment by grossmannmartin** [comment]
It makes the most sense to me that this change could be made only by superadmin.
Settings moved to domains.yml looks a bit odd because currencies are in admin and default currency will suddenly be elsewhere.

**Comment by PetrHeinz** [comment]
@grossmannmartin Well, imagine we would had the basic front-end currencies for domains in `domains.yml` and the default currency in administration set similarly as locale is set in #806. Then, it would make sense to either rename the *Pricing > Currencies* agenda to *Pricing > Exchange rates* (considering the `Currency` entity holds only code - which is ISO 4217, name - which is used only in administration, and the exchange rate). Alternatively, it could make sense to get rid of the admin page altogether considering that the exchange rate is in fact never used (since #585).

In  fact, the `Currency` not being an entity but a value object instead (holding just the currency code) might help us to implement the Money type as described in #745. But that's just my train of thought about possible long-term changes, that would support moving the setting to `domains.yml`.

**Comment by PetrHeinz** [comment]
On the other hand, having the *Pricing > Currencies* having accessible only by a superadmin would be very easy to implement, and it help a lot reducing the risk of problems. Maybe it's a great first step.

**Comment by henzigo** [comment]
ping

**Comment by PetrHeinz** [comment]
@LukasHeinz - Can we at least change this administration agenda to superadmin-only? Maybe with a note that the prices will not be recalculated after change of currency on a domain? It will avoid most problems at a pretty low cost in terms of effort or backward-compatibility.

**Comment by LukasHeinz** [comment]
We will move domain currency setting to superadmin section.

**Comment by LukasHeinz** [comment]
It is not complicated and can prevent big problems. Please fix it

**Comment by pk16011990** [comment]
remove stale label... Please accept #1338...

**Comment by sslt** [comment]
Issue will be closed with release of patch 9.0.1 next week.

**Comment by s3tezsky** [comment]
Solved in mentioned PR
