### ISSUE TITLE
Provide more information about current version in installation guide

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#794]
### What is happening
From time to time, we perform BC breaking changes in our installation guides, even though we have a process that should ensure avoiding this.
See e.g. https://github.com/shopsys/shopsys/pull/737

And now once again, in the installation guide, I see an instruction to run
```
./scripts/install.sh
```
however, this is not released yet so I am not able to do that when installing `project-base` from the last beta version (`beta5`) :disappointed: 

### Expected result
As our process with writing TODO comments in the documentation does not work properly, I suggest adding a simple note to the beginning of each installation guide, that would say: "Beware, you are viewing installation guide for the current master. Installation guide for the last release might be more relevant for you." where "Installation guide for the last release" would be a link to the last released version of the guide. This could be modified automatically during the release process. I do not insist on this particular words, however, the idea is clear IMHO.

**Comment by grossmannmartin** [comment]
I suggest taking a look at documentation generator (for example https://www.mkdocs.org) and have documentation on a website with version switcher (and maybe a warning about actual version) as Symfony or Doctrine has. 

In this way, we won't be forced to maintain this type of todo comments (= change on release).

**Comment by vitek-rostislav** [comment]
Hi @grossmannmartin, thanks for your comment, I do agree with you, however, users have these problems already and transfer to some documentation generator seems quite complicated to me. I am looking for a quick solution now :slightly_smiling_face:

**Comment by simara-svatopluk** [comment]
I see your point and I think it will became even more relevant after stable release. But in that time, the solution could be a bit different

**Comment by PetrHeinz** [comment]
We could maintain some sort of note about current version in specific articles (probably index and installation guides) with the help of Releaser.

Eg.:

> *This documentation article is for version which is not released yet. See the [version for `v7.0.0-beta4`](https://github.com/shopsys/shopsys/blob/v7.0.0-beta4/docs/index.md).*

during release it would be replaced with something like this:

> *This documentation article is for version `v7.0.0-beta5`. Switch to another tag to see other versions.*

and after release, reverted back using the incremented version number
