### ISSUE TITLE
non-specific docker image version causes breaks like with php=7.2.14 in beta4

### ISSUE THREAD

**Issue by boris-brtan** [shopsys/shopsys#797]
### What is happening

Beta4 with alpine image `php:7.2-fpm-alpine` is broken on some php extension packages when during `tests-acceptance` phing target the process fails on
```
Codeception PHP Testing Framework v2.5.3
Powered by PHPUnit 7.5.3 by Sebastian Bergmann and contributors.
Running with seed:


In PostgreSql.php line 115:

  SQLSTATE[42P06]: Duplicate schema: 7 ERROR:  schema "public" already exists
``` 
there is this extension:
```
pdo_pgsql
PDO Driver for PostgreSQL => enabled
PostgreSQL(libpq) Version => 11.1
Module version => 7.2.14
```
with 7.2.13 and this extension it seems to work
```
pdo_pgsql
PDO Driver for PostgreSQL => enabled
PostgreSQL(libpq) Version => 10.5
Module version => 7.2.13
```

### Expected result

to use specific versions in `Dockerfiles` like `FROM php:7.2.13-fpm-alpine as base` or `FROM php:7.2.14-fpm-stretch as base`

**Comment by boris-brtan** [comment]
also there is problem with maintanence when one side would not know about the other side.
Example:
on CI or with developer PC will be with tag php:7.2-fpm-alpine downloaded version php:7.2.13-fpm-alpine and this will be cached for about 2-3 weeks after release of 14 15 16 someone new will pull php:7.2-fpm-alpine and it will be php:7.2.16-fpm-alpine and something will be corrupted. Automatically that person will create issue but some developer try it on own PC and on CI and the result could be wrong answer to the author of the issue.

**Comment by PetrHeinz** [comment]
Not sure whether I'd recommend depending on a specific patch version, it may be hard to maintain...

**Comment by boris-brtan** [comment]
if we decide to use not specific versions and remove pulled images then we could try to improve build speed
for instance:
https://github.com/ilikenwf/apt-fast/
`docker-php-ext-install -j$(nproc)`
.....
....
...

**Comment by simara-svatopluk** [comment]
I have only suggestions
* if we want to be perfectly stable, we should use patch versions - less things to break
* if we want to be progressive, we shouldn't use patch versions - more things can break, but latest

Since the `Dockerfile` is in `project-base`, the final decision is always by implementation team. So this decision (progressive/stable) only affect us.

**Comment by boris-brtan** [comment]
perfectly stable is the solution
