### ISSUE TITLE
problem with install by docker - SQL error

### ISSUE THREAD

**Issue by jan-oliva** [shopsys/shopsys#810]
### install  v7.0.0-beta5

install by instructions from:
installation-using-docker-linux.md
installation-using-docker-application-setup.md

Docker version 17.09.1-ce, build f4ffd2511ce9
docker-compose version 1.17.0

### After install v7.0.0-beta5

On 127.0.0.1:8000 shown SQL error

`
Doctrine\DBAL\Exception\TableNotFoundException
An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.link AS link_3, t0.domain_id AS domain_id_4, t0.position AS position_5, t0.hidden AS hidden_6 FROM slider_items t0 WHERE t0.domain_id = ? AND t0.hidden = ?' with params [1, 0]:
SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "slider_items" does not exist
LINE 1: ...osition AS position_5, t0.hidden AS hidden_6 FROM slider_ite...
`
Probably problem with doctrine migrations. Command bin-console orm:check  tell db schema is not sync, but migrations:migrate riase SQL errors.

**Comment by PetrHeinz** [comment]
Hello @jan-oliva, thanks for reporting, did you build the application using the command `php phing build-demo-dev` inside of the `php-fpm` container? Did it finish OK?

We use some customized functionality around Doctrine migration you can read about in [the docs](https://github.com/shopsys/shopsys/blob/master/docs/introduction/database-migrations.md).

I would try rebuilding the database using `docker-compose exec php-fpm ./phing db-demo`, that should recreate the whole DB, run all migrations and fill it with data from fixtures.

**Comment by jan-oliva** [comment]
I tried it one more time and installed instance running OK. I used  `docker-compose build --force-rm --no-cache` to complete rebuild container after new git clone.

We can close this issue.

Thanks
