### ISSUE TITLE
Installing ocramius/package-versions failed

### ISSUE THREAD

**Issue by pabloneruda1** [shopsys/shopsys#812]
After 

`./scripts/install.sh`

i have following errors:

`Loading composer repositories with package information`
`Updating dependencies (including require-dev)`
`Package operations: 172 installs, 0 updates, 0 removals`
`- Installing ocramius/package-versions (1.3.0): Loading from cache`
`Failed to execute unzip -qq  '/var/www/html/vendor/ocramius/package-versions/cfd9e1f12060246b1808bcf5322f3074' -d '/var/www/html/vendor/composer/9c1431bf'`

`[/var/www/html/vendor/ocramius/package-versions/cfd9e1f12060246b1808bcf5322f3074]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /var/www/html/vendor/ocramius/package-versions/cfd9e1f12060246b1808bcf5322f3074 or
        /var/www/html/vendor/ocramius/package-versions/cfd9e1f12060246b1808bcf5322f3074.zip, and cannot find /var/www/html/vendor/ocramius/package-versions/cfd9e1f12060246b1808bcf5322f3074.ZIP, period.`

    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class
`Plugin installation failed, rolling back`
`- Removing ocramius/package-versions (1.3.0)`

`[UnexpectedValueException]`
`Plugin ocramius/package-versions could not be initialized, class not found: PackageVersions\Installer`

Virtual server on VirtualBox 5.2.26 with Ubuntu 18.04

**Comment by vitek-rostislav** [comment]
Hi, could you please provide more info about your use case? I see you are running the `./scripts/install.sh` script that is not released yet, so are you installing a master of the whole `shopsys/shopsys` monorepo?

**Comment by litecart-cs** [comment]
First I followed the instructions here:
https://github.com/shopsys/shopsys/blob/master/docs/installation/installation-using-docker-linux.md
and here:
https://github.com/shopsys/shopsys/blob/master/docs/installation/installation-using-docker-application-setup.md

but after
`composer install`
installation always freezes without any error  - the same
`composer install -v`

So I used install.sh from monorepo with this error...

**Comment by vitek-rostislav** [comment]
> First I followed the instructions here:
[/docs/installation/installation-using-docker-linux.md@`master`](https://github.com/shopsys/shopsys/blob/master/docs/installation/installation-using-docker-linux.md)
and here:
[/docs/installation/installation-using-docker-application-setup.md@`master`](https://github.com/shopsys/shopsys/blob/master/docs/installation/installation-using-docker-application-setup.md)
but after
`composer install`
installation always freezes without any error - the same
`composer install -v`
So I used install.sh from monorepo with this error...

Hi @litecart-cs, TBH, I am a little bit confused now - is your comment related to the original issue? Are you the same person as @pabloneruda1? :slightly_smiling_face: 

@litecart-cs, it seems that you are using Docker on Windows - in such a case,  composer can freeze this way when you have unsufficient memory usage set (see the installation guide, section "Requirements" - https://github.com/shopsys/shopsys/blob/master/docs/installation/installation-using-docker-windows-10-pro-higher.md#requirements)
