### ISSUE TITLE
Use phpstan-doctrine

### ISSUE THREAD

**Issue by simara-svatopluk** [shopsys/shopsys#820]
Use https://github.com/phpstan/phpstan-doctrine to check doctrine-related problems. 

There is hopefully no trouble right now, but it is a step towards safer code.

**Comment by henzigo** [comment]
Probably this will be solved by #1040

**Comment by simara-svatopluk** [comment]
It won't. phpstan level 4 include rules for common php code. This suggested package checks doctrine-related problems, like `DQL`, `QueryBuilder` and more

**Comment by boris-brtan** [comment]
it was added as a part of lvl3 commit https://github.com/shopsys/shopsys/pull/1040/commits/c78de45f654c5671d903c988f47862eb9f320017#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R151

**Comment by simara-svatopluk** [comment]
you both are right, I edited the #1040 description so it closes this issue
