### ISSUE TITLE
Registration - E-mail tooltip 

### ISSUE THREAD

**Issue by PetraPiprekova** [shopsys/shopsys#832]
Front-end - Registration - E-mail - tooltip

### What is happening
If a user enters an already registered e-mail, the e-mail in the tooltip is not visible.
![tooltip](https://user-images.githubusercontent.com/43062403/52853302-81055880-311b-11e9-99c7-ddbf9fc7370f.jpg)

### Expected result
Make a flexible tooltip.

**Comment by boris-brtan** [comment]
is this flexible ?
![image](https://user-images.githubusercontent.com/39240194/53071726-62b8a780-34e3-11e9-9091-bcc96d14de7f.png)

**Comment by PetraPiprekova** [comment]
I think the email should be in one line.

**Comment by boris-brtan** [comment]
so maybe it does make sense to change it into `This email is already registered`

**Comment by PetraPiprekova** [comment]
It looks like a good solution.

**Comment by boris-brtan** [comment]
already merged
