### ISSUE TITLE
Native install - SQLSTATE[42883]: Undefined function: 7 ERROR:  function pg_catalog.unaccent(unknown, text) does not exist

### ISSUE THREAD

**Issue by jan-oliva** [shopsys/shopsys#834]
### php phing build-demo-dev

this command genrate error message

```
Migration 20180603135339 was executed but did not result in any SQL statements.

  ++ migrated (0.23s)

  ++ migrating 20180603135340

Migration 20180603135340 failed during Execution. Error An exception occurred while executing 'CREATE OR REPLACE FUNCTION immutable_unaccent(text)
            RETURNS text AS
            $$
            SELECT pg_catalog.unaccent('pg_catalog.unaccent', $1)
            $$
            LANGUAGE SQL IMMUTABLE':


SQLSTATE[42883]: Undefined function: 7 ERROR:  function pg_catalog.unaccent(unknown, text) does not exist
LINE 4:             SELECT pg_catalog.unaccent('pg_catalog.unaccent'...
                           ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

In MigrateCommand.php line 69:
```

Using postgresql version 10.6

**Comment by PetrHeinz** [comment]
Hello, it might help to recreate the `unaccent` extension and collations with the `./phing db-create` (and `./phing test-db-demo` for the test DB). See [docs of the `db-create` Phing target](https://github.com/shopsys/shopsys/blob/v7.0.0-beta5/docs/introduction/console-commands-for-application-management-phing-targets.md#db-create) for details.

**Comment by grossmannmartin** [comment]
Hello @jan-oliva, I had the same problem.
I had to create root user for postgre with `sudo -u postgres createuser --createdb --superuser --pwprompt root` and use this user to connect to database from application.

Please let us know if some advice helped you.

**Comment by TomasLudvik** [comment]
Hey guys @PetrHeinz and @grossmannmartin,

are we able to create some better exception with text, try to run php phing db-create test-db-create to solve this problem?

**Comment by PetrHeinz** [comment]
@TomasLudvik We're not even sure whether the command helped or not.

**Comment by TomasLudvik** [comment]
@PetrHeinz I know, but I have encountered this error many times and that command was solution for me and even on our public Slack there were some questions about it and command helped.
