### ISSUE TITLE
sniff for proper usage of variables in string

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#839]
### What is happening
AFAIK, we have never used variables in strings in this manner:
```
"Some string {$someVariable}..."
```

However, there is no sniff nor written rule for that. The same applies to other ways of using variables in string, such as simple concatenation, is it ok? I would prefer using `sprintf()` method only.

### Expected result
Consensus on the way how we use variables in strings and automatic sniff (or even a fixer) for that :slightly_smiling_face:

**Comment by boris-brtan** [comment]
maybe we need to check first why the new shopsys/coding-standards allows such use. maybe it became a standard.

**Comment by pk16011990** [comment]
it would be good standard...

**Comment by pk16011990** [comment]
.
