### ISSUE TITLE
Need to rebuild image on next deploys can be missed easily in production installation guide

### ISSUE THREAD

**Issue by grossmannmartin** [shopsys/shopsys#841]
Based on feedback from users. 

Section *Next deploys* in production installation guide contains instructions on how to perform deploy of changes to production (https://github.com/shopsys/shopsys/blob/master/docs/installation/installation-using-docker-on-production-server.md#next-deploys)

### What is happening
One of the essentials steps is the need to rebuild the image, but information about this step can be easily missed as it is part of the larger paragraph with not so pressing information.

![snimek obrazovky 2019-02-18 v 13 24 19](https://user-images.githubusercontent.com/1177414/52950839-a0e98600-3380-11e9-930c-afaee12578ae.png)

Users tend to run highlighted commands only and in this case, their changes in code are not propagated into a new container.

### Expected result
Users (especially those not so familiar with docker principles) should be fully aware of what they have to do to perform smooth next deploys.

**Comment by simara-svatopluk** [comment]
The solution could be a general form of highlight that we'll use for important instructions that are easy to miss.

**Comment by TomasLudvik** [comment]
It would be nice to add some code block.

**Comment by henzigo** [comment]
ping

**Comment by grossmannmartin** [comment]
The documentation site (https://docs.shopsys.com) uses admonitions to emphasize important or interesting statements (see more https://docs.shopsys.com/en/8.0/contributing/guidelines-for-writing-documentation/)

This is already highlighted https://docs.shopsys.com/en/8.0/installation/installation-using-docker-on-production-server/

![Snímek obrazovky 2020-01-15 v 17 20 14](https://user-images.githubusercontent.com/1177414/72451043-a1bab000-37bb-11ea-8bcb-ca32e812785e.png)

Closing
