### ISSUE TITLE
Remove "rounding to 50 cents functionality"

### ISSUE THREAD

**Issue by simara-svatopluk** [shopsys/shopsys#847]
### What is happening
I think that the rouding to 50 cents functionality is in the SSFW for historical reasons - in days that there where still 50 hellers in Czech. I would vote for removing the functionality if it is not used anymore.

### Expected result
Remove or explain where it is used.

**Comment by pk16011990** [comment]
@LukasHeinz what do you think about it? Can I do PR?

**Comment by henzigo** [comment]
.

**Comment by s3tezsky** [comment]
We are able to configure this in administration thanks to #1487
