### ISSUE TITLE
Shippings ang payments - image

### ISSUE THREAD

**Issue by PetraPiprekova** [shopsys/shopsys#849]
Administration -> Shippings and payments

### What is happening
The uploaded image can't be deleted.

### Expected result
Please fix it.

**Comment by boris-brtan** [comment]
this seems like behavior of the single image entities. Should it be also fixed for product categories, flags, ... ?

**Comment by PatrikBajer** [comment]
Yep, prefer to change all single image entities.

**Comment by PatrikBajer** [comment]
> this seems like behavior of the single image entities. Should it be also fixed for product categories, brands, languages, ... ?

Yep, prefer to change all single image entities.

**Comment by PetrHeinz** [comment]
This is duplicate with *US-2629* from our internal backlog. Oddly it is marked as *In Progress* with @vitek-rostislav assigned. Any info?

**Comment by vitek-rostislav** [comment]
Well, it was 20 months ago :laughing: But if I remember correctly, I worked on that with @TomasLudvik, we wanted to extend the `ImageUpload` component and we wanted to generalize it to work with files as well, however, we failed to deliver it in reasonable time and the user story was scratched then...

**Comment by PatrikBajer** [comment]
Any progress here?

**Comment by vitek-rostislav** [comment]
Hi @PatrikBajer, no progress so far...It seems to me that this is a "not-so-important" feature request and there are lots of more important things to do. However, If you have a different feeling, please let me know :wink:

**Comment by pk16011990** [comment]
.

**Comment by henzigo** [comment]
Maybe this is already fixed in 9.0-dev. Can you check it? @grossmannmartin

**Comment by grossmannmartin** [comment]
Thanks! You're right it was actually solved by #1531 – thanks @TomasLudvik!
Closing.
