### ISSUE TITLE
Feed: calculatedSellingDenied vs sellingDenied 

### ISSUE THREAD

**Issue by Miroslav-Stopka** [shopsys/shopsys#855]
Hi,

I probably found a bug in feeds exports :(

### What is happening

1. There exist two attributes with information about denial from sales - calculatedSellingDenied and sellingDenied.

2. SellingDenied is configurable in administration and I think, this attribute itself has not some direct impact on products visibility or offerability. The important one is calculatedSellingDenied, this attribute is based on several conditions and if this conditions are not met, this attribute is based on sellingDenied.

3. Offerability of product is based on calculatedSellingDenied. This means product can be set as sellingDenied=TRUE and this product can be still offerable=buyable. And from the other site, this means product can be set as sellingDenied=FALSE and this product still **does not have to be** offerable=buyable

4. Frontend of framework uses calculatedSellingDenied - **this is correct state**

5. Export of products into feeds checks sellingDenied - **this is incorrect state**

### Expected result
Feeds exports checks calculatedSellingDenied instead of sellingDenied

Thank you :)

**Comment by simara-svatopluk** [comment]
@Miroslav-Stopka may I ask you for CR of #889 ?

**Comment by Miroslav-Stopka** [comment]
Hi @simara-svatopluk,

I do not have much free time for answering immediately :( Looks like you've already solved it 👍 

Thank you
