### ISSUE TITLE
Expand selectbox with categories for Heureka.cz product feed

### ISSUE THREAD

**Issue by PetraPiprekova** [shopsys/shopsys#862]
Administration -> Categories -> Heureka.cz product feed (selectbox)

### What is happening
Full name of category isn't displayed in the selectbox.

### Expected result
Please expand the selectbox.

**Comment by vitek-rostislav** [comment]
Hi, could you please provide a screenshot? :slightly_smiling_face:

**Comment by PetraPiprekova** [comment]
Sure, here it is.
![image](https://user-images.githubusercontent.com/43062403/53569235-0816ef80-3b64-11e9-9d94-4a6881769784.png)
