### ISSUE TITLE
BC promise is lacking section about dependencies

### ISSUE THREAD

**Issue by PetrHeinz** [shopsys/shopsys#872]
### What is happening

Our [BC promise](https://github.com/shopsys/shopsys/blob/v7.0.0-beta6/docs/contributing/backward-compatibility-promise.md) is currently lacking sections about dependencies (Composer and NPM), which might be useful to address.

### Expected result

Backward compatibility of dependencies and reasonable expectations about it is explained in our BC promise in similar fashion and scope as other subsections of *The BC Promise in Detail*.

**Comment by boris-brtan** [comment]
could be good to solve this problem on this commit https://github.com/shopsys/shopsys/pull/978/commits/f94aef8723d02ed45f69b5b071b76e9cbe915391

**Comment by PetrHeinz** [comment]
I've separated the question of Phing targets into its own issue #1012
