### ISSUE TITLE
Accented e-mail is incorrectly converted 

### ISSUE THREAD

**Issue by PetraPiprekova** [shopsys/shopsys#896]
### What is happening
I can register/finish the order with e-mail petra@žíčýřžščýřž.cz
Then the e-mail is converted to the form petra@xn--1caaa5at7gbc63fda9fde.cz

@patrikbajer reported, that they fix it like text, but disadvantage is that keyboard for e-mail doesn´t show on mobile phone.

Can we fix it?

**Comment by boris-brtan** [comment]
seems like it is behavior of all webkit browsers...it converts input value into IDNA ASCII form
gecko browser like FF sends original mail value

**Comment by PetrHeinz** [comment]
@PetraPiprekova Is it really wrong behavior? If so, please suggest how should it behave and why. Thanks.

**Comment by PatrikBajer** [comment]
Just imagine situation. Customer make order with that email adress patrik.bajer@ččšěčěšč.com - after that customer send that order. System edit that email to patrik.bajer@xn--beaaaaa6fb17cd.com.

Frontend order -> http://prntscr.com/nwuamu - We can see email - **patrik.bajer@xn--beaaaaa6fb17cd.com**

Administration order -> http://prntscr.com/nwuasw - We can see email - **patrik.bajer@čččšěčěšč.com**

Database order -> We can see email - **patrik.bajer@xn--beaaaaa6fb17cd.com**

Problem is - If I can use email patrik.bajer@ččšěčěšč.com, I want that email in Database/IS etc.. 

It's same like if I set name "Patrik" and system convert it to "abpsdf-k" = there is some problem. (I used the "name" like as an exmaple, but it's same like email problem)

**Comment by LukasHeinz** [comment]
Nowadays in an email address you can use all Unicode characters. This is theory by standards. In reality, a lot of servers cannot work with Unicode characters. Therefore it is resolved by [translating it to ASCII](https://en.wikipedia.org/wiki/International_email#Interoperability_via_downgrading).

So generally there should not be restrictions on used characters. On the other hand, the usage of such characters in most cases indicates that the user did a mistake and e-mail will not be delivered.

The question is - do we want to allow users to use Unicode? 

Option 1) We disable the usage of Unicode.

Option 2) We allow usage of Unicode and keep in the database the Unicode version of email address but when it is used to really send an email, it will be translated do ASCII version (the ASCII version ill be served only to the SMTP server, and not users)
