### ISSUE TITLE
Image of brand overlaps the name

### ISSUE THREAD

**Issue by PetraPiprekova** [shopsys/shopsys#897]
### What is happening
When the name of the brand is too long, the image of brand overlaps the name.

Can we fix it?

Reported by @patrikbajer 

![image](https://user-images.githubusercontent.com/43062403/54685384-f7301d00-4b16-11e9-9cbd-0ecd1aee5d43.png)

**Comment by PatrikBajer** [comment]
Any update?

**Comment by vitek-rostislav** [comment]
Hi @PatrikBajer, sadly, no progress so far.

**Comment by LukasHeinz** [comment]
There should be at least two lines reserved for brand name...

**Comment by TomasGottvald** [comment]
This issue is solved by #1371 - Closing.
