### ISSUE TITLE
Brand overview URL

### ISSUE THREAD

**Issue by PetraPiprekova** [shopsys/shopsys#898]
### What is happening
Brand overview page is called "Brand overview" but URL of this page has format eshopurl.com/brands-list. Why?

Repotred by @patrikbajer

**Comment by PetrHeinz** [comment]
The title was changed to "Brand overview" for better user experience, but routes and controller actions were never renamed. The terminology could use a bit more consistency, but changing route names, class names, controller actions etc. would break backward compatibility.

How should we tackle this problem? Is it actually confusing or was the question just out of sheer curiosity?

**Comment by PatrikBajer** [comment]
It's confusing for me, but thanks for your response. You can close that issue.
