### ISSUE TITLE
Installation (linux) using install.sh script fails when the user is not in docker group

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#908]
### What is happening
Reported by Adam Tyroň.

When installing the framework on Linux using `./scripts/install.sh`, there is a problem when the user is not in `docker` group (in such a case, `docker-compose` command must be executed with `sudo` privileges) - the whole installation fails with confusing error message.

### Expected result
The script works even in such a situation or the behavior is documented somehow.

**Comment by grossmannmartin** [comment]
Hi @vitek-rostislav,
I prepared a fix in #908, if you're interested.
