### ISSUE TITLE
It is not possible to choose place within shipping method Zasilkovna

### ISSUE THREAD

**Issue by VitMickal** [shopsys/shopsys#911]
### What is happening
There is a issue when trying to choose a place within shipping method Zásilkovna, see attached printscren
![image](https://user-images.githubusercontent.com/46707076/55007259-6312f980-4fdf-11e9-8098-41dd77131c4e.png)

Replication steps:
https://production.shopsys.com -> add product to cart -> open cart -> Continue order -> select Zasilkovna -> choose place 

### Expected result
Customer should be able to choose place within Zasilkovna shipping method and finish the order.

**Comment by vitek-rostislav** [comment]
This issue belongs to another repository - https://github.com/shopsys/demoshop, am I right?

**Comment by vitek-rostislav** [comment]
And it seems it has been fixed already :grin: https://github.com/shopsys/demoshop/issues/41

**Comment by PetrHeinz** [comment]
@vitek-rostislav You're exactly right, I'm closing this issue :slightly_smiling_face:
