### ISSUE TITLE
Error with filesystem while using native installation on Windows

### ISSUE THREAD

**Issue by TomasLudvik** [shopsys/shopsys#913]
### What is happening
When installing application with demodata or uploading image in administration there is error File not found when moving file from local filesystem to abstract one.

![Pasted_image_at_2019-03-27__2_24_PM](https://user-images.githubusercontent.com/5638367/55086111-2101ba80-50a8-11e9-906a-3f42a53addbd.png)

### Expected result
It should work.

**Comment by boris-brtan** [comment]
with the use of `php phing server-run` seems like Local adapter got problem with labels part `C:`
this worked for me
```
    kernel.cache_dir: '/Users/user/Documents/projects/project-base/var/cache/dev/'
    shopsys.root_dir: '/Users/user/Documents/projects/project-base/'
```
the same thing solves the problem with ImageDataFixtures (demodata)
maybe if you can managed to chroot it or you will use apache or nginx with chroot functionality, there will be no need for any change.

**Comment by boris-brtan** [comment]
https://github.com/thephpleague/flysystem/issues/739
