### ISSUE TITLE
Exact versions of dependencies in Dockerfile

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#917]
### What is happening
Reported by @henzigo.

Our Dockerfile allows installing new versions of some dependencies during the build of the image which is error-prone. Our implementation team was not able to install the application thanks to broken version of some dependency. It is fixed now, however, it can happen again anytime :frowning_face: 

### Expected result
- There are exact versions of dependencies defined in Dockerfile so we are sure that no broken library is installed during the application build.
- There is some process that ensures periodical upgrading of the dependencies (if necessary).

**Comment by boris-brtan** [comment]
seems to me like duplicate of #797
