### ISSUE TITLE
There is no documentation about breadcrumb generation

### ISSUE THREAD

**Issue by henzigo** [shopsys/shopsys#919]
### What is happening

I wasn't able to create new page on FE, because i didn't know how to work with breadcrumb. In documentation there isn't any mention how to work with that. 

### Expected result

In documentation should exist instructions how to work with breadcrumb.

**Comment by TomasLudvik** [comment]
I agree with @henzigo and I would like to a

**Comment by PetrHeinz** [comment]
Related to #1090, maybe both can be addressed at the same time...

**Comment by boris-brtan** [comment]
#1176 closes #919 #1090 #1111
https://help.github.com/en/articles/closing-issues-using-keywords
If the commit is in a non-default branch, the issue will remain open and the issue will be referenced with a tooltip.
