### ISSUE TITLE
Problem with parameter filter when not existing parameter value is in URL

### ISSUE THREAD

**Issue by boris-brtan** [shopsys/shopsys#929]
### What is happening

if we pick some options in filter and add into URL some not existing one or some that has been disabled
the whole option group is cleared and the result list is like with no option group checked
`/electronics/?product_filter_form[parameters][1][]=2&product_filter_form[parameters][1][]=14&product_filter_form[parameters][1][]=666`
### Expected result

The not existing filter option should be ignored and filter should applies the existing ones for the result list.
Maybe to have this behavior explained somewhere whether this is really a buggy situation.

**Comment by boris-brtan** [comment]
maybe redirect to the URL with existings one would be GREAT...

**Comment by pk16011990** [comment]
remove stale

**Comment by boris-brtan** [comment]
> remove stale

why? did you or do you still have the same problem ?
