### ISSUE TITLE
Hardcoded language values

### ISSUE THREAD

**Issue by eyeskiller** [shopsys/shopsys#934]
### What is happening

I noticed a really weird approach when we received following error:

```
Shopsys\FrameworkBundle\Model\Localization\Exception\InvalidLocaleException

Locale "ro" is not valid
```
I found this:

_vendor/shopsys/framework/src/Model/Localization/Localization.php_
```PHP
class Localization
{
    const DEFAULT_COLLATION = 'en_US';

    /**
     * @var string[]
     */
    protected $languageNamesByLocale = [
        'cs' => 'Čeština',
        'de' => 'Deutsch',
        'en' => 'English',
        'hu' => 'Magyar',
        'pl' => 'Polski',
        'sk' => 'Slovenčina',
    ];

    /**
     * @var string[]
     */
    protected $collationsByLocale = [
        'cs' => 'cs_CZ',
        'de' => 'de_DE',
        'en' => 'en_US',
        'hu' => 'hu_HU',
        'pl' => 'pl_PL',
        'sk' => 'sk_SK',
    ];
```
Why these values are harcoded and this is not part of some config? It really doesn't make a sense, now. 

### Expected result
Great to have some configuration with language settings, to prevent overriding core libraries.

**Comment by vitek-rostislav** [comment]
resolved by https://github.com/shopsys/shopsys/pull/1004
