### ISSUE TITLE
Scalar typehints without declare strict types

### ISSUE THREAD

**Issue by pk16011990** [shopsys/shopsys#938]
I don't know if this is a mistake or intention, but eg. `Shopsys\ShopBundle\DataFixtures\Demo\UserDataFixtureLoader` contains scalar typehint in method `getCountryByNameAndDomain` but this file does not contain `declare(strict_types=1);`

I am confused, because some files contain it and in my point of view this combination can caused unexpected behaviour.

Files without declare strict types and use scalar type hints cast input/output and It can camouflage some errors without warning. 

### Expected result
In my code is solution strict use of declar strict types, when I want use scalar typehints. Slevomat coding standards can help with this (SlevomatCodingStandard.TypeHints.DeclareStrictTypes)

**Comment by pk16011990** [comment]
It is not stale, this is still the current problem...

**Comment by vitek-rostislav** [comment]
For `project-base` files, this has been already solved in https://github.com/shopsys/shopsys/pull/1256
