### ISSUE TITLE
ProductListFriendlyUrlDataProvider variables mismatch

### ISSUE THREAD

**Issue by roulajan** [shopsys/shopsys#945]
ProductListFriendlyUrlDataProvider

In class **framework/src/Model/Product/ProductListFriendlyUrlDataProvider.php**  line 62 and 63 there is variable mismatch. Variables 'id' and 'name' are switched:

            $friendlyUrlData->name = $data['id'];
            $friendlyUrlData->id = $data['name'];

instead of:

            $friendlyUrlData->id = $data['id'];
            $friendlyUrlData->name = $data['name'];

**Comment by roulajan** [comment]
Same for ProductDetailFriendlyUrlDataProvider

**Comment by vitek-rostislav** [comment]
Hi @roulajan, thanks for reporting, in fact, the problem is in all `FriendlyUrlDataProviderInterface` implementations, I have prepared a fix in #948 :wink:
