### ISSUE TITLE
Unification of filesystem usage

### ISSUE THREAD

**Issue by grossmannmartin** [shopsys/shopsys#950]
In the application, we recommend using the abstract filesystem, but usages are inconsistent.

Mostly we require some implementation of `Flysystem\FilesystemInterface` along with `MountManager` to do some work, even if everything could be done via MountManager

In several classes we still use `Symfony\Filesystem` which can (probably) lead to unexpected results if someone tries to change for example the location of local filesystem. 

This can lead to issues like #686, #805 and #913 

Most weird usage is in `ImageDataFixture` class, where
`$this->localFilesystem` is symfony filesystem
`$this->filesystem` is main or local (?) flysystem
`$this->mountManager` is clear
 
```php
if ($this->localFilesystem->exists($filepath)) {
    $newFilepath = $target . $file->getRelativePathname();

    if ($this->filesystem->has($newFilepath)) {
        $this->filesystem->delete($newFilepath);
    }

    $this->mountManager->copy('local://' . $filepath, 'main://' . $newFilepath);
}
```

### Expected result
After a talk with @MattCzerner and @boris-brtan we suggest to

**Stop using symfony filesystem completely (it is used in approx 32 classes)**

**Local filesystem should have root set to `project-base`, not `/`**

**We should use relative paths only** – see https://github.com/thephpleague/flysystem/issues/739#issuecomment-280773887

**In classes that need to work with images should be used only `MountManager` class**

Currently we can run into the following code
```php 
public function __construct(
    ...
    FilesystemInterface $filesystem, 
    MountManager $mountManager
) {
...
}

...

protected function finishFile(): void
{
    if ($this->filesystem->has($this->feedFilepath)) {
        $this->filesystem->delete($this->feedFilepath);
    }

    $this->mountManager->move('local://' . $this->getTemporaryLocalFilepath(), 'main://' . $this->feedFilepath);
}
```

Main question to me here: Is `$this->filesystem` local or main?

**Comment by TomasLudvik** [comment]
Hello @grossmannmartin,
I understand your problem, but I think there is reason why it is made this way. `Flysystem\FilesystemInterface` does not support such wide functionality to manage files as `Symfony\Filesystem` does so we kept `Symfony\Filesystem` for managing local files and those then moved to abstract filesystem using `MountManager`.

**Comment by boris-brtan** [comment]
another thing `packages/framework/src/Model/Sitemap/SitemapDumper.php`

**Comment by henzigo** [comment]
It's really weird and nobody knows how to work with this. I understand that you need `localFilesystem`, but I do not completely understand why there is `FilesystemInterface` and `MountManager`. What is the benefit of this and why we can't use only one class?

**Comment by grossmannmartin** [comment]
I do agree it's really weird. I try to summarize the behavior, maybe we came into something.

Let's presume the following configuration:
- main filesystem is configured as an external filesystem (s3)
- local filesystem use the local hard drive (mostly used for temporary files)
- I pick feed generation as a use-case to explain the behavior

When you requesting `FileSystemInterface` in a constructor of any class, you get main filesystem instance. 
The instance of this class allows you to work only with main filesystem.

When you generate feed, you need to save somewhere partially generated file. It's not really good to save every change to the external filesystem (it's slower than local SSD).
So you use local filesystem. But after the feed is generated, you have to move it to the main filesystem.

Local filesystem knows how to handle local filesystem and main filesystem knows how to handle external filesystem. 
To copy files between these two filesystems is `MountManager`. The only thing the mount manager does on copying, is read streamed data from one filesystem and write stream into the other.

So from this, it seems we cannot simply use just one class... Or do you have any idea?
