### ISSUE TITLE
Update terraform config for gCloud infrastructure

### ISSUE THREAD

**Issue by boris-brtan** [shopsys/shopsys#951]
### What is happening

There are warnings from gCloud during the deployment about deprecated setting for location.
```
Warning: data.google_container_engine_versions.primary: "zone": [DEPRECATED] Use location instead
Warning: google_container_cluster.primary: "zone": [DEPRECATED] Use location instead
```

### Expected result

To have terraform files up to date.

**Comment by grossmannmartin** [comment]
I'll save you my little issue, don't worry!
