### ISSUE TITLE
cron does not working with 00

### ISSUE THREAD

**Issue by stanoMilan** [shopsys/shopsys#953]
### What is happening

If I declare cron in config as:
- { name: shopsys.cron, hours: '23', minutes: '00' }

This cron will never start

### Expected result

This cron runing in 23:00

**Comment by pk16011990** [comment]
Another expected result can be that input "00" is not valid.

**Comment by boris-brtan** [comment]
https://crontab.guru/

**Comment by PetrHeinz** [comment]
The fix will be in `v7.2.0`
