### ISSUE TITLE
CartMigrationFacade concept

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#955]
### What is happening

After discussions with @sspooky13, I decided to create a new issue on our `CartMigrationFacade`. In #770, he proposed handling the situation when `$session`is null so there is no risk of calling a method on null. Almost the same modification was proposed in #814, however, it was closed and not merged after check of Redis was added to the build process in #815. 

From my point of view, the original problem is not solved - there is still a risk of calling a method on null. 

More on that, it is quite weird that the method is called at the end of each request (`onKernelController`) - as its purpose is a preservation of a cart content when a user is logged in/logged out/registered.

### Expected result
The behavior of `CartMigrationFacade::onKernelController()` is examined and reworked so there is no risk of calling a method on null and/or the code is executed only at appropriate times.

We should also think about what should happen when the session is null - is it ok that in such a case that cart is not preserved? Or should the user be asked to repeat his action?

**Comment by sspooky13** [comment]
Hello,
it's something news with this issue? 🤔 
I still think this can be solved only add this condition
```diff
    /**
     * @param \Symfony\Component\HttpKernel\Event\FilterControllerEvent $filterControllerEvent
     */
    public function onKernelController(FilterControllerEvent $filterControllerEvent)
    {
        $session = $filterControllerEvent->getRequest()->getSession();

+       if ($session !== null) {
            $previousCartIdentifier = $session->get(static::SESSION_PREVIOUS_CART_IDENTIFIER);
            if (!empty($previousCartIdentifier) && $previousCartIdentifier !== $session->getId()) {
                $previousCustomerIdentifier = $this->customerIdentifierFactory->getOnlyWithCartIdentifier($previousCartIdentifier);
                $cart = $this->cartFacade->findCartByCustomerIdentifier($previousCustomerIdentifier);

                if ($cart !== null) {
                    $this->mergeCurrentCartWithCart($cart);
                }
            }
            $session->set(static::SESSION_PREVIOUS_CART_IDENTIFIER, $session->getId());
+       }
    }
```
because I don't care why session does not exist, for that should exist different check. This method is only for migrating cart.
