### ISSUE TITLE
Travis builds for shopsys packages are failing

### ISSUE THREAD

**Issue by vitek-rostislav** [shopsys/shopsys#957]
### What is happening
After the release of `7.1.0`, Travis builds started to failing - it is caused by [this commit](https://github.com/shopsys/shopsys/commit/073324a5ea257a85122fbc97ea08bfb978ddbeab) - Some Symplify services can not be autowired (see eg. https://travis-ci.org/shopsys/framework/jobs/521133575).
@TomasLudvik prepared [the fix by reverting the commit](https://github.com/shopsys/shopsys/pull/923), however, @boris-brtan has a valid point that it could be solved by including better-php-doc-parser config into our `easy-coding-standard.yml`.

I am wondering how could this happen when upgrading to the next minor of `symplify/better-php-doc-parser`, @TomasVotruba do you have any information on that, please?

### Expected result
All Shopsys Travis builds are passing.

**Comment by TomasVotruba** [comment]
See https://github.com/Symplify/Symplify/issues/1516#issuecomment-478582822
Upgrade to 5.4.16, where this is fixed

**Comment by TomasLudvik** [comment]
@TomasVotruba sadly it is not see https://travis-ci.org/shopsys/framework/jobs/521133575 there is v5.4.16 of better-phpdoc-parser installed.

**Comment by vitek-rostislav** [comment]
Hi @TomasVotruba, thanks for your response :+1: Currently, I am trying to fix it by adding `better-phpdoc-parser` config to `easy-coding-standard.yml` in our `coding-standards` package as suggested here - https://github.com/Symplify/BetterPhpDocParser/blob/master/README.md#usage. 

You are suggesting to upgrade to `5.4.16`, but which package do you mean? We have direct dependency on `"symplify/easy-coding-standard": "^5.2.17",` and marked `"symplify/better-phpdoc-parser": "5.4.14|5.4.15"` as conflicting.

In travis build, I can see that version `5.4.16` of `symplify/better-phpdoc-parser` is installed indeed, however, `5.4.13` version of `symplify/easy-coding-standard` is installed - so we should upgrade this package to `5.4.16` as well, am I right? :slightly_smiling_face:

**Comment by TomasVotruba** [comment]
Always use the same version for all vendor packages. E.g. for symfony/* use 4.2 everywhere. Saves much troubles :)

**Comment by boris-brtan** [comment]
so what about this hotfix?
```diff
imports:
    - { resource: '%vendor_dir%/shopsys/coding-standards/easy-coding-standard.yml', ignore_errors: true  }
+   - { resource: '%vendor_dir%/symplify/better-phpdoc-parser/config/config.yaml', ignore_errors: true }
```
https://github.com/shopsys/shopsys/compare/bb-ecs-hotfix
https://travis-ci.org/shopsys/google-cloud-bundle/builds/521733665
would it be too far from reality or is it sufficient ?

**Comment by boris-brtan** [comment]
now i see that also phpunit needs to have spl autoload for better-phpdoc-parser
https://travis-ci.org/shopsys/coding-standards/jobs/521733810
