### ISSUE TITLE
BC promise is lacking a section about forms

### ISSUE THREAD

**Issue by PetrHeinz** [shopsys/shopsys#963]
### What is happening

Our [BC promise](https://github.com/shopsys/shopsys/blob/v7.1.0/docs/contributing/backward-compatibility-promise.md) is currently lacking sections about forms, which might be useful to address. Can users assume forms will not be changed in a minor release (eg. will structure be the same / will view, normal and model data format be the same / ...)?

For example, in #956 form fields in `PaymentFormType` and `TransportFormType` were moved into other `GroupType` (which has the option `inherit_data = true`, so the data will be the same)- should this be considered a BC break? It will not break anything, unless users modify the forms manually. In that case, it would cause a break which is easily detectable (smoke tests would fail) and easily fixable (by changing the paths).

### Expected result

Backward compatibility of forms and reasonable expectations about it is explained in our BC promise in similar fashion and scope as other subsections of *The BC Promise in Detail*.

*Note: Related to #872 - also a request to extend the BC promise.*

**Comment by PetrHeinz** [comment]
In my point of view, such modification of forms should not be considered a BC break, but I'm not sure where exactly to draw the line. The ease of detection and correction seem necessary for considering it backward-compatible, and we should imho definitely promise to mention all these changes in the upgrade notes.

But maybe, this would pose too big of an inconvenience for the users... What do you think?

**Comment by simara-svatopluk** [comment]
I think we already cover this situation in BC promise by section "PHP Code". #956 is a BC break because it changes interface.

Simpler situation
```php
// FW
function configuration(): array
{
    return [
        'env' => 'dev',
    ];
}
```

```php
// user
$configuration = configuration();
if ($configuration['env']) ...
```

And let's change key now (similar to chaning form item name)
```php
// FW
function configuration(): array
{
    return [
        'environment' => 'dev',
    ];
}
```

Will user's code work? Nope. So it is a BC break because we changed the interface.

**Comment by PetrHeinz** [comment]
@simara-svatopluk Our BC promise for PHP Code links [Symfony BC Promise](https://symfony.com/doc/3.4/contributing/code/bc.html) which speaks about interfaces in the sense of [PHP object interface](https://www.php.net/manual/en/language.oop5.interfaces.php), not in a broader sense imo.

For example, I think we may, according to the BC promise, change the name of a method parameter (eg. `public function __construct($myVariable)` => `public function __construct($myOtherVariable)`, even though it would break *some* user code. Imagine service configuration with arguments indexed by parameter name:
```yaml
services:
  my_service:
  class: Foo
  arguments:
    $myVariable: 123
```

That's why I think we should be explicit about what we consider a part of the interface (in the broader meaning).

**Comment by simara-svatopluk** [comment]
Hm... Symfony BC is not mentioning interface changes... that is strange. Only thing it mentions is "Change return type: NO", but it is just a type, not a structure.

Then I vote for clarifying what interface change is a BC break and what is not. And as I explained in example above, changing array/object structure is a BC break as the user code is broken.
