### ISSUE TITLE
Setting of default VAT rate per domain

### ISSUE THREAD

**Issue by PetraPiprekova** [shopsys/shopsys#973]
### What is happening
Currently, I can't select a default VAT for domain. For example, a problem may arise when a company operates in more than one country and each is paying a different VAT rate.

Reported by @patrikbajer

### Expected result
Please consider dividing VAT for domains

**Comment by vitek-rostislav** [comment]
Hi, we discussed this, and currently, it is not listed in our priorities, however, our CPO (@LukasHeinz) keeps your request in mind :wink:

**Comment by LukasHeinz** [comment]
In the long term plan, I would like to add features for pricing after the pricing is removed to a separate package. But as I see the number of upvotes I see that there might be a reason to reconsider our plans. 
Do I get it right that implementing such a feature is complicated? What is the most difficult part? Can you recommend us something that might help you in implementation (except implementing whole feature into core SSFW)?

**Comment by sspooky13** [comment]
Hello @pesektomas,
I see https://github.com/shopsys/shopsys/pull/1498 should close this issue but it's still opened.
Do you think this can be closed? 🤔 

Thanks 🤝

**Comment by pesektomas** [comment]
Hello @sspooky13,

thx.
