### ISSUE TITLE
Rename e-mail attachment after saving

### ISSUE THREAD

**Issue by PetraPiprekova** [shopsys/shopsys#974]
### What is happening
Communication with customer -> E-mail templates

If I upload a file with the name "terms_and_conditions.pdf" to e-mail template, the file is automatically renamed to 1.pdf after saving.

Reported by @patrikbajer

### Expected result
The file name should be retained after saving.

**Comment by boris-brtan** [comment]
why?

**Comment by LukasHeinz** [comment]
A user that receives email with attachment should get an attachement with the correct name. For Internal use un application, it can be `1.pdf` but when it is attached it should have a proper name.

**Comment by PatrikBajer** [comment]
Any news?

**Comment by pk16011990** [comment]
Is it resolved by #1547?

**Comment by sslt** [comment]
It is resolved in #1547 by @TomasLudvik . I believe, This issue can be safely closed.

**Comment by TomasLudvik** [comment]
@sslt is absolutely right, closing
