### ISSUE TITLE
Missing documentation: How create new project with my domains configuration

### ISSUE THREAD

**Issue by pk16011990** [shopsys/shopsys#983]
I created a new project based on Shopsys framework, and during that time I had several problems before I achieved a successful build.

Current documentation contains how to build SSFW (with default 2 domains), how add domain, how to change locale, but It does not contain how create new project with another domain settings.

My workflow was: I followed instructions from `Installation Using Docker for xxx` and `application setup` but troubles started after creating `domains_urls.yml`. I didnt want to create project with two domains, but with three. I filled 3 domains... Ok, I edited `domains.yml` and changed locale of all domains (I want German instead of English) and there started my problems (on something I found documentation, but for somethink no... And searching in your documentation is unconfortable).

I dont want create project with 2 domains (EN and CS), and then change languages and add next domains. I want create project with my own configuration. 

Maybe it is about my mindset, but this workflow is natural to me in software projects. I can change my mindset, but I need warning in documentation.

Troubles what I had:
* change locales in datafixtures (mandatory locale wasnt here) and add data for new  3th domain - partially documented
* fix locale in tests - partially documented
* add and change elasticsearch configuration - not documented
* change default currency on domains - not documented
* administration language - documented

Some is documented, but in different pages then  aplication setup or ther is missing warning.

**Comment by pk16011990** [comment]
.

**Comment by vitek-rostislav** [comment]
Hi @pk16011990, we have already evaluated a user-story for simplification of work with tests and data fixtures with various domains and locales configuration that could help with this.

There is also a [new article in the docs](https://github.com/shopsys/shopsys/blob/master/docs/introduction/start-building-your-application.md) that should guide the developer through all the necessary steps after the default installation (it is linked from the application setup page).

I would say it addresses all the issues you mentioned that you were missing, what do you think?

There still remains the question of whether it is a good approach to install the application using default setup (2 domains) and then change all the settings...I will discuss this further with @PetrHeinz :wink:

**Comment by pk16011990** [comment]
.

**Comment by henzigo** [comment]
Stale bot, please

**Comment by henzigo** [comment]
Good boy 👍

**Comment by s3tezsky** [comment]
Hi @pk16011990,

this issue is pretty old and many changes were done from that time. I have checked your troubles and compares to documentation.

---
> I dont want create project with 2 domains (EN and CS), and then change languages and add next domains. I want create project with my own configuration.

This is recommended right at the top of the page [here](https://github.com/shopsys/shopsys/blob/master/docs/introduction/start-building-your-application.md#start-building-your-application) (`If you don't have a working application, install it first.`).

---
> change default currency on domains - not documented

It has been already documented [here](https://docs.shopsys.com/en/9.0/introduction/start-building-your-application/#set-up-default-currency)

---
I have also updated the docs to be more clear in #1992 where you can watch our progres or leave us some feedback.

**Comment by s3tezsky** [comment]
Thanks @pk16011990 for your feedback. Do not worry about closing this issue, we are still planing to improve our documentation until `v9.2`. We moved your thoughts into our internal backlog.
