### ISSUE TITLE
Duplicated phing targets for dump translations

### ISSUE THREAD

**Issue by pk16011990** [shopsys/shopsys#984]
Phing contains two different targets with same functions and same description. It is confusing.

Target `dump-translations` is alias for `dump-translations-project-base`? Why?

I needed to do dump and after `phing -l` I didn't know which one to use.

**Comment by vitek-rostislav** [comment]
Hi, thanks for pointing this out. If I remember correctly, this was done to differentiate the phing targets in project-base and in monorepo, am I right @TomasLudvik? :slightly_smiling_face: 

Related to https://github.com/shopsys/shopsys/pull/969.

**Comment by TomasLudvik** [comment]
Hi, I am not sure at all :-/ we should take a look on that

**Comment by vitek-rostislav** [comment]
Yes, I do agree that we should take a look at it, there is also #742 that complains about unclear phing targets. I have updated US-5760 in our internal backlog to deal with these problems, and I will try to push it into the upcoming sprint.
