### ISSUE TITLE
Admin: Inconsistent page design for creating variant

### ISSUE THREAD

**Issue by pk16011990** [shopsys/shopsys#986]
Admin page `admin/product/create-variant/` does not have submit button fixed on the botton of page like another administration page.

It causes that extending of `VariantFormType` adds new form fields under submit button. Submit button in the middle of form is weird :) Yes I can solve this by #956, but now is unreleased yet and this page is inconsistent.

**Comment by boris-brtan** [comment]
hello, we will release a new release 7.3.0 in a few days.

**Comment by henzigo** [comment]
Hello, #956 was already released in 7.2.0, but submit button on that page is still inconsistent or It will be solved in 7.3.0?

**Comment by vitek-rostislav** [comment]
Hi, I do think that it will be solved in `7.3.0`, or do you have any other information @boris-brtan?

@pk16011990, so your requirement is to have the fixed bar with submit button on this page as well, do I get it right?

**Comment by pk16011990** [comment]
@vitek-rostislav, yes, you are right. New form fields are under submit button without the fixed bar...

**Comment by vitek-rostislav** [comment]
ping :slightly_smiling_face:

**Comment by pk16011990** [comment]
stale bot, see on #1674... This is active issue...

**Comment by s3tezsky** [comment]
Solved in mentioned PR
