### ISSUE TITLE
Bad experience with searching in documentation

### ISSUE THREAD

**Issue by pk16011990** [shopsys/shopsys#987]
When i work with Shopsys Framework I dont know everything. I try found help in documentation but it is really hard for me now.

Documentation is only as a part of git repo. I can use github searching, but it is silly and search only in latest version (I guess master?). I can't limit Google to just one repository and MD files. And local search via IDE is very silly.

Silly for me means, that I don't know what I should search and I make typos - google solve this problems.

Do you plan independent web with documentation? With some breadcrumb or side menu for better orientation? With version selection? :heart:

**Comment by vitek-rostislav** [comment]
Hi @pk16011990, yes, we are planning to create such a web with documentation :wink: 

It will be done as a side project by me, @grossmannmartin and @TomasLudvik within the next 6 months probably.

**Comment by LukasHeinz** [comment]
Hi @pk16011990 , we are aware of the fact that GitHub documentation is not ideal and we will introduce a webpage for documentation within the next months.

**Comment by grossmannmartin** [comment]
Hi @pk16011990,
I'm happy to announce to you our new documentation site is available on https://docs.shopsys.com. You can browse documentation for different versions of SSFW, explore articles thanks to the well-arranged menu and also searching experience is much better than on Github. 

Closing this issue as resolved.
