### ISSUE TITLE
Standardize nullable typehints with default value

### ISSUE THREAD

**Issue by simara-svatopluk** [shopsys/shopsys#994]
### What is happening
When we want a nullable typehint with default value, we are freely using one of following notations
```php
function xxx(int $a = null)
function xxx(?int $a = null)

function xxx(Category $a = null)
function xxx(?Category $a = null)
```

Using non-question mark variation `xxx(int $a = null)` is just wrong as is greatly explained in https://github.com/doctrine/common/pull/805#discussion_r128762923

### Expected result
* use only question mark variation
  * `function xxx(?int $a = null)`
  * `function xxx(?Category $a = null)`
* use it for new code only
* add rule to coding standards that are not checked automatically
* when releasing a new version
  * add sniff
  * fix the old code

**Comment by boris-brtan** [comment]
fixed bz merge. @TomasLudvik please do not forget to add there keyword closes or fix fixes ,....
