### ISSUE TITLE
Documentation Up

### ISSUE THREAD

**Issue by eyeskiller** [shopsys/shopsys#996]
Misleading informations about version of PostgreSQL.

### What is happening
You are running PostgreSQL 10.5 in your Docker container, but you are recommending version PostgreSQL 9.5 for native installation. Sometimes it results in error:
```
Doctrine\DBAL\Driver\PDOException #55000

SQLSTATE[55000]: Object not in prerequisite state: 7 ERROR:  currval of sequence "administrator_activities_id_seq" is not yet defined in this sessionDoctrine\DBAL\Driver\PDOException #55000

SQLSTATE[55000]: Object not in prerequisite state: 7 ERROR:  currval of sequence "administrator_activities_id_seq" is not yet defined in this session
```

### Expected result
Good to have **same** versions for **Docker** and for **native** installations. :-)

**Comment by boris-brtan** [comment]
Hello @eyeskiller ,
THX for the notice, we already work on the update of the native installation document and the version of PostgreSQL version will be contained in application requirements markdown https://github.com/shopsys/shopsys/blob/bb-native-installation/docs/installation/application-requirements.md .
Maybe you also encountered also missing environment variable in parameters.yml for elasticsearch service index, it will be contained in the parameters.yml.dist file and application-configuration 
https://github.com/shopsys/shopsys/blob/bb-native-installation/docs/installation/application-configuration.md

**Comment by eyeskiller** [comment]
Yeah, sorry - I noticed late that you already answered me. I just followed instructions on Slack. :-) Sorry. :-)

**Comment by boris-brtan** [comment]
closed by merge
